// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `hmac_md5` functions for `arm`.
#![allow(dead_code)]

/// Starts an HMAC-MD5 computation with a key of at most 64 bytes: makes the MD5 streaming state `*inner` represent `K₀ ⊕ ipad` and `*outer` represent `K₀ ⊕ opad`, where `K₀` is the `key_len` bytes at `key` padded with zeros to 64 bytes (FIPS 198-1). The text is then absorbed with `vg_md5_update` on `*inner` (its `count` starting at 64), and the MAC computed with `vg_hmac_md5_finalize`.
///
/// Contract: `VG.Spec.Hmac.Instance.initContract` of `VG.Spec.Hmac.md5I`. Constant time: only the pointers and `key_len` may affect timing, not the key.
///
/// # Safety
///
/// * `inner` must be valid for reads and writes of 80 bytes.
/// * `outer` must be valid for reads and writes of 80 bytes.
/// * `key` must be valid for reads of `key_len` bytes.
/// * `scratch` must be valid for reads and writes of 384 bytes.
/// * `key_len` must be at most 64.
/// * The contents of `scratch` on return are unspecified.
/// * `inner`, `outer` and `scratch` must not overlap each other, `key` or the arguments on the stack (distinct Rust objects never do).
/// * None of `inner`, `outer`, `key` and `scratch` may overlap the 16 bytes of stack below the stack pointer, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_hmac_md5_init(inner: *mut [u8; 80], outer: *mut [u8; 80], key: *const u8, key_len: usize, scratch: *mut [u64; 48]) {
    core::arch::naked_asm!(
        "ldr r12, [sp, #0]",
        "str r4, [r12, #112]",
        "str r5, [r12, #116]",
        "str r6, [r12, #120]",
        "str r7, [r12, #124]",
        "str r8, [r12, #128]",
        "str r9, [r12, #132]",
        "str r10, [r12, #136]",
        "str lr, [r12, #140]",
        "str r11, [r12, #144]",
        "mov r4, r0",
        "mov r5, r1",
        "mov r6, r2",
        "mov r11, r12",
        "mov r8, #0",
        "mov r9, r3",
        "cmp r9, #0",
        "beq 20f",
        "22:",
        "add r2, r6, r8",
        "ldrb r12, [r2, #0]",
        "eor r1, r12, #54",
        "add r2, r11, r8",
        "strb r1, [r2, #148]",
        "eor r1, r12, #92",
        "strb r1, [r2, #212]",
        "add r8, r8, #1",
        "subs r9, r9, #1",
        "bne 22b",
        "b 21f",
        "20:",
        "21:",
        "movw r9, #64",
        "subs r9, r9, r8",
        "beq 23f",
        "25:",
        "add r2, r11, r8",
        "mov r1, #54",
        "strb r1, [r2, #148]",
        "mov r1, #92",
        "strb r1, [r2, #212]",
        "add r8, r8, #1",
        "subs r9, r9, #1",
        "bne 25b",
        "b 24f",
        "23:",
        "24:",
        "mov r0, r4",
        "bl {vg_md5_init}",
        "mov r0, r4",
        "movw r12, #148",
        "add r1, r11, r12",
        "movw r7, #64",
        "mov r10, r11",
        "movw r2, #0",
        "mov r3, #0",
        "push {{r1, r7, r10, r12}}",
        "bl {vg_md5_update}",
        "ldr r1, [sp], #16",
        "mov r0, r5",
        "bl {vg_md5_init}",
        "mov r0, r5",
        "movw r12, #212",
        "add r1, r11, r12",
        "movw r7, #64",
        "mov r10, r11",
        "movw r2, #0",
        "mov r3, #0",
        "push {{r1, r7, r10, r12}}",
        "bl {vg_md5_update}",
        "ldr r1, [sp], #16",
        "ldr r4, [r11, #112]",
        "ldr r5, [r11, #116]",
        "ldr r6, [r11, #120]",
        "ldr r7, [r11, #124]",
        "ldr r8, [r11, #128]",
        "ldr r9, [r11, #132]",
        "ldr r10, [r11, #136]",
        "ldr lr, [r11, #140]",
        "ldr r11, [r11, #144]",
        "bx lr",
        vg_md5_init = sym super::md5::vg_md5_init,
        vg_md5_update = sym super::md5::vg_md5_update,
    )
}

/// Finishes an HMAC-MD5 computation: if, for a 64-byte key `K₀` and a text of fewer than 2⁶⁴ − 64 bytes, the MD5 streaming state `*inner` represents `(K₀ ⊕ ipad) ‖ text`, of `count` bytes, and `*outer` represents `K₀ ⊕ opad`, writes the HMAC-MD5 of the text under `K₀` (16 bytes) to `*out`.
///
/// Contract: `VG.Spec.Hmac.Instance.finalizeContract` of `VG.Spec.Hmac.md5I`. Constant time: only the pointers and `count` may affect timing, not the states.
///
/// # Safety
///
/// * `inner` must be valid for reads and writes of 80 bytes.
/// * `outer` must be valid for reads of 80 bytes.
/// * `out` must be valid for reads and writes of 16 bytes.
/// * `scratch` must be valid for reads and writes of 384 bytes.
/// * The contents of `inner` on return are unspecified.
/// * The contents of `scratch` on return are unspecified.
/// * `inner`, `out` and `scratch` must not overlap each other, `outer` or the arguments on the stack (distinct Rust objects never do).
/// * None of `inner`, `outer`, `out` and `scratch` may overlap the 16 bytes of stack below the stack pointer, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_hmac_md5_finalize(inner: *mut [u8; 80], outer: *const [u8; 80], count: u64, out: *mut [u8; 16], scratch: *mut [u64; 48]) {
    core::arch::naked_asm!(
        "ldr r12, [sp, #4]",
        "str r4, [r12, #112]",
        "str r5, [r12, #116]",
        "str r6, [r12, #120]",
        "str r7, [r12, #124]",
        "str r8, [r12, #128]",
        "str r9, [r12, #132]",
        "str r10, [r12, #136]",
        "str lr, [r12, #140]",
        "str r11, [r12, #144]",
        "mov r5, r1",
        "ldr r7, [sp, #0]",
        "mov r11, r12",
        "movw r12, #164",
        "add r1, r11, r12",
        "mov r12, r11",
        "push {{r1, r12}}",
        "bl {vg_md5_finalize}",
        "ldr r1, [sp], #8",
        "mov r3, r11",
        "movw r12, #148",
        "add r0, r11, r12",
        "movw r12, #164",
        "add r6, r11, r12",
        "ldr r12, [r5, #0]",
        "str r12, [r0, #0]",
        "ldr r12, [r5, #4]",
        "str r12, [r0, #4]",
        "ldr r12, [r5, #8]",
        "str r12, [r0, #8]",
        "ldr r12, [r5, #12]",
        "str r12, [r0, #12]",
        "mov r12, #128",
        "str r12, [r6, #16]",
        "mov r12, #0",
        "str r12, [r6, #20]",
        "str r12, [r6, #24]",
        "str r12, [r6, #28]",
        "str r12, [r6, #32]",
        "str r12, [r6, #36]",
        "str r12, [r6, #40]",
        "str r12, [r6, #44]",
        "str r12, [r6, #48]",
        "str r12, [r6, #52]",
        "movw r12, #640",
        "movt r12, #0",
        "str r12, [r6, #56]",
        "movw r12, #0",
        "movt r12, #0",
        "str r12, [r6, #60]",
        "mov r1, r6",
        "mov r2, #1",
        "bl {vg_md5_compress}",
        "mov r6, r7",
        "ldr r9, [r0, #0]",
        "str r9, [r6, #0]",
        "ldr r9, [r0, #4]",
        "str r9, [r6, #4]",
        "ldr r9, [r0, #8]",
        "str r9, [r6, #8]",
        "ldr r9, [r0, #12]",
        "str r9, [r6, #12]",
        "ldr r4, [r11, #112]",
        "ldr r5, [r11, #116]",
        "ldr r6, [r11, #120]",
        "ldr r7, [r11, #124]",
        "ldr r8, [r11, #128]",
        "ldr r9, [r11, #132]",
        "ldr r10, [r11, #136]",
        "ldr lr, [r11, #140]",
        "ldr r11, [r11, #144]",
        "bx lr",
        vg_md5_finalize = sym super::md5::vg_md5_finalize,
        vg_md5_compress = sym super::md5::vg_md5_compress,
    )
}
