// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `hmac_sha384` functions for `x86`.
#![allow(dead_code)]

/// Starts an HMAC-SHA-384 computation with a key of at most 128 bytes: makes the SHA-384 streaming state `*inner` represent `K₀ ⊕ ipad` and `*outer` represent `K₀ ⊕ opad`, where `K₀` is the `key_len` bytes at `key` padded with zeros to 128 bytes (FIPS 198-1). The text is then absorbed with `vg_sha512_update` on `*inner` (its `count` starting at 128), and the MAC computed with `vg_hmac_sha384_finalize`.
///
/// Contract: `VG.Spec.Hmac.Instance.initContract` of `VG.Spec.Hmac.sha384I`. Constant time: only the pointers and `key_len` may affect timing, not the key.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `key_len` must be at most 128.
/// * `inner` and `outer` must each be valid for reads and writes of 192 bytes.
/// * `key` must be valid for reads of `key_len` bytes.
/// * `scratch` must be valid for reads and writes of 768 bytes; its contents on return are unspecified.
/// * `inner`, `outer` and `scratch` must not overlap each other or `key` (distinct Rust objects never do).
/// * None of `inner`, `outer`, `key` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 48 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_hmac_sha384_init(inner: *mut [u8; 192], outer: *mut [u8; 192], key: *const u8, key_len: usize, scratch: *mut [u64; 96]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+20]",
        "mov DWORD PTR [eax+272], ebx",
        "mov DWORD PTR [eax+276], esi",
        "mov DWORD PTR [eax+280], edi",
        "mov DWORD PTR [eax+284], ebp",
        "mov ebp, eax",
        "mov esi, DWORD PTR [esp+12]",
        "mov edi, DWORD PTR [esp+16]",
        "mov ebx, 0",
        "test edi, edi",
        "je 20f",
        "22:",
        "mov eax, esi",
        "add eax, ebx",
        "movzx eax, BYTE PTR [eax]",
        "mov ecx, eax",
        "xor eax, 54",
        "mov edx, ebp",
        "add edx, ebx",
        "mov BYTE PTR [edx+288], al",
        "xor ecx, 92",
        "mov BYTE PTR [edx+416], cl",
        "add ebx, 1",
        "cmp ebx, edi",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, 54",
        "mov ecx, 92",
        "cmp ebx, 128",
        "je 23f",
        "25:",
        "mov edx, ebp",
        "add edx, ebx",
        "mov BYTE PTR [edx+288], al",
        "mov BYTE PTR [edx+416], cl",
        "add ebx, 1",
        "cmp ebx, 128",
        "jne 25b",
        "jmp 24f",
        "23:",
        "24:",
        "mov ebx, DWORD PTR [esp+4]",
        "mov esi, DWORD PTR [esp+8]",
        "push ebx",
        "call {vg_sha384_init}",
        "pop eax",
        "mov eax, 0",
        "mov edi, 0",
        "mov ecx, 128",
        "mov edx, ebp",
        "add edx, 288",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push edi",
        "push ebx",
        "call {vg_sha512_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "push esi",
        "call {vg_sha384_init}",
        "pop eax",
        "mov eax, 0",
        "mov edi, 0",
        "mov ecx, 128",
        "mov edx, ebp",
        "add edx, 416",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push edi",
        "push esi",
        "call {vg_sha512_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, ebp",
        "mov ebx, DWORD PTR [eax+272]",
        "mov esi, DWORD PTR [eax+276]",
        "mov edi, DWORD PTR [eax+280]",
        "mov ebp, DWORD PTR [eax+284]",
        "ret",
        vg_sha384_init = sym super::sha512::vg_sha384_init,
        vg_sha512_update = sym super::sha512::vg_sha512_update,
    )
}

/// Finishes an HMAC-SHA-384 computation: if, for a 128-byte key `K₀` and a text of fewer than 2⁶⁴ − 128 bytes, the SHA-384 streaming state `*inner` represents `(K₀ ⊕ ipad) ‖ text`, of `count` bytes, and `*outer` represents `K₀ ⊕ opad`, writes the HMAC-SHA-384 of the text under `K₀` (48 bytes) to `*out`.
///
/// Contract: `VG.Spec.Hmac.Instance.finalizeContract` of `VG.Spec.Hmac.sha384I`. Constant time: only the pointers and `count` may affect timing, not the states.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `inner` must be valid for reads and writes of 192 bytes; its contents on return are unspecified.
/// * `outer` must be valid for reads of 192 bytes.
/// * `out` must be valid for writes of 48 bytes.
/// * `scratch` must be valid for reads and writes of 768 bytes; its contents on return are unspecified.
/// * `inner`, `out` and `scratch` must not overlap each other or `outer` (distinct Rust objects never do).
/// * None of `inner`, `outer`, `out` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 48 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_hmac_sha384_finalize(inner: *mut [u8; 192], outer: *const [u8; 192], count: u64, out: *mut [u8; 48], scratch: *mut [u64; 96]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+272], ebx",
        "mov DWORD PTR [eax+276], esi",
        "mov DWORD PTR [eax+280], edi",
        "mov DWORD PTR [eax+284], ebp",
        "mov ebp, eax",
        "mov ebx, DWORD PTR [esp+4]",
        "mov esi, DWORD PTR [esp+8]",
        "mov edi, DWORD PTR [esp+20]",
        "mov eax, DWORD PTR [esp+12]",
        "mov ecx, DWORD PTR [esp+16]",
        "mov edx, ebp",
        "add edx, 288",
        "push ebp",
        "push edx",
        "push ecx",
        "push eax",
        "push ebx",
        "call {vg_sha512_finalize}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ecx, 0",
        "20:",
        "mov eax, esi",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax]",
        "mov eax, ebx",
        "add eax, ecx",
        "mov BYTE PTR [eax], dl",
        "add ecx, 1",
        "cmp ecx, 192",
        "jne 20b",
        "mov eax, 0",
        "mov esi, 128",
        "mov ecx, 48",
        "mov edx, ebp",
        "add edx, 288",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push esi",
        "push ebx",
        "call {vg_sha512_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, 176",
        "mov ecx, 0",
        "mov edx, ebp",
        "add edx, 288",
        "push ebp",
        "push edx",
        "push ecx",
        "push eax",
        "push ebx",
        "call {vg_sha512_finalize}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ecx, 0",
        "21:",
        "mov eax, ebp",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax+288]",
        "mov eax, edi",
        "add eax, ecx",
        "mov BYTE PTR [eax], dl",
        "add ecx, 1",
        "cmp ecx, 48",
        "jne 21b",
        "mov eax, ebp",
        "mov ebx, DWORD PTR [eax+272]",
        "mov esi, DWORD PTR [eax+276]",
        "mov edi, DWORD PTR [eax+280]",
        "mov ebp, DWORD PTR [eax+284]",
        "ret",
        vg_sha512_finalize = sym super::sha512::vg_sha512_finalize,
        vg_sha512_update = sym super::sha512::vg_sha512_update,
    )
}
