// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `hmac_sha512_256` functions for `x86`.
#![allow(dead_code)]

/// Starts an HMAC-SHA-512/256 computation with a key of at most 128 bytes: makes the SHA-512/256 streaming state `*inner` represent `K₀ ⊕ ipad` and `*outer` represent `K₀ ⊕ opad`, where `K₀` is the `key_len` bytes at `key` padded with zeros to 128 bytes (FIPS 198-1). The text is then absorbed with `vg_sha512_update` on `*inner` (its `count` starting at 128), and the MAC computed with `vg_hmac_sha512_256_finalize`.
///
/// Contract: `VG.Spec.Hmac.Instance.initContract` of `VG.Spec.Hmac.sha512_256I`. Constant time: only the pointers and `key_len` may affect timing, not the key.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `inner` must be valid for reads and writes of 192 bytes.
/// * `outer` must be valid for reads and writes of 192 bytes.
/// * `key` must be valid for reads of `key_len` bytes.
/// * `scratch` must be valid for reads and writes of 1872 bytes.
/// * `key_len` must be at most 128.
/// * The contents of `scratch` on return are unspecified.
/// * `inner`, `outer` and `scratch` must not overlap each other or `key` (distinct Rust objects never do).
/// * None of `inner`, `outer`, `key` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 48 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_hmac_sha512_256_init(inner: *mut [u8; 192], outer: *mut [u8; 192], key: *const u8, key_len: usize, scratch: *mut [u64; 234]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+20]",
        "mov DWORD PTR [eax+272], ebx",
        "mov DWORD PTR [eax+276], esi",
        "mov DWORD PTR [eax+280], edi",
        "mov DWORD PTR [eax+284], ebp",
        "mov ebp, eax",
        "mov esi, DWORD PTR [esp+12]",
        "mov edi, DWORD PTR [esp+16]",
        "mov ebx, 0",
        "test edi, edi",
        "je 20f",
        "22:",
        "mov eax, esi",
        "add eax, ebx",
        "movzx eax, BYTE PTR [eax]",
        "mov ecx, eax",
        "xor eax, 54",
        "mov edx, ebp",
        "add edx, ebx",
        "mov BYTE PTR [edx+288], al",
        "xor ecx, 92",
        "mov BYTE PTR [edx+416], cl",
        "add ebx, 1",
        "cmp ebx, edi",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, 54",
        "mov ecx, 92",
        "cmp ebx, 128",
        "je 23f",
        "25:",
        "mov edx, ebp",
        "add edx, ebx",
        "mov BYTE PTR [edx+288], al",
        "mov BYTE PTR [edx+416], cl",
        "add ebx, 1",
        "cmp ebx, 128",
        "jne 25b",
        "jmp 24f",
        "23:",
        "24:",
        "mov ebx, DWORD PTR [esp+4]",
        "mov esi, DWORD PTR [esp+8]",
        "push ebx",
        "call {vg_sha512_256_init}",
        "pop eax",
        "mov eax, 0",
        "mov edi, 0",
        "mov ecx, 128",
        "mov edx, ebp",
        "add edx, 288",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push edi",
        "push ebx",
        "call {vg_sha512_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "push esi",
        "call {vg_sha512_256_init}",
        "pop eax",
        "mov eax, 0",
        "mov edi, 0",
        "mov ecx, 128",
        "mov edx, ebp",
        "add edx, 416",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push edi",
        "push esi",
        "call {vg_sha512_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, ebp",
        "mov ebx, DWORD PTR [eax+272]",
        "mov esi, DWORD PTR [eax+276]",
        "mov edi, DWORD PTR [eax+280]",
        "mov ebp, DWORD PTR [eax+284]",
        "ret",
        vg_sha512_256_init = sym super::sha512::vg_sha512_256_init,
        vg_sha512_update = sym super::sha512::vg_sha512_update,
    )
}

/// Finishes an HMAC-SHA-512/256 computation: if, for a 128-byte key `K₀` and a text of fewer than 2⁶⁴ − 128 bytes, the SHA-512/256 streaming state `*inner` represents `(K₀ ⊕ ipad) ‖ text`, of `count` bytes, and `*outer` represents `K₀ ⊕ opad`, writes the HMAC-SHA-512/256 of the text under `K₀` (32 bytes) to `*out`.
///
/// Contract: `VG.Spec.Hmac.Instance.finalizeContract` of `VG.Spec.Hmac.sha512_256I`. Constant time: only the pointers and `count` may affect timing, not the states.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `inner` must be valid for reads and writes of 192 bytes.
/// * `outer` must be valid for reads of 192 bytes.
/// * `out` must be valid for reads and writes of 32 bytes.
/// * `scratch` must be valid for reads and writes of 1872 bytes.
/// * The contents of `inner` on return are unspecified.
/// * The contents of `scratch` on return are unspecified.
/// * `inner`, `out` and `scratch` must not overlap each other or `outer` (distinct Rust objects never do).
/// * None of `inner`, `outer`, `out` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 48 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_hmac_sha512_256_finalize(inner: *mut [u8; 192], outer: *const [u8; 192], count: u64, out: *mut [u8; 32], scratch: *mut [u64; 234]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+272], ebx",
        "mov DWORD PTR [eax+276], esi",
        "mov DWORD PTR [eax+280], edi",
        "mov DWORD PTR [eax+284], ebp",
        "mov ebp, eax",
        "mov ebx, DWORD PTR [esp+4]",
        "mov esi, DWORD PTR [esp+8]",
        "mov edi, DWORD PTR [esp+20]",
        "mov eax, DWORD PTR [esp+12]",
        "mov ecx, DWORD PTR [esp+16]",
        "mov edx, ebp",
        "add edx, 288",
        "push ebp",
        "push edx",
        "push ecx",
        "push eax",
        "push ebx",
        "call {vg_sha512_finalize}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ecx, DWORD PTR [esi]",
        "mov DWORD PTR [ebx], ecx",
        "mov ecx, DWORD PTR [esi+4]",
        "mov DWORD PTR [ebx+4], ecx",
        "mov ecx, DWORD PTR [esi+8]",
        "mov DWORD PTR [ebx+8], ecx",
        "mov ecx, DWORD PTR [esi+12]",
        "mov DWORD PTR [ebx+12], ecx",
        "mov ecx, DWORD PTR [esi+16]",
        "mov DWORD PTR [ebx+16], ecx",
        "mov ecx, DWORD PTR [esi+20]",
        "mov DWORD PTR [ebx+20], ecx",
        "mov ecx, DWORD PTR [esi+24]",
        "mov DWORD PTR [ebx+24], ecx",
        "mov ecx, DWORD PTR [esi+28]",
        "mov DWORD PTR [ebx+28], ecx",
        "mov ecx, DWORD PTR [esi+32]",
        "mov DWORD PTR [ebx+32], ecx",
        "mov ecx, DWORD PTR [esi+36]",
        "mov DWORD PTR [ebx+36], ecx",
        "mov ecx, DWORD PTR [esi+40]",
        "mov DWORD PTR [ebx+40], ecx",
        "mov ecx, DWORD PTR [esi+44]",
        "mov DWORD PTR [ebx+44], ecx",
        "mov ecx, DWORD PTR [esi+48]",
        "mov DWORD PTR [ebx+48], ecx",
        "mov ecx, DWORD PTR [esi+52]",
        "mov DWORD PTR [ebx+52], ecx",
        "mov ecx, DWORD PTR [esi+56]",
        "mov DWORD PTR [ebx+56], ecx",
        "mov ecx, DWORD PTR [esi+60]",
        "mov DWORD PTR [ebx+60], ecx",
        "mov ecx, DWORD PTR [ebp+288]",
        "mov DWORD PTR [ebx+64], ecx",
        "mov ecx, DWORD PTR [ebp+292]",
        "mov DWORD PTR [ebx+68], ecx",
        "mov ecx, DWORD PTR [ebp+296]",
        "mov DWORD PTR [ebx+72], ecx",
        "mov ecx, DWORD PTR [ebp+300]",
        "mov DWORD PTR [ebx+76], ecx",
        "mov ecx, DWORD PTR [ebp+304]",
        "mov DWORD PTR [ebx+80], ecx",
        "mov ecx, DWORD PTR [ebp+308]",
        "mov DWORD PTR [ebx+84], ecx",
        "mov ecx, DWORD PTR [ebp+312]",
        "mov DWORD PTR [ebx+88], ecx",
        "mov ecx, DWORD PTR [ebp+316]",
        "mov DWORD PTR [ebx+92], ecx",
        "mov ecx, 128",
        "mov DWORD PTR [ebx+96], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+100], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+104], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+108], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+112], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+116], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+120], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+124], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+128], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+132], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+136], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+140], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+144], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+148], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+152], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+156], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+160], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+164], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+168], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+172], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+176], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+180], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebx+184], ecx",
        "mov ecx, 327680",
        "mov DWORD PTR [ebx+188], ecx",
        "mov eax, ebx",
        "add eax, 64",
        "mov ecx, 1",
        "push ebp",
        "push ecx",
        "push eax",
        "push ebx",
        "call {vg_sha512_compress}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, ebx",
        "add eax, 64",
        "mov ecx, DWORD PTR [ebx]",
        "mov edx, DWORD PTR [ebx+4]",
        "bswap edx",
        "bswap ecx",
        "mov DWORD PTR [eax], edx",
        "mov DWORD PTR [eax+4], ecx",
        "mov ecx, DWORD PTR [ebx+8]",
        "mov edx, DWORD PTR [ebx+12]",
        "bswap edx",
        "bswap ecx",
        "mov DWORD PTR [eax+8], edx",
        "mov DWORD PTR [eax+12], ecx",
        "mov ecx, DWORD PTR [ebx+16]",
        "mov edx, DWORD PTR [ebx+20]",
        "bswap edx",
        "bswap ecx",
        "mov DWORD PTR [eax+16], edx",
        "mov DWORD PTR [eax+20], ecx",
        "mov ecx, DWORD PTR [ebx+24]",
        "mov edx, DWORD PTR [ebx+28]",
        "bswap edx",
        "bswap ecx",
        "mov DWORD PTR [eax+24], edx",
        "mov DWORD PTR [eax+28], ecx",
        "mov ecx, DWORD PTR [ebx+32]",
        "mov edx, DWORD PTR [ebx+36]",
        "bswap edx",
        "bswap ecx",
        "mov DWORD PTR [eax+32], edx",
        "mov DWORD PTR [eax+36], ecx",
        "mov ecx, DWORD PTR [ebx+40]",
        "mov edx, DWORD PTR [ebx+44]",
        "bswap edx",
        "bswap ecx",
        "mov DWORD PTR [eax+40], edx",
        "mov DWORD PTR [eax+44], ecx",
        "mov ecx, DWORD PTR [ebx+48]",
        "mov edx, DWORD PTR [ebx+52]",
        "bswap edx",
        "bswap ecx",
        "mov DWORD PTR [eax+48], edx",
        "mov DWORD PTR [eax+52], ecx",
        "mov ecx, DWORD PTR [ebx+56]",
        "mov edx, DWORD PTR [ebx+60]",
        "bswap edx",
        "bswap ecx",
        "mov DWORD PTR [eax+56], edx",
        "mov DWORD PTR [eax+60], ecx",
        "mov ecx, DWORD PTR [ebx+64]",
        "mov DWORD PTR [edi], ecx",
        "mov ecx, DWORD PTR [ebx+68]",
        "mov DWORD PTR [edi+4], ecx",
        "mov ecx, DWORD PTR [ebx+72]",
        "mov DWORD PTR [edi+8], ecx",
        "mov ecx, DWORD PTR [ebx+76]",
        "mov DWORD PTR [edi+12], ecx",
        "mov ecx, DWORD PTR [ebx+80]",
        "mov DWORD PTR [edi+16], ecx",
        "mov ecx, DWORD PTR [ebx+84]",
        "mov DWORD PTR [edi+20], ecx",
        "mov ecx, DWORD PTR [ebx+88]",
        "mov DWORD PTR [edi+24], ecx",
        "mov ecx, DWORD PTR [ebx+92]",
        "mov DWORD PTR [edi+28], ecx",
        "mov eax, ebp",
        "mov ebx, DWORD PTR [eax+272]",
        "mov esi, DWORD PTR [eax+276]",
        "mov edi, DWORD PTR [eax+280]",
        "mov ebp, DWORD PTR [eax+284]",
        "ret",
        vg_sha512_finalize = sym super::sha512::vg_sha512_finalize,
        vg_sha512_compress = sym super::sha512::vg_sha512_compress,
    )
}
