// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `mldsa44` functions for `x86`.
#![allow(dead_code)]

/// ML-DSA-44 key generation from a seed, `ML-DSA.KeyGen_internal(ξ)` (FIPS 204 Algorithm 6): with the 32-byte seed `ξ` at `seed`, writes the public key to `*pk` and the private key to `*sk`. Returns 1 on success. Returns 0 if a loop reaches its bound, which is at least the limit of FIPS 204 Appendix C, Table 3 (this happens with probability about 2^-256 or less): the outputs are then unspecified, and the caller must destroy them and treat the operation as failed.
///
/// Contract: `VG.Spec.MlDsa.keyGenContract`. Constant time but for `ρ` and rejections: timing may depend on the pointers, on `ρ` (the first 32 bytes of the public key), and on which half-bytes of the SHAKE256 outputs `RejBoundedPoly` rejects (`rejBoundedLeak`, which is independent of the coefficients it samples), but not on anything else of the seed or the keys.
///
/// The function saves its caller's callee-saved registers in a frame of 16 bytes; its calls use the 80 bytes of stack below it.
///
/// It samples every polynomial of `A` and of `s1` and `s2` whatever the samplers return, and zeroes the polynomial of a sampler that fails rather than branching on it: its timing does not depend on whether key generation fails.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `seed` must be valid for reads of 32 bytes.
/// * `pk` must be valid for reads and writes of 1312 bytes.
/// * `sk` must be valid for reads and writes of 2560 bytes.
/// * `scratch` must be valid for reads and writes of 77824 bytes.
/// * `seed` must be random bytes from an approved RBG (FIPS 204 §3.6.1), or a seed so generated before.
/// * `scratch` is working space: on return it holds intermediate values, which the caller must destroy (FIPS 204 §3.6.3).
/// * `pk`, `sk` and `scratch` must not overlap each other or `seed` (distinct Rust objects never do).
/// * None of `seed`, `pk`, `sk` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 96 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_mldsa44_keygen(seed: *const [u8; 32], pk: *mut [u8; 1312], sk: *mut [u8; 2560], scratch: *mut [u64; 9728]) -> u32 {
    core::arch::naked_asm!(
        "push ebx",
        "push esi",
        "push edi",
        "push ebp",
        "mov esi, DWORD PTR [esp+32]",
        "mov eax, 1",
        "mov DWORD PTR [esi+900], eax",
        "mov eax, 4",
        "mov BYTE PTR [esi+896], al",
        "mov eax, 4",
        "mov BYTE PTR [esi+897], al",
        "mov edx, esi",
        "add edx, 0",
        "mov eax, 0",
        "mov ecx, 50",
        "20:",
        "mov DWORD PTR [edx], eax",
        "add edx, 4",
        "sub ecx, 1",
        "jne 20b",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 0",
        "mov ebx, DWORD PTR [esp+20]",
        "add ebx, 0",
        "mov ebp, 32",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebp",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_absorb}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 32",
        "mov ebx, esi",
        "add ebx, 896",
        "mov ebp, 2",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebp",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_absorb}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 34",
        "mov ebx, 31",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_pad}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 0",
        "mov ebx, esi",
        "add ebx, 1024",
        "mov ebp, 128",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebp",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_squeeze}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov edi, esi",
        "add edi, 1024",
        "mov ebp, esi",
        "add ebp, 1152",
        "mov ecx, 8",
        "21:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 21b",
        "mov edi, esi",
        "add edi, 1056",
        "mov ebp, esi",
        "add ebp, 1216",
        "mov ecx, 16",
        "22:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 22b",
        "mov eax, 0",
        "mov BYTE PTR [esi+1281], al",
        "mov eax, 0",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 0",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 4096",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 4096",
        "mov ecx, 256",
        "23:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 23b",
        "mov eax, 1",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 0",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 5120",
        "mov ecx, 256",
        "24:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 24b",
        "mov eax, 2",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 0",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 6144",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 6144",
        "mov ecx, 256",
        "25:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 25b",
        "mov eax, 3",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 0",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 7168",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 7168",
        "mov ecx, 256",
        "26:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 26b",
        "mov eax, 0",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 1",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 8192",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 8192",
        "mov ecx, 256",
        "27:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 27b",
        "mov eax, 1",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 1",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 9216",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 9216",
        "mov ecx, 256",
        "28:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 28b",
        "mov eax, 2",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 1",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 10240",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 10240",
        "mov ecx, 256",
        "29:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 29b",
        "mov eax, 3",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 1",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 11264",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 11264",
        "mov ecx, 256",
        "210:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 210b",
        "mov eax, 0",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 2",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 12288",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 12288",
        "mov ecx, 256",
        "211:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 211b",
        "mov eax, 1",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 2",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 13312",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 13312",
        "mov ecx, 256",
        "212:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 212b",
        "mov eax, 2",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 2",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 14336",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 14336",
        "mov ecx, 256",
        "213:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 213b",
        "mov eax, 3",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 2",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 15360",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 15360",
        "mov ecx, 256",
        "214:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 214b",
        "mov eax, 0",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 3",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 16384",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 16384",
        "mov ecx, 256",
        "215:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 215b",
        "mov eax, 1",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 3",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 17408",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 17408",
        "mov ecx, 256",
        "216:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 216b",
        "mov eax, 2",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 3",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 18432",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 18432",
        "mov ecx, 256",
        "217:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 217b",
        "mov eax, 3",
        "mov BYTE PTR [esi+1184], al",
        "mov eax, 3",
        "mov BYTE PTR [esi+1185], al",
        "mov eax, esi",
        "add eax, 1152",
        "mov ecx, esi",
        "add ecx, 19456",
        "mov edx, esi",
        "add edx, 2048",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 19456",
        "mov ecx, 256",
        "218:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 218b",
        "mov eax, 0",
        "mov BYTE PTR [esi+1280], al",
        "mov eax, esi",
        "add eax, 1216",
        "mov ecx, 2",
        "mov edx, esi",
        "add edx, 20480",
        "mov ebx, esi",
        "add ebx, 2048",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_bounded_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 20480",
        "mov ecx, 256",
        "219:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 219b",
        "mov eax, 1",
        "mov BYTE PTR [esi+1280], al",
        "mov eax, esi",
        "add eax, 1216",
        "mov ecx, 2",
        "mov edx, esi",
        "add edx, 21504",
        "mov ebx, esi",
        "add ebx, 2048",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_bounded_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 21504",
        "mov ecx, 256",
        "220:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 220b",
        "mov eax, 2",
        "mov BYTE PTR [esi+1280], al",
        "mov eax, esi",
        "add eax, 1216",
        "mov ecx, 2",
        "mov edx, esi",
        "add edx, 22528",
        "mov ebx, esi",
        "add ebx, 2048",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_bounded_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 22528",
        "mov ecx, 256",
        "221:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 221b",
        "mov eax, 3",
        "mov BYTE PTR [esi+1280], al",
        "mov eax, esi",
        "add eax, 1216",
        "mov ecx, 2",
        "mov edx, esi",
        "add edx, 23552",
        "mov ebx, esi",
        "add ebx, 2048",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_bounded_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 23552",
        "mov ecx, 256",
        "222:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 222b",
        "mov eax, 4",
        "mov BYTE PTR [esi+1280], al",
        "mov eax, esi",
        "add eax, 1216",
        "mov ecx, 2",
        "mov edx, esi",
        "add edx, 24576",
        "mov ebx, esi",
        "add ebx, 2048",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_bounded_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 24576",
        "mov ecx, 256",
        "223:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 223b",
        "mov eax, 5",
        "mov BYTE PTR [esi+1280], al",
        "mov eax, esi",
        "add eax, 1216",
        "mov ecx, 2",
        "mov edx, esi",
        "add edx, 25600",
        "mov ebx, esi",
        "add ebx, 2048",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_bounded_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 25600",
        "mov ecx, 256",
        "224:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 224b",
        "mov eax, 6",
        "mov BYTE PTR [esi+1280], al",
        "mov eax, esi",
        "add eax, 1216",
        "mov ecx, 2",
        "mov edx, esi",
        "add edx, 26624",
        "mov ebx, esi",
        "add ebx, 2048",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_bounded_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 26624",
        "mov ecx, 256",
        "225:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 225b",
        "mov eax, 7",
        "mov BYTE PTR [esi+1280], al",
        "mov eax, esi",
        "add eax, 1216",
        "mov ecx, 2",
        "mov edx, esi",
        "add edx, 27648",
        "mov ebx, esi",
        "add ebx, 2048",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_bounded_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov edx, 0",
        "sub edx, eax",
        "mov ecx, DWORD PTR [esi+900]",
        "and ecx, eax",
        "mov DWORD PTR [esi+900], ecx",
        "mov edi, esi",
        "add edi, 27648",
        "mov ecx, 256",
        "226:",
        "mov eax, DWORD PTR [edi]",
        "and eax, edx",
        "mov DWORD PTR [edi], eax",
        "add edi, 4",
        "sub ecx, 1",
        "jne 226b",
        "mov edi, esi",
        "add edi, 1024",
        "mov ebp, DWORD PTR [esp+24]",
        "add ebp, 0",
        "mov ecx, 8",
        "227:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 227b",
        "mov edi, esi",
        "add edi, 1024",
        "mov ebp, DWORD PTR [esp+28]",
        "add ebp, 0",
        "mov ecx, 8",
        "228:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 228b",
        "mov edi, esi",
        "add edi, 1120",
        "mov ebp, DWORD PTR [esp+28]",
        "add ebp, 32",
        "mov ecx, 8",
        "229:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 229b",
        "mov eax, esi",
        "add eax, 20480",
        "mov ecx, 2",
        "mov edx, 2",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 128",
        "mov edi, 96",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 21504",
        "mov ecx, 2",
        "mov edx, 2",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 224",
        "mov edi, 96",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 22528",
        "mov ecx, 2",
        "mov edx, 2",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 320",
        "mov edi, 96",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 23552",
        "mov ecx, 2",
        "mov edx, 2",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 416",
        "mov edi, 96",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 24576",
        "mov ecx, 2",
        "mov edx, 2",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 512",
        "mov edi, 96",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 25600",
        "mov ecx, 2",
        "mov edx, 2",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 608",
        "mov edi, 96",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 26624",
        "mov ecx, 2",
        "mov edx, 2",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 704",
        "mov edi, 96",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 27648",
        "mov ecx, 2",
        "mov edx, 2",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 800",
        "mov edi, 96",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 20480",
        "mov ecx, esi",
        "add ecx, 2048",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 21504",
        "mov ecx, esi",
        "add ecx, 2048",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 22528",
        "mov ecx, esi",
        "add ecx, 2048",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 23552",
        "mov ecx, esi",
        "add ecx, 2048",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 4096",
        "mov edx, esi",
        "add edx, 20480",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 21504",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 6144",
        "mov edx, esi",
        "add edx, 22528",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 7168",
        "mov edx, esi",
        "add edx, 23552",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 2048",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 24576",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 29696",
        "mov edx, esi",
        "add edx, 30720",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_power2round}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 29696",
        "mov ecx, 1023",
        "mov edx, DWORD PTR [esp+24]",
        "add edx, 32",
        "mov ebx, 320",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_simple_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 30720",
        "mov ecx, 4095",
        "mov edx, 4096",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 896",
        "mov edi, 416",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 8192",
        "mov edx, esi",
        "add edx, 20480",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 9216",
        "mov edx, esi",
        "add edx, 21504",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 10240",
        "mov edx, esi",
        "add edx, 22528",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 11264",
        "mov edx, esi",
        "add edx, 23552",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 2048",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 25600",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 29696",
        "mov edx, esi",
        "add edx, 30720",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_power2round}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 29696",
        "mov ecx, 1023",
        "mov edx, DWORD PTR [esp+24]",
        "add edx, 352",
        "mov ebx, 320",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_simple_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 30720",
        "mov ecx, 4095",
        "mov edx, 4096",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 1312",
        "mov edi, 416",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 12288",
        "mov edx, esi",
        "add edx, 20480",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 13312",
        "mov edx, esi",
        "add edx, 21504",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 14336",
        "mov edx, esi",
        "add edx, 22528",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 15360",
        "mov edx, esi",
        "add edx, 23552",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 2048",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 26624",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 29696",
        "mov edx, esi",
        "add edx, 30720",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_power2round}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 29696",
        "mov ecx, 1023",
        "mov edx, DWORD PTR [esp+24]",
        "add edx, 672",
        "mov ebx, 320",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_simple_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 30720",
        "mov ecx, 4095",
        "mov edx, 4096",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 1728",
        "mov edi, 416",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 16384",
        "mov edx, esi",
        "add edx, 20480",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 17408",
        "mov edx, esi",
        "add edx, 21504",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 18432",
        "mov edx, esi",
        "add edx, 22528",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 19456",
        "mov edx, esi",
        "add edx, 23552",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 2048",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 27648",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 29696",
        "mov edx, esi",
        "add edx, 30720",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_power2round}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 29696",
        "mov ecx, 1023",
        "mov edx, DWORD PTR [esp+24]",
        "add edx, 992",
        "mov ebx, 320",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_simple_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 30720",
        "mov ecx, 4095",
        "mov edx, 4096",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 2144",
        "mov edi, 416",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov edx, esi",
        "add edx, 0",
        "mov eax, 0",
        "mov ecx, 50",
        "230:",
        "mov DWORD PTR [edx], eax",
        "add edx, 4",
        "sub ecx, 1",
        "jne 230b",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 0",
        "mov ebx, DWORD PTR [esp+24]",
        "add ebx, 0",
        "mov ebp, 1312",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebp",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_absorb}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 88",
        "mov ebx, 31",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_pad}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 0",
        "mov ebx, DWORD PTR [esp+28]",
        "add ebx, 64",
        "mov ebp, 64",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebp",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_squeeze}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esi+900]",
        "mov esi, DWORD PTR [esp+8]",
        "mov edi, DWORD PTR [esp+4]",
        "mov ebp, DWORD PTR [esp]",
        "pop ebx",
        "pop ebx",
        "pop ebx",
        "pop ebx",
        "ret",
        vg_keccak_absorb = sym super::sha3::vg_keccak_absorb,
        vg_keccak_pad = sym super::sha3::vg_keccak_pad,
        vg_keccak_squeeze = sym super::sha3::vg_keccak_squeeze,
        vg_mldsa_rej_ntt_poly = sym super::mldsa::vg_mldsa_rej_ntt_poly,
        vg_mldsa_rej_bounded_poly = sym super::mldsa::vg_mldsa_rej_bounded_poly,
        vg_mldsa_bit_pack = sym super::mldsa::vg_mldsa_bit_pack,
        vg_mldsa_ntt = sym super::mldsa::vg_mldsa_ntt,
        vg_mldsa_multiply_ntt = sym super::mldsa::vg_mldsa_multiply_ntt,
        vg_mldsa_multiply_add_ntt = sym super::mldsa::vg_mldsa_multiply_add_ntt,
        vg_mldsa_inv_ntt = sym super::mldsa::vg_mldsa_inv_ntt,
        vg_mldsa_add = sym super::mldsa::vg_mldsa_add,
        vg_mldsa_power2round = sym super::mldsa::vg_mldsa_power2round,
        vg_mldsa_simple_bit_pack = sym super::mldsa::vg_mldsa_simple_bit_pack,
    )
}
