// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `mldsa44` functions for `x86`.
#![allow(dead_code)]

/// ML-DSA-44 signing of a message representative, `ML-DSA.Sign_internal(sk, M′, rnd)` (FIPS 204 Algorithm 7) with `μ` computed by the caller: with the private key `*sk`, the 64-byte message representative `μ = H(tr ‖ M′, 64)` at `mu` (for the public key hash `tr`, bytes 64–127 of `*sk`) and the randomness `*rnd`, writes the signature to `*sig`. Returns 1 on success. Returns 0 if a loop reaches its bound, which is at least the limit of FIPS 204 Appendix C, Table 3 (this happens with probability about 2^-256 or less): the outputs are then unspecified, and the caller must destroy them and treat the operation as failed.
///
/// Contract: `VG.Spec.MlDsa.signContract`. Constant time but for `ρ` and the rejection sampling: timing may depend on the pointers, on `ρ` (the first 32 bytes of `*sk`), on the number of iterations of the signing loop and the commitment hash of each, and on the hint of the signature (`signLeak`), but not on anything else of the key, the message representative or the randomness.
///
/// The function keeps its working space, `Â`, `ŝ₁`, `ŝ₂`, `t̂₀` and the polynomials of each iteration in `scratch`, and calls the ML-DSA primitives (`vg_mldsa_*`) and the Keccak functions.
///
/// The signing loop runs at most 814 iterations (FIPS 204 Appendix C). Each iteration computes every validity check and combines them without branching: the one branch on their result is the only place an iteration's outcome affects timing.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `sk` must be valid for reads of 2560 bytes.
/// * `mu` must be valid for reads of 64 bytes.
/// * `rnd` must be valid for reads of 32 bytes.
/// * `sig` must be valid for reads and writes of 2420 bytes.
/// * `scratch` must be valid for reads and writes of 77824 bytes.
/// * `sk` must have been written by `vg_mldsa44_keygen`.
/// * `rnd` must be fresh random bytes (FIPS 204 §3.6.1), or 32 zero bytes for deterministic signing.
/// * `scratch` is working space: on return it holds intermediate values, which the caller must destroy (FIPS 204 §3.6.3).
/// * `sig` and `scratch` must not overlap each other, `sk`, `mu` or `rnd` (distinct Rust objects never do).
/// * None of `sk`, `mu`, `rnd`, `sig` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 96 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_mldsa44_sign(sk: *const [u8; 2560], mu: *const [u8; 64], rnd: *const [u8; 32], sig: *mut [u8; 2420], scratch: *mut [u64; 9728]) -> u32 {
    core::arch::naked_asm!(
        "push ebx",
        "push esi",
        "push edi",
        "push ebp",
        "mov esi, DWORD PTR [esp+36]",
        "mov eax, 1",
        "mov DWORD PTR [esi+840], eax",
        "mov edi, DWORD PTR [esp+20]",
        "add edi, 0",
        "mov ebp, esi",
        "add ebp, 856",
        "mov ecx, 8",
        "20:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 20b",
        "mov eax, 0",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 0",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 38912",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 1",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 0",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 39936",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 2",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 0",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 40960",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 3",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 0",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 41984",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 0",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 1",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 43008",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 1",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 1",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 44032",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 2",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 1",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 45056",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 3",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 1",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 46080",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 0",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 2",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 47104",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 1",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 2",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 48128",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 2",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 2",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 49152",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 3",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 2",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 50176",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 0",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 3",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 51200",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 1",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 3",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 52224",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 2",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 3",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 53248",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, 3",
        "mov BYTE PTR [esi+888], al",
        "mov eax, 3",
        "mov BYTE PTR [esi+889], al",
        "mov eax, esi",
        "add eax, 856",
        "mov ecx, esi",
        "add ecx, 54272",
        "mov edx, esi",
        "add edx, 3072",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_rej_ntt_poly}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, DWORD PTR [esi+840]",
        "test eax, eax",
        "jne 21f",
        "jmp 22f",
        "21:",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 128",
        "mov ecx, 96",
        "mov edx, 2",
        "mov ebx, 2",
        "mov edi, esi",
        "add edi, 26624",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 26624",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 224",
        "mov ecx, 96",
        "mov edx, 2",
        "mov ebx, 2",
        "mov edi, esi",
        "add edi, 27648",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 27648",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 320",
        "mov ecx, 96",
        "mov edx, 2",
        "mov ebx, 2",
        "mov edi, esi",
        "add edi, 28672",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 28672",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 416",
        "mov ecx, 96",
        "mov edx, 2",
        "mov ebx, 2",
        "mov edi, esi",
        "add edi, 29696",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 29696",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 512",
        "mov ecx, 96",
        "mov edx, 2",
        "mov ebx, 2",
        "mov edi, esi",
        "add edi, 30720",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 30720",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 608",
        "mov ecx, 96",
        "mov edx, 2",
        "mov ebx, 2",
        "mov edi, esi",
        "add edi, 31744",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 31744",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 704",
        "mov ecx, 96",
        "mov edx, 2",
        "mov ebx, 2",
        "mov edi, esi",
        "add edi, 32768",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 32768",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 800",
        "mov ecx, 96",
        "mov edx, 2",
        "mov ebx, 2",
        "mov edi, esi",
        "add edi, 33792",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 33792",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 896",
        "mov ecx, 416",
        "mov edx, 4095",
        "mov ebx, 4096",
        "mov edi, esi",
        "add edi, 34816",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 34816",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 1312",
        "mov ecx, 416",
        "mov edx, 4095",
        "mov ebx, 4096",
        "mov edi, esi",
        "add edi, 35840",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 35840",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 1728",
        "mov ecx, 416",
        "mov edx, 4095",
        "mov ebx, 4096",
        "mov edi, esi",
        "add edi, 36864",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 36864",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, 2144",
        "mov ecx, 416",
        "mov edx, 4095",
        "mov ebx, 4096",
        "mov edi, esi",
        "add edi, 37888",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_unpack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 37888",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov edi, DWORD PTR [esp+20]",
        "add edi, 32",
        "mov ebp, esi",
        "add ebp, 896",
        "mov ecx, 8",
        "23:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 23b",
        "mov edi, DWORD PTR [esp+28]",
        "add edi, 0",
        "mov ebp, esi",
        "add ebp, 928",
        "mov ecx, 8",
        "24:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 24b",
        "mov edx, esi",
        "add edx, 0",
        "mov eax, 0",
        "mov ecx, 50",
        "25:",
        "mov DWORD PTR [edx], eax",
        "add edx, 4",
        "sub ecx, 1",
        "jne 25b",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 0",
        "mov ebx, esi",
        "add ebx, 896",
        "mov ebp, 64",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebp",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_absorb}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 64",
        "mov ebx, DWORD PTR [esp+24]",
        "add ebx, 0",
        "mov ebp, 64",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebp",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_absorb}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 128",
        "mov ebx, 31",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_pad}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 0",
        "mov ebx, esi",
        "add ebx, 960",
        "mov ebp, 64",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebp",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_squeeze}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, 0",
        "mov DWORD PTR [esi+848], eax",
        "mov eax, 814",
        "mov DWORD PTR [esi+844], eax",
        "26:",
        "mov eax, DWORD PTR [esi+848]",
        "add eax, 0",
        "mov BYTE PTR [esi+1024], al",
        "shr eax, 8",
        "mov BYTE PTR [esi+1025], al",
        "mov eax, esi",
        "add eax, 960",
        "mov ecx, 131072",
        "mov edx, esi",
        "add edx, 14336",
        "mov ebx, esi",
        "add ebx, 3072",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_expand_mask_poly}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov edi, esi",
        "add edi, 14336",
        "mov ebp, esi",
        "add ebp, 18432",
        "mov ecx, 256",
        "27:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 27b",
        "mov eax, esi",
        "add eax, 18432",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esi+848]",
        "add eax, 1",
        "mov BYTE PTR [esi+1024], al",
        "shr eax, 8",
        "mov BYTE PTR [esi+1025], al",
        "mov eax, esi",
        "add eax, 960",
        "mov ecx, 131072",
        "mov edx, esi",
        "add edx, 15360",
        "mov ebx, esi",
        "add ebx, 3072",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_expand_mask_poly}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov edi, esi",
        "add edi, 15360",
        "mov ebp, esi",
        "add ebp, 19456",
        "mov ecx, 256",
        "28:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 28b",
        "mov eax, esi",
        "add eax, 19456",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esi+848]",
        "add eax, 2",
        "mov BYTE PTR [esi+1024], al",
        "shr eax, 8",
        "mov BYTE PTR [esi+1025], al",
        "mov eax, esi",
        "add eax, 960",
        "mov ecx, 131072",
        "mov edx, esi",
        "add edx, 16384",
        "mov ebx, esi",
        "add ebx, 3072",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_expand_mask_poly}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov edi, esi",
        "add edi, 16384",
        "mov ebp, esi",
        "add ebp, 20480",
        "mov ecx, 256",
        "29:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 29b",
        "mov eax, esi",
        "add eax, 20480",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esi+848]",
        "add eax, 3",
        "mov BYTE PTR [esi+1024], al",
        "shr eax, 8",
        "mov BYTE PTR [esi+1025], al",
        "mov eax, esi",
        "add eax, 960",
        "mov ecx, 131072",
        "mov edx, esi",
        "add edx, 17408",
        "mov ebx, esi",
        "add ebx, 3072",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_expand_mask_poly}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov edi, esi",
        "add edi, 17408",
        "mov ebp, esi",
        "add ebp, 21504",
        "mov ecx, 256",
        "210:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 210b",
        "mov eax, esi",
        "add eax, 21504",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 22528",
        "mov ecx, esi",
        "add ecx, 38912",
        "mov edx, esi",
        "add edx, 18432",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 22528",
        "mov ecx, esi",
        "add ecx, 39936",
        "mov edx, esi",
        "add edx, 19456",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 22528",
        "mov ecx, esi",
        "add ecx, 40960",
        "mov edx, esi",
        "add edx, 20480",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 22528",
        "mov ecx, esi",
        "add ecx, 41984",
        "mov edx, esi",
        "add edx, 21504",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 22528",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 23552",
        "mov ecx, esi",
        "add ecx, 43008",
        "mov edx, esi",
        "add edx, 18432",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 23552",
        "mov ecx, esi",
        "add ecx, 44032",
        "mov edx, esi",
        "add edx, 19456",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 23552",
        "mov ecx, esi",
        "add ecx, 45056",
        "mov edx, esi",
        "add edx, 20480",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 23552",
        "mov ecx, esi",
        "add ecx, 46080",
        "mov edx, esi",
        "add edx, 21504",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 23552",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 24576",
        "mov ecx, esi",
        "add ecx, 47104",
        "mov edx, esi",
        "add edx, 18432",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 24576",
        "mov ecx, esi",
        "add ecx, 48128",
        "mov edx, esi",
        "add edx, 19456",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 24576",
        "mov ecx, esi",
        "add ecx, 49152",
        "mov edx, esi",
        "add edx, 20480",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 24576",
        "mov ecx, esi",
        "add ecx, 50176",
        "mov edx, esi",
        "add edx, 21504",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 24576",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 25600",
        "mov ecx, esi",
        "add ecx, 51200",
        "mov edx, esi",
        "add edx, 18432",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 25600",
        "mov ecx, esi",
        "add ecx, 52224",
        "mov edx, esi",
        "add edx, 19456",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 25600",
        "mov ecx, esi",
        "add ecx, 53248",
        "mov edx, esi",
        "add edx, 20480",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 25600",
        "mov ecx, esi",
        "add ecx, 54272",
        "mov edx, esi",
        "add edx, 21504",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_add_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 25600",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 22528",
        "mov ecx, 95232",
        "mov edx, esi",
        "add edx, 6144",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_high_bits}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, 43",
        "mov edx, esi",
        "add edx, 2048",
        "mov ebx, 192",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_simple_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 23552",
        "mov ecx, 95232",
        "mov edx, esi",
        "add edx, 6144",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_high_bits}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, 43",
        "mov edx, esi",
        "add edx, 2240",
        "mov ebx, 192",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_simple_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 24576",
        "mov ecx, 95232",
        "mov edx, esi",
        "add edx, 6144",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_high_bits}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, 43",
        "mov edx, esi",
        "add edx, 2432",
        "mov ebx, 192",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_simple_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 25600",
        "mov ecx, 95232",
        "mov edx, esi",
        "add edx, 6144",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_high_bits}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, 43",
        "mov edx, esi",
        "add edx, 2624",
        "mov ebx, 192",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_simple_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov edx, esi",
        "add edx, 0",
        "mov eax, 0",
        "mov ecx, 50",
        "211:",
        "mov DWORD PTR [edx], eax",
        "add edx, 4",
        "sub ecx, 1",
        "jne 211b",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 0",
        "mov ebx, DWORD PTR [esp+24]",
        "add ebx, 0",
        "mov ebp, 64",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebp",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_absorb}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 64",
        "mov ebx, esi",
        "add ebx, 2048",
        "mov ebp, 768",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebp",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_absorb}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 16",
        "mov ebx, 31",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_pad}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 0",
        "mov ecx, 136",
        "mov edx, 0",
        "mov ebx, esi",
        "add ebx, 1040",
        "mov ebp, 32",
        "mov edi, esi",
        "add edi, 200",
        "push edi",
        "push ebp",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_keccak_squeeze}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 1040",
        "mov ecx, 32",
        "mov edx, 39",
        "mov ebx, esi",
        "add ebx, 5120",
        "mov edi, esi",
        "add edi, 3072",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_sample_in_ball}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "test eax, eax",
        "jne 212f",
        "mov eax, 0",
        "mov DWORD PTR [esi+840], eax",
        "mov eax, 1",
        "mov DWORD PTR [esi+844], eax",
        "jmp 213f",
        "212:",
        "mov eax, esi",
        "add eax, 5120",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, 1",
        "mov DWORD PTR [esi+840], eax",
        "mov eax, 0",
        "mov DWORD PTR [esi+852], eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 26624",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 14336",
        "mov ecx, esi",
        "add ecx, 6144",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 14336",
        "mov ecx, 130994",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 27648",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 15360",
        "mov ecx, esi",
        "add ecx, 6144",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 15360",
        "mov ecx, 130994",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 28672",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 16384",
        "mov ecx, esi",
        "add ecx, 6144",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 16384",
        "mov ecx, 130994",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 29696",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 17408",
        "mov ecx, esi",
        "add ecx, 6144",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 17408",
        "mov ecx, 130994",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 30720",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 22528",
        "mov ecx, esi",
        "add ecx, 6144",
        "push ecx",
        "push eax",
        "call {vg_mldsa_sub}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 22528",
        "mov ecx, 95232",
        "mov edx, esi",
        "add edx, 7168",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_low_bits}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 7168",
        "mov ecx, 95154",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 31744",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 23552",
        "mov ecx, esi",
        "add ecx, 6144",
        "push ecx",
        "push eax",
        "call {vg_mldsa_sub}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 23552",
        "mov ecx, 95232",
        "mov edx, esi",
        "add edx, 7168",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_low_bits}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 7168",
        "mov ecx, 95154",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 32768",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 24576",
        "mov ecx, esi",
        "add ecx, 6144",
        "push ecx",
        "push eax",
        "call {vg_mldsa_sub}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 24576",
        "mov ecx, 95232",
        "mov edx, esi",
        "add edx, 7168",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_low_bits}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 7168",
        "mov ecx, 95154",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 33792",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 6144",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 25600",
        "mov ecx, esi",
        "add ecx, 6144",
        "push ecx",
        "push eax",
        "call {vg_mldsa_sub}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 25600",
        "mov ecx, 95232",
        "mov edx, esi",
        "add edx, 7168",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_low_bits}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 7168",
        "mov ecx, 95154",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 34816",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, 95232",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov edi, esi",
        "add edi, 22528",
        "mov ebp, esi",
        "add ebp, 9216",
        "mov ecx, 256",
        "214:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 214b",
        "mov eax, esi",
        "add eax, 22528",
        "mov ecx, esi",
        "add ecx, 8192",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 9216",
        "mov ecx, esi",
        "add ecx, 22528",
        "push ecx",
        "push eax",
        "call {vg_mldsa_sub}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 9216",
        "mov ecx, esi",
        "add ecx, 22528",
        "mov edx, 95232",
        "mov ebx, esi",
        "add ebx, 10240",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_make_hint}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+852]",
        "add ecx, eax",
        "mov DWORD PTR [esi+852], ecx",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 35840",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, 95232",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov edi, esi",
        "add edi, 23552",
        "mov ebp, esi",
        "add ebp, 9216",
        "mov ecx, 256",
        "215:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 215b",
        "mov eax, esi",
        "add eax, 23552",
        "mov ecx, esi",
        "add ecx, 8192",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 9216",
        "mov ecx, esi",
        "add ecx, 23552",
        "push ecx",
        "push eax",
        "call {vg_mldsa_sub}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 9216",
        "mov ecx, esi",
        "add ecx, 23552",
        "mov edx, 95232",
        "mov ebx, esi",
        "add ebx, 11264",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_make_hint}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+852]",
        "add ecx, eax",
        "mov DWORD PTR [esi+852], ecx",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 36864",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, 95232",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov edi, esi",
        "add edi, 24576",
        "mov ebp, esi",
        "add ebp, 9216",
        "mov ecx, 256",
        "216:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 216b",
        "mov eax, esi",
        "add eax, 24576",
        "mov ecx, esi",
        "add ecx, 8192",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 9216",
        "mov ecx, esi",
        "add ecx, 24576",
        "push ecx",
        "push eax",
        "call {vg_mldsa_sub}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 9216",
        "mov ecx, esi",
        "add ecx, 24576",
        "mov edx, 95232",
        "mov ebx, esi",
        "add ebx, 12288",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_make_hint}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+852]",
        "add ecx, eax",
        "mov DWORD PTR [esi+852], ecx",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, esi",
        "add ecx, 5120",
        "mov edx, esi",
        "add edx, 37888",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_multiply_ntt}",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, esi",
        "add ecx, 3072",
        "push ecx",
        "push eax",
        "call {vg_mldsa_inv_ntt}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 8192",
        "mov ecx, 95232",
        "push ecx",
        "push eax",
        "call {vg_mldsa_norm_lt}",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov edi, esi",
        "add edi, 25600",
        "mov ebp, esi",
        "add ebp, 9216",
        "mov ecx, 256",
        "217:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 217b",
        "mov eax, esi",
        "add eax, 25600",
        "mov ecx, esi",
        "add ecx, 8192",
        "push ecx",
        "push eax",
        "call {vg_mldsa_add}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 9216",
        "mov ecx, esi",
        "add ecx, 25600",
        "push ecx",
        "push eax",
        "call {vg_mldsa_sub}",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 9216",
        "mov ecx, esi",
        "add ecx, 25600",
        "mov edx, 95232",
        "mov ebx, esi",
        "add ebx, 13312",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_make_hint}",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "pop ecx",
        "mov ecx, DWORD PTR [esi+852]",
        "add ecx, eax",
        "mov DWORD PTR [esi+852], ecx",
        "mov eax, DWORD PTR [esi+852]",
        "sub eax, 81",
        "shr eax, 31",
        "mov ecx, DWORD PTR [esi+840]",
        "and ecx, eax",
        "mov DWORD PTR [esi+840], ecx",
        "mov eax, DWORD PTR [esi+840]",
        "test eax, eax",
        "jne 218f",
        "mov eax, DWORD PTR [esi+848]",
        "add eax, 4",
        "mov DWORD PTR [esi+848], eax",
        "jmp 219f",
        "218:",
        "mov eax, 1",
        "mov DWORD PTR [esi+844], eax",
        "219:",
        "213:",
        "mov eax, DWORD PTR [esi+844]",
        "sub eax, 1",
        "mov DWORD PTR [esi+844], eax",
        "jne 26b",
        "mov eax, DWORD PTR [esi+840]",
        "test eax, eax",
        "jne 220f",
        "jmp 221f",
        "220:",
        "mov edi, esi",
        "add edi, 1040",
        "mov ebp, DWORD PTR [esp+32]",
        "add ebp, 0",
        "mov ecx, 8",
        "222:",
        "mov eax, DWORD PTR [edi]",
        "mov DWORD PTR [ebp], eax",
        "add edi, 4",
        "add ebp, 4",
        "sub ecx, 1",
        "jne 222b",
        "mov eax, esi",
        "add eax, 14336",
        "mov ecx, 131071",
        "mov edx, 131072",
        "mov ebx, DWORD PTR [esp+32]",
        "add ebx, 32",
        "mov edi, 576",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 15360",
        "mov ecx, 131071",
        "mov edx, 131072",
        "mov ebx, DWORD PTR [esp+32]",
        "add ebx, 608",
        "mov edi, 576",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 16384",
        "mov ecx, 131071",
        "mov edx, 131072",
        "mov ebx, DWORD PTR [esp+32]",
        "add ebx, 1184",
        "mov edi, 576",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 17408",
        "mov ecx, 131071",
        "mov edx, 131072",
        "mov ebx, DWORD PTR [esp+32]",
        "add ebx, 1760",
        "mov edi, 576",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, esi",
        "add eax, 10240",
        "mov ecx, 1024",
        "mov edx, 80",
        "mov ebx, DWORD PTR [esp+32]",
        "add ebx, 2336",
        "mov edi, 84",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_mldsa_hint_bit_pack}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "221:",
        "22:",
        "mov eax, DWORD PTR [esi+840]",
        "mov esi, DWORD PTR [esp+8]",
        "mov edi, DWORD PTR [esp+4]",
        "mov ebp, DWORD PTR [esp]",
        "pop ebx",
        "pop ebx",
        "pop ebx",
        "pop ebx",
        "ret",
        vg_mldsa_rej_ntt_poly = sym super::mldsa::vg_mldsa_rej_ntt_poly,
        vg_mldsa_bit_unpack = sym super::mldsa::vg_mldsa_bit_unpack,
        vg_mldsa_ntt = sym super::mldsa::vg_mldsa_ntt,
        vg_keccak_absorb = sym super::sha3::vg_keccak_absorb,
        vg_keccak_pad = sym super::sha3::vg_keccak_pad,
        vg_keccak_squeeze = sym super::sha3::vg_keccak_squeeze,
        vg_mldsa_expand_mask_poly = sym super::mldsa::vg_mldsa_expand_mask_poly,
        vg_mldsa_multiply_ntt = sym super::mldsa::vg_mldsa_multiply_ntt,
        vg_mldsa_multiply_add_ntt = sym super::mldsa::vg_mldsa_multiply_add_ntt,
        vg_mldsa_inv_ntt = sym super::mldsa::vg_mldsa_inv_ntt,
        vg_mldsa_high_bits = sym super::mldsa::vg_mldsa_high_bits,
        vg_mldsa_simple_bit_pack = sym super::mldsa::vg_mldsa_simple_bit_pack,
        vg_mldsa_sample_in_ball = sym super::mldsa::vg_mldsa_sample_in_ball,
        vg_mldsa_add = sym super::mldsa::vg_mldsa_add,
        vg_mldsa_norm_lt = sym super::mldsa::vg_mldsa_norm_lt,
        vg_mldsa_sub = sym super::mldsa::vg_mldsa_sub,
        vg_mldsa_low_bits = sym super::mldsa::vg_mldsa_low_bits,
        vg_mldsa_make_hint = sym super::mldsa::vg_mldsa_make_hint,
        vg_mldsa_bit_pack = sym super::mldsa::vg_mldsa_bit_pack,
        vg_mldsa_hint_bit_pack = sym super::mldsa::vg_mldsa_hint_bit_pack,
    )
}
