// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `pbkdf2_sha256` functions for `x86`.
#![allow(dead_code)]

/// Runs `n` steps of PBKDF2-HMAC-SHA-256's iteration: if, for a 64-byte key `K₀`, the SHA-256 streaming state in bytes 0 to 95 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 96 to 191 represents `K₀ ⊕ opad` (as `vg_hmac_sha256_init` leaves them), repeats `U ← HMAC-SHA-256 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Pbkdf2.iterateSha256Contract`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `key` must be valid for reads of 192 bytes, and `u` for reads of 32 bytes.
/// * `t` must be valid for reads and writes of 32 bytes.
/// * `scratch` must be valid for reads and writes of 832 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u` (distinct Rust objects never do).
/// * None of `key`, `u`, `t` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 20 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_pbkdf2_hmac_sha256_iterate(key: *const [u8; 192], u: *const [u8; 32], n: u32, t: *mut [u8; 32], scratch: *mut [u64; 104]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+20]",
        "mov DWORD PTR [eax+112], ebx",
        "mov DWORD PTR [eax+116], esi",
        "mov DWORD PTR [eax+120], edi",
        "mov DWORD PTR [eax+124], ebp",
        "mov ebp, eax",
        "mov esi, DWORD PTR [esp+4]",
        "mov edi, DWORD PTR [esp+12]",
        "mov ebx, DWORD PTR [esp+16]",
        "mov edx, DWORD PTR [esp+8]",
        "mov ecx, DWORD PTR [edx]",
        "mov DWORD PTR [ebp+192], ecx",
        "mov ecx, DWORD PTR [edx+4]",
        "mov DWORD PTR [ebp+196], ecx",
        "mov ecx, DWORD PTR [edx+8]",
        "mov DWORD PTR [ebp+200], ecx",
        "mov ecx, DWORD PTR [edx+12]",
        "mov DWORD PTR [ebp+204], ecx",
        "mov ecx, DWORD PTR [edx+16]",
        "mov DWORD PTR [ebp+208], ecx",
        "mov ecx, DWORD PTR [edx+20]",
        "mov DWORD PTR [ebp+212], ecx",
        "mov ecx, DWORD PTR [edx+24]",
        "mov DWORD PTR [ebp+216], ecx",
        "mov ecx, DWORD PTR [edx+28]",
        "mov DWORD PTR [ebp+220], ecx",
        "mov ecx, DWORD PTR [ebx]",
        "mov DWORD PTR [ebp+160], ecx",
        "mov ecx, DWORD PTR [ebx+4]",
        "mov DWORD PTR [ebp+164], ecx",
        "mov ecx, DWORD PTR [ebx+8]",
        "mov DWORD PTR [ebp+168], ecx",
        "mov ecx, DWORD PTR [ebx+12]",
        "mov DWORD PTR [ebp+172], ecx",
        "mov ecx, DWORD PTR [ebx+16]",
        "mov DWORD PTR [ebp+176], ecx",
        "mov ecx, DWORD PTR [ebx+20]",
        "mov DWORD PTR [ebp+180], ecx",
        "mov ecx, DWORD PTR [ebx+24]",
        "mov DWORD PTR [ebp+184], ecx",
        "mov ecx, DWORD PTR [ebx+28]",
        "mov DWORD PTR [ebp+188], ecx",
        "mov ecx, 128",
        "mov DWORD PTR [ebp+224], ecx",
        "mov ecx, 0",
        "mov DWORD PTR [ebp+228], ecx",
        "mov DWORD PTR [ebp+232], ecx",
        "mov DWORD PTR [ebp+236], ecx",
        "mov DWORD PTR [ebp+240], ecx",
        "mov DWORD PTR [ebp+244], ecx",
        "mov DWORD PTR [ebp+248], ecx",
        "mov ecx, 196608",
        "mov DWORD PTR [ebp+252], ecx",
        "test edi, edi",
        "je 20f",
        "22:",
        "mov ecx, DWORD PTR [esi]",
        "mov DWORD PTR [ebx], ecx",
        "mov ecx, DWORD PTR [esi+4]",
        "mov DWORD PTR [ebx+4], ecx",
        "mov ecx, DWORD PTR [esi+8]",
        "mov DWORD PTR [ebx+8], ecx",
        "mov ecx, DWORD PTR [esi+12]",
        "mov DWORD PTR [ebx+12], ecx",
        "mov ecx, DWORD PTR [esi+16]",
        "mov DWORD PTR [ebx+16], ecx",
        "mov ecx, DWORD PTR [esi+20]",
        "mov DWORD PTR [ebx+20], ecx",
        "mov ecx, DWORD PTR [esi+24]",
        "mov DWORD PTR [ebx+24], ecx",
        "mov ecx, DWORD PTR [esi+28]",
        "mov DWORD PTR [ebx+28], ecx",
        "mov eax, ebp",
        "add eax, 192",
        "mov ecx, 1",
        "push ebp",
        "push ecx",
        "push eax",
        "push ebx",
        "call {vg_sha256_compress}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ecx, DWORD PTR [ebx]",
        "bswap ecx",
        "mov DWORD PTR [ebp+192], ecx",
        "mov ecx, DWORD PTR [ebx+4]",
        "bswap ecx",
        "mov DWORD PTR [ebp+196], ecx",
        "mov ecx, DWORD PTR [ebx+8]",
        "bswap ecx",
        "mov DWORD PTR [ebp+200], ecx",
        "mov ecx, DWORD PTR [ebx+12]",
        "bswap ecx",
        "mov DWORD PTR [ebp+204], ecx",
        "mov ecx, DWORD PTR [ebx+16]",
        "bswap ecx",
        "mov DWORD PTR [ebp+208], ecx",
        "mov ecx, DWORD PTR [ebx+20]",
        "bswap ecx",
        "mov DWORD PTR [ebp+212], ecx",
        "mov ecx, DWORD PTR [ebx+24]",
        "bswap ecx",
        "mov DWORD PTR [ebp+216], ecx",
        "mov ecx, DWORD PTR [ebx+28]",
        "bswap ecx",
        "mov DWORD PTR [ebp+220], ecx",
        "mov ecx, DWORD PTR [esi+96]",
        "mov DWORD PTR [ebx], ecx",
        "mov ecx, DWORD PTR [esi+100]",
        "mov DWORD PTR [ebx+4], ecx",
        "mov ecx, DWORD PTR [esi+104]",
        "mov DWORD PTR [ebx+8], ecx",
        "mov ecx, DWORD PTR [esi+108]",
        "mov DWORD PTR [ebx+12], ecx",
        "mov ecx, DWORD PTR [esi+112]",
        "mov DWORD PTR [ebx+16], ecx",
        "mov ecx, DWORD PTR [esi+116]",
        "mov DWORD PTR [ebx+20], ecx",
        "mov ecx, DWORD PTR [esi+120]",
        "mov DWORD PTR [ebx+24], ecx",
        "mov ecx, DWORD PTR [esi+124]",
        "mov DWORD PTR [ebx+28], ecx",
        "mov eax, ebp",
        "add eax, 192",
        "mov ecx, 1",
        "push ebp",
        "push ecx",
        "push eax",
        "push ebx",
        "call {vg_sha256_compress}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ecx, DWORD PTR [ebx]",
        "bswap ecx",
        "mov DWORD PTR [ebp+192], ecx",
        "mov ecx, DWORD PTR [ebx+4]",
        "bswap ecx",
        "mov DWORD PTR [ebp+196], ecx",
        "mov ecx, DWORD PTR [ebx+8]",
        "bswap ecx",
        "mov DWORD PTR [ebp+200], ecx",
        "mov ecx, DWORD PTR [ebx+12]",
        "bswap ecx",
        "mov DWORD PTR [ebp+204], ecx",
        "mov ecx, DWORD PTR [ebx+16]",
        "bswap ecx",
        "mov DWORD PTR [ebp+208], ecx",
        "mov ecx, DWORD PTR [ebx+20]",
        "bswap ecx",
        "mov DWORD PTR [ebp+212], ecx",
        "mov ecx, DWORD PTR [ebx+24]",
        "bswap ecx",
        "mov DWORD PTR [ebp+216], ecx",
        "mov ecx, DWORD PTR [ebx+28]",
        "bswap ecx",
        "mov DWORD PTR [ebp+220], ecx",
        "mov ecx, DWORD PTR [ebp+160]",
        "xor ecx, DWORD PTR [ebp+192]",
        "mov DWORD PTR [ebp+160], ecx",
        "mov ecx, DWORD PTR [ebp+164]",
        "xor ecx, DWORD PTR [ebp+196]",
        "mov DWORD PTR [ebp+164], ecx",
        "mov ecx, DWORD PTR [ebp+168]",
        "xor ecx, DWORD PTR [ebp+200]",
        "mov DWORD PTR [ebp+168], ecx",
        "mov ecx, DWORD PTR [ebp+172]",
        "xor ecx, DWORD PTR [ebp+204]",
        "mov DWORD PTR [ebp+172], ecx",
        "mov ecx, DWORD PTR [ebp+176]",
        "xor ecx, DWORD PTR [ebp+208]",
        "mov DWORD PTR [ebp+176], ecx",
        "mov ecx, DWORD PTR [ebp+180]",
        "xor ecx, DWORD PTR [ebp+212]",
        "mov DWORD PTR [ebp+180], ecx",
        "mov ecx, DWORD PTR [ebp+184]",
        "xor ecx, DWORD PTR [ebp+216]",
        "mov DWORD PTR [ebp+184], ecx",
        "mov ecx, DWORD PTR [ebp+188]",
        "xor ecx, DWORD PTR [ebp+220]",
        "mov DWORD PTR [ebp+188], ecx",
        "sub edi, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov ecx, DWORD PTR [ebp+160]",
        "mov DWORD PTR [ebx], ecx",
        "mov ecx, DWORD PTR [ebp+164]",
        "mov DWORD PTR [ebx+4], ecx",
        "mov ecx, DWORD PTR [ebp+168]",
        "mov DWORD PTR [ebx+8], ecx",
        "mov ecx, DWORD PTR [ebp+172]",
        "mov DWORD PTR [ebx+12], ecx",
        "mov ecx, DWORD PTR [ebp+176]",
        "mov DWORD PTR [ebx+16], ecx",
        "mov ecx, DWORD PTR [ebp+180]",
        "mov DWORD PTR [ebx+20], ecx",
        "mov ecx, DWORD PTR [ebp+184]",
        "mov DWORD PTR [ebx+24], ecx",
        "mov ecx, DWORD PTR [ebp+188]",
        "mov DWORD PTR [ebx+28], ecx",
        "mov eax, ebp",
        "mov ebx, DWORD PTR [eax+112]",
        "mov esi, DWORD PTR [eax+116]",
        "mov edi, DWORD PTR [eax+120]",
        "mov ebp, DWORD PTR [eax+124]",
        "ret",
        vg_sha256_compress = sym super::sha256::vg_sha256_compress,
    )
}
