// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `pbkdf2_md5` functions for `x86`.
#![allow(dead_code)]

/// Runs `n` steps of PBKDF2-HMAC-MD5's iteration: if, for a 64-byte key `K₀`, the MD5 streaming state in bytes 0 to 79 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 80 to 159 represents `K₀ ⊕ opad` (as `vg_hmac_md5_init` leaves them), repeats `U ← HMAC-MD5 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.md5I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `key` must be valid for reads of 160 bytes.
/// * `u` must be valid for reads of 16 bytes.
/// * `t` must be valid for reads and writes of 16 bytes.
/// * `scratch` must be valid for reads and writes of 384 bytes.
/// * The contents of `scratch` on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u` (distinct Rust objects never do).
/// * None of `key`, `u`, `t` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 48 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_pbkdf2_hmac_md5_iterate(key: *const [u8; 160], u: *const [u8; 16], n: u32, t: *mut [u8; 16], scratch: *mut [u64; 48]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+20]",
        "mov DWORD PTR [eax+112], ebx",
        "mov DWORD PTR [eax+116], esi",
        "mov DWORD PTR [eax+120], edi",
        "mov DWORD PTR [eax+124], ebp",
        "mov ebp, eax",
        "mov edi, DWORD PTR [esp+12]",
        "mov esi, DWORD PTR [esp+8]",
        "mov ecx, 0",
        "20:",
        "mov eax, esi",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax]",
        "mov eax, ebp",
        "add eax, ecx",
        "mov BYTE PTR [eax+224], dl",
        "add ecx, 1",
        "cmp ecx, 16",
        "jne 20b",
        "test edi, edi",
        "je 21f",
        "23:",
        "mov esi, DWORD PTR [esp+4]",
        "mov ecx, 0",
        "24:",
        "mov eax, esi",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax]",
        "mov eax, ebp",
        "add eax, ecx",
        "mov BYTE PTR [eax+128], dl",
        "add ecx, 1",
        "cmp ecx, 80",
        "jne 24b",
        "mov ebx, ebp",
        "add ebx, 128",
        "mov eax, 0",
        "mov esi, 64",
        "mov ecx, 16",
        "mov edx, ebp",
        "add edx, 224",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push esi",
        "push ebx",
        "call {vg_md5_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebx, ebp",
        "add ebx, 128",
        "mov eax, 80",
        "mov ecx, 0",
        "mov edx, ebp",
        "add edx, 208",
        "push ebp",
        "push edx",
        "push ecx",
        "push eax",
        "push ebx",
        "call {vg_md5_finalize}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov esi, DWORD PTR [esp+4]",
        "mov ecx, 0",
        "25:",
        "mov eax, esi",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax+80]",
        "mov eax, ebp",
        "add eax, ecx",
        "mov BYTE PTR [eax+128], dl",
        "add ecx, 1",
        "cmp ecx, 80",
        "jne 25b",
        "mov ebx, ebp",
        "add ebx, 128",
        "mov eax, 0",
        "mov esi, 64",
        "mov ecx, 16",
        "mov edx, ebp",
        "add edx, 208",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push esi",
        "push ebx",
        "call {vg_md5_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebx, ebp",
        "add ebx, 128",
        "mov eax, 80",
        "mov ecx, 0",
        "mov edx, ebp",
        "add edx, 224",
        "push ebp",
        "push edx",
        "push ecx",
        "push eax",
        "push ebx",
        "call {vg_md5_finalize}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov esi, DWORD PTR [esp+16]",
        "mov ecx, 0",
        "26:",
        "mov eax, ebp",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax+224]",
        "mov eax, esi",
        "add eax, ecx",
        "movzx ebx, BYTE PTR [eax]",
        "xor edx, ebx",
        "mov BYTE PTR [eax], dl",
        "add ecx, 1",
        "cmp ecx, 16",
        "jne 26b",
        "sub edi, 1",
        "jne 23b",
        "jmp 22f",
        "21:",
        "22:",
        "mov eax, ebp",
        "mov ebx, DWORD PTR [eax+112]",
        "mov esi, DWORD PTR [eax+116]",
        "mov edi, DWORD PTR [eax+120]",
        "mov ebp, DWORD PTR [eax+124]",
        "ret",
        vg_md5_update = sym super::md5::vg_md5_update,
        vg_md5_finalize = sym super::md5::vg_md5_finalize,
    )
}

/// PBKDF2-HMAC-MD5 (RFC 8018 §5.2, with HMAC-MD5 as the pseudorandom function): writes the `out_len`-byte key derived from the `password_len` bytes at `password` and the `salt_len` bytes at `salt` with `c` iterations to `out`. Calls the verified MD5 and HMAC-MD5 functions and `vg_pbkdf2_hmac_md5_iterate`.
///
/// Contract: `VG.Spec.Hmac.Instance.pbkdf2Contract` of `VG.Spec.Hmac.md5I`. Constant time: only the pointers, the lengths and `c` may affect timing, not the password, the salt or the key.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `password` must be valid for reads of `password_len` bytes.
/// * `salt` must be valid for reads of `salt_len` bytes.
/// * `out` must be valid for reads and writes of `out_len` bytes.
/// * `scratch` must be valid for reads and writes of 1024 bytes.
/// * `c` must be positive, and `out_len` at most `(2^32 - 1) * 16`.
/// * The contents of `scratch` on return are unspecified.
/// * `out` and `scratch` must not overlap each other, `password` or `salt` (distinct Rust objects never do).
/// * None of `password`, `salt`, `out` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 76 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_pbkdf2_hmac_md5(password: *const u8, password_len: usize, salt: *const u8, salt_len: usize, c: u32, out: *mut u8, out_len: usize, scratch: *mut [u64; 128]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+32]",
        "mov DWORD PTR [eax+384], ebx",
        "mov DWORD PTR [eax+388], esi",
        "mov DWORD PTR [eax+392], edi",
        "mov DWORD PTR [eax+396], ebp",
        "mov ebp, eax",
        "mov ecx, DWORD PTR [esp+8]",
        "cmp ecx, 65",
        "jae 20f",
        "mov edx, DWORD PTR [esp+4]",
        "jmp 21f",
        "20:",
        "mov edi, ebp",
        "add edi, 640",
        "push edi",
        "call {vg_md5_init}",
        "pop eax",
        "mov eax, 0",
        "mov esi, 0",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, DWORD PTR [esp+4]",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push esi",
        "push edi",
        "call {vg_md5_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+8]",
        "mov ecx, 0",
        "mov edx, ebp",
        "add edx, 752",
        "push ebp",
        "push edx",
        "push ecx",
        "push eax",
        "push edi",
        "call {vg_md5_finalize}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov edx, ebp",
        "add edx, 752",
        "mov ecx, 16",
        "21:",
        "mov edi, ebp",
        "add edi, 400",
        "mov esi, ebp",
        "add esi, 480",
        "push ebp",
        "push ecx",
        "push edx",
        "push esi",
        "push edi",
        "call {vg_hmac_md5_init}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ecx, 0",
        "22:",
        "mov eax, ebp",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax+400]",
        "mov eax, ebp",
        "add eax, ecx",
        "mov BYTE PTR [eax+560], dl",
        "add ecx, 1",
        "cmp ecx, 80",
        "jne 22b",
        "mov edi, ebp",
        "add edi, 560",
        "mov eax, 0",
        "mov esi, 64",
        "mov ecx, DWORD PTR [esp+16]",
        "mov edx, DWORD PTR [esp+12]",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push esi",
        "push edi",
        "call {vg_md5_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, 1",
        "bswap eax",
        "mov DWORD PTR [ebp+768], eax",
        "mov ebx, 0",
        "mov ecx, DWORD PTR [esp+28]",
        "test ecx, ecx",
        "je 23f",
        "25:",
        "mov ecx, 0",
        "26:",
        "mov eax, ebp",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax+560]",
        "mov eax, ebp",
        "add eax, ecx",
        "mov BYTE PTR [eax+640], dl",
        "add ecx, 1",
        "cmp ecx, 80",
        "jne 26b",
        "mov edi, ebp",
        "add edi, 640",
        "mov esi, DWORD PTR [esp+16]",
        "add esi, 64",
        "mov eax, 0",
        "mov ecx, 4",
        "mov edx, ebp",
        "add edx, 768",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push esi",
        "push edi",
        "call {vg_md5_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov edx, ebp",
        "add edx, 640",
        "mov esi, ebp",
        "add esi, 480",
        "mov eax, DWORD PTR [esp+16]",
        "add eax, 68",
        "mov ecx, 0",
        "mov edi, ebp",
        "add edi, 720",
        "push ebp",
        "push edi",
        "push ecx",
        "push eax",
        "push esi",
        "push edx",
        "call {vg_hmac_md5_finalize}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ecx, 0",
        "27:",
        "mov eax, ebp",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax+720]",
        "mov eax, ebp",
        "add eax, ecx",
        "mov BYTE PTR [eax+736], dl",
        "add ecx, 1",
        "cmp ecx, 16",
        "jne 27b",
        "mov esi, ebp",
        "add esi, 400",
        "mov eax, ebp",
        "add eax, 720",
        "mov ecx, DWORD PTR [esp+20]",
        "sub ecx, 1",
        "mov edx, ebp",
        "add edx, 736",
        "push ebp",
        "push edx",
        "push ecx",
        "push eax",
        "push esi",
        "call {vg_pbkdf2_hmac_md5_iterate}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ecx, DWORD PTR [esp+28]",
        "sub ecx, ebx",
        "cmp ecx, 16",
        "jb 28f",
        "mov ecx, 16",
        "jmp 29f",
        "28:",
        "29:",
        "mov esi, ecx",
        "mov edi, DWORD PTR [esp+24]",
        "add edi, ebx",
        "mov ecx, 0",
        "210:",
        "mov eax, ebp",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax+736]",
        "mov eax, edi",
        "add eax, ecx",
        "mov BYTE PTR [eax], dl",
        "add ecx, 1",
        "cmp ecx, esi",
        "jne 210b",
        "add ebx, esi",
        "mov eax, DWORD PTR [ebp+768]",
        "bswap eax",
        "add eax, 1",
        "bswap eax",
        "mov DWORD PTR [ebp+768], eax",
        "mov eax, DWORD PTR [esp+28]",
        "cmp ebx, eax",
        "jne 25b",
        "jmp 24f",
        "23:",
        "24:",
        "mov eax, ebp",
        "mov ebx, DWORD PTR [eax+384]",
        "mov esi, DWORD PTR [eax+388]",
        "mov edi, DWORD PTR [eax+392]",
        "mov ebp, DWORD PTR [eax+396]",
        "ret",
        vg_md5_init = sym super::md5::vg_md5_init,
        vg_md5_update = sym super::md5::vg_md5_update,
        vg_md5_finalize = sym super::md5::vg_md5_finalize,
        vg_hmac_md5_init = sym super::hmac_md5::vg_hmac_md5_init,
        vg_hmac_md5_finalize = sym super::hmac_md5::vg_hmac_md5_finalize,
        vg_pbkdf2_hmac_md5_iterate = sym super::pbkdf2_md5::vg_pbkdf2_hmac_md5_iterate,
    )
}
