// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `pbkdf2_sha1` functions for `x86`.
#![allow(dead_code)]

/// Runs `n` steps of PBKDF2-HMAC-SHA-1's iteration: if, for a 64-byte key `K₀`, the SHA-1 streaming state in bytes 0 to 83 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 84 to 167 represents `K₀ ⊕ opad` (as `vg_hmac_sha1_init` leaves them), repeats `U ← HMAC-SHA-1 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.sha1I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `key` must be valid for reads of 168 bytes.
/// * `u` must be valid for reads of 20 bytes.
/// * `t` must be valid for reads and writes of 20 bytes.
/// * `scratch` must be valid for reads and writes of 448 bytes.
/// * The contents of `scratch` on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u` (distinct Rust objects never do).
/// * None of `key`, `u`, `t` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 48 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_pbkdf2_hmac_sha1_iterate(key: *const [u8; 168], u: *const [u8; 20], n: u32, t: *mut [u8; 20], scratch: *mut [u64; 56]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+20]",
        "mov DWORD PTR [eax+160], ebx",
        "mov DWORD PTR [eax+164], esi",
        "mov DWORD PTR [eax+168], edi",
        "mov DWORD PTR [eax+172], ebp",
        "mov ebp, eax",
        "mov edi, DWORD PTR [esp+12]",
        "mov esi, DWORD PTR [esp+8]",
        "mov ecx, 0",
        "20:",
        "mov eax, esi",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax]",
        "mov eax, ebp",
        "add eax, ecx",
        "mov BYTE PTR [eax+280], dl",
        "add ecx, 1",
        "cmp ecx, 20",
        "jne 20b",
        "test edi, edi",
        "je 21f",
        "23:",
        "mov esi, DWORD PTR [esp+4]",
        "mov ecx, 0",
        "24:",
        "mov eax, esi",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax]",
        "mov eax, ebp",
        "add eax, ecx",
        "mov BYTE PTR [eax+176], dl",
        "add ecx, 1",
        "cmp ecx, 84",
        "jne 24b",
        "mov ebx, ebp",
        "add ebx, 176",
        "mov eax, 0",
        "mov esi, 64",
        "mov ecx, 20",
        "mov edx, ebp",
        "add edx, 280",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push esi",
        "push ebx",
        "call {vg_sha1_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebx, ebp",
        "add ebx, 176",
        "mov eax, 84",
        "mov ecx, 0",
        "mov edx, ebp",
        "add edx, 260",
        "push ebp",
        "push edx",
        "push ecx",
        "push eax",
        "push ebx",
        "call {vg_sha1_finalize}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov esi, DWORD PTR [esp+4]",
        "mov ecx, 0",
        "25:",
        "mov eax, esi",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax+84]",
        "mov eax, ebp",
        "add eax, ecx",
        "mov BYTE PTR [eax+176], dl",
        "add ecx, 1",
        "cmp ecx, 84",
        "jne 25b",
        "mov ebx, ebp",
        "add ebx, 176",
        "mov eax, 0",
        "mov esi, 64",
        "mov ecx, 20",
        "mov edx, ebp",
        "add edx, 260",
        "push ebp",
        "push ecx",
        "push edx",
        "push eax",
        "push esi",
        "push ebx",
        "call {vg_sha1_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebx, ebp",
        "add ebx, 176",
        "mov eax, 84",
        "mov ecx, 0",
        "mov edx, ebp",
        "add edx, 280",
        "push ebp",
        "push edx",
        "push ecx",
        "push eax",
        "push ebx",
        "call {vg_sha1_finalize}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov esi, DWORD PTR [esp+16]",
        "mov ecx, 0",
        "26:",
        "mov eax, ebp",
        "add eax, ecx",
        "movzx edx, BYTE PTR [eax+280]",
        "mov eax, esi",
        "add eax, ecx",
        "movzx ebx, BYTE PTR [eax]",
        "xor edx, ebx",
        "mov BYTE PTR [eax], dl",
        "add ecx, 1",
        "cmp ecx, 20",
        "jne 26b",
        "sub edi, 1",
        "jne 23b",
        "jmp 22f",
        "21:",
        "22:",
        "mov eax, ebp",
        "mov ebx, DWORD PTR [eax+160]",
        "mov esi, DWORD PTR [eax+164]",
        "mov edi, DWORD PTR [eax+168]",
        "mov ebp, DWORD PTR [eax+172]",
        "ret",
        vg_sha1_update = sym super::sha1::vg_sha1_update,
        vg_sha1_finalize = sym super::sha1::vg_sha1_finalize,
    )
}
