// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `poly1305` functions for `x86`.
#![allow(dead_code)]

/// Starts a Poly1305 computation (RFC 8439 §2.5): makes the streaming state `*state` represent the empty message under the 32-byte one-time key `*key`.
///
/// Contract: `VG.Spec.Poly1305.initContract`. The streaming state is the accumulator followed by the key (`VG.Spec.Poly1305.Repr`). Constant time: only the pointers may affect timing, not the key.
///
/// # Safety
///
/// * `state` must be valid for writes of 128 bytes.
/// * `key` must be valid for reads of 32 bytes.
/// * `state` must not overlap `key`, the arguments or the return address on the stack, and nothing may wrap around the end of the address space (distinct Rust objects never do).
/// * `state` must not overlap `key` or the arguments on the stack (distinct Rust objects never do).
/// * Neither `state` nor `key` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_poly1305_init(state: *mut [u64; 16], key: *const [u8; 32]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, DWORD PTR [ecx]",
        "mov DWORD PTR [eax+24], edx",
        "mov edx, DWORD PTR [ecx+4]",
        "mov DWORD PTR [eax+28], edx",
        "mov edx, DWORD PTR [ecx+8]",
        "mov DWORD PTR [eax+32], edx",
        "mov edx, DWORD PTR [ecx+12]",
        "mov DWORD PTR [eax+36], edx",
        "mov edx, DWORD PTR [ecx+16]",
        "mov DWORD PTR [eax+40], edx",
        "mov edx, DWORD PTR [ecx+20]",
        "mov DWORD PTR [eax+44], edx",
        "mov edx, DWORD PTR [ecx+24]",
        "mov DWORD PTR [eax+48], edx",
        "mov edx, DWORD PTR [ecx+28]",
        "mov DWORD PTR [eax+52], edx",
        "mov edx, 0",
        "mov DWORD PTR [eax], edx",
        "mov DWORD PTR [eax+4], edx",
        "mov DWORD PTR [eax+8], edx",
        "mov DWORD PTR [eax+12], edx",
        "mov DWORD PTR [eax+16], edx",
        "mov DWORD PTR [eax+20], edx",
        "ret",
    )
}

/// Absorbs whole blocks into a Poly1305 computation: if the streaming state `*state` represents a message under a key, it then represents that message followed by the `n` 16-byte blocks at `blocks`, under the same key.
///
/// Contract: `VG.Spec.Poly1305.blocksContract`. Constant time: only the pointers and `n` may affect timing, not the state or the data.
///
/// # Safety
///
/// * `state` must be valid for reads and writes of 128 bytes.
/// * `blocks` must be valid for reads of `16 * n` bytes.
/// * `state` must not overlap `blocks`, the arguments or the return address on the stack, and nothing may wrap around the end of the address space (distinct Rust objects never do).
/// * `state` must not overlap `blocks` or the arguments on the stack (distinct Rust objects never do).
/// * Neither `state` nor `blocks` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_poly1305_blocks(state: *mut [u64; 16], blocks: *const [u8; 16], n: usize) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+4]",
        "mov DWORD PTR [eax+100], ebx",
        "mov DWORD PTR [eax+104], esi",
        "mov DWORD PTR [eax+108], edi",
        "mov DWORD PTR [eax+112], ebp",
        "mov edi, eax",
        "mov eax, DWORD PTR [edi+24]",
        "and eax, 268435455",
        "mov DWORD PTR [edi+56], eax",
        "mov eax, DWORD PTR [edi+28]",
        "and eax, 268435452",
        "mov DWORD PTR [edi+60], eax",
        "mov ecx, eax",
        "shr ecx, 2",
        "add eax, ecx",
        "mov DWORD PTR [edi+72], eax",
        "mov eax, DWORD PTR [edi+32]",
        "and eax, 268435452",
        "mov DWORD PTR [edi+64], eax",
        "mov ecx, eax",
        "shr ecx, 2",
        "add eax, ecx",
        "mov DWORD PTR [edi+76], eax",
        "mov eax, DWORD PTR [edi+36]",
        "and eax, 268435452",
        "mov DWORD PTR [edi+68], eax",
        "mov ecx, eax",
        "shr ecx, 2",
        "add eax, ecx",
        "mov DWORD PTR [edi+80], eax",
        "mov esi, DWORD PTR [esp+8]",
        "mov ecx, DWORD PTR [esp+12]",
        "mov DWORD PTR [edi+116], ecx",
        "test ecx, ecx",
        "je 20f",
        "22:",
        "mov eax, DWORD PTR [edi]",
        "add eax, DWORD PTR [esi]",
        "mov DWORD PTR [edi], eax",
        "mov eax, DWORD PTR [edi+4]",
        "adc eax, DWORD PTR [esi+4]",
        "mov DWORD PTR [edi+4], eax",
        "mov eax, DWORD PTR [edi+8]",
        "adc eax, DWORD PTR [esi+8]",
        "mov DWORD PTR [edi+8], eax",
        "mov eax, DWORD PTR [edi+12]",
        "adc eax, DWORD PTR [esi+12]",
        "mov DWORD PTR [edi+12], eax",
        "mov eax, DWORD PTR [edi+16]",
        "adc eax, 1",
        "mov DWORD PTR [edi+16], eax",
        "mov ebx, 0",
        "mov ebp, 0",
        "mov eax, DWORD PTR [edi]",
        "mov ecx, DWORD PTR [edi+56]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+4]",
        "mov ecx, DWORD PTR [edi+80]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+8]",
        "mov ecx, DWORD PTR [edi+76]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+12]",
        "mov ecx, DWORD PTR [edi+72]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov DWORD PTR [edi+84], ebx",
        "mov ebx, ebp",
        "mov ebp, 0",
        "mov eax, DWORD PTR [edi]",
        "mov ecx, DWORD PTR [edi+60]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+4]",
        "mov ecx, DWORD PTR [edi+56]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+8]",
        "mov ecx, DWORD PTR [edi+80]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+12]",
        "mov ecx, DWORD PTR [edi+76]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+16]",
        "mov ecx, DWORD PTR [edi+72]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov DWORD PTR [edi+88], ebx",
        "mov ebx, ebp",
        "mov ebp, 0",
        "mov eax, DWORD PTR [edi]",
        "mov ecx, DWORD PTR [edi+64]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+4]",
        "mov ecx, DWORD PTR [edi+60]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+8]",
        "mov ecx, DWORD PTR [edi+56]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+12]",
        "mov ecx, DWORD PTR [edi+80]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+16]",
        "mov ecx, DWORD PTR [edi+76]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov DWORD PTR [edi+92], ebx",
        "mov ebx, ebp",
        "mov ebp, 0",
        "mov eax, DWORD PTR [edi]",
        "mov ecx, DWORD PTR [edi+68]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+4]",
        "mov ecx, DWORD PTR [edi+64]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+8]",
        "mov ecx, DWORD PTR [edi+60]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+12]",
        "mov ecx, DWORD PTR [edi+56]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+16]",
        "mov ecx, DWORD PTR [edi+80]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov DWORD PTR [edi+96], ebx",
        "mov ebx, ebp",
        "mov ebp, 0",
        "mov eax, DWORD PTR [edi+16]",
        "mov ecx, DWORD PTR [edi+56]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, ebx",
        "shr eax, 2",
        "mov ecx, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, ecx",
        "and ebx, 3",
        "add eax, DWORD PTR [edi+84]",
        "mov DWORD PTR [edi], eax",
        "mov eax, DWORD PTR [edi+88]",
        "adc eax, 0",
        "mov DWORD PTR [edi+4], eax",
        "mov eax, DWORD PTR [edi+92]",
        "adc eax, 0",
        "mov DWORD PTR [edi+8], eax",
        "mov eax, DWORD PTR [edi+96]",
        "adc eax, 0",
        "mov DWORD PTR [edi+12], eax",
        "adc ebx, 0",
        "mov DWORD PTR [edi+16], ebx",
        "add esi, 16",
        "mov ecx, DWORD PTR [edi+116]",
        "sub ecx, 1",
        "mov DWORD PTR [edi+116], ecx",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [edi]",
        "add eax, 5",
        "mov DWORD PTR [edi+84], eax",
        "mov eax, DWORD PTR [edi+4]",
        "adc eax, 0",
        "mov DWORD PTR [edi+88], eax",
        "mov eax, DWORD PTR [edi+8]",
        "adc eax, 0",
        "mov DWORD PTR [edi+92], eax",
        "mov eax, DWORD PTR [edi+12]",
        "adc eax, 0",
        "mov DWORD PTR [edi+96], eax",
        "mov eax, DWORD PTR [edi+16]",
        "adc eax, 0",
        "mov edx, eax",
        "shr eax, 2",
        "mov ebp, 0",
        "sub ebp, eax",
        "mov eax, DWORD PTR [edi]",
        "mov ecx, DWORD PTR [edi+84]",
        "xor ecx, eax",
        "and ecx, ebp",
        "xor eax, ecx",
        "mov DWORD PTR [edi], eax",
        "mov eax, DWORD PTR [edi+4]",
        "mov ecx, DWORD PTR [edi+88]",
        "xor ecx, eax",
        "and ecx, ebp",
        "xor eax, ecx",
        "mov DWORD PTR [edi+4], eax",
        "mov eax, DWORD PTR [edi+8]",
        "mov ecx, DWORD PTR [edi+92]",
        "xor ecx, eax",
        "and ecx, ebp",
        "xor eax, ecx",
        "mov DWORD PTR [edi+8], eax",
        "mov eax, DWORD PTR [edi+12]",
        "mov ecx, DWORD PTR [edi+96]",
        "xor ecx, eax",
        "and ecx, ebp",
        "xor eax, ecx",
        "mov DWORD PTR [edi+12], eax",
        "mov eax, DWORD PTR [edi+16]",
        "xor edx, eax",
        "and edx, ebp",
        "xor eax, edx",
        "and eax, 3",
        "mov DWORD PTR [edi+16], eax",
        "mov eax, 0",
        "mov DWORD PTR [edi+20], eax",
        "mov eax, edi",
        "mov ebx, DWORD PTR [eax+100]",
        "mov esi, DWORD PTR [eax+104]",
        "mov edi, DWORD PTR [eax+108]",
        "mov ebp, DWORD PTR [eax+112]",
        "ret",
    )
}

/// Finishes a Poly1305 computation: if the streaming state `*state` represents a message under a key, writes the tag of that message followed by the `len` bytes at `tail`, under that key, to `*out`.
///
/// Contract: `VG.Spec.Poly1305.finalizeTailContract`. Constant time: only the pointers and `len` may affect timing, not the state or the data.
///
/// # Safety
///
/// * `len` must be less than 16.
/// * `state` must be valid for reads and writes of 128 bytes; its contents on return are unspecified.
/// * `tail` must be valid for reads of `len` bytes.
/// * `out` must be valid for writes of 16 bytes.
/// * These three regions must not overlap each other, and `state` and `out` must not overlap the arguments or the return address on the stack; nothing may wrap around the end of the address space (distinct Rust objects never do).
/// * `state` and `out` must not overlap each other, `tail` or the arguments on the stack (distinct Rust objects never do).
/// * None of `state`, `tail` and `out` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_poly1305_finalize(state: *mut [u64; 16], tail: *const u8, len: usize, out: *mut [u8; 16]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+4]",
        "mov DWORD PTR [eax+100], ebx",
        "mov DWORD PTR [eax+104], esi",
        "mov DWORD PTR [eax+108], edi",
        "mov DWORD PTR [eax+112], ebp",
        "mov edi, eax",
        "mov eax, DWORD PTR [edi+24]",
        "and eax, 268435455",
        "mov DWORD PTR [edi+56], eax",
        "mov eax, DWORD PTR [edi+28]",
        "and eax, 268435452",
        "mov DWORD PTR [edi+60], eax",
        "mov ecx, eax",
        "shr ecx, 2",
        "add eax, ecx",
        "mov DWORD PTR [edi+72], eax",
        "mov eax, DWORD PTR [edi+32]",
        "and eax, 268435452",
        "mov DWORD PTR [edi+64], eax",
        "mov ecx, eax",
        "shr ecx, 2",
        "add eax, ecx",
        "mov DWORD PTR [edi+76], eax",
        "mov eax, DWORD PTR [edi+36]",
        "and eax, 268435452",
        "mov DWORD PTR [edi+68], eax",
        "mov ecx, eax",
        "shr ecx, 2",
        "add eax, ecx",
        "mov DWORD PTR [edi+80], eax",
        "mov ecx, DWORD PTR [esp+12]",
        "test ecx, ecx",
        "je 20f",
        "mov ebx, DWORD PTR [esp+16]",
        "mov eax, 0",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], eax",
        "mov DWORD PTR [ebx+8], eax",
        "mov DWORD PTR [ebx+12], eax",
        "mov esi, DWORD PTR [esp+8]",
        "mov ecx, DWORD PTR [esp+12]",
        "22:",
        "movzx eax, BYTE PTR [esi]",
        "mov BYTE PTR [ebx], al",
        "add esi, 1",
        "add ebx, 1",
        "sub ecx, 1",
        "jne 22b",
        "mov eax, 1",
        "mov BYTE PTR [ebx], al",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [edi]",
        "add eax, DWORD PTR [esi]",
        "mov DWORD PTR [edi], eax",
        "mov eax, DWORD PTR [edi+4]",
        "adc eax, DWORD PTR [esi+4]",
        "mov DWORD PTR [edi+4], eax",
        "mov eax, DWORD PTR [edi+8]",
        "adc eax, DWORD PTR [esi+8]",
        "mov DWORD PTR [edi+8], eax",
        "mov eax, DWORD PTR [edi+12]",
        "adc eax, DWORD PTR [esi+12]",
        "mov DWORD PTR [edi+12], eax",
        "mov eax, DWORD PTR [edi+16]",
        "adc eax, 0",
        "mov DWORD PTR [edi+16], eax",
        "mov ebx, 0",
        "mov ebp, 0",
        "mov eax, DWORD PTR [edi]",
        "mov ecx, DWORD PTR [edi+56]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+4]",
        "mov ecx, DWORD PTR [edi+80]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+8]",
        "mov ecx, DWORD PTR [edi+76]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+12]",
        "mov ecx, DWORD PTR [edi+72]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov DWORD PTR [edi+84], ebx",
        "mov ebx, ebp",
        "mov ebp, 0",
        "mov eax, DWORD PTR [edi]",
        "mov ecx, DWORD PTR [edi+60]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+4]",
        "mov ecx, DWORD PTR [edi+56]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+8]",
        "mov ecx, DWORD PTR [edi+80]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+12]",
        "mov ecx, DWORD PTR [edi+76]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+16]",
        "mov ecx, DWORD PTR [edi+72]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov DWORD PTR [edi+88], ebx",
        "mov ebx, ebp",
        "mov ebp, 0",
        "mov eax, DWORD PTR [edi]",
        "mov ecx, DWORD PTR [edi+64]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+4]",
        "mov ecx, DWORD PTR [edi+60]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+8]",
        "mov ecx, DWORD PTR [edi+56]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+12]",
        "mov ecx, DWORD PTR [edi+80]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+16]",
        "mov ecx, DWORD PTR [edi+76]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov DWORD PTR [edi+92], ebx",
        "mov ebx, ebp",
        "mov ebp, 0",
        "mov eax, DWORD PTR [edi]",
        "mov ecx, DWORD PTR [edi+68]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+4]",
        "mov ecx, DWORD PTR [edi+64]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+8]",
        "mov ecx, DWORD PTR [edi+60]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+12]",
        "mov ecx, DWORD PTR [edi+56]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, DWORD PTR [edi+16]",
        "mov ecx, DWORD PTR [edi+80]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov DWORD PTR [edi+96], ebx",
        "mov ebx, ebp",
        "mov ebp, 0",
        "mov eax, DWORD PTR [edi+16]",
        "mov ecx, DWORD PTR [edi+56]",
        "mul ecx",
        "add ebx, eax",
        "adc ebp, edx",
        "mov eax, ebx",
        "shr eax, 2",
        "mov ecx, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, ecx",
        "and ebx, 3",
        "add eax, DWORD PTR [edi+84]",
        "mov DWORD PTR [edi], eax",
        "mov eax, DWORD PTR [edi+88]",
        "adc eax, 0",
        "mov DWORD PTR [edi+4], eax",
        "mov eax, DWORD PTR [edi+92]",
        "adc eax, 0",
        "mov DWORD PTR [edi+8], eax",
        "mov eax, DWORD PTR [edi+96]",
        "adc eax, 0",
        "mov DWORD PTR [edi+12], eax",
        "adc ebx, 0",
        "mov DWORD PTR [edi+16], ebx",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [edi]",
        "add eax, 5",
        "mov DWORD PTR [edi+84], eax",
        "mov eax, DWORD PTR [edi+4]",
        "adc eax, 0",
        "mov DWORD PTR [edi+88], eax",
        "mov eax, DWORD PTR [edi+8]",
        "adc eax, 0",
        "mov DWORD PTR [edi+92], eax",
        "mov eax, DWORD PTR [edi+12]",
        "adc eax, 0",
        "mov DWORD PTR [edi+96], eax",
        "mov eax, DWORD PTR [edi+16]",
        "adc eax, 0",
        "mov edx, eax",
        "shr eax, 2",
        "mov ebp, 0",
        "sub ebp, eax",
        "mov eax, DWORD PTR [edi]",
        "mov ecx, DWORD PTR [edi+84]",
        "xor ecx, eax",
        "and ecx, ebp",
        "xor eax, ecx",
        "mov DWORD PTR [edi], eax",
        "mov eax, DWORD PTR [edi+4]",
        "mov ecx, DWORD PTR [edi+88]",
        "xor ecx, eax",
        "and ecx, ebp",
        "xor eax, ecx",
        "mov DWORD PTR [edi+4], eax",
        "mov eax, DWORD PTR [edi+8]",
        "mov ecx, DWORD PTR [edi+92]",
        "xor ecx, eax",
        "and ecx, ebp",
        "xor eax, ecx",
        "mov DWORD PTR [edi+8], eax",
        "mov eax, DWORD PTR [edi+12]",
        "mov ecx, DWORD PTR [edi+96]",
        "xor ecx, eax",
        "and ecx, ebp",
        "xor eax, ecx",
        "mov DWORD PTR [edi+12], eax",
        "mov eax, DWORD PTR [edi+16]",
        "xor edx, eax",
        "and edx, ebp",
        "xor eax, edx",
        "and eax, 3",
        "mov DWORD PTR [edi+16], eax",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [edi]",
        "add eax, DWORD PTR [edi+40]",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [edi+4]",
        "adc eax, DWORD PTR [edi+44]",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [edi+8]",
        "adc eax, DWORD PTR [edi+48]",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [edi+12]",
        "adc eax, DWORD PTR [edi+52]",
        "mov DWORD PTR [esi+12], eax",
        "mov eax, edi",
        "mov ebx, DWORD PTR [eax+100]",
        "mov esi, DWORD PTR [eax+104]",
        "mov edi, DWORD PTR [eax+108]",
        "mov ebp, DWORD PTR [eax+112]",
        "ret",
    )
}
