// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `scrypt` functions for `x86`.
#![allow(dead_code)]

/// The Salsa20/8 Core (RFC 7914 §3): replaces the 64 bytes `*b` by their Salsa20/8 Core (the 16 little-endian words, 8 rounds, then the input added word by word).
///
/// Contract: `VG.Spec.Scrypt.salsaContract`. Constant time: only the pointers may affect timing, not the data.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `b` must be valid for reads and writes of 64 bytes.
/// * `scratch` must be valid for reads and writes of 64 bytes. It is working space: its contents on return are unspecified.
/// * `b` and `scratch` must not overlap each other (distinct Rust objects never do).
/// * Neither `b` nor `scratch` may overlap the arguments on the stack, overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_salsa20_8(b: *mut [u8; 64], scratch: *mut [u32; 16]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, DWORD PTR [eax]",
        "mov DWORD PTR [ecx], edx",
        "mov edx, DWORD PTR [eax+4]",
        "mov DWORD PTR [ecx+4], edx",
        "mov edx, DWORD PTR [eax+8]",
        "mov DWORD PTR [ecx+8], edx",
        "mov edx, DWORD PTR [eax+12]",
        "mov DWORD PTR [ecx+12], edx",
        "mov edx, DWORD PTR [eax+16]",
        "mov DWORD PTR [ecx+16], edx",
        "mov edx, DWORD PTR [eax+20]",
        "mov DWORD PTR [ecx+20], edx",
        "mov edx, DWORD PTR [eax+24]",
        "mov DWORD PTR [ecx+24], edx",
        "mov edx, DWORD PTR [eax+28]",
        "mov DWORD PTR [ecx+28], edx",
        "mov edx, DWORD PTR [eax+32]",
        "mov DWORD PTR [ecx+32], edx",
        "mov edx, DWORD PTR [eax+36]",
        "mov DWORD PTR [ecx+36], edx",
        "mov edx, DWORD PTR [eax+40]",
        "mov DWORD PTR [ecx+40], edx",
        "mov edx, DWORD PTR [eax+44]",
        "mov DWORD PTR [ecx+44], edx",
        "mov edx, DWORD PTR [eax+48]",
        "mov DWORD PTR [ecx+48], edx",
        "mov edx, DWORD PTR [eax+52]",
        "mov DWORD PTR [ecx+52], edx",
        "mov edx, DWORD PTR [eax+56]",
        "mov DWORD PTR [ecx+56], edx",
        "mov edx, DWORD PTR [eax+60]",
        "mov DWORD PTR [ecx+60], edx",
        "mov edx, DWORD PTR [ecx]",
        "add edx, DWORD PTR [ecx+48]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+16]",
        "mov DWORD PTR [ecx+16], edx",
        "mov edx, DWORD PTR [ecx+16]",
        "add edx, DWORD PTR [ecx]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+32]",
        "mov DWORD PTR [ecx+32], edx",
        "mov edx, DWORD PTR [ecx+32]",
        "add edx, DWORD PTR [ecx+16]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+48]",
        "mov DWORD PTR [ecx+48], edx",
        "mov edx, DWORD PTR [ecx+48]",
        "add edx, DWORD PTR [ecx+32]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx]",
        "mov DWORD PTR [ecx], edx",
        "mov edx, DWORD PTR [ecx+20]",
        "add edx, DWORD PTR [ecx+4]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+36]",
        "mov DWORD PTR [ecx+36], edx",
        "mov edx, DWORD PTR [ecx+36]",
        "add edx, DWORD PTR [ecx+20]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+52]",
        "mov DWORD PTR [ecx+52], edx",
        "mov edx, DWORD PTR [ecx+52]",
        "add edx, DWORD PTR [ecx+36]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+4]",
        "mov DWORD PTR [ecx+4], edx",
        "mov edx, DWORD PTR [ecx+4]",
        "add edx, DWORD PTR [ecx+52]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+20]",
        "mov DWORD PTR [ecx+20], edx",
        "mov edx, DWORD PTR [ecx+40]",
        "add edx, DWORD PTR [ecx+24]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+56]",
        "mov DWORD PTR [ecx+56], edx",
        "mov edx, DWORD PTR [ecx+56]",
        "add edx, DWORD PTR [ecx+40]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+8]",
        "mov DWORD PTR [ecx+8], edx",
        "mov edx, DWORD PTR [ecx+8]",
        "add edx, DWORD PTR [ecx+56]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+24]",
        "mov DWORD PTR [ecx+24], edx",
        "mov edx, DWORD PTR [ecx+24]",
        "add edx, DWORD PTR [ecx+8]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+40]",
        "mov DWORD PTR [ecx+40], edx",
        "mov edx, DWORD PTR [ecx+60]",
        "add edx, DWORD PTR [ecx+44]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+12]",
        "mov DWORD PTR [ecx+12], edx",
        "mov edx, DWORD PTR [ecx+12]",
        "add edx, DWORD PTR [ecx+60]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+28]",
        "mov DWORD PTR [ecx+28], edx",
        "mov edx, DWORD PTR [ecx+28]",
        "add edx, DWORD PTR [ecx+12]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+44]",
        "mov DWORD PTR [ecx+44], edx",
        "mov edx, DWORD PTR [ecx+44]",
        "add edx, DWORD PTR [ecx+28]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+60]",
        "mov DWORD PTR [ecx+60], edx",
        "mov edx, DWORD PTR [ecx]",
        "add edx, DWORD PTR [ecx+12]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+4]",
        "mov DWORD PTR [ecx+4], edx",
        "mov edx, DWORD PTR [ecx+4]",
        "add edx, DWORD PTR [ecx]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+8]",
        "mov DWORD PTR [ecx+8], edx",
        "mov edx, DWORD PTR [ecx+8]",
        "add edx, DWORD PTR [ecx+4]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+12]",
        "mov DWORD PTR [ecx+12], edx",
        "mov edx, DWORD PTR [ecx+12]",
        "add edx, DWORD PTR [ecx+8]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx]",
        "mov DWORD PTR [ecx], edx",
        "mov edx, DWORD PTR [ecx+20]",
        "add edx, DWORD PTR [ecx+16]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+24]",
        "mov DWORD PTR [ecx+24], edx",
        "mov edx, DWORD PTR [ecx+24]",
        "add edx, DWORD PTR [ecx+20]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+28]",
        "mov DWORD PTR [ecx+28], edx",
        "mov edx, DWORD PTR [ecx+28]",
        "add edx, DWORD PTR [ecx+24]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+16]",
        "mov DWORD PTR [ecx+16], edx",
        "mov edx, DWORD PTR [ecx+16]",
        "add edx, DWORD PTR [ecx+28]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+20]",
        "mov DWORD PTR [ecx+20], edx",
        "mov edx, DWORD PTR [ecx+40]",
        "add edx, DWORD PTR [ecx+36]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+44]",
        "mov DWORD PTR [ecx+44], edx",
        "mov edx, DWORD PTR [ecx+44]",
        "add edx, DWORD PTR [ecx+40]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+32]",
        "mov DWORD PTR [ecx+32], edx",
        "mov edx, DWORD PTR [ecx+32]",
        "add edx, DWORD PTR [ecx+44]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+36]",
        "mov DWORD PTR [ecx+36], edx",
        "mov edx, DWORD PTR [ecx+36]",
        "add edx, DWORD PTR [ecx+32]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+40]",
        "mov DWORD PTR [ecx+40], edx",
        "mov edx, DWORD PTR [ecx+60]",
        "add edx, DWORD PTR [ecx+56]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+48]",
        "mov DWORD PTR [ecx+48], edx",
        "mov edx, DWORD PTR [ecx+48]",
        "add edx, DWORD PTR [ecx+60]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+52]",
        "mov DWORD PTR [ecx+52], edx",
        "mov edx, DWORD PTR [ecx+52]",
        "add edx, DWORD PTR [ecx+48]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+56]",
        "mov DWORD PTR [ecx+56], edx",
        "mov edx, DWORD PTR [ecx+56]",
        "add edx, DWORD PTR [ecx+52]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+60]",
        "mov DWORD PTR [ecx+60], edx",
        "mov edx, DWORD PTR [ecx]",
        "add edx, DWORD PTR [ecx+48]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+16]",
        "mov DWORD PTR [ecx+16], edx",
        "mov edx, DWORD PTR [ecx+16]",
        "add edx, DWORD PTR [ecx]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+32]",
        "mov DWORD PTR [ecx+32], edx",
        "mov edx, DWORD PTR [ecx+32]",
        "add edx, DWORD PTR [ecx+16]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+48]",
        "mov DWORD PTR [ecx+48], edx",
        "mov edx, DWORD PTR [ecx+48]",
        "add edx, DWORD PTR [ecx+32]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx]",
        "mov DWORD PTR [ecx], edx",
        "mov edx, DWORD PTR [ecx+20]",
        "add edx, DWORD PTR [ecx+4]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+36]",
        "mov DWORD PTR [ecx+36], edx",
        "mov edx, DWORD PTR [ecx+36]",
        "add edx, DWORD PTR [ecx+20]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+52]",
        "mov DWORD PTR [ecx+52], edx",
        "mov edx, DWORD PTR [ecx+52]",
        "add edx, DWORD PTR [ecx+36]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+4]",
        "mov DWORD PTR [ecx+4], edx",
        "mov edx, DWORD PTR [ecx+4]",
        "add edx, DWORD PTR [ecx+52]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+20]",
        "mov DWORD PTR [ecx+20], edx",
        "mov edx, DWORD PTR [ecx+40]",
        "add edx, DWORD PTR [ecx+24]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+56]",
        "mov DWORD PTR [ecx+56], edx",
        "mov edx, DWORD PTR [ecx+56]",
        "add edx, DWORD PTR [ecx+40]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+8]",
        "mov DWORD PTR [ecx+8], edx",
        "mov edx, DWORD PTR [ecx+8]",
        "add edx, DWORD PTR [ecx+56]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+24]",
        "mov DWORD PTR [ecx+24], edx",
        "mov edx, DWORD PTR [ecx+24]",
        "add edx, DWORD PTR [ecx+8]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+40]",
        "mov DWORD PTR [ecx+40], edx",
        "mov edx, DWORD PTR [ecx+60]",
        "add edx, DWORD PTR [ecx+44]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+12]",
        "mov DWORD PTR [ecx+12], edx",
        "mov edx, DWORD PTR [ecx+12]",
        "add edx, DWORD PTR [ecx+60]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+28]",
        "mov DWORD PTR [ecx+28], edx",
        "mov edx, DWORD PTR [ecx+28]",
        "add edx, DWORD PTR [ecx+12]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+44]",
        "mov DWORD PTR [ecx+44], edx",
        "mov edx, DWORD PTR [ecx+44]",
        "add edx, DWORD PTR [ecx+28]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+60]",
        "mov DWORD PTR [ecx+60], edx",
        "mov edx, DWORD PTR [ecx]",
        "add edx, DWORD PTR [ecx+12]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+4]",
        "mov DWORD PTR [ecx+4], edx",
        "mov edx, DWORD PTR [ecx+4]",
        "add edx, DWORD PTR [ecx]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+8]",
        "mov DWORD PTR [ecx+8], edx",
        "mov edx, DWORD PTR [ecx+8]",
        "add edx, DWORD PTR [ecx+4]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+12]",
        "mov DWORD PTR [ecx+12], edx",
        "mov edx, DWORD PTR [ecx+12]",
        "add edx, DWORD PTR [ecx+8]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx]",
        "mov DWORD PTR [ecx], edx",
        "mov edx, DWORD PTR [ecx+20]",
        "add edx, DWORD PTR [ecx+16]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+24]",
        "mov DWORD PTR [ecx+24], edx",
        "mov edx, DWORD PTR [ecx+24]",
        "add edx, DWORD PTR [ecx+20]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+28]",
        "mov DWORD PTR [ecx+28], edx",
        "mov edx, DWORD PTR [ecx+28]",
        "add edx, DWORD PTR [ecx+24]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+16]",
        "mov DWORD PTR [ecx+16], edx",
        "mov edx, DWORD PTR [ecx+16]",
        "add edx, DWORD PTR [ecx+28]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+20]",
        "mov DWORD PTR [ecx+20], edx",
        "mov edx, DWORD PTR [ecx+40]",
        "add edx, DWORD PTR [ecx+36]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+44]",
        "mov DWORD PTR [ecx+44], edx",
        "mov edx, DWORD PTR [ecx+44]",
        "add edx, DWORD PTR [ecx+40]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+32]",
        "mov DWORD PTR [ecx+32], edx",
        "mov edx, DWORD PTR [ecx+32]",
        "add edx, DWORD PTR [ecx+44]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+36]",
        "mov DWORD PTR [ecx+36], edx",
        "mov edx, DWORD PTR [ecx+36]",
        "add edx, DWORD PTR [ecx+32]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+40]",
        "mov DWORD PTR [ecx+40], edx",
        "mov edx, DWORD PTR [ecx+60]",
        "add edx, DWORD PTR [ecx+56]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+48]",
        "mov DWORD PTR [ecx+48], edx",
        "mov edx, DWORD PTR [ecx+48]",
        "add edx, DWORD PTR [ecx+60]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+52]",
        "mov DWORD PTR [ecx+52], edx",
        "mov edx, DWORD PTR [ecx+52]",
        "add edx, DWORD PTR [ecx+48]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+56]",
        "mov DWORD PTR [ecx+56], edx",
        "mov edx, DWORD PTR [ecx+56]",
        "add edx, DWORD PTR [ecx+52]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+60]",
        "mov DWORD PTR [ecx+60], edx",
        "mov edx, DWORD PTR [ecx]",
        "add edx, DWORD PTR [ecx+48]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+16]",
        "mov DWORD PTR [ecx+16], edx",
        "mov edx, DWORD PTR [ecx+16]",
        "add edx, DWORD PTR [ecx]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+32]",
        "mov DWORD PTR [ecx+32], edx",
        "mov edx, DWORD PTR [ecx+32]",
        "add edx, DWORD PTR [ecx+16]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+48]",
        "mov DWORD PTR [ecx+48], edx",
        "mov edx, DWORD PTR [ecx+48]",
        "add edx, DWORD PTR [ecx+32]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx]",
        "mov DWORD PTR [ecx], edx",
        "mov edx, DWORD PTR [ecx+20]",
        "add edx, DWORD PTR [ecx+4]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+36]",
        "mov DWORD PTR [ecx+36], edx",
        "mov edx, DWORD PTR [ecx+36]",
        "add edx, DWORD PTR [ecx+20]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+52]",
        "mov DWORD PTR [ecx+52], edx",
        "mov edx, DWORD PTR [ecx+52]",
        "add edx, DWORD PTR [ecx+36]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+4]",
        "mov DWORD PTR [ecx+4], edx",
        "mov edx, DWORD PTR [ecx+4]",
        "add edx, DWORD PTR [ecx+52]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+20]",
        "mov DWORD PTR [ecx+20], edx",
        "mov edx, DWORD PTR [ecx+40]",
        "add edx, DWORD PTR [ecx+24]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+56]",
        "mov DWORD PTR [ecx+56], edx",
        "mov edx, DWORD PTR [ecx+56]",
        "add edx, DWORD PTR [ecx+40]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+8]",
        "mov DWORD PTR [ecx+8], edx",
        "mov edx, DWORD PTR [ecx+8]",
        "add edx, DWORD PTR [ecx+56]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+24]",
        "mov DWORD PTR [ecx+24], edx",
        "mov edx, DWORD PTR [ecx+24]",
        "add edx, DWORD PTR [ecx+8]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+40]",
        "mov DWORD PTR [ecx+40], edx",
        "mov edx, DWORD PTR [ecx+60]",
        "add edx, DWORD PTR [ecx+44]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+12]",
        "mov DWORD PTR [ecx+12], edx",
        "mov edx, DWORD PTR [ecx+12]",
        "add edx, DWORD PTR [ecx+60]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+28]",
        "mov DWORD PTR [ecx+28], edx",
        "mov edx, DWORD PTR [ecx+28]",
        "add edx, DWORD PTR [ecx+12]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+44]",
        "mov DWORD PTR [ecx+44], edx",
        "mov edx, DWORD PTR [ecx+44]",
        "add edx, DWORD PTR [ecx+28]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+60]",
        "mov DWORD PTR [ecx+60], edx",
        "mov edx, DWORD PTR [ecx]",
        "add edx, DWORD PTR [ecx+12]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+4]",
        "mov DWORD PTR [ecx+4], edx",
        "mov edx, DWORD PTR [ecx+4]",
        "add edx, DWORD PTR [ecx]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+8]",
        "mov DWORD PTR [ecx+8], edx",
        "mov edx, DWORD PTR [ecx+8]",
        "add edx, DWORD PTR [ecx+4]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+12]",
        "mov DWORD PTR [ecx+12], edx",
        "mov edx, DWORD PTR [ecx+12]",
        "add edx, DWORD PTR [ecx+8]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx]",
        "mov DWORD PTR [ecx], edx",
        "mov edx, DWORD PTR [ecx+20]",
        "add edx, DWORD PTR [ecx+16]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+24]",
        "mov DWORD PTR [ecx+24], edx",
        "mov edx, DWORD PTR [ecx+24]",
        "add edx, DWORD PTR [ecx+20]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+28]",
        "mov DWORD PTR [ecx+28], edx",
        "mov edx, DWORD PTR [ecx+28]",
        "add edx, DWORD PTR [ecx+24]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+16]",
        "mov DWORD PTR [ecx+16], edx",
        "mov edx, DWORD PTR [ecx+16]",
        "add edx, DWORD PTR [ecx+28]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+20]",
        "mov DWORD PTR [ecx+20], edx",
        "mov edx, DWORD PTR [ecx+40]",
        "add edx, DWORD PTR [ecx+36]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+44]",
        "mov DWORD PTR [ecx+44], edx",
        "mov edx, DWORD PTR [ecx+44]",
        "add edx, DWORD PTR [ecx+40]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+32]",
        "mov DWORD PTR [ecx+32], edx",
        "mov edx, DWORD PTR [ecx+32]",
        "add edx, DWORD PTR [ecx+44]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+36]",
        "mov DWORD PTR [ecx+36], edx",
        "mov edx, DWORD PTR [ecx+36]",
        "add edx, DWORD PTR [ecx+32]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+40]",
        "mov DWORD PTR [ecx+40], edx",
        "mov edx, DWORD PTR [ecx+60]",
        "add edx, DWORD PTR [ecx+56]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+48]",
        "mov DWORD PTR [ecx+48], edx",
        "mov edx, DWORD PTR [ecx+48]",
        "add edx, DWORD PTR [ecx+60]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+52]",
        "mov DWORD PTR [ecx+52], edx",
        "mov edx, DWORD PTR [ecx+52]",
        "add edx, DWORD PTR [ecx+48]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+56]",
        "mov DWORD PTR [ecx+56], edx",
        "mov edx, DWORD PTR [ecx+56]",
        "add edx, DWORD PTR [ecx+52]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+60]",
        "mov DWORD PTR [ecx+60], edx",
        "mov edx, DWORD PTR [ecx]",
        "add edx, DWORD PTR [ecx+48]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+16]",
        "mov DWORD PTR [ecx+16], edx",
        "mov edx, DWORD PTR [ecx+16]",
        "add edx, DWORD PTR [ecx]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+32]",
        "mov DWORD PTR [ecx+32], edx",
        "mov edx, DWORD PTR [ecx+32]",
        "add edx, DWORD PTR [ecx+16]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+48]",
        "mov DWORD PTR [ecx+48], edx",
        "mov edx, DWORD PTR [ecx+48]",
        "add edx, DWORD PTR [ecx+32]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx]",
        "mov DWORD PTR [ecx], edx",
        "mov edx, DWORD PTR [ecx+20]",
        "add edx, DWORD PTR [ecx+4]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+36]",
        "mov DWORD PTR [ecx+36], edx",
        "mov edx, DWORD PTR [ecx+36]",
        "add edx, DWORD PTR [ecx+20]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+52]",
        "mov DWORD PTR [ecx+52], edx",
        "mov edx, DWORD PTR [ecx+52]",
        "add edx, DWORD PTR [ecx+36]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+4]",
        "mov DWORD PTR [ecx+4], edx",
        "mov edx, DWORD PTR [ecx+4]",
        "add edx, DWORD PTR [ecx+52]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+20]",
        "mov DWORD PTR [ecx+20], edx",
        "mov edx, DWORD PTR [ecx+40]",
        "add edx, DWORD PTR [ecx+24]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+56]",
        "mov DWORD PTR [ecx+56], edx",
        "mov edx, DWORD PTR [ecx+56]",
        "add edx, DWORD PTR [ecx+40]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+8]",
        "mov DWORD PTR [ecx+8], edx",
        "mov edx, DWORD PTR [ecx+8]",
        "add edx, DWORD PTR [ecx+56]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+24]",
        "mov DWORD PTR [ecx+24], edx",
        "mov edx, DWORD PTR [ecx+24]",
        "add edx, DWORD PTR [ecx+8]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+40]",
        "mov DWORD PTR [ecx+40], edx",
        "mov edx, DWORD PTR [ecx+60]",
        "add edx, DWORD PTR [ecx+44]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+12]",
        "mov DWORD PTR [ecx+12], edx",
        "mov edx, DWORD PTR [ecx+12]",
        "add edx, DWORD PTR [ecx+60]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+28]",
        "mov DWORD PTR [ecx+28], edx",
        "mov edx, DWORD PTR [ecx+28]",
        "add edx, DWORD PTR [ecx+12]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+44]",
        "mov DWORD PTR [ecx+44], edx",
        "mov edx, DWORD PTR [ecx+44]",
        "add edx, DWORD PTR [ecx+28]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+60]",
        "mov DWORD PTR [ecx+60], edx",
        "mov edx, DWORD PTR [ecx]",
        "add edx, DWORD PTR [ecx+12]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+4]",
        "mov DWORD PTR [ecx+4], edx",
        "mov edx, DWORD PTR [ecx+4]",
        "add edx, DWORD PTR [ecx]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+8]",
        "mov DWORD PTR [ecx+8], edx",
        "mov edx, DWORD PTR [ecx+8]",
        "add edx, DWORD PTR [ecx+4]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+12]",
        "mov DWORD PTR [ecx+12], edx",
        "mov edx, DWORD PTR [ecx+12]",
        "add edx, DWORD PTR [ecx+8]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx]",
        "mov DWORD PTR [ecx], edx",
        "mov edx, DWORD PTR [ecx+20]",
        "add edx, DWORD PTR [ecx+16]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+24]",
        "mov DWORD PTR [ecx+24], edx",
        "mov edx, DWORD PTR [ecx+24]",
        "add edx, DWORD PTR [ecx+20]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+28]",
        "mov DWORD PTR [ecx+28], edx",
        "mov edx, DWORD PTR [ecx+28]",
        "add edx, DWORD PTR [ecx+24]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+16]",
        "mov DWORD PTR [ecx+16], edx",
        "mov edx, DWORD PTR [ecx+16]",
        "add edx, DWORD PTR [ecx+28]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+20]",
        "mov DWORD PTR [ecx+20], edx",
        "mov edx, DWORD PTR [ecx+40]",
        "add edx, DWORD PTR [ecx+36]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+44]",
        "mov DWORD PTR [ecx+44], edx",
        "mov edx, DWORD PTR [ecx+44]",
        "add edx, DWORD PTR [ecx+40]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+32]",
        "mov DWORD PTR [ecx+32], edx",
        "mov edx, DWORD PTR [ecx+32]",
        "add edx, DWORD PTR [ecx+44]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+36]",
        "mov DWORD PTR [ecx+36], edx",
        "mov edx, DWORD PTR [ecx+36]",
        "add edx, DWORD PTR [ecx+32]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+40]",
        "mov DWORD PTR [ecx+40], edx",
        "mov edx, DWORD PTR [ecx+60]",
        "add edx, DWORD PTR [ecx+56]",
        "ror edx, 25",
        "xor edx, DWORD PTR [ecx+48]",
        "mov DWORD PTR [ecx+48], edx",
        "mov edx, DWORD PTR [ecx+48]",
        "add edx, DWORD PTR [ecx+60]",
        "ror edx, 23",
        "xor edx, DWORD PTR [ecx+52]",
        "mov DWORD PTR [ecx+52], edx",
        "mov edx, DWORD PTR [ecx+52]",
        "add edx, DWORD PTR [ecx+48]",
        "ror edx, 19",
        "xor edx, DWORD PTR [ecx+56]",
        "mov DWORD PTR [ecx+56], edx",
        "mov edx, DWORD PTR [ecx+56]",
        "add edx, DWORD PTR [ecx+52]",
        "ror edx, 14",
        "xor edx, DWORD PTR [ecx+60]",
        "mov DWORD PTR [ecx+60], edx",
        "mov edx, DWORD PTR [ecx]",
        "add edx, DWORD PTR [eax]",
        "mov DWORD PTR [eax], edx",
        "mov edx, DWORD PTR [ecx+4]",
        "add edx, DWORD PTR [eax+4]",
        "mov DWORD PTR [eax+4], edx",
        "mov edx, DWORD PTR [ecx+8]",
        "add edx, DWORD PTR [eax+8]",
        "mov DWORD PTR [eax+8], edx",
        "mov edx, DWORD PTR [ecx+12]",
        "add edx, DWORD PTR [eax+12]",
        "mov DWORD PTR [eax+12], edx",
        "mov edx, DWORD PTR [ecx+16]",
        "add edx, DWORD PTR [eax+16]",
        "mov DWORD PTR [eax+16], edx",
        "mov edx, DWORD PTR [ecx+20]",
        "add edx, DWORD PTR [eax+20]",
        "mov DWORD PTR [eax+20], edx",
        "mov edx, DWORD PTR [ecx+24]",
        "add edx, DWORD PTR [eax+24]",
        "mov DWORD PTR [eax+24], edx",
        "mov edx, DWORD PTR [ecx+28]",
        "add edx, DWORD PTR [eax+28]",
        "mov DWORD PTR [eax+28], edx",
        "mov edx, DWORD PTR [ecx+32]",
        "add edx, DWORD PTR [eax+32]",
        "mov DWORD PTR [eax+32], edx",
        "mov edx, DWORD PTR [ecx+36]",
        "add edx, DWORD PTR [eax+36]",
        "mov DWORD PTR [eax+36], edx",
        "mov edx, DWORD PTR [ecx+40]",
        "add edx, DWORD PTR [eax+40]",
        "mov DWORD PTR [eax+40], edx",
        "mov edx, DWORD PTR [ecx+44]",
        "add edx, DWORD PTR [eax+44]",
        "mov DWORD PTR [eax+44], edx",
        "mov edx, DWORD PTR [ecx+48]",
        "add edx, DWORD PTR [eax+48]",
        "mov DWORD PTR [eax+48], edx",
        "mov edx, DWORD PTR [ecx+52]",
        "add edx, DWORD PTR [eax+52]",
        "mov DWORD PTR [eax+52], edx",
        "mov edx, DWORD PTR [ecx+56]",
        "add edx, DWORD PTR [eax+56]",
        "mov DWORD PTR [eax+56], edx",
        "mov edx, DWORD PTR [ecx+60]",
        "add edx, DWORD PTR [eax+60]",
        "mov DWORD PTR [eax+60], edx",
        "ret",
    )
}

/// scryptBlockMix (RFC 7914 §4) with block size parameter `r`: writes scryptBlockMix of the `128 * r` bytes at `b` to the `128 * ry` bytes at `y`. Calls `vg_salsa20_8` for each 64-byte block.
///
/// Contract: `VG.Spec.Scrypt.blockMixContract`. Constant time: only the pointers and `r` may affect timing, not the data.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `ry` must equal `r`, and `r` must be positive.
/// * `b` must be valid for reads of `128 * r` bytes, and `y` for reads and writes of `128 * ry` bytes.
/// * `scratch` must be valid for reads and writes of 128 bytes. It is working space: its contents on return are unspecified.
/// * `y` and `scratch` must not overlap each other or `b` (distinct Rust objects never do).
/// * None of `b`, `y` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 12 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_scrypt_blockmix(b: *const [u8; 128], r: usize, y: *mut [u8; 128], ry: usize, scratch: *mut [u32; 32]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+20]",
        "mov DWORD PTR [eax+64], ebx",
        "mov DWORD PTR [eax+68], esi",
        "mov DWORD PTR [eax+72], edi",
        "mov DWORD PTR [eax+76], ebp",
        "mov ebx, DWORD PTR [esp+4]",
        "mov esi, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [esp+8]",
        "mov ecx, 64",
        "mul ecx",
        "mov edi, esi",
        "add edi, eax",
        "mov ebp, ebx",
        "add ebp, eax",
        "add ebp, eax",
        "sub ebp, 64",
        "20:",
        "mov eax, DWORD PTR [ebp]",
        "xor eax, DWORD PTR [ebx]",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [ebp+4]",
        "xor eax, DWORD PTR [ebx+4]",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [ebp+8]",
        "xor eax, DWORD PTR [ebx+8]",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [ebp+12]",
        "xor eax, DWORD PTR [ebx+12]",
        "mov DWORD PTR [esi+12], eax",
        "mov eax, DWORD PTR [ebp+16]",
        "xor eax, DWORD PTR [ebx+16]",
        "mov DWORD PTR [esi+16], eax",
        "mov eax, DWORD PTR [ebp+20]",
        "xor eax, DWORD PTR [ebx+20]",
        "mov DWORD PTR [esi+20], eax",
        "mov eax, DWORD PTR [ebp+24]",
        "xor eax, DWORD PTR [ebx+24]",
        "mov DWORD PTR [esi+24], eax",
        "mov eax, DWORD PTR [ebp+28]",
        "xor eax, DWORD PTR [ebx+28]",
        "mov DWORD PTR [esi+28], eax",
        "mov eax, DWORD PTR [ebp+32]",
        "xor eax, DWORD PTR [ebx+32]",
        "mov DWORD PTR [esi+32], eax",
        "mov eax, DWORD PTR [ebp+36]",
        "xor eax, DWORD PTR [ebx+36]",
        "mov DWORD PTR [esi+36], eax",
        "mov eax, DWORD PTR [ebp+40]",
        "xor eax, DWORD PTR [ebx+40]",
        "mov DWORD PTR [esi+40], eax",
        "mov eax, DWORD PTR [ebp+44]",
        "xor eax, DWORD PTR [ebx+44]",
        "mov DWORD PTR [esi+44], eax",
        "mov eax, DWORD PTR [ebp+48]",
        "xor eax, DWORD PTR [ebx+48]",
        "mov DWORD PTR [esi+48], eax",
        "mov eax, DWORD PTR [ebp+52]",
        "xor eax, DWORD PTR [ebx+52]",
        "mov DWORD PTR [esi+52], eax",
        "mov eax, DWORD PTR [ebp+56]",
        "xor eax, DWORD PTR [ebx+56]",
        "mov DWORD PTR [esi+56], eax",
        "mov eax, DWORD PTR [ebp+60]",
        "xor eax, DWORD PTR [ebx+60]",
        "mov DWORD PTR [esi+60], eax",
        "mov eax, DWORD PTR [esp+20]",
        "push eax",
        "push esi",
        "call {vg_salsa20_8}",
        "pop eax",
        "pop eax",
        "add ebx, 64",
        "mov eax, DWORD PTR [esi]",
        "xor eax, DWORD PTR [ebx]",
        "mov DWORD PTR [edi], eax",
        "mov eax, DWORD PTR [esi+4]",
        "xor eax, DWORD PTR [ebx+4]",
        "mov DWORD PTR [edi+4], eax",
        "mov eax, DWORD PTR [esi+8]",
        "xor eax, DWORD PTR [ebx+8]",
        "mov DWORD PTR [edi+8], eax",
        "mov eax, DWORD PTR [esi+12]",
        "xor eax, DWORD PTR [ebx+12]",
        "mov DWORD PTR [edi+12], eax",
        "mov eax, DWORD PTR [esi+16]",
        "xor eax, DWORD PTR [ebx+16]",
        "mov DWORD PTR [edi+16], eax",
        "mov eax, DWORD PTR [esi+20]",
        "xor eax, DWORD PTR [ebx+20]",
        "mov DWORD PTR [edi+20], eax",
        "mov eax, DWORD PTR [esi+24]",
        "xor eax, DWORD PTR [ebx+24]",
        "mov DWORD PTR [edi+24], eax",
        "mov eax, DWORD PTR [esi+28]",
        "xor eax, DWORD PTR [ebx+28]",
        "mov DWORD PTR [edi+28], eax",
        "mov eax, DWORD PTR [esi+32]",
        "xor eax, DWORD PTR [ebx+32]",
        "mov DWORD PTR [edi+32], eax",
        "mov eax, DWORD PTR [esi+36]",
        "xor eax, DWORD PTR [ebx+36]",
        "mov DWORD PTR [edi+36], eax",
        "mov eax, DWORD PTR [esi+40]",
        "xor eax, DWORD PTR [ebx+40]",
        "mov DWORD PTR [edi+40], eax",
        "mov eax, DWORD PTR [esi+44]",
        "xor eax, DWORD PTR [ebx+44]",
        "mov DWORD PTR [edi+44], eax",
        "mov eax, DWORD PTR [esi+48]",
        "xor eax, DWORD PTR [ebx+48]",
        "mov DWORD PTR [edi+48], eax",
        "mov eax, DWORD PTR [esi+52]",
        "xor eax, DWORD PTR [ebx+52]",
        "mov DWORD PTR [edi+52], eax",
        "mov eax, DWORD PTR [esi+56]",
        "xor eax, DWORD PTR [ebx+56]",
        "mov DWORD PTR [edi+56], eax",
        "mov eax, DWORD PTR [esi+60]",
        "xor eax, DWORD PTR [ebx+60]",
        "mov DWORD PTR [edi+60], eax",
        "mov eax, DWORD PTR [esp+20]",
        "push eax",
        "push edi",
        "call {vg_salsa20_8}",
        "pop eax",
        "pop eax",
        "mov ebp, edi",
        "add ebx, 64",
        "add esi, 64",
        "add edi, 64",
        "mov eax, DWORD PTR [esp+8]",
        "mov ecx, 64",
        "mul ecx",
        "mov ecx, DWORD PTR [esp+12]",
        "add eax, ecx",
        "cmp esi, eax",
        "jne 20b",
        "mov eax, DWORD PTR [esp+20]",
        "mov ebx, DWORD PTR [eax+64]",
        "mov esi, DWORD PTR [eax+68]",
        "mov edi, DWORD PTR [eax+72]",
        "mov ebp, DWORD PTR [eax+76]",
        "ret",
        vg_salsa20_8 = sym super::scrypt::vg_salsa20_8,
    )
}

/// scryptROMix (RFC 7914 §5) with block size parameter `r` and cost parameter `N = vlen / r`: replaces the `128 * r` bytes at `b` by their scryptROMix. Step 2 writes `V[0], …, V[N - 1]` to `v`. Calls `vg_scrypt_blockmix` for each scryptBlockMix.
///
/// Contract: `VG.Spec.Scrypt.roMixContract`. Not constant time in the indices: timing may depend on the pointers, `r`, `N` and the indices `j` of step 3 (`VG.Spec.Scrypt.roMixIndices`), which are derived from the data and so leak information about it (as in every scrypt that indexes `V` directly), but on nothing else.
///
/// The function may overwrite the arguments on the stack, as the calling convention lets it.
///
/// # Safety
///
/// * `r` must be positive, `vlen` must be `N * r` for a power of two `N`, and `slen` must be `r + 2`.
/// * `b` must be valid for reads and writes of `128 * r` bytes, `v` of `128 * vlen` bytes and `scratch` of `128 * slen` bytes. `v` and `scratch` are working space: their contents on return are unspecified.
/// * `b`, `v` and `scratch` must not overlap each other (distinct Rust objects never do).
/// * None of `b`, `v` and `scratch` may overlap the arguments on the stack, overlap the return address on the stack or the 36 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_scrypt_romix(b: *mut [u8; 128], r: usize, v: *mut [u8; 128], vlen: usize, scratch: *mut [u8; 128], slen: usize) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+20]",
        "mov DWORD PTR [eax+128], ebx",
        "mov DWORD PTR [eax+132], esi",
        "mov DWORD PTR [eax+136], edi",
        "mov DWORD PTR [eax+140], ebp",
        "mov eax, DWORD PTR [esp+8]",
        "mov ecx, 1",
        "mov edx, DWORD PTR [esp+16]",
        "add edx, edx",
        "20:",
        "add eax, eax",
        "add ecx, ecx",
        "cmp eax, edx",
        "jne 20b",
        "shr ecx, 1",
        "mov ebp, ecx",
        "mov ebx, ecx",
        "mov esi, DWORD PTR [esp+12]",
        "21:",
        "mov eax, DWORD PTR [esp+8]",
        "mov ecx, 32",
        "mul ecx",
        "mov edx, eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, esi",
        "22:",
        "mov edi, DWORD PTR [eax]",
        "mov DWORD PTR [ecx], edi",
        "add eax, 4",
        "add ecx, 4",
        "sub edx, 1",
        "jne 22b",
        "mov eax, DWORD PTR [esp+20]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, DWORD PTR [esp+4]",
        "push eax",
        "push ecx",
        "push edx",
        "push ecx",
        "push esi",
        "call {vg_scrypt_blockmix}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+8]",
        "mov ecx, 128",
        "mul ecx",
        "add esi, eax",
        "sub ebx, 1",
        "jne 21b",
        "mov ebx, ebp",
        "23:",
        "mov eax, DWORD PTR [esp+8]",
        "mov ecx, 128",
        "mul ecx",
        "mov edi, eax",
        "mov ecx, DWORD PTR [esp+4]",
        "add eax, ecx",
        "sub eax, 64",
        "mov eax, DWORD PTR [eax]",
        "mov ecx, ebp",
        "sub ecx, 1",
        "and eax, ecx",
        "mul edi",
        "mov ecx, DWORD PTR [esp+12]",
        "add ecx, eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov edx, DWORD PTR [esp+20]",
        "add edx, 192",
        "shr edi, 2",
        "24:",
        "mov esi, DWORD PTR [eax]",
        "xor esi, DWORD PTR [ecx]",
        "mov DWORD PTR [edx], esi",
        "add eax, 4",
        "add ecx, 4",
        "add edx, 4",
        "sub edi, 1",
        "jne 24b",
        "mov esi, DWORD PTR [esp+20]",
        "add esi, 192",
        "mov eax, DWORD PTR [esp+20]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, DWORD PTR [esp+4]",
        "push eax",
        "push ecx",
        "push edx",
        "push ecx",
        "push esi",
        "call {vg_scrypt_blockmix}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "sub ebx, 1",
        "jne 23b",
        "mov eax, DWORD PTR [esp+20]",
        "mov ebx, DWORD PTR [eax+128]",
        "mov esi, DWORD PTR [eax+132]",
        "mov edi, DWORD PTR [eax+136]",
        "mov ebp, DWORD PTR [eax+140]",
        "ret",
        vg_scrypt_blockmix = sym super::scrypt::vg_scrypt_blockmix,
    )
}
