// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `zeroize` functions for `x86`.
#![allow(dead_code)]

/// Wipes a buffer: sets the `len` bytes at `p` to zero, and writes no other memory. A call of it is not a dead store the compiler may remove, since the compiler cannot see its code.
///
/// Contract: `VG.Spec.Zeroize.zeroizeContract`. Constant time: only `p` and `len` may affect timing, not the bytes wiped.
///
/// # Safety
///
/// * `p` must be valid for reads and writes of `len` bytes.
/// * `p` must not overlap the arguments on the stack (distinct Rust objects never do).
/// * `p` must not overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_zeroize(p: *mut u8, len: usize) {
    core::arch::naked_asm!(
        "mov eax, 0",
        "mov ecx, DWORD PTR [esp+4]",
        "mov edx, DWORD PTR [esp+8]",
        "shr edx, 2",
        "cmp edx, 0",
        "je 20f",
        "22:",
        "mov DWORD PTR [ecx], eax",
        "add ecx, 4",
        "sub edx, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov edx, DWORD PTR [esp+8]",
        "and edx, 3",
        "cmp edx, 0",
        "je 23f",
        "25:",
        "mov BYTE PTR [ecx], al",
        "add ecx, 1",
        "sub edx, 1",
        "jne 25b",
        "jmp 24f",
        "23:",
        "24:",
        "ret",
    )
}
