name = "HMAC-SHA-384, HMAC-SHA-512, HMAC-SHA-512/224, HMAC-SHA-512/256"
family = "MACs"
specs = ["Hmac/Generic", "Sha512"]
modules = ["src/hmac.rs", "src/hashes/sha512.rs"]
asm = ["hmac", "sha512"]
functions = ["vg_hmac_sha384_init", "vg_hmac_sha384_finalize", "vg_hmac_sha512_init", "vg_hmac_sha512_finalize", "vg_hmac_sha512_224_init", "vg_hmac_sha512_224_finalize", "vg_hmac_sha512_256_init", "vg_hmac_sha512_256_finalize"]
