name = "NIST CAVP SHA byte-oriented test vectors (SHA-1, SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224 and SHA-512/256 .rsp files only)"
directories = ["nist-cavp/sha1", "nist-cavp/sha224", "nist-cavp/sha256", "nist-cavp/sha512"]
url = "https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/shs/shabytetestvectors.zip"
sha256 = "929ef80b7b3418aca026643f6f248815913b60e01741a44bba9e118067f4c9b8"
retrieved = 2026-09-27
