name = "NIST ACVP HMAC-SHA2-384 test vectors: the internalProjection.json of HMAC-SHA2-384-1.0, which has each test case's inputs and expected MAC"
directories = ["nist-acvp/HMAC-SHA2-384-1.0"]
url = "https://raw.githubusercontent.com/usnistgov/ACVP-Server/975de31eb83d87039ec88934fdc47d8c312b892d/gen-val/json-files/HMAC-SHA2-384-1.0/internalProjection.json"
sha256 = "47a2937d640dd0bc06770c6f42ccf34b5c66d3ee14de788166e5858992c2ff11"
retrieved = 2026-10-02
