// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `chacha20` functions for `x86_64`.
#![allow(dead_code)]

/// XORs the first `len` bytes of the ChaCha20 keystream of the 16-word state `*state` (RFC 8439 §2.4: the block function of the state with its block counter, word 12, advanced by 0, 1, … modulo 2³²) into the `len` bytes at `data`, calling `vg_chacha20_block` for each 64 bytes.
///
/// Contract: `VG.Spec.ChaCha20.xorContract`. Constant time: only the pointers and `len` may affect timing, not the state or the data.
///
/// # Safety
///
/// * `state` must be valid for reads and writes of 64 bytes; its contents on return are unspecified.
/// * `data` must be valid for reads and writes of `len` bytes.
/// * `buf` must be valid for reads and writes of 320 bytes; its contents on return are unspecified.
/// * These three regions must not overlap each other, the return address on the stack, or the 8 bytes of stack below it, where its calls of `vg_chacha20_block` store their return address, and none of them may wrap around the end of the address space (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_chacha20_xor(state: *mut [u32; 16], data: *mut u8, len: usize, buf: *mut [u32; 80]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [rcx+256], rbx",
        "mov QWORD PTR [rcx+264], rbp",
        "mov QWORD PTR [rcx+272], r12",
        "mov rbx, rdi",
        "mov rbp, rsi",
        "mov r12, rdx",
        "mov rsi, rcx",
        "test r12, r12",
        "je 20f",
        "22:",
        "mov rdi, rbx",
        "call {vg_chacha20_block}",
        "mov rdx, r12",
        "cmp r12, 64",
        "jb 23f",
        "mov edx, 64",
        "jmp 24f",
        "23:",
        "24:",
        "mov ecx, 0",
        "25:",
        "movzx eax, BYTE PTR [rbp+rcx*1]",
        "movzx r8d, BYTE PTR [rsi+rcx*1]",
        "xor rax, r8",
        "mov BYTE PTR [rbp+rcx*1], al",
        "add rcx, 1",
        "cmp rcx, rdx",
        "jne 25b",
        "mov eax, DWORD PTR [rbx+48]",
        "add eax, 1",
        "mov DWORD PTR [rbx+48], eax",
        "add rbp, rdx",
        "sub r12, rdx",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [rsi+256]",
        "mov rbp, QWORD PTR [rsi+264]",
        "mov r12, QWORD PTR [rsi+272]",
        "ret",
        vg_chacha20_block = sym super::chacha20::vg_chacha20_block,
    )
}

/// The ChaCha20 block function (RFC 8439 §2.3): writes the block function of the 16-word state `*state` (20 rounds, then the input state added word by word) to the first 16 words of `*buf`.
///
/// Contract: `VG.Spec.ChaCha20.blockContract`. Constant time: only the pointers may affect timing, not the state.
///
/// # Safety
///
/// * `state` must be valid for reads of 64 bytes.
/// * `buf` must be valid for reads and writes of 256 bytes. On return its first 64 bytes hold the result and the rest is unspecified.
/// * `buf` must not overlap `state`, nor the return address on the stack (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_chacha20_block(state: *const [u32; 16], buf: *mut [u32; 64]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [rsi+144], rbx",
        "mov QWORD PTR [rsi+152], rbp",
        "mov QWORD PTR [rsi+160], r12",
        "mov QWORD PTR [rsi+168], r13",
        "mov QWORD PTR [rsi+176], r14",
        "mov QWORD PTR [rsi+184], r15",
        "mov eax, DWORD PTR [rdi]",
        "mov DWORD PTR [rsi+64], eax",
        "mov eax, DWORD PTR [rdi+4]",
        "mov DWORD PTR [rsi+68], eax",
        "mov eax, DWORD PTR [rdi+8]",
        "mov DWORD PTR [rsi+72], eax",
        "mov eax, DWORD PTR [rdi+12]",
        "mov DWORD PTR [rsi+76], eax",
        "mov eax, DWORD PTR [rdi+16]",
        "mov DWORD PTR [rsi+80], eax",
        "mov eax, DWORD PTR [rdi+20]",
        "mov DWORD PTR [rsi+84], eax",
        "mov eax, DWORD PTR [rdi+24]",
        "mov DWORD PTR [rsi+88], eax",
        "mov eax, DWORD PTR [rdi+28]",
        "mov DWORD PTR [rsi+92], eax",
        "mov eax, DWORD PTR [rdi+32]",
        "mov DWORD PTR [rsi+96], eax",
        "mov eax, DWORD PTR [rdi+36]",
        "mov DWORD PTR [rsi+100], eax",
        "mov eax, DWORD PTR [rdi+40]",
        "mov DWORD PTR [rsi+104], eax",
        "mov DWORD PTR [rsi+136], eax",
        "mov eax, DWORD PTR [rdi+44]",
        "mov DWORD PTR [rsi+108], eax",
        "mov DWORD PTR [rsi+140], eax",
        "mov eax, DWORD PTR [rdi+48]",
        "mov DWORD PTR [rsi+112], eax",
        "mov eax, DWORD PTR [rdi+52]",
        "mov DWORD PTR [rsi+116], eax",
        "mov eax, DWORD PTR [rdi+56]",
        "mov DWORD PTR [rsi+120], eax",
        "mov eax, DWORD PTR [rdi+60]",
        "mov DWORD PTR [rsi+124], eax",
        "mov eax, DWORD PTR [rsi+64]",
        "mov ebx, DWORD PTR [rsi+68]",
        "mov ecx, DWORD PTR [rsi+72]",
        "mov edx, DWORD PTR [rsi+76]",
        "mov edi, DWORD PTR [rsi+80]",
        "mov ebp, DWORD PTR [rsi+84]",
        "mov r8d, DWORD PTR [rsi+88]",
        "mov r9d, DWORD PTR [rsi+92]",
        "mov r14d, DWORD PTR [rsi+96]",
        "mov r15d, DWORD PTR [rsi+100]",
        "mov r10d, DWORD PTR [rsi+112]",
        "mov r11d, DWORD PTR [rsi+116]",
        "mov r12d, DWORD PTR [rsi+120]",
        "mov r13d, DWORD PTR [rsi+124]",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 16",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 20",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 24",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 25",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 16",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 20",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 24",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 25",
        "mov DWORD PTR [rsi+128], r14d",
        "mov DWORD PTR [rsi+132], r15d",
        "mov r14d, DWORD PTR [rsi+136]",
        "mov r15d, DWORD PTR [rsi+140]",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 16",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 20",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 24",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 25",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 16",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 20",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 24",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 25",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 16",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 20",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 24",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 25",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 16",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 20",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 24",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 25",
        "mov DWORD PTR [rsi+136], r14d",
        "mov DWORD PTR [rsi+140], r15d",
        "mov r14d, DWORD PTR [rsi+128]",
        "mov r15d, DWORD PTR [rsi+132]",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 16",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 20",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 24",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 25",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 16",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 20",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 24",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 25",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 16",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 20",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 24",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 25",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 16",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 20",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 24",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 25",
        "mov DWORD PTR [rsi+128], r14d",
        "mov DWORD PTR [rsi+132], r15d",
        "mov r14d, DWORD PTR [rsi+136]",
        "mov r15d, DWORD PTR [rsi+140]",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 16",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 20",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 24",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 25",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 16",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 20",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 24",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 25",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 16",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 20",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 24",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 25",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 16",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 20",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 24",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 25",
        "mov DWORD PTR [rsi+136], r14d",
        "mov DWORD PTR [rsi+140], r15d",
        "mov r14d, DWORD PTR [rsi+128]",
        "mov r15d, DWORD PTR [rsi+132]",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 16",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 20",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 24",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 25",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 16",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 20",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 24",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 25",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 16",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 20",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 24",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 25",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 16",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 20",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 24",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 25",
        "mov DWORD PTR [rsi+128], r14d",
        "mov DWORD PTR [rsi+132], r15d",
        "mov r14d, DWORD PTR [rsi+136]",
        "mov r15d, DWORD PTR [rsi+140]",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 16",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 20",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 24",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 25",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 16",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 20",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 24",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 25",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 16",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 20",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 24",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 25",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 16",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 20",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 24",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 25",
        "mov DWORD PTR [rsi+136], r14d",
        "mov DWORD PTR [rsi+140], r15d",
        "mov r14d, DWORD PTR [rsi+128]",
        "mov r15d, DWORD PTR [rsi+132]",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 16",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 20",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 24",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 25",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 16",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 20",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 24",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 25",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 16",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 20",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 24",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 25",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 16",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 20",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 24",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 25",
        "mov DWORD PTR [rsi+128], r14d",
        "mov DWORD PTR [rsi+132], r15d",
        "mov r14d, DWORD PTR [rsi+136]",
        "mov r15d, DWORD PTR [rsi+140]",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 16",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 20",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 24",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 25",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 16",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 20",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 24",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 25",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 16",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 20",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 24",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 25",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 16",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 20",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 24",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 25",
        "mov DWORD PTR [rsi+136], r14d",
        "mov DWORD PTR [rsi+140], r15d",
        "mov r14d, DWORD PTR [rsi+128]",
        "mov r15d, DWORD PTR [rsi+132]",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 16",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 20",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 24",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 25",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 16",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 20",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 24",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 25",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 16",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 20",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 24",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 25",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 16",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 20",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 24",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 25",
        "mov DWORD PTR [rsi+128], r14d",
        "mov DWORD PTR [rsi+132], r15d",
        "mov r14d, DWORD PTR [rsi+136]",
        "mov r15d, DWORD PTR [rsi+140]",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 16",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 20",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 24",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 25",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 16",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 20",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 24",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 25",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 16",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 20",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 24",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 25",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 16",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 20",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 24",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 25",
        "mov DWORD PTR [rsi+136], r14d",
        "mov DWORD PTR [rsi+140], r15d",
        "mov r14d, DWORD PTR [rsi+128]",
        "mov r15d, DWORD PTR [rsi+132]",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 16",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 20",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 24",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 25",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 16",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 20",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 24",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 25",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 16",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 20",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 24",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 25",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 16",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 20",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 24",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 25",
        "mov DWORD PTR [rsi+128], r14d",
        "mov DWORD PTR [rsi+132], r15d",
        "mov r14d, DWORD PTR [rsi+136]",
        "mov r15d, DWORD PTR [rsi+140]",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 16",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 20",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 24",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 25",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 16",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 20",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 24",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 25",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 16",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 20",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 24",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 25",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 16",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 20",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 24",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 25",
        "mov DWORD PTR [rsi+136], r14d",
        "mov DWORD PTR [rsi+140], r15d",
        "mov r14d, DWORD PTR [rsi+128]",
        "mov r15d, DWORD PTR [rsi+132]",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 16",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 20",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 24",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 25",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 16",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 20",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 24",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 25",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 16",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 20",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 24",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 25",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 16",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 20",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 24",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 25",
        "mov DWORD PTR [rsi+128], r14d",
        "mov DWORD PTR [rsi+132], r15d",
        "mov r14d, DWORD PTR [rsi+136]",
        "mov r15d, DWORD PTR [rsi+140]",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 16",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 20",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 24",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 25",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 16",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 20",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 24",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 25",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 16",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 20",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 24",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 25",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 16",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 20",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 24",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 25",
        "mov DWORD PTR [rsi+136], r14d",
        "mov DWORD PTR [rsi+140], r15d",
        "mov r14d, DWORD PTR [rsi+128]",
        "mov r15d, DWORD PTR [rsi+132]",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 16",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 20",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 24",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 25",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 16",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 20",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 24",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 25",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 16",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 20",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 24",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 25",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 16",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 20",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 24",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 25",
        "mov DWORD PTR [rsi+128], r14d",
        "mov DWORD PTR [rsi+132], r15d",
        "mov r14d, DWORD PTR [rsi+136]",
        "mov r15d, DWORD PTR [rsi+140]",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 16",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 20",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 24",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 25",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 16",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 20",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 24",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 25",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 16",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 20",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 24",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 25",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 16",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 20",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 24",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 25",
        "mov DWORD PTR [rsi+136], r14d",
        "mov DWORD PTR [rsi+140], r15d",
        "mov r14d, DWORD PTR [rsi+128]",
        "mov r15d, DWORD PTR [rsi+132]",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 16",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 20",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 24",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 25",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 16",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 20",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 24",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 25",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 16",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 20",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 24",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 25",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 16",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 20",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 24",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 25",
        "mov DWORD PTR [rsi+128], r14d",
        "mov DWORD PTR [rsi+132], r15d",
        "mov r14d, DWORD PTR [rsi+136]",
        "mov r15d, DWORD PTR [rsi+140]",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 16",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 20",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 24",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 25",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 16",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 20",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 24",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 25",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 16",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 20",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 24",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 25",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 16",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 20",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 24",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 25",
        "mov DWORD PTR [rsi+136], r14d",
        "mov DWORD PTR [rsi+140], r15d",
        "mov r14d, DWORD PTR [rsi+128]",
        "mov r15d, DWORD PTR [rsi+132]",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 16",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 20",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 24",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 25",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 16",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 20",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 24",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 25",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 16",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 20",
        "add eax, edi",
        "xor r10d, eax",
        "ror r10d, 24",
        "add r14d, r10d",
        "xor edi, r14d",
        "ror edi, 25",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 16",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 20",
        "add ebx, ebp",
        "xor r11d, ebx",
        "ror r11d, 24",
        "add r15d, r11d",
        "xor ebp, r15d",
        "ror ebp, 25",
        "mov DWORD PTR [rsi+128], r14d",
        "mov DWORD PTR [rsi+132], r15d",
        "mov r14d, DWORD PTR [rsi+136]",
        "mov r15d, DWORD PTR [rsi+140]",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 16",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 20",
        "add ecx, r8d",
        "xor r12d, ecx",
        "ror r12d, 24",
        "add r14d, r12d",
        "xor r8d, r14d",
        "ror r8d, 25",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 16",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 20",
        "add edx, r9d",
        "xor r13d, edx",
        "ror r13d, 24",
        "add r15d, r13d",
        "xor r9d, r15d",
        "ror r9d, 25",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 16",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 20",
        "add eax, ebp",
        "xor r13d, eax",
        "ror r13d, 24",
        "add r14d, r13d",
        "xor ebp, r14d",
        "ror ebp, 25",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 16",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 20",
        "add ebx, r8d",
        "xor r10d, ebx",
        "ror r10d, 24",
        "add r15d, r10d",
        "xor r8d, r15d",
        "ror r8d, 25",
        "mov DWORD PTR [rsi+136], r14d",
        "mov DWORD PTR [rsi+140], r15d",
        "mov r14d, DWORD PTR [rsi+128]",
        "mov r15d, DWORD PTR [rsi+132]",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 16",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 20",
        "add ecx, r9d",
        "xor r11d, ecx",
        "ror r11d, 24",
        "add r14d, r11d",
        "xor r9d, r14d",
        "ror r9d, 25",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 16",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 20",
        "add edx, edi",
        "xor r12d, edx",
        "ror r12d, 24",
        "add r15d, r12d",
        "xor edi, r15d",
        "ror edi, 25",
        "mov DWORD PTR [rsi], eax",
        "mov DWORD PTR [rsi+4], ebx",
        "mov DWORD PTR [rsi+8], ecx",
        "mov DWORD PTR [rsi+12], edx",
        "mov DWORD PTR [rsi+16], edi",
        "mov DWORD PTR [rsi+20], ebp",
        "mov DWORD PTR [rsi+24], r8d",
        "mov DWORD PTR [rsi+28], r9d",
        "mov DWORD PTR [rsi+32], r14d",
        "mov DWORD PTR [rsi+36], r15d",
        "mov eax, DWORD PTR [rsi+136]",
        "mov DWORD PTR [rsi+40], eax",
        "mov eax, DWORD PTR [rsi+140]",
        "mov DWORD PTR [rsi+44], eax",
        "mov DWORD PTR [rsi+48], r10d",
        "mov DWORD PTR [rsi+52], r11d",
        "mov DWORD PTR [rsi+56], r12d",
        "mov DWORD PTR [rsi+60], r13d",
        "mov eax, DWORD PTR [rsi]",
        "add eax, DWORD PTR [rsi+64]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, DWORD PTR [rsi+68]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, DWORD PTR [rsi+72]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, DWORD PTR [rsi+76]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, DWORD PTR [rsi+16]",
        "add eax, DWORD PTR [rsi+80]",
        "mov DWORD PTR [rsi+16], eax",
        "mov eax, DWORD PTR [rsi+20]",
        "add eax, DWORD PTR [rsi+84]",
        "mov DWORD PTR [rsi+20], eax",
        "mov eax, DWORD PTR [rsi+24]",
        "add eax, DWORD PTR [rsi+88]",
        "mov DWORD PTR [rsi+24], eax",
        "mov eax, DWORD PTR [rsi+28]",
        "add eax, DWORD PTR [rsi+92]",
        "mov DWORD PTR [rsi+28], eax",
        "mov eax, DWORD PTR [rsi+32]",
        "add eax, DWORD PTR [rsi+96]",
        "mov DWORD PTR [rsi+32], eax",
        "mov eax, DWORD PTR [rsi+36]",
        "add eax, DWORD PTR [rsi+100]",
        "mov DWORD PTR [rsi+36], eax",
        "mov eax, DWORD PTR [rsi+40]",
        "add eax, DWORD PTR [rsi+104]",
        "mov DWORD PTR [rsi+40], eax",
        "mov eax, DWORD PTR [rsi+44]",
        "add eax, DWORD PTR [rsi+108]",
        "mov DWORD PTR [rsi+44], eax",
        "mov eax, DWORD PTR [rsi+48]",
        "add eax, DWORD PTR [rsi+112]",
        "mov DWORD PTR [rsi+48], eax",
        "mov eax, DWORD PTR [rsi+52]",
        "add eax, DWORD PTR [rsi+116]",
        "mov DWORD PTR [rsi+52], eax",
        "mov eax, DWORD PTR [rsi+56]",
        "add eax, DWORD PTR [rsi+120]",
        "mov DWORD PTR [rsi+56], eax",
        "mov eax, DWORD PTR [rsi+60]",
        "add eax, DWORD PTR [rsi+124]",
        "mov DWORD PTR [rsi+60], eax",
        "mov rbx, QWORD PTR [rsi+144]",
        "mov rbp, QWORD PTR [rsi+152]",
        "mov r12, QWORD PTR [rsi+160]",
        "mov r13, QWORD PTR [rsi+168]",
        "mov r14, QWORD PTR [rsi+176]",
        "mov r15, QWORD PTR [rsi+184]",
        "ret",
    )
}
