// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `ct` functions for `x86_64`.
#![allow(dead_code)]

/// Compares two byte strings in constant time: returns 1 if the `a_len` bytes at `a` are the `b_len` bytes at `b` (so byte strings of different lengths are unequal), and 0 otherwise. Writes no memory.
///
/// Contract: `VG.Spec.Ct.eqContract`. Constant time: only the pointers, `a_len` and `b_len` may affect timing, not the bytes compared; only the result depends on them.
///
/// # Safety
///
/// * `a` must be valid for reads of `a_len` bytes.
/// * `b` must be valid for reads of `b_len` bytes.
/// * Neither `a` nor `b` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_ct_eq(a: *const u8, a_len: usize, b: *const u8, b_len: usize) -> u32 {
    core::arch::naked_asm!(
        "mov rax, 0",
        "mov r8, rsi",
        "cmp r8, rcx",
        "je 20f",
        "jmp 21f",
        "20:",
        "mov r8, 0",
        "cmp r8, rsi",
        "je 22f",
        ".p2align 6",
        "24:",
        "movzx r9d, BYTE PTR [rdi+r8*1]",
        "movzx r10d, BYTE PTR [rdx+r8*1]",
        "xor r9, r10",
        "or rax, r9",
        "add r8, 1",
        "cmp r8, rsi",
        "jne 24b",
        "jmp 23f",
        "22:",
        "23:",
        "sub rax, 1",
        "shr rax, 63",
        "21:",
        "ret",
    )
}
