// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `gcm` functions for `x86_64`.
#![allow(dead_code)]

/// GHASH (NIST SP 800-38D §6.4) continued over whole blocks: with the hash subkey `H` the block at `h`, replaces the block `Y` at `*y` with `Yₙ`, where `Y₀ = Y` and `Yᵢ = (Yᵢ₋₁ ⊕ Xᵢ) • H` for the `n` 16-byte blocks `X₁ … Xₙ` starting at `data` (blocks big-endian, `•` the multiplication of §6.3).
///
/// Contract: `VG.Spec.Gcm.ghashContract`. Constant time: only the pointers and `n` may affect timing, not `H`, `Y` or the data.
///
/// # Safety
///
/// * `h` must be valid for reads of 16 bytes.
/// * `y` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 256 bytes; its contents on return are unspecified.
/// * `y` and `scratch` must not overlap each other, `h` or `data` (`h` and `data` may overlap). None of the four regions may overlap the return address on the stack or wrap around the end of the address space (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_ghash(h: *const [u8; 16], y: *mut [u8; 16], data: *const [u8; 16], n: usize, scratch: *mut [u64; 32]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8], rbx",
        "mov QWORD PTR [r8+8], rbp",
        "mov QWORD PTR [r8+16], r12",
        "mov QWORD PTR [r8+24], r13",
        "mov QWORD PTR [r8+32], r14",
        "mov QWORD PTR [r8+40], r15",
        "test rcx, rcx",
        "je 20f",
        "22:",
        "mov r9, QWORD PTR [rsi]",
        "bswap r9",
        "mov r13, QWORD PTR [rdx]",
        "bswap r13",
        "xor r9, r13",
        "mov r10, QWORD PTR [rsi+8]",
        "bswap r10",
        "mov r13, QWORD PTR [rdx+8]",
        "bswap r13",
        "xor r10, r13",
        "mov rbx, QWORD PTR [rdi]",
        "bswap rbx",
        "mov rbp, QWORD PTR [rdi+8]",
        "bswap rbp",
        "mov r11, 0",
        "mov rax, 0",
        "movabs r14, -2233785415175766016",
        "mov r15, 16",
        "23:",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "sub r15, 1",
        "jne 23b",
        "bswap r11",
        "mov QWORD PTR [rsi], r11",
        "bswap rax",
        "mov QWORD PTR [rsi+8], rax",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r8]",
        "mov rbp, QWORD PTR [r8+8]",
        "mov r12, QWORD PTR [r8+16]",
        "mov r13, QWORD PTR [r8+24]",
        "mov r14, QWORD PTR [r8+32]",
        "mov r15, QWORD PTR [r8+40]",
        "ret",
    )
}

/// The CPU features `vg_ghash_pclmul` requires (`Artifact.features`).
pub(crate) const VG_GHASH_PCLMUL_FEATURES: &[&str] = &["pclmulqdq", "ssse3"];

/// GHASH (SP 800-38D §6.4), with PCLMULQDQ: replaces the block `*y` with `GHASH_H` continued from `*y` over the `n` 16-byte blocks starting at `data`, where `H` is the hash subkey `*h` (`Y ← (Y ⊕ Xᵢ) • H` for each block `Xᵢ`, in order). Four blocks at a time, with `H²`, `H³` and `H⁴` computed on each call.
///
/// Contract: `VG.Spec.Gcm.ghashContract`. Constant time: only the pointers and `n` may affect timing, not `H`, `Y` or the data.
///
/// # Safety
///
/// * `h` must be valid for reads of 16 bytes.
/// * `y` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 256 bytes; its contents on return are unspecified.
/// * `y` and `scratch` must not overlap each other, `h`, `data`, or the return address on the stack (distinct Rust objects never do).
/// * The CPU must support the `pclmulqdq` and `ssse3` target features.
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_ghash_pclmul(h: *const [u8; 16], y: *mut [u8; 16], data: *const [u8; 16], n: usize, scratch: *mut [u64; 32]) {
    core::arch::naked_asm!(
        "movabs rax, 579005069656919567",
        "movq xmm0, rax",
        "movabs rax, 283686952306183",
        "movq xmm12, rax",
        "punpcklqdq xmm0, xmm12",
        "movabs rax, 0",
        "movq xmm1, rax",
        "movabs rax, -4467570830351532032",
        "movq xmm12, rax",
        "punpcklqdq xmm1, xmm12",
        "movdqu xmm7, XMMWORD PTR [rdi]",
        "pshufb xmm7, xmm0",
        "movabs rax, 1",
        "movq xmm13, rax",
        "movabs rax, -4467570830351532032",
        "movq xmm12, rax",
        "punpcklqdq xmm13, xmm12",
        "movabs rax, -1",
        "movq xmm14, rax",
        "punpcklqdq xmm14, xmm14",
        "movdqa xmm3, xmm7",
        "psllq xmm3, 1",
        "movdqa xmm11, xmm7",
        "psrlq xmm11, 63",
        "pslldq xmm11, 8",
        "por xmm3, xmm11",
        "pshufd xmm11, xmm7, 255",
        "psrld xmm11, 31",
        "paddd xmm11, xmm14",
        "pandn xmm11, xmm13",
        "pxor xmm3, xmm11",
        "pxor xmm8, xmm8",
        "pxor xmm9, xmm9",
        "pxor xmm10, xmm10",
        "movdqa xmm11, xmm3",
        "pclmulqdq xmm11, xmm3, 0",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm3",
        "pclmulqdq xmm11, xmm3, 17",
        "pxor xmm10, xmm11",
        "movdqa xmm11, xmm3",
        "pclmulqdq xmm11, xmm3, 1",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm3",
        "pclmulqdq xmm11, xmm3, 16",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm9",
        "psrldq xmm11, 8",
        "pxor xmm10, xmm11",
        "pslldq xmm9, 8",
        "pxor xmm8, xmm9",
        "movdqa xmm11, xmm8",
        "pclmulqdq xmm11, xmm1, 16",
        "pshufd xmm8, xmm8, 78",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm8",
        "pclmulqdq xmm11, xmm1, 16",
        "pshufd xmm8, xmm8, 78",
        "pxor xmm8, xmm11",
        "movdqa xmm4, xmm10",
        "pxor xmm4, xmm8",
        "pxor xmm8, xmm8",
        "pxor xmm9, xmm9",
        "pxor xmm10, xmm10",
        "movdqa xmm11, xmm4",
        "pclmulqdq xmm11, xmm3, 0",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm4",
        "pclmulqdq xmm11, xmm3, 17",
        "pxor xmm10, xmm11",
        "movdqa xmm11, xmm4",
        "pclmulqdq xmm11, xmm3, 1",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm4",
        "pclmulqdq xmm11, xmm3, 16",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm9",
        "psrldq xmm11, 8",
        "pxor xmm10, xmm11",
        "pslldq xmm9, 8",
        "pxor xmm8, xmm9",
        "movdqa xmm11, xmm8",
        "pclmulqdq xmm11, xmm1, 16",
        "pshufd xmm8, xmm8, 78",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm8",
        "pclmulqdq xmm11, xmm1, 16",
        "pshufd xmm8, xmm8, 78",
        "pxor xmm8, xmm11",
        "movdqa xmm5, xmm10",
        "pxor xmm5, xmm8",
        "pxor xmm8, xmm8",
        "pxor xmm9, xmm9",
        "pxor xmm10, xmm10",
        "movdqa xmm11, xmm5",
        "pclmulqdq xmm11, xmm3, 0",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm5",
        "pclmulqdq xmm11, xmm3, 17",
        "pxor xmm10, xmm11",
        "movdqa xmm11, xmm5",
        "pclmulqdq xmm11, xmm3, 1",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm5",
        "pclmulqdq xmm11, xmm3, 16",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm9",
        "psrldq xmm11, 8",
        "pxor xmm10, xmm11",
        "pslldq xmm9, 8",
        "pxor xmm8, xmm9",
        "movdqa xmm11, xmm8",
        "pclmulqdq xmm11, xmm1, 16",
        "pshufd xmm8, xmm8, 78",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm8",
        "pclmulqdq xmm11, xmm1, 16",
        "pshufd xmm8, xmm8, 78",
        "pxor xmm8, xmm11",
        "movdqa xmm6, xmm10",
        "pxor xmm6, xmm8",
        "movdqu xmm2, XMMWORD PTR [rsi]",
        "pshufb xmm2, xmm0",
        "cmp rcx, 4",
        "jb 20f",
        "22:",
        "pxor xmm8, xmm8",
        "pxor xmm9, xmm9",
        "pxor xmm10, xmm10",
        "movdqu xmm7, XMMWORD PTR [rdx]",
        "pshufb xmm7, xmm0",
        "pxor xmm7, xmm2",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm6, 0",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm6, 17",
        "pxor xmm10, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm6, 1",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm6, 16",
        "pxor xmm9, xmm11",
        "movdqu xmm7, XMMWORD PTR [rdx+16]",
        "pshufb xmm7, xmm0",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm5, 0",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm5, 17",
        "pxor xmm10, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm5, 1",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm5, 16",
        "pxor xmm9, xmm11",
        "movdqu xmm7, XMMWORD PTR [rdx+32]",
        "pshufb xmm7, xmm0",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm4, 0",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm4, 17",
        "pxor xmm10, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm4, 1",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm4, 16",
        "pxor xmm9, xmm11",
        "movdqu xmm7, XMMWORD PTR [rdx+48]",
        "pshufb xmm7, xmm0",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm3, 0",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm3, 17",
        "pxor xmm10, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm3, 1",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm3, 16",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm9",
        "psrldq xmm11, 8",
        "pxor xmm10, xmm11",
        "pslldq xmm9, 8",
        "pxor xmm8, xmm9",
        "movdqa xmm11, xmm8",
        "pclmulqdq xmm11, xmm1, 16",
        "pshufd xmm8, xmm8, 78",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm8",
        "pclmulqdq xmm11, xmm1, 16",
        "pshufd xmm8, xmm8, 78",
        "pxor xmm8, xmm11",
        "movdqa xmm2, xmm10",
        "pxor xmm2, xmm8",
        "add rdx, 64",
        "sub rcx, 4",
        "cmp rcx, 4",
        "jae 22b",
        "jmp 21f",
        "20:",
        "21:",
        "test rcx, rcx",
        "je 23f",
        "25:",
        "pxor xmm8, xmm8",
        "pxor xmm9, xmm9",
        "pxor xmm10, xmm10",
        "movdqu xmm7, XMMWORD PTR [rdx]",
        "pshufb xmm7, xmm0",
        "pxor xmm7, xmm2",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm3, 0",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm3, 17",
        "pxor xmm10, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm3, 1",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm7",
        "pclmulqdq xmm11, xmm3, 16",
        "pxor xmm9, xmm11",
        "movdqa xmm11, xmm9",
        "psrldq xmm11, 8",
        "pxor xmm10, xmm11",
        "pslldq xmm9, 8",
        "pxor xmm8, xmm9",
        "movdqa xmm11, xmm8",
        "pclmulqdq xmm11, xmm1, 16",
        "pshufd xmm8, xmm8, 78",
        "pxor xmm8, xmm11",
        "movdqa xmm11, xmm8",
        "pclmulqdq xmm11, xmm1, 16",
        "pshufd xmm8, xmm8, 78",
        "pxor xmm8, xmm11",
        "movdqa xmm2, xmm10",
        "pxor xmm2, xmm8",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 25b",
        "jmp 24f",
        "23:",
        "24:",
        "pshufb xmm2, xmm0",
        "movdqu XMMWORD PTR [rsi], xmm2",
        "ret",
    )
}
