// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `gcm` functions for `x86_64`.
#![allow(dead_code)]

/// GHASH (NIST SP 800-38D §6.4) continued over whole blocks: with the hash subkey `H` the block at `h`, replaces the block `Y` at `*y` with `Yₙ`, where `Y₀ = Y` and `Yᵢ = (Yᵢ₋₁ ⊕ Xᵢ) • H` for the `n` 16-byte blocks `X₁ … Xₙ` starting at `data` (blocks big-endian, `•` the multiplication of §6.3).
///
/// Contract: `VG.Spec.Gcm.ghashContract`. Constant time: only the pointers and `n` may affect timing, not `H`, `Y` or the data.
///
/// # Safety
///
/// * `h` must be valid for reads of 16 bytes.
/// * `y` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 256 bytes; its contents on return are unspecified.
/// * `y` and `scratch` must not overlap each other, `h` or `data` (`h` and `data` may overlap). None of the four regions may overlap the return address on the stack or wrap around the end of the address space (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_ghash(h: *const [u8; 16], y: *mut [u8; 16], data: *const [u8; 16], n: usize, scratch: *mut [u64; 32]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8], rbx",
        "mov QWORD PTR [r8+8], rbp",
        "mov QWORD PTR [r8+16], r12",
        "mov QWORD PTR [r8+24], r13",
        "mov QWORD PTR [r8+32], r14",
        "mov QWORD PTR [r8+40], r15",
        "test rcx, rcx",
        "je 20f",
        "22:",
        "mov r9, QWORD PTR [rsi]",
        "bswap r9",
        "mov r13, QWORD PTR [rdx]",
        "bswap r13",
        "xor r9, r13",
        "mov r10, QWORD PTR [rsi+8]",
        "bswap r10",
        "mov r13, QWORD PTR [rdx+8]",
        "bswap r13",
        "xor r10, r13",
        "mov rbx, QWORD PTR [rdi]",
        "bswap rbx",
        "mov rbp, QWORD PTR [rdi+8]",
        "bswap rbp",
        "mov r11, 0",
        "mov rax, 0",
        "movabs r14, -2233785415175766016",
        "mov r15, 16",
        "23:",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "add r10, r10",
        "adc r9, r9",
        "sbb r12, r12",
        "mov r13, rbx",
        "and r13, r12",
        "xor r11, r13",
        "mov r13, rbp",
        "and r13, r12",
        "xor rax, r13",
        "mov r13, rbx",
        "and r13, 1",
        "ror r13, 1",
        "shr rbp, 1",
        "sbb r12, r12",
        "or rbp, r13",
        "shr rbx, 1",
        "and r12, r14",
        "xor rbx, r12",
        "sub r15, 1",
        "jne 23b",
        "bswap r11",
        "mov QWORD PTR [rsi], r11",
        "bswap rax",
        "mov QWORD PTR [rsi+8], rax",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r8]",
        "mov rbp, QWORD PTR [r8+8]",
        "mov r12, QWORD PTR [r8+16]",
        "mov r13, QWORD PTR [r8+24]",
        "mov r14, QWORD PTR [r8+32]",
        "mov r15, QWORD PTR [r8+40]",
        "ret",
    )
}
