// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `mldsa44` functions for `x86_64`.
#![allow(dead_code)]

/// ML-DSA-44 key generation from a seed, `ML-DSA.KeyGen_internal(ξ)` (FIPS 204 Algorithm 6): with the 32-byte seed `ξ` at `seed`, writes the public key to `*pk` and the private key to `*sk`. Returns 1 on success. Returns 0 if a loop reaches its bound, which is at least the limit of FIPS 204 Appendix C, Table 3 (this happens with probability about 2^-256 or less): the outputs are then unspecified, and the caller must destroy them and treat the operation as failed.
///
/// Contract: `VG.Spec.MlDsa.keyGenContract`. Constant time but for `ρ` and rejections: timing may depend on the pointers, on `ρ` (the first 32 bytes of the public key), and on which half-bytes of the SHAKE256 outputs `RejBoundedPoly` rejects (`rejBoundedLeak`, which is independent of the coefficients it samples), but not on anything else of the seed or the keys.
///
/// The function saves its caller's callee-saved registers in `scratch`; its calls use the 24 bytes of stack below its return address.
///
/// It samples every polynomial of `A` and of `s1` and `s2` whatever the samplers return, and zeroes the polynomial of a sampler that fails rather than branching on it: its timing does not depend on whether key generation fails.
///
/// # Safety
///
/// * `seed` must be valid for reads of 32 bytes.
/// * `pk` must be valid for reads and writes of 1312 bytes.
/// * `sk` must be valid for reads and writes of 2560 bytes.
/// * `scratch` must be valid for reads and writes of 77824 bytes.
/// * `seed` must be random bytes from an approved RBG (FIPS 204 §3.6.1), or a seed so generated before.
/// * `scratch` is working space: on return it holds intermediate values, which the caller must destroy (FIPS 204 §3.6.3).
/// * `pk`, `sk` and `scratch` must not overlap each other or `seed` (distinct Rust objects never do).
/// * None of `seed`, `pk`, `sk` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mldsa44_keygen(seed: *const [u8; 32], pk: *mut [u8; 1312], sk: *mut [u8; 2560], scratch: *mut [u64; 9728]) -> u32 {
    core::arch::naked_asm!(
        "mov QWORD PTR [rcx+840], rbx",
        "mov QWORD PTR [rcx+848], rbp",
        "mov QWORD PTR [rcx+856], r12",
        "mov QWORD PTR [rcx+864], r13",
        "mov QWORD PTR [rcx+872], r14",
        "mov QWORD PTR [rcx+880], r15",
        "mov rbx, rcx",
        "mov rbp, rdi",
        "mov r12, rsi",
        "mov r13, rdx",
        "mov r15d, 1",
        "mov eax, 4",
        "mov BYTE PTR [rbx+896], al",
        "mov eax, 4",
        "mov BYTE PTR [rbx+897], al",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbp",
        "add rcx, 0",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 32",
        "mov rcx, rbx",
        "add rcx, 896",
        "mov r8d, 2",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 34",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1024",
        "mov r8d, 128",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 1024",
        "mov ecx, 32",
        "20:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 20b",
        "mov rdi, rbx",
        "add rdi, 1216",
        "mov rsi, rbx",
        "add rsi, 1056",
        "mov ecx, 64",
        "21:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 21b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+1281], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 4096",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 4096",
        "mov ecx, 256",
        "22:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 22b",
        "mov eax, 1",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 5120",
        "mov ecx, 256",
        "23:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 23b",
        "mov eax, 2",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 6144",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov ecx, 256",
        "24:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 24b",
        "mov eax, 3",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 7168",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 7168",
        "mov ecx, 256",
        "25:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 25b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 8192",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov ecx, 256",
        "26:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 26b",
        "mov eax, 1",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 9216",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov ecx, 256",
        "27:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 27b",
        "mov eax, 2",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 10240",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 10240",
        "mov ecx, 256",
        "28:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 28b",
        "mov eax, 3",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 11264",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 11264",
        "mov ecx, 256",
        "29:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 29b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 12288",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 12288",
        "mov ecx, 256",
        "210:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 210b",
        "mov eax, 1",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 13312",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 13312",
        "mov ecx, 256",
        "211:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 211b",
        "mov eax, 2",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 14336",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 14336",
        "mov ecx, 256",
        "212:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 212b",
        "mov eax, 3",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 15360",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 15360",
        "mov ecx, 256",
        "213:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 213b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 16384",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 16384",
        "mov ecx, 256",
        "214:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 214b",
        "mov eax, 1",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 17408",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 17408",
        "mov ecx, 256",
        "215:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 215b",
        "mov eax, 2",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 18432",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 18432",
        "mov ecx, 256",
        "216:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 216b",
        "mov eax, 3",
        "mov BYTE PTR [rbx+1184], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+1185], al",
        "mov rdi, rbx",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 19456",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov ecx, 256",
        "217:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 217b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+1280], al",
        "mov rdi, rbx",
        "add rdi, 1216",
        "mov esi, 2",
        "mov rdx, rbx",
        "add rdx, 20480",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mldsa_rej_bounded_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov ecx, 256",
        "218:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 218b",
        "mov eax, 1",
        "mov BYTE PTR [rbx+1280], al",
        "mov rdi, rbx",
        "add rdi, 1216",
        "mov esi, 2",
        "mov rdx, rbx",
        "add rdx, 21504",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mldsa_rej_bounded_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 21504",
        "mov ecx, 256",
        "219:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 219b",
        "mov eax, 2",
        "mov BYTE PTR [rbx+1280], al",
        "mov rdi, rbx",
        "add rdi, 1216",
        "mov esi, 2",
        "mov rdx, rbx",
        "add rdx, 22528",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mldsa_rej_bounded_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov ecx, 256",
        "220:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 220b",
        "mov eax, 3",
        "mov BYTE PTR [rbx+1280], al",
        "mov rdi, rbx",
        "add rdi, 1216",
        "mov esi, 2",
        "mov rdx, rbx",
        "add rdx, 23552",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mldsa_rej_bounded_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov ecx, 256",
        "221:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 221b",
        "mov eax, 4",
        "mov BYTE PTR [rbx+1280], al",
        "mov rdi, rbx",
        "add rdi, 1216",
        "mov esi, 2",
        "mov rdx, rbx",
        "add rdx, 24576",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mldsa_rej_bounded_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov ecx, 256",
        "222:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 222b",
        "mov eax, 5",
        "mov BYTE PTR [rbx+1280], al",
        "mov rdi, rbx",
        "add rdi, 1216",
        "mov esi, 2",
        "mov rdx, rbx",
        "add rdx, 25600",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mldsa_rej_bounded_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov ecx, 256",
        "223:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 223b",
        "mov eax, 6",
        "mov BYTE PTR [rbx+1280], al",
        "mov rdi, rbx",
        "add rdi, 1216",
        "mov esi, 2",
        "mov rdx, rbx",
        "add rdx, 26624",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mldsa_rej_bounded_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov ecx, 256",
        "224:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 224b",
        "mov eax, 7",
        "mov BYTE PTR [rbx+1280], al",
        "mov rdi, rbx",
        "add rdi, 1216",
        "mov esi, 2",
        "mov rdx, rbx",
        "add rdx, 27648",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mldsa_rej_bounded_poly}",
        "and r15d, eax",
        "mov r8d, 0",
        "sub r8d, eax",
        "mov rdi, rbx",
        "add rdi, 27648",
        "mov ecx, 256",
        "225:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, r8d",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 225b",
        "mov rdi, r12",
        "add rdi, 0",
        "mov rsi, rbx",
        "add rsi, 1024",
        "mov ecx, 32",
        "226:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 226b",
        "mov rdi, r13",
        "add rdi, 0",
        "mov rsi, rbx",
        "add rsi, 1024",
        "mov ecx, 32",
        "227:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 227b",
        "mov rdi, r13",
        "add rdi, 32",
        "mov rsi, rbx",
        "add rsi, 1120",
        "mov ecx, 32",
        "228:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 228b",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov esi, 2",
        "mov edx, 2",
        "mov rcx, r13",
        "add rcx, 128",
        "mov r8d, 96",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 21504",
        "mov esi, 2",
        "mov edx, 2",
        "mov rcx, r13",
        "add rcx, 224",
        "mov r8d, 96",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov esi, 2",
        "mov edx, 2",
        "mov rcx, r13",
        "add rcx, 320",
        "mov r8d, 96",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov esi, 2",
        "mov edx, 2",
        "mov rcx, r13",
        "add rcx, 416",
        "mov r8d, 96",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov esi, 2",
        "mov edx, 2",
        "mov rcx, r13",
        "add rcx, 512",
        "mov r8d, 96",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov esi, 2",
        "mov edx, 2",
        "mov rcx, r13",
        "add rcx, 608",
        "mov r8d, 96",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov esi, 2",
        "mov edx, 2",
        "mov rcx, r13",
        "add rcx, 704",
        "mov r8d, 96",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 27648",
        "mov esi, 2",
        "mov edx, 2",
        "mov rcx, r13",
        "add rcx, 800",
        "mov r8d, 96",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 21504",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 4096",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 21504",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 6144",
        "mov rdx, rbx",
        "add rdx, 22528",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 7168",
        "mov rdx, rbx",
        "add rdx, 23552",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 24576",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 29696",
        "mov rdx, rbx",
        "add rdx, 30720",
        "call {vg_mldsa_power2round}",
        "mov rdi, rbx",
        "add rdi, 29696",
        "mov esi, 1023",
        "mov rdx, r12",
        "add rdx, 32",
        "mov ecx, 320",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 30720",
        "mov esi, 4095",
        "mov edx, 4096",
        "mov rcx, r13",
        "add rcx, 896",
        "mov r8d, 416",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 8192",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 9216",
        "mov rdx, rbx",
        "add rdx, 21504",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 10240",
        "mov rdx, rbx",
        "add rdx, 22528",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 11264",
        "mov rdx, rbx",
        "add rdx, 23552",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 25600",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 29696",
        "mov rdx, rbx",
        "add rdx, 30720",
        "call {vg_mldsa_power2round}",
        "mov rdi, rbx",
        "add rdi, 29696",
        "mov esi, 1023",
        "mov rdx, r12",
        "add rdx, 352",
        "mov ecx, 320",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 30720",
        "mov esi, 4095",
        "mov edx, 4096",
        "mov rcx, r13",
        "add rcx, 1312",
        "mov r8d, 416",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 12288",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 13312",
        "mov rdx, rbx",
        "add rdx, 21504",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 14336",
        "mov rdx, rbx",
        "add rdx, 22528",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 15360",
        "mov rdx, rbx",
        "add rdx, 23552",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 26624",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 29696",
        "mov rdx, rbx",
        "add rdx, 30720",
        "call {vg_mldsa_power2round}",
        "mov rdi, rbx",
        "add rdi, 29696",
        "mov esi, 1023",
        "mov rdx, r12",
        "add rdx, 672",
        "mov ecx, 320",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 30720",
        "mov esi, 4095",
        "mov edx, 4096",
        "mov rcx, r13",
        "add rcx, 1728",
        "mov r8d, 416",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 16384",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 17408",
        "mov rdx, rbx",
        "add rdx, 21504",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 18432",
        "mov rdx, rbx",
        "add rdx, 22528",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 19456",
        "mov rdx, rbx",
        "add rdx, 23552",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 27648",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 29696",
        "mov rdx, rbx",
        "add rdx, 30720",
        "call {vg_mldsa_power2round}",
        "mov rdi, rbx",
        "add rdi, 29696",
        "mov esi, 1023",
        "mov rdx, r12",
        "add rdx, 992",
        "mov ecx, 320",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 30720",
        "mov esi, 4095",
        "mov edx, 4096",
        "mov rcx, r13",
        "add rcx, 2144",
        "mov r8d, 416",
        "call {vg_mldsa_bit_pack}",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, r12",
        "add rcx, 0",
        "mov r8d, 1312",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 88",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, r13",
        "add rcx, 64",
        "mov r8d, 64",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov eax, r15d",
        "mov r15, QWORD PTR [rbx+880]",
        "mov r14, QWORD PTR [rbx+872]",
        "mov r13, QWORD PTR [rbx+864]",
        "mov r12, QWORD PTR [rbx+856]",
        "mov rbp, QWORD PTR [rbx+848]",
        "mov rbx, QWORD PTR [rbx+840]",
        "ret",
        vg_keccak_absorb = sym super::sha3::vg_keccak_absorb,
        vg_keccak_pad = sym super::sha3::vg_keccak_pad,
        vg_keccak_squeeze = sym super::sha3::vg_keccak_squeeze,
        vg_mldsa_rej_ntt_poly = sym super::mldsa::vg_mldsa_rej_ntt_poly,
        vg_mldsa_rej_bounded_poly = sym super::mldsa::vg_mldsa_rej_bounded_poly,
        vg_mldsa_bit_pack = sym super::mldsa::vg_mldsa_bit_pack,
        vg_mldsa_ntt = sym super::mldsa::vg_mldsa_ntt,
        vg_mldsa_multiply_ntt = sym super::mldsa::vg_mldsa_multiply_ntt,
        vg_mldsa_multiply_add_ntt = sym super::mldsa::vg_mldsa_multiply_add_ntt,
        vg_mldsa_inv_ntt = sym super::mldsa::vg_mldsa_inv_ntt,
        vg_mldsa_add = sym super::mldsa::vg_mldsa_add,
        vg_mldsa_power2round = sym super::mldsa::vg_mldsa_power2round,
        vg_mldsa_simple_bit_pack = sym super::mldsa::vg_mldsa_simple_bit_pack,
    )
}
