// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `mldsa65` functions for `x86_64`.
#![allow(dead_code)]

/// ML-DSA-65 verification of a signature of a message representative, `ML-DSA.Verify_internal(pk, M′, σ)` (FIPS 204 Algorithm 8) with `μ` computed by the caller: with the public key `*pk`, the 64-byte message representative `μ = H(H(pk, 64) ‖ M′, 64)` at `mu` and the signature `*sig`, returns 1 if the signature is valid, and 0 if it is not or if a loop reaches its bound, which is at least the limit of FIPS 204 Appendix C, Table 3 (this happens with probability about 2^-256 or less).
///
/// Contract: `VG.Spec.MlDsa.verifyContract`. Not constant time: timing may depend on the public key, the message representative and the signature.
///
/// It calls the `vg_mldsa_*` primitives and the SHAKE256 sponge. The samplers' results are combined without a branch, so the only branches depend on the public key and the signature.
///
/// # Safety
///
/// * `pk` must be valid for reads of 1952 bytes.
/// * `mu` must be valid for reads of 64 bytes.
/// * `sig` must be valid for reads of 3309 bytes.
/// * `scratch` must be valid for reads and writes of 103424 bytes.
/// * `scratch` is working space: on return it holds intermediate values, which the caller must destroy (FIPS 204 §3.6.3).
/// * `scratch` must not overlap `pk`, `mu` or `sig` (distinct Rust objects never do).
/// * None of `pk`, `mu`, `sig` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mldsa65_verify(pk: *const [u8; 1952], mu: *const [u8; 64], sig: *const [u8; 3309], scratch: *mut [u64; 12928]) -> u32 {
    core::arch::naked_asm!(
        "mov QWORD PTR [rcx+840], rbx",
        "mov QWORD PTR [rcx+848], rbp",
        "mov QWORD PTR [rcx+856], r12",
        "mov QWORD PTR [rcx+864], r13",
        "mov QWORD PTR [rcx+872], r14",
        "mov QWORD PTR [rcx+880], r15",
        "mov rbx, rcx",
        "mov rbp, rdi",
        "mov r12, rsi",
        "mov r13, rdx",
        "mov r15d, 1",
        "mov rdi, r13",
        "add rdi, 3248",
        "mov esi, 61",
        "mov edx, 55",
        "mov rcx, rbx",
        "add rcx, 8192",
        "mov r8d, 1536",
        "call {vg_mldsa_hint_bit_unpack}",
        "mov r15d, eax",
        "test r15d, r15d",
        "jne 20f",
        "jmp 21f",
        "20:",
        "mov rdi, r13",
        "add rdi, 48",
        "mov esi, 640",
        "mov edx, 524287",
        "mov ecx, 524288",
        "mov r8, rbx",
        "add r8, 16384",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 16384",
        "mov esi, 524092",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, r13",
        "add rdi, 688",
        "mov esi, 640",
        "mov edx, 524287",
        "mov ecx, 524288",
        "mov r8, rbx",
        "add r8, 17408",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 17408",
        "mov esi, 524092",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, r13",
        "add rdi, 1328",
        "mov esi, 640",
        "mov edx, 524287",
        "mov ecx, 524288",
        "mov r8, rbx",
        "add r8, 18432",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 18432",
        "mov esi, 524092",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, r13",
        "add rdi, 1968",
        "mov esi, 640",
        "mov edx, 524287",
        "mov ecx, 524288",
        "mov r8, rbx",
        "add r8, 19456",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov esi, 524092",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, r13",
        "add rdi, 2608",
        "mov esi, 640",
        "mov edx, 524287",
        "mov ecx, 524288",
        "mov r8, rbx",
        "add r8, 20480",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov esi, 524092",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "test r15d, r15d",
        "jne 22f",
        "jmp 23f",
        "22:",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbp",
        "add rsi, 0",
        "mov ecx, 32",
        "24:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 24b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 28672",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov ecx, 256",
        "25:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 25b",
        "mov eax, 1",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 29696",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 29696",
        "mov ecx, 256",
        "26:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 26b",
        "mov eax, 2",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 30720",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 30720",
        "mov ecx, 256",
        "27:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 27b",
        "mov eax, 3",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 31744",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 31744",
        "mov ecx, 256",
        "28:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 28b",
        "mov eax, 4",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 32768",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 32768",
        "mov ecx, 256",
        "29:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 29b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 36864",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 36864",
        "mov ecx, 256",
        "210:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 210b",
        "mov eax, 1",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 37888",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 37888",
        "mov ecx, 256",
        "211:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 211b",
        "mov eax, 2",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 38912",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 38912",
        "mov ecx, 256",
        "212:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 212b",
        "mov eax, 3",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 39936",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 39936",
        "mov ecx, 256",
        "213:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 213b",
        "mov eax, 4",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 40960",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 40960",
        "mov ecx, 256",
        "214:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 214b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 45056",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 45056",
        "mov ecx, 256",
        "215:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 215b",
        "mov eax, 1",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 46080",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 46080",
        "mov ecx, 256",
        "216:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 216b",
        "mov eax, 2",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 47104",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 47104",
        "mov ecx, 256",
        "217:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 217b",
        "mov eax, 3",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 48128",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 48128",
        "mov ecx, 256",
        "218:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 218b",
        "mov eax, 4",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 49152",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 49152",
        "mov ecx, 256",
        "219:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 219b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 53248",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 53248",
        "mov ecx, 256",
        "220:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 220b",
        "mov eax, 1",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 54272",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 54272",
        "mov ecx, 256",
        "221:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 221b",
        "mov eax, 2",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 55296",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 55296",
        "mov ecx, 256",
        "222:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 222b",
        "mov eax, 3",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 56320",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 56320",
        "mov ecx, 256",
        "223:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 223b",
        "mov eax, 4",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 57344",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 57344",
        "mov ecx, 256",
        "224:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 224b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 4",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 61440",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 61440",
        "mov ecx, 256",
        "225:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 225b",
        "mov eax, 1",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 4",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 62464",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 62464",
        "mov ecx, 256",
        "226:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 226b",
        "mov eax, 2",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 4",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 63488",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 63488",
        "mov ecx, 256",
        "227:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 227b",
        "mov eax, 3",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 4",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 64512",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 64512",
        "mov ecx, 256",
        "228:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 228b",
        "mov eax, 4",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 4",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 65536",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 65536",
        "mov ecx, 256",
        "229:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 229b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 5",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 69632",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 69632",
        "mov ecx, 256",
        "230:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 230b",
        "mov eax, 1",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 5",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 70656",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 70656",
        "mov ecx, 256",
        "231:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 231b",
        "mov eax, 2",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 5",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 71680",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 71680",
        "mov ecx, 256",
        "232:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 232b",
        "mov eax, 3",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 5",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 72704",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 72704",
        "mov ecx, 256",
        "233:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 233b",
        "mov eax, 4",
        "mov BYTE PTR [rbx+928], al",
        "mov eax, 5",
        "mov BYTE PTR [rbx+929], al",
        "mov rdi, rbx",
        "add rdi, 896",
        "mov rsi, rbx",
        "add rsi, 73728",
        "mov rdx, rbx",
        "add rdx, 4096",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 73728",
        "mov ecx, 256",
        "234:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 234b",
        "mov rdi, r13",
        "add rdi, 0",
        "mov esi, 48",
        "mov edx, 49",
        "mov rcx, rbx",
        "add rcx, 23552",
        "mov r8, rbx",
        "add r8, 4096",
        "call {vg_mldsa_sample_in_ball}",
        "and r15d, eax",
        "mov edx, 0",
        "sub edx, eax",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov ecx, 256",
        "235:",
        "mov eax, DWORD PTR [rdi]",
        "and eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "sub rcx, 1",
        "jne 235b",
        "mov rdi, rbx",
        "add rdi, 16384",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 17408",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 18432",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 28672",
        "mov rdx, rbx",
        "add rdx, 16384",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 29696",
        "mov rdx, rbx",
        "add rdx, 17408",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 30720",
        "mov rdx, rbx",
        "add rdx, 18432",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 31744",
        "mov rdx, rbx",
        "add rdx, 19456",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 32768",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbp",
        "add rdi, 32",
        "mov rsi, rbx",
        "add rsi, 24576",
        "call {vg_mldsa_unpack_t1}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 23552",
        "mov rdx, rbx",
        "add rdx, 24576",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 25600",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov rsi, rbx",
        "add rsi, 26624",
        "mov edx, 261888",
        "mov rcx, rbx",
        "add rcx, 27648",
        "call {vg_mldsa_use_hint}",
        "mov rdi, rbx",
        "add rdi, 27648",
        "mov esi, 15",
        "mov rdx, rbx",
        "add rdx, 1024",
        "mov ecx, 128",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 36864",
        "mov rdx, rbx",
        "add rdx, 16384",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 37888",
        "mov rdx, rbx",
        "add rdx, 17408",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 38912",
        "mov rdx, rbx",
        "add rdx, 18432",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 39936",
        "mov rdx, rbx",
        "add rdx, 19456",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 40960",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbp",
        "add rdi, 352",
        "mov rsi, rbx",
        "add rsi, 24576",
        "call {vg_mldsa_unpack_t1}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 23552",
        "mov rdx, rbx",
        "add rdx, 24576",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 25600",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 26624",
        "mov edx, 261888",
        "mov rcx, rbx",
        "add rcx, 27648",
        "call {vg_mldsa_use_hint}",
        "mov rdi, rbx",
        "add rdi, 27648",
        "mov esi, 15",
        "mov rdx, rbx",
        "add rdx, 1152",
        "mov ecx, 128",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 45056",
        "mov rdx, rbx",
        "add rdx, 16384",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 46080",
        "mov rdx, rbx",
        "add rdx, 17408",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 47104",
        "mov rdx, rbx",
        "add rdx, 18432",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 48128",
        "mov rdx, rbx",
        "add rdx, 19456",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 49152",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbp",
        "add rdi, 672",
        "mov rsi, rbx",
        "add rsi, 24576",
        "call {vg_mldsa_unpack_t1}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 23552",
        "mov rdx, rbx",
        "add rdx, 24576",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 25600",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 10240",
        "mov rsi, rbx",
        "add rsi, 26624",
        "mov edx, 261888",
        "mov rcx, rbx",
        "add rcx, 27648",
        "call {vg_mldsa_use_hint}",
        "mov rdi, rbx",
        "add rdi, 27648",
        "mov esi, 15",
        "mov rdx, rbx",
        "add rdx, 1280",
        "mov ecx, 128",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 53248",
        "mov rdx, rbx",
        "add rdx, 16384",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 54272",
        "mov rdx, rbx",
        "add rdx, 17408",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 55296",
        "mov rdx, rbx",
        "add rdx, 18432",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 56320",
        "mov rdx, rbx",
        "add rdx, 19456",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 57344",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbp",
        "add rdi, 992",
        "mov rsi, rbx",
        "add rsi, 24576",
        "call {vg_mldsa_unpack_t1}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 23552",
        "mov rdx, rbx",
        "add rdx, 24576",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 25600",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 11264",
        "mov rsi, rbx",
        "add rsi, 26624",
        "mov edx, 261888",
        "mov rcx, rbx",
        "add rcx, 27648",
        "call {vg_mldsa_use_hint}",
        "mov rdi, rbx",
        "add rdi, 27648",
        "mov esi, 15",
        "mov rdx, rbx",
        "add rdx, 1408",
        "mov ecx, 128",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 61440",
        "mov rdx, rbx",
        "add rdx, 16384",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 62464",
        "mov rdx, rbx",
        "add rdx, 17408",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 63488",
        "mov rdx, rbx",
        "add rdx, 18432",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 64512",
        "mov rdx, rbx",
        "add rdx, 19456",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 65536",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbp",
        "add rdi, 1312",
        "mov rsi, rbx",
        "add rsi, 24576",
        "call {vg_mldsa_unpack_t1}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 23552",
        "mov rdx, rbx",
        "add rdx, 24576",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 25600",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 12288",
        "mov rsi, rbx",
        "add rsi, 26624",
        "mov edx, 261888",
        "mov rcx, rbx",
        "add rcx, 27648",
        "call {vg_mldsa_use_hint}",
        "mov rdi, rbx",
        "add rdi, 27648",
        "mov esi, 15",
        "mov rdx, rbx",
        "add rdx, 1536",
        "mov ecx, 128",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 69632",
        "mov rdx, rbx",
        "add rdx, 16384",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 70656",
        "mov rdx, rbx",
        "add rdx, 17408",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 71680",
        "mov rdx, rbx",
        "add rdx, 18432",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 72704",
        "mov rdx, rbx",
        "add rdx, 19456",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 73728",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbp",
        "add rdi, 1632",
        "mov rsi, rbx",
        "add rsi, 24576",
        "call {vg_mldsa_unpack_t1}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 23552",
        "mov rdx, rbx",
        "add rdx, 24576",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 25600",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 13312",
        "mov rsi, rbx",
        "add rsi, 26624",
        "mov edx, 261888",
        "mov rcx, rbx",
        "add rcx, 27648",
        "call {vg_mldsa_use_hint}",
        "mov rdi, rbx",
        "add rdi, 27648",
        "mov esi, 15",
        "mov rdx, rbx",
        "add rdx, 1664",
        "mov ecx, 128",
        "call {vg_mldsa_simple_bit_pack}",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, r12",
        "add rcx, 0",
        "mov r8d, 64",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 64",
        "mov rcx, rbx",
        "add rcx, 1024",
        "mov r8d, 768",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 16",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 2048",
        "mov r8d, 48",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rsi, rbx",
        "add rsi, 2048",
        "mov rdi, r13",
        "add rdi, 0",
        "mov ecx, 48",
        "mov edx, 0",
        "236:",
        "movzx eax, BYTE PTR [rsi]",
        "movzx r8d, BYTE PTR [rdi]",
        "xor rax, r8",
        "or rdx, rax",
        "add rsi, 1",
        "add rdi, 1",
        "sub rcx, 1",
        "jne 236b",
        "sub rdx, 1",
        "sbb rax, rax",
        "and r15d, eax",
        "23:",
        "21:",
        "mov eax, r15d",
        "mov r15, QWORD PTR [rbx+880]",
        "mov r14, QWORD PTR [rbx+872]",
        "mov r13, QWORD PTR [rbx+864]",
        "mov r12, QWORD PTR [rbx+856]",
        "mov rbp, QWORD PTR [rbx+848]",
        "mov rbx, QWORD PTR [rbx+840]",
        "ret",
        vg_mldsa_hint_bit_unpack = sym super::mldsa::vg_mldsa_hint_bit_unpack,
        vg_mldsa_bit_unpack = sym super::mldsa::vg_mldsa_bit_unpack,
        vg_mldsa_norm_lt = sym super::mldsa::vg_mldsa_norm_lt,
        vg_mldsa_rej_ntt_poly = sym super::mldsa::vg_mldsa_rej_ntt_poly,
        vg_mldsa_sample_in_ball = sym super::mldsa::vg_mldsa_sample_in_ball,
        vg_mldsa_ntt = sym super::mldsa::vg_mldsa_ntt,
        vg_mldsa_multiply_ntt = sym super::mldsa::vg_mldsa_multiply_ntt,
        vg_mldsa_multiply_add_ntt = sym super::mldsa::vg_mldsa_multiply_add_ntt,
        vg_mldsa_unpack_t1 = sym super::mldsa::vg_mldsa_unpack_t1,
        vg_mldsa_sub = sym super::mldsa::vg_mldsa_sub,
        vg_mldsa_inv_ntt = sym super::mldsa::vg_mldsa_inv_ntt,
        vg_mldsa_use_hint = sym super::mldsa::vg_mldsa_use_hint,
        vg_mldsa_simple_bit_pack = sym super::mldsa::vg_mldsa_simple_bit_pack,
        vg_keccak_absorb = sym super::sha3::vg_keccak_absorb,
        vg_keccak_pad = sym super::sha3::vg_keccak_pad,
        vg_keccak_squeeze = sym super::sha3::vg_keccak_squeeze,
    )
}
