// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `mldsa` functions for `x86_64`.
#![allow(dead_code)]

/// `SimpleBitPack(f, b)` (FIPS 204 Algorithm 16): writes the 256 coefficients of `*f` to `out` as `bitlen b`-bit little-endian fields.
///
/// Contract: `VG.Spec.MlDsa.simpleBitPackContract`. Constant time: only the pointers, `b` and `len` may affect timing, not the data.
///
/// # Safety
///
/// * `f` must be valid for reads of 1024 bytes.
/// * `out` must be valid for reads and writes of `len` bytes.
/// * `b` must be 1023, 43 or 15, and `len` must be `32 * bitlen b` (320, 192 or 128).
/// * Each of the 256 `u32`s of `f` must be at most `b`.
/// * `out` must not overlap `f` (distinct Rust objects never do).
/// * Neither `f` nor `out` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mldsa_simple_bit_pack(f: *const [u32; 256], b: u32, out: *mut u8, len: usize) {
    core::arch::naked_asm!(
        "mov esi, esi",
        "mov r8, rdx",
        "cmp esi, 15",
        "je 20f",
        "cmp esi, 43",
        "je 22f",
        "mov ecx, 64",
        "24:",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi]",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "mov eax, DWORD PTR [rdi+4]",
        "ror rax, 62",
        "add r10, rax",
        "mov BYTE PTR [r8+1], r10b",
        "shr r10, 8",
        "mov eax, DWORD PTR [rdi+8]",
        "ror rax, 60",
        "add r10, rax",
        "mov BYTE PTR [r8+2], r10b",
        "shr r10, 8",
        "mov eax, DWORD PTR [rdi+12]",
        "ror rax, 58",
        "add r10, rax",
        "mov BYTE PTR [r8+3], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+4], r10b",
        "shr r10, 8",
        "add rdi, 16",
        "add r8, 5",
        "sub rcx, 1",
        "jne 24b",
        "jmp 23f",
        "22:",
        "mov ecx, 64",
        "25:",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi]",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+4]",
        "ror rax, 58",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "mov eax, DWORD PTR [rdi+8]",
        "ror rax, 60",
        "add r10, rax",
        "mov BYTE PTR [r8+1], r10b",
        "shr r10, 8",
        "mov eax, DWORD PTR [rdi+12]",
        "ror rax, 62",
        "add r10, rax",
        "mov BYTE PTR [r8+2], r10b",
        "shr r10, 8",
        "add rdi, 16",
        "add r8, 3",
        "sub rcx, 1",
        "jne 25b",
        "23:",
        "jmp 21f",
        "20:",
        "mov ecx, 128",
        "26:",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi]",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+4]",
        "ror rax, 60",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "add rdi, 8",
        "add r8, 1",
        "sub rcx, 1",
        "jne 26b",
        "21:",
        "ret",
    )
}

/// `BitPack(f mod± q, a, b)` (FIPS 204 Algorithm 17): writes `b - (fᵢ mod± q)` for the 256 coefficients `fᵢ` of `*f` to `out` as `bitlen (a + b)`-bit little-endian fields.
///
/// Contract: `VG.Spec.MlDsa.bitPackContract`. Constant time: only the pointers, `a`, `b` and `len` may affect timing, not the data.
///
/// # Safety
///
/// * `f` must be valid for reads of 1024 bytes.
/// * `out` must be valid for reads and writes of `len` bytes.
/// * `(a, b)` must be `(2, 2)`, `(4, 4)`, `(4095, 4096)`, `(2^17 - 1, 2^17)` or `(2^19 - 1, 2^19)`, and `len` must be `32 * bitlen (a + b)`.
/// * Each of the 256 `u32`s of `f` must be less than `q` = 8380417.
/// * Each coefficient `fᵢ mod± q` of `f` (the one of `fᵢ` and `fᵢ - q` whose absolute value is less than `q/2`) must be in `[-a, b]`.
/// * `out` must not overlap `f` (distinct Rust objects never do).
/// * Neither `f` nor `out` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mldsa_bit_pack(f: *const [u32; 256], a: u32, b: u32, out: *mut u8, len: usize) {
    core::arch::naked_asm!(
        "mov edx, edx",
        "mov r8, rcx",
        "cmp edx, 2",
        "je 20f",
        "cmp edx, 4",
        "je 22f",
        "cmp edx, 4096",
        "je 24f",
        "cmp edx, 131072",
        "je 26f",
        "mov ecx, 128",
        "28:",
        "mov r10d, 0",
        "mov eax, 524288",
        "sub eax, DWORD PTR [rdi]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+1], r10b",
        "shr r10, 8",
        "mov eax, 524288",
        "sub eax, DWORD PTR [rdi+4]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 60",
        "add r10, rax",
        "mov BYTE PTR [r8+2], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+3], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+4], r10b",
        "shr r10, 8",
        "add rdi, 8",
        "add r8, 5",
        "sub rcx, 1",
        "jne 28b",
        "jmp 27f",
        "26:",
        "mov ecx, 64",
        "29:",
        "mov r10d, 0",
        "mov eax, 131072",
        "sub eax, DWORD PTR [rdi]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+1], r10b",
        "shr r10, 8",
        "mov eax, 131072",
        "sub eax, DWORD PTR [rdi+4]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 62",
        "add r10, rax",
        "mov BYTE PTR [r8+2], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+3], r10b",
        "shr r10, 8",
        "mov eax, 131072",
        "sub eax, DWORD PTR [rdi+8]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 60",
        "add r10, rax",
        "mov BYTE PTR [r8+4], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+5], r10b",
        "shr r10, 8",
        "mov eax, 131072",
        "sub eax, DWORD PTR [rdi+12]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 58",
        "add r10, rax",
        "mov BYTE PTR [r8+6], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+7], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+8], r10b",
        "shr r10, 8",
        "add rdi, 16",
        "add r8, 9",
        "sub rcx, 1",
        "jne 29b",
        "27:",
        "jmp 25f",
        "24:",
        "mov ecx, 32",
        "210:",
        "mov r10d, 0",
        "mov eax, 4096",
        "sub eax, DWORD PTR [rdi]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "mov eax, 4096",
        "sub eax, DWORD PTR [rdi+4]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 59",
        "add r10, rax",
        "mov BYTE PTR [r8+1], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+2], r10b",
        "shr r10, 8",
        "mov eax, 4096",
        "sub eax, DWORD PTR [rdi+8]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 62",
        "add r10, rax",
        "mov BYTE PTR [r8+3], r10b",
        "shr r10, 8",
        "mov eax, 4096",
        "sub eax, DWORD PTR [rdi+12]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 57",
        "add r10, rax",
        "mov BYTE PTR [r8+4], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+5], r10b",
        "shr r10, 8",
        "mov eax, 4096",
        "sub eax, DWORD PTR [rdi+16]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 60",
        "add r10, rax",
        "mov BYTE PTR [r8+6], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+7], r10b",
        "shr r10, 8",
        "mov eax, 4096",
        "sub eax, DWORD PTR [rdi+20]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 63",
        "add r10, rax",
        "mov BYTE PTR [r8+8], r10b",
        "shr r10, 8",
        "mov eax, 4096",
        "sub eax, DWORD PTR [rdi+24]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 58",
        "add r10, rax",
        "mov BYTE PTR [r8+9], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+10], r10b",
        "shr r10, 8",
        "mov eax, 4096",
        "sub eax, DWORD PTR [rdi+28]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 61",
        "add r10, rax",
        "mov BYTE PTR [r8+11], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+12], r10b",
        "shr r10, 8",
        "add rdi, 32",
        "add r8, 13",
        "sub rcx, 1",
        "jne 210b",
        "25:",
        "jmp 23f",
        "22:",
        "mov ecx, 128",
        "211:",
        "mov r10d, 0",
        "mov eax, 4",
        "sub eax, DWORD PTR [rdi]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "add r10, rax",
        "mov eax, 4",
        "sub eax, DWORD PTR [rdi+4]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 60",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "add rdi, 8",
        "add r8, 1",
        "sub rcx, 1",
        "jne 211b",
        "23:",
        "jmp 21f",
        "20:",
        "mov ecx, 32",
        "212:",
        "mov r10d, 0",
        "mov eax, 2",
        "sub eax, DWORD PTR [rdi]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "add r10, rax",
        "mov eax, 2",
        "sub eax, DWORD PTR [rdi+4]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 61",
        "add r10, rax",
        "mov eax, 2",
        "sub eax, DWORD PTR [rdi+8]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 58",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "mov eax, 2",
        "sub eax, DWORD PTR [rdi+12]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 63",
        "add r10, rax",
        "mov eax, 2",
        "sub eax, DWORD PTR [rdi+16]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 60",
        "add r10, rax",
        "mov eax, 2",
        "sub eax, DWORD PTR [rdi+20]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 57",
        "add r10, rax",
        "mov BYTE PTR [r8+1], r10b",
        "shr r10, 8",
        "mov eax, 2",
        "sub eax, DWORD PTR [rdi+24]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 62",
        "add r10, rax",
        "mov eax, 2",
        "sub eax, DWORD PTR [rdi+28]",
        "sbb r11d, r11d",
        "and r11d, 8380417",
        "add eax, r11d",
        "ror rax, 59",
        "add r10, rax",
        "mov BYTE PTR [r8+2], r10b",
        "shr r10, 8",
        "add rdi, 32",
        "add r8, 3",
        "sub rcx, 1",
        "jne 212b",
        "21:",
        "ret",
    )
}

/// `BitUnpack(v, a, b)` (FIPS 204 Algorithm 19): writes `b - x` for the 256 `bitlen (a + b)`-bit little-endian fields `x` of the `len` bytes at `v`, modulo `q` = 8380417, to `*f`.
///
/// Contract: `VG.Spec.MlDsa.bitUnpackContract`. Constant time: only the pointers, `len`, `a` and `b` may affect timing, not the data.
///
/// # Safety
///
/// * `v` must be valid for reads of `len` bytes.
/// * `f` must be valid for reads and writes of 1024 bytes.
/// * `(a, b)` must be `(2, 2)`, `(4, 4)`, `(4095, 4096)`, `(2^17 - 1, 2^17)` or `(2^19 - 1, 2^19)`, and `len` must be `32 * bitlen (a + b)`.
/// * `f` must not overlap `v` (distinct Rust objects never do).
/// * Neither `v` nor `f` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mldsa_bit_unpack(v: *const u8, len: usize, a: u32, b: u32, f: *mut [u32; 256]) {
    core::arch::naked_asm!(
        "mov ecx, ecx",
        "mov rsi, r8",
        "cmp ecx, 2",
        "je 20f",
        "cmp ecx, 4",
        "je 22f",
        "cmp ecx, 4096",
        "je 24f",
        "cmp ecx, 131072",
        "je 26f",
        "mov ecx, 128",
        "28:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi]",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+1]",
        "ror rax, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+2]",
        "ror rax, 48",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 1048575",
        "shr r10, 20",
        "mov r11d, 524288",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi], r11d",
        "movzx eax, BYTE PTR [rdi+3]",
        "ror rax, 60",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+4]",
        "ror rax, 52",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 1048575",
        "shr r10, 20",
        "mov r11d, 524288",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+4], r11d",
        "add rdi, 5",
        "add rsi, 8",
        "sub rcx, 1",
        "jne 28b",
        "jmp 27f",
        "26:",
        "mov ecx, 64",
        "29:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi]",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+1]",
        "ror rax, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+2]",
        "ror rax, 48",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 262143",
        "shr r10, 18",
        "mov r11d, 131072",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi], r11d",
        "movzx eax, BYTE PTR [rdi+3]",
        "ror rax, 58",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+4]",
        "ror rax, 50",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 262143",
        "shr r10, 18",
        "mov r11d, 131072",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+4], r11d",
        "movzx eax, BYTE PTR [rdi+5]",
        "ror rax, 60",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+6]",
        "ror rax, 52",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 262143",
        "shr r10, 18",
        "mov r11d, 131072",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+8], r11d",
        "movzx eax, BYTE PTR [rdi+7]",
        "ror rax, 62",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+8]",
        "ror rax, 54",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 262143",
        "shr r10, 18",
        "mov r11d, 131072",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+12], r11d",
        "add rdi, 9",
        "add rsi, 16",
        "sub rcx, 1",
        "jne 29b",
        "27:",
        "jmp 25f",
        "24:",
        "mov ecx, 32",
        "210:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi]",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+1]",
        "ror rax, 56",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 8191",
        "shr r10, 13",
        "mov r11d, 4096",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi], r11d",
        "movzx eax, BYTE PTR [rdi+2]",
        "ror rax, 61",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+3]",
        "ror rax, 53",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 8191",
        "shr r10, 13",
        "mov r11d, 4096",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+4], r11d",
        "movzx eax, BYTE PTR [rdi+4]",
        "ror rax, 58",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 8191",
        "shr r10, 13",
        "mov r11d, 4096",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+8], r11d",
        "movzx eax, BYTE PTR [rdi+5]",
        "ror rax, 63",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+6]",
        "ror rax, 55",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 8191",
        "shr r10, 13",
        "mov r11d, 4096",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+12], r11d",
        "movzx eax, BYTE PTR [rdi+7]",
        "ror rax, 60",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+8]",
        "ror rax, 52",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 8191",
        "shr r10, 13",
        "mov r11d, 4096",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+16], r11d",
        "movzx eax, BYTE PTR [rdi+9]",
        "ror rax, 57",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 8191",
        "shr r10, 13",
        "mov r11d, 4096",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+20], r11d",
        "movzx eax, BYTE PTR [rdi+10]",
        "ror rax, 62",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+11]",
        "ror rax, 54",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 8191",
        "shr r10, 13",
        "mov r11d, 4096",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+24], r11d",
        "movzx eax, BYTE PTR [rdi+12]",
        "ror rax, 59",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 8191",
        "shr r10, 13",
        "mov r11d, 4096",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+28], r11d",
        "add rdi, 13",
        "add rsi, 32",
        "sub rcx, 1",
        "jne 210b",
        "25:",
        "jmp 23f",
        "22:",
        "mov ecx, 128",
        "211:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi]",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 15",
        "shr r10, 4",
        "mov r11d, 4",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi], r11d",
        "mov rax, r10",
        "and eax, 15",
        "shr r10, 4",
        "mov r11d, 4",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+4], r11d",
        "add rdi, 1",
        "add rsi, 8",
        "sub rcx, 1",
        "jne 211b",
        "23:",
        "jmp 21f",
        "20:",
        "mov ecx, 32",
        "212:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi]",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 7",
        "shr r10, 3",
        "mov r11d, 2",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi], r11d",
        "mov rax, r10",
        "and eax, 7",
        "shr r10, 3",
        "mov r11d, 2",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+4], r11d",
        "movzx eax, BYTE PTR [rdi+1]",
        "ror rax, 62",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 7",
        "shr r10, 3",
        "mov r11d, 2",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+8], r11d",
        "mov rax, r10",
        "and eax, 7",
        "shr r10, 3",
        "mov r11d, 2",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+12], r11d",
        "mov rax, r10",
        "and eax, 7",
        "shr r10, 3",
        "mov r11d, 2",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+16], r11d",
        "movzx eax, BYTE PTR [rdi+2]",
        "ror rax, 63",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 7",
        "shr r10, 3",
        "mov r11d, 2",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+20], r11d",
        "mov rax, r10",
        "and eax, 7",
        "shr r10, 3",
        "mov r11d, 2",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+24], r11d",
        "mov rax, r10",
        "and eax, 7",
        "shr r10, 3",
        "mov r11d, 2",
        "sub r11d, eax",
        "sbb eax, eax",
        "and eax, 8380417",
        "add r11d, eax",
        "mov DWORD PTR [rsi+28], r11d",
        "add rdi, 3",
        "add rsi, 32",
        "sub rcx, 1",
        "jne 212b",
        "21:",
        "ret",
    )
}

/// The polynomial `t1 · 2^13` of a public key (FIPS 204 Algorithm 23 and line 9 of Algorithm 8): writes the 256 10-bit little-endian fields of the 320 bytes `*v`, each multiplied by 2^13, to `*f`.
///
/// Contract: `VG.Spec.MlDsa.unpackT1Contract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `v` must be valid for reads of 320 bytes.
/// * `f` must be valid for reads and writes of 1024 bytes.
/// * `f` must not overlap `v` (distinct Rust objects never do).
/// * Neither `v` nor `f` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mldsa_unpack_t1(v: *const [u8; 320], f: *mut [u32; 256]) {
    core::arch::naked_asm!(
        "mov ecx, 64",
        "20:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi]",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+1]",
        "ror rax, 56",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 1023",
        "shr r10, 10",
        "ror eax, 19",
        "mov DWORD PTR [rsi], eax",
        "movzx eax, BYTE PTR [rdi+2]",
        "ror rax, 58",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 1023",
        "shr r10, 10",
        "ror eax, 19",
        "mov DWORD PTR [rsi+4], eax",
        "movzx eax, BYTE PTR [rdi+3]",
        "ror rax, 60",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 1023",
        "shr r10, 10",
        "ror eax, 19",
        "mov DWORD PTR [rsi+8], eax",
        "movzx eax, BYTE PTR [rdi+4]",
        "ror rax, 62",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 1023",
        "shr r10, 10",
        "ror eax, 19",
        "mov DWORD PTR [rsi+12], eax",
        "add rdi, 5",
        "add rsi, 16",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// `HintBitPack` (FIPS 204 Algorithm 20): writes the encoding of the hint of `k = len - omega` polynomials of 256 coefficients at `h` (a coefficient is 1 if it is not 0) to the `len = omega + k` bytes at `y`.
///
/// Contract: `VG.Spec.MlDsa.hintBitPackContract`. Not constant time in the hint: timing may depend on the pointers, `hlen`, `omega`, `len` and the hint at `h` (which the signature it encodes reveals), but not on anything else.
///
/// # Safety
///
/// * `h` must be valid for reads of `4 * hlen` bytes.
/// * `y` must be valid for reads and writes of `len` bytes.
/// * `(omega, len - omega)` must be `(80, 4)`, `(55, 6)` or `(75, 8)`, and `hlen` must be `256 * (len - omega)`.
/// * The hint at `h` must have at most `omega` coefficients that are not 0.
/// * `y` must not overlap `h` (distinct Rust objects never do).
/// * Neither `h` nor `y` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mldsa_hint_bit_pack(h: *const u32, hlen: usize, omega: u32, y: *mut u8, len: usize) {
    core::arch::naked_asm!(
        "mov edx, edx",
        "mov eax, 0",
        "mov r9, rcx",
        "mov r10, r8",
        "20:",
        "mov BYTE PTR [r9], al",
        "add r9, 1",
        "sub r10, 1",
        "jne 20b",
        "mov r9, rcx",
        "add r9, rdx",
        "mov r10, r8",
        "sub r10, rdx",
        "21:",
        "mov r11d, 0",
        "22:",
        "mov esi, DWORD PTR [rdi]",
        "cmp esi, 0",
        "jne 23f",
        "jmp 24f",
        "23:",
        "mov BYTE PTR [rcx+rax*1], r11b",
        "add rax, 1",
        "24:",
        "add rdi, 4",
        "add r11, 1",
        "cmp r11d, 256",
        "jne 22b",
        "mov BYTE PTR [r9], al",
        "add r9, 1",
        "sub r10, 1",
        "jne 21b",
        "ret",
    )
}
