// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `mldsa44` functions for `x86_64`.
#![allow(dead_code)]

/// ML-DSA-44 signing of a message representative, `ML-DSA.Sign_internal(sk, M′, rnd)` (FIPS 204 Algorithm 7) with `μ` computed by the caller: with the private key `*sk`, the 64-byte message representative `μ = H(tr ‖ M′, 64)` at `mu` (for the public key hash `tr`, bytes 64–127 of `*sk`) and the randomness `*rnd`, writes the signature to `*sig`. Returns 1 on success. Returns 0 if a loop reaches its bound, which is at least the limit of FIPS 204 Appendix C, Table 3 (this happens with probability about 2^-256 or less): the outputs are then unspecified, and the caller must destroy them and treat the operation as failed.
///
/// Contract: `VG.Spec.MlDsa.signContract`. Constant time but for `ρ` and the rejection sampling: timing may depend on the pointers, on `ρ` (the first 32 bytes of `*sk`), on the number of iterations of the signing loop and the commitment hash of each, and on the hint of the signature (`signLeak`), but not on anything else of the key, the message representative or the randomness.
///
/// The function saves its caller's callee-saved registers in `scratch`; its calls use the 24 bytes of stack below its return address.
///
/// The signing loop runs at most 814 iterations (FIPS 204 Appendix C). Each iteration computes every validity check and combines them without branching: the one branch on their result is the only place an iteration's outcome affects timing.
///
/// # Safety
///
/// * `sk` must be valid for reads of 2560 bytes.
/// * `mu` must be valid for reads of 64 bytes.
/// * `rnd` must be valid for reads of 32 bytes.
/// * `sig` must be valid for reads and writes of 2420 bytes.
/// * `scratch` must be valid for reads and writes of 77824 bytes.
/// * `sk` must have been written by `vg_mldsa44_keygen`.
/// * `rnd` must be fresh random bytes (FIPS 204 §3.6.1), or 32 zero bytes for deterministic signing.
/// * `scratch` is working space: on return it holds intermediate values, which the caller must destroy (FIPS 204 §3.6.3).
/// * `sig` and `scratch` must not overlap each other, `sk`, `mu` or `rnd` (distinct Rust objects never do).
/// * None of `sk`, `mu`, `rnd`, `sig` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mldsa44_sign(sk: *const [u8; 2560], mu: *const [u8; 64], rnd: *const [u8; 32], sig: *mut [u8; 2420], scratch: *mut [u64; 9728]) -> u32 {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+840], rbx",
        "mov QWORD PTR [r8+848], rbp",
        "mov QWORD PTR [r8+856], r12",
        "mov QWORD PTR [r8+864], r13",
        "mov QWORD PTR [r8+872], r14",
        "mov QWORD PTR [r8+880], r15",
        "mov rbx, r8",
        "mov rbp, rdi",
        "mov r12, rsi",
        "mov r13, rdx",
        "mov r14, rcx",
        "mov r15d, 1",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbp",
        "add rsi, 0",
        "mov ecx, 32",
        "20:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 20b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 38912",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 1",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 39936",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 2",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 40960",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 3",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 41984",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 0",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 43008",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 1",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 44032",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 2",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 45056",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 3",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 46080",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 0",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 47104",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 1",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 48128",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 2",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 49152",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 3",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 50176",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 0",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 51200",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 1",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 52224",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 2",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 53248",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "mov eax, 3",
        "mov BYTE PTR [rbx+944], al",
        "mov eax, 3",
        "mov BYTE PTR [rbx+945], al",
        "mov rdi, rbx",
        "add rdi, 912",
        "mov rsi, rbx",
        "add rsi, 54272",
        "mov rdx, rbx",
        "add rdx, 3072",
        "call {vg_mldsa_rej_ntt_poly}",
        "and r15d, eax",
        "test r15d, r15d",
        "jne 21f",
        "jmp 22f",
        "21:",
        "mov rdi, rbp",
        "add rdi, 128",
        "mov esi, 96",
        "mov edx, 2",
        "mov ecx, 2",
        "mov r8, rbx",
        "add r8, 26624",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 26624",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbp",
        "add rdi, 224",
        "mov esi, 96",
        "mov edx, 2",
        "mov ecx, 2",
        "mov r8, rbx",
        "add r8, 27648",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 27648",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbp",
        "add rdi, 320",
        "mov esi, 96",
        "mov edx, 2",
        "mov ecx, 2",
        "mov r8, rbx",
        "add r8, 28672",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 28672",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbp",
        "add rdi, 416",
        "mov esi, 96",
        "mov edx, 2",
        "mov ecx, 2",
        "mov r8, rbx",
        "add r8, 29696",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 29696",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbp",
        "add rdi, 512",
        "mov esi, 96",
        "mov edx, 2",
        "mov ecx, 2",
        "mov r8, rbx",
        "add r8, 30720",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 30720",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbp",
        "add rdi, 608",
        "mov esi, 96",
        "mov edx, 2",
        "mov ecx, 2",
        "mov r8, rbx",
        "add r8, 31744",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 31744",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbp",
        "add rdi, 704",
        "mov esi, 96",
        "mov edx, 2",
        "mov ecx, 2",
        "mov r8, rbx",
        "add r8, 32768",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 32768",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbp",
        "add rdi, 800",
        "mov esi, 96",
        "mov edx, 2",
        "mov ecx, 2",
        "mov r8, rbx",
        "add r8, 33792",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 33792",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbp",
        "add rdi, 896",
        "mov esi, 416",
        "mov edx, 4095",
        "mov ecx, 4096",
        "mov r8, rbx",
        "add r8, 34816",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 34816",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbp",
        "add rdi, 1312",
        "mov esi, 416",
        "mov edx, 4095",
        "mov ecx, 4096",
        "mov r8, rbx",
        "add r8, 35840",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 35840",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbp",
        "add rdi, 1728",
        "mov esi, 416",
        "mov edx, 4095",
        "mov ecx, 4096",
        "mov r8, rbx",
        "add r8, 36864",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 36864",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbp",
        "add rdi, 2144",
        "mov esi, 416",
        "mov edx, 4095",
        "mov ecx, 4096",
        "mov r8, rbx",
        "add r8, 37888",
        "call {vg_mldsa_bit_unpack}",
        "mov rdi, rbx",
        "add rdi, 37888",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbp",
        "add rcx, 32",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 32",
        "mov rcx, r13",
        "add rcx, 0",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 64",
        "mov rcx, r12",
        "add rcx, 0",
        "mov r8d, 64",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 128",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 960",
        "mov r8d, 64",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov eax, 0",
        "mov QWORD PTR [rbx+896], rax",
        "mov eax, 814",
        "mov QWORD PTR [rbx+888], rax",
        "23:",
        "mov rax, QWORD PTR [rbx+896]",
        "add rax, 0",
        "mov BYTE PTR [rbx+1024], al",
        "shr rax, 8",
        "mov BYTE PTR [rbx+1025], al",
        "mov rdi, rbx",
        "add rdi, 960",
        "mov esi, 131072",
        "mov rdx, rbx",
        "add rdx, 14336",
        "mov rcx, rbx",
        "add rcx, 3072",
        "call {vg_mldsa_expand_mask_poly}",
        "mov rdi, rbx",
        "add rdi, 18432",
        "mov rsi, rbx",
        "add rsi, 14336",
        "mov ecx, 1024",
        "24:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 24b",
        "mov rdi, rbx",
        "add rdi, 18432",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rax, QWORD PTR [rbx+896]",
        "add rax, 1",
        "mov BYTE PTR [rbx+1024], al",
        "shr rax, 8",
        "mov BYTE PTR [rbx+1025], al",
        "mov rdi, rbx",
        "add rdi, 960",
        "mov esi, 131072",
        "mov rdx, rbx",
        "add rdx, 15360",
        "mov rcx, rbx",
        "add rcx, 3072",
        "call {vg_mldsa_expand_mask_poly}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 15360",
        "mov ecx, 1024",
        "25:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 25b",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rax, QWORD PTR [rbx+896]",
        "add rax, 2",
        "mov BYTE PTR [rbx+1024], al",
        "shr rax, 8",
        "mov BYTE PTR [rbx+1025], al",
        "mov rdi, rbx",
        "add rdi, 960",
        "mov esi, 131072",
        "mov rdx, rbx",
        "add rdx, 16384",
        "mov rcx, rbx",
        "add rcx, 3072",
        "call {vg_mldsa_expand_mask_poly}",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov rsi, rbx",
        "add rsi, 16384",
        "mov ecx, 1024",
        "26:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 26b",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rax, QWORD PTR [rbx+896]",
        "add rax, 3",
        "mov BYTE PTR [rbx+1024], al",
        "shr rax, 8",
        "mov BYTE PTR [rbx+1025], al",
        "mov rdi, rbx",
        "add rdi, 960",
        "mov esi, 131072",
        "mov rdx, rbx",
        "add rdx, 17408",
        "mov rcx, rbx",
        "add rcx, 3072",
        "call {vg_mldsa_expand_mask_poly}",
        "mov rdi, rbx",
        "add rdi, 21504",
        "mov rsi, rbx",
        "add rsi, 17408",
        "mov ecx, 1024",
        "27:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 27b",
        "mov rdi, rbx",
        "add rdi, 21504",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov rsi, rbx",
        "add rsi, 38912",
        "mov rdx, rbx",
        "add rdx, 18432",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov rsi, rbx",
        "add rsi, 39936",
        "mov rdx, rbx",
        "add rdx, 19456",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov rsi, rbx",
        "add rsi, 40960",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov rsi, rbx",
        "add rsi, 41984",
        "mov rdx, rbx",
        "add rdx, 21504",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov rsi, rbx",
        "add rsi, 43008",
        "mov rdx, rbx",
        "add rdx, 18432",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov rsi, rbx",
        "add rsi, 44032",
        "mov rdx, rbx",
        "add rdx, 19456",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov rsi, rbx",
        "add rsi, 45056",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov rsi, rbx",
        "add rsi, 46080",
        "mov rdx, rbx",
        "add rdx, 21504",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 47104",
        "mov rdx, rbx",
        "add rdx, 18432",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 48128",
        "mov rdx, rbx",
        "add rdx, 19456",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 49152",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 50176",
        "mov rdx, rbx",
        "add rdx, 21504",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 51200",
        "mov rdx, rbx",
        "add rdx, 18432",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 52224",
        "mov rdx, rbx",
        "add rdx, 19456",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 53248",
        "mov rdx, rbx",
        "add rdx, 20480",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 54272",
        "mov rdx, rbx",
        "add rdx, 21504",
        "call {vg_mldsa_multiply_add_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov esi, 95232",
        "mov rdx, rbx",
        "add rdx, 6144",
        "call {vg_mldsa_high_bits}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov esi, 43",
        "mov rdx, rbx",
        "add rdx, 2048",
        "mov ecx, 192",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov esi, 95232",
        "mov rdx, rbx",
        "add rdx, 6144",
        "call {vg_mldsa_high_bits}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov esi, 43",
        "mov rdx, rbx",
        "add rdx, 2240",
        "mov ecx, 192",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov esi, 95232",
        "mov rdx, rbx",
        "add rdx, 6144",
        "call {vg_mldsa_high_bits}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov esi, 43",
        "mov rdx, rbx",
        "add rdx, 2432",
        "mov ecx, 192",
        "call {vg_mldsa_simple_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov esi, 95232",
        "mov rdx, rbx",
        "add rdx, 6144",
        "call {vg_mldsa_high_bits}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov esi, 43",
        "mov rdx, rbx",
        "add rdx, 2624",
        "mov ecx, 192",
        "call {vg_mldsa_simple_bit_pack}",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, r12",
        "add rcx, 0",
        "mov r8d, 64",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 64",
        "mov rcx, rbx",
        "add rcx, 2048",
        "mov r8d, 768",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 16",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1040",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rdi, rbx",
        "add rdi, 1040",
        "mov esi, 32",
        "mov edx, 39",
        "mov rcx, rbx",
        "add rcx, 5120",
        "mov r8, rbx",
        "add r8, 3072",
        "call {vg_mldsa_sample_in_ball}",
        "test eax, eax",
        "jne 28f",
        "mov r15d, 0",
        "mov eax, 1",
        "mov QWORD PTR [rbx+888], rax",
        "jmp 29f",
        "28:",
        "mov rdi, rbx",
        "add rdi, 5120",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_ntt}",
        "mov r15d, 1",
        "mov eax, 0",
        "mov QWORD PTR [rbx+904], rax",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 26624",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 14336",
        "mov rsi, rbx",
        "add rsi, 6144",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 14336",
        "mov esi, 130994",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 27648",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 15360",
        "mov rsi, rbx",
        "add rsi, 6144",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 15360",
        "mov esi, 130994",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 28672",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 16384",
        "mov rsi, rbx",
        "add rsi, 6144",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 16384",
        "mov esi, 130994",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 29696",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 17408",
        "mov rsi, rbx",
        "add rsi, 6144",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 17408",
        "mov esi, 130994",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 30720",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov rsi, rbx",
        "add rsi, 6144",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov esi, 95232",
        "mov rdx, rbx",
        "add rdx, 7168",
        "call {vg_mldsa_low_bits}",
        "mov rdi, rbx",
        "add rdi, 7168",
        "mov esi, 95154",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 31744",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov rsi, rbx",
        "add rsi, 6144",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov esi, 95232",
        "mov rdx, rbx",
        "add rdx, 7168",
        "call {vg_mldsa_low_bits}",
        "mov rdi, rbx",
        "add rdi, 7168",
        "mov esi, 95154",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 32768",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 6144",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov esi, 95232",
        "mov rdx, rbx",
        "add rdx, 7168",
        "call {vg_mldsa_low_bits}",
        "mov rdi, rbx",
        "add rdi, 7168",
        "mov esi, 95154",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 33792",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 6144",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov esi, 95232",
        "mov rdx, rbx",
        "add rdx, 7168",
        "call {vg_mldsa_low_bits}",
        "mov rdi, rbx",
        "add rdi, 7168",
        "mov esi, 95154",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 34816",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov esi, 95232",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 22528",
        "mov ecx, 1024",
        "210:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 210b",
        "mov rdi, rbx",
        "add rdi, 22528",
        "mov rsi, rbx",
        "add rsi, 8192",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 22528",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 22528",
        "mov edx, 95232",
        "mov rcx, rbx",
        "add rcx, 10240",
        "call {vg_mldsa_make_hint}",
        "mov ecx, DWORD PTR [rbx+904]",
        "add ecx, eax",
        "mov QWORD PTR [rbx+904], rcx",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 35840",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov esi, 95232",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 23552",
        "mov ecx, 1024",
        "211:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 211b",
        "mov rdi, rbx",
        "add rdi, 23552",
        "mov rsi, rbx",
        "add rsi, 8192",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 23552",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 23552",
        "mov edx, 95232",
        "mov rcx, rbx",
        "add rcx, 11264",
        "call {vg_mldsa_make_hint}",
        "mov ecx, DWORD PTR [rbx+904]",
        "add ecx, eax",
        "mov QWORD PTR [rbx+904], rcx",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 36864",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov esi, 95232",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 24576",
        "mov ecx, 1024",
        "212:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 212b",
        "mov rdi, rbx",
        "add rdi, 24576",
        "mov rsi, rbx",
        "add rsi, 8192",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 24576",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 24576",
        "mov edx, 95232",
        "mov rcx, rbx",
        "add rcx, 12288",
        "call {vg_mldsa_make_hint}",
        "mov ecx, DWORD PTR [rbx+904]",
        "add ecx, eax",
        "mov QWORD PTR [rbx+904], rcx",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov rsi, rbx",
        "add rsi, 5120",
        "mov rdx, rbx",
        "add rdx, 37888",
        "call {vg_mldsa_multiply_ntt}",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov rsi, rbx",
        "add rsi, 3072",
        "call {vg_mldsa_inv_ntt}",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov esi, 95232",
        "call {vg_mldsa_norm_lt}",
        "and r15d, eax",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 25600",
        "mov ecx, 1024",
        "213:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 213b",
        "mov rdi, rbx",
        "add rdi, 25600",
        "mov rsi, rbx",
        "add rsi, 8192",
        "call {vg_mldsa_add}",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 25600",
        "call {vg_mldsa_sub}",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 25600",
        "mov edx, 95232",
        "mov rcx, rbx",
        "add rcx, 13312",
        "call {vg_mldsa_make_hint}",
        "mov ecx, DWORD PTR [rbx+904]",
        "add ecx, eax",
        "mov QWORD PTR [rbx+904], rcx",
        "mov eax, DWORD PTR [rbx+904]",
        "sub rax, 81",
        "shr rax, 63",
        "and r15d, eax",
        "test r15d, r15d",
        "jne 214f",
        "mov rax, QWORD PTR [rbx+896]",
        "add rax, 4",
        "mov QWORD PTR [rbx+896], rax",
        "jmp 215f",
        "214:",
        "mov eax, 1",
        "mov QWORD PTR [rbx+888], rax",
        "215:",
        "29:",
        "mov rax, QWORD PTR [rbx+888]",
        "sub rax, 1",
        "mov QWORD PTR [rbx+888], rax",
        "jne 23b",
        "test r15d, r15d",
        "jne 216f",
        "jmp 217f",
        "216:",
        "mov rdi, r14",
        "add rdi, 0",
        "mov rsi, rbx",
        "add rsi, 1040",
        "mov ecx, 32",
        "218:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 218b",
        "mov rdi, rbx",
        "add rdi, 14336",
        "mov esi, 131071",
        "mov edx, 131072",
        "mov rcx, r14",
        "add rcx, 32",
        "mov r8d, 576",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 15360",
        "mov esi, 131071",
        "mov edx, 131072",
        "mov rcx, r14",
        "add rcx, 608",
        "mov r8d, 576",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 16384",
        "mov esi, 131071",
        "mov edx, 131072",
        "mov rcx, r14",
        "add rcx, 1184",
        "mov r8d, 576",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 17408",
        "mov esi, 131071",
        "mov edx, 131072",
        "mov rcx, r14",
        "add rcx, 1760",
        "mov r8d, 576",
        "call {vg_mldsa_bit_pack}",
        "mov rdi, rbx",
        "add rdi, 10240",
        "mov esi, 1024",
        "mov edx, 80",
        "mov rcx, r14",
        "add rcx, 2336",
        "mov r8d, 84",
        "call {vg_mldsa_hint_bit_pack}",
        "217:",
        "22:",
        "mov eax, r15d",
        "mov r15, QWORD PTR [rbx+880]",
        "mov r14, QWORD PTR [rbx+872]",
        "mov r13, QWORD PTR [rbx+864]",
        "mov r12, QWORD PTR [rbx+856]",
        "mov rbp, QWORD PTR [rbx+848]",
        "mov rbx, QWORD PTR [rbx+840]",
        "ret",
        vg_mldsa_rej_ntt_poly = sym super::mldsa::vg_mldsa_rej_ntt_poly,
        vg_mldsa_bit_unpack = sym super::mldsa::vg_mldsa_bit_unpack,
        vg_mldsa_ntt = sym super::mldsa::vg_mldsa_ntt,
        vg_keccak_absorb = sym super::sha3::vg_keccak_absorb,
        vg_keccak_pad = sym super::sha3::vg_keccak_pad,
        vg_keccak_squeeze = sym super::sha3::vg_keccak_squeeze,
        vg_mldsa_expand_mask_poly = sym super::mldsa::vg_mldsa_expand_mask_poly,
        vg_mldsa_multiply_ntt = sym super::mldsa::vg_mldsa_multiply_ntt,
        vg_mldsa_multiply_add_ntt = sym super::mldsa::vg_mldsa_multiply_add_ntt,
        vg_mldsa_inv_ntt = sym super::mldsa::vg_mldsa_inv_ntt,
        vg_mldsa_high_bits = sym super::mldsa::vg_mldsa_high_bits,
        vg_mldsa_simple_bit_pack = sym super::mldsa::vg_mldsa_simple_bit_pack,
        vg_mldsa_sample_in_ball = sym super::mldsa::vg_mldsa_sample_in_ball,
        vg_mldsa_add = sym super::mldsa::vg_mldsa_add,
        vg_mldsa_norm_lt = sym super::mldsa::vg_mldsa_norm_lt,
        vg_mldsa_sub = sym super::mldsa::vg_mldsa_sub,
        vg_mldsa_low_bits = sym super::mldsa::vg_mldsa_low_bits,
        vg_mldsa_make_hint = sym super::mldsa::vg_mldsa_make_hint,
        vg_mldsa_bit_pack = sym super::mldsa::vg_mldsa_bit_pack,
        vg_mldsa_hint_bit_pack = sym super::mldsa::vg_mldsa_hint_bit_pack,
    )
}
