// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `mlkem` functions for `x86_64`.
#![allow(dead_code)]

/// The ML-KEM number-theoretic transform, `NTT` (FIPS 203 Algorithm 9), of the polynomial `*f` (256 coefficients less than `q` = 3329), in place.
///
/// Contract: `VG.Spec.MlKem.nttContract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `f` must be valid for reads and writes of 1024 bytes, and each of its 256 `u32`s must be less than 3329.
/// * `scratch` must be valid for reads and writes of 1024 bytes. It is working space: on return it may hold intermediate values, which the caller must destroy (FIPS 203 §3.3).
/// * `f` and `scratch` must not overlap each other (distinct Rust objects never do).
/// * Neither `f` nor `scratch` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_ntt(f: *mut [u32; 256], scratch: *mut [u64; 128]) {
    core::arch::naked_asm!(
        "mov r9, rsi",
        "mov eax, 1",
        "mov DWORD PTR [r9], eax",
        "mov eax, 1729",
        "mov DWORD PTR [r9+4], eax",
        "mov eax, 2580",
        "mov DWORD PTR [r9+8], eax",
        "mov eax, 3289",
        "mov DWORD PTR [r9+12], eax",
        "mov eax, 2642",
        "mov DWORD PTR [r9+16], eax",
        "mov eax, 630",
        "mov DWORD PTR [r9+20], eax",
        "mov eax, 1897",
        "mov DWORD PTR [r9+24], eax",
        "mov eax, 848",
        "mov DWORD PTR [r9+28], eax",
        "mov eax, 1062",
        "mov DWORD PTR [r9+32], eax",
        "mov eax, 1919",
        "mov DWORD PTR [r9+36], eax",
        "mov eax, 193",
        "mov DWORD PTR [r9+40], eax",
        "mov eax, 797",
        "mov DWORD PTR [r9+44], eax",
        "mov eax, 2786",
        "mov DWORD PTR [r9+48], eax",
        "mov eax, 3260",
        "mov DWORD PTR [r9+52], eax",
        "mov eax, 569",
        "mov DWORD PTR [r9+56], eax",
        "mov eax, 1746",
        "mov DWORD PTR [r9+60], eax",
        "mov eax, 296",
        "mov DWORD PTR [r9+64], eax",
        "mov eax, 2447",
        "mov DWORD PTR [r9+68], eax",
        "mov eax, 1339",
        "mov DWORD PTR [r9+72], eax",
        "mov eax, 1476",
        "mov DWORD PTR [r9+76], eax",
        "mov eax, 3046",
        "mov DWORD PTR [r9+80], eax",
        "mov eax, 56",
        "mov DWORD PTR [r9+84], eax",
        "mov eax, 2240",
        "mov DWORD PTR [r9+88], eax",
        "mov eax, 1333",
        "mov DWORD PTR [r9+92], eax",
        "mov eax, 1426",
        "mov DWORD PTR [r9+96], eax",
        "mov eax, 2094",
        "mov DWORD PTR [r9+100], eax",
        "mov eax, 535",
        "mov DWORD PTR [r9+104], eax",
        "mov eax, 2882",
        "mov DWORD PTR [r9+108], eax",
        "mov eax, 2393",
        "mov DWORD PTR [r9+112], eax",
        "mov eax, 2879",
        "mov DWORD PTR [r9+116], eax",
        "mov eax, 1974",
        "mov DWORD PTR [r9+120], eax",
        "mov eax, 821",
        "mov DWORD PTR [r9+124], eax",
        "mov eax, 289",
        "mov DWORD PTR [r9+128], eax",
        "mov eax, 331",
        "mov DWORD PTR [r9+132], eax",
        "mov eax, 3253",
        "mov DWORD PTR [r9+136], eax",
        "mov eax, 1756",
        "mov DWORD PTR [r9+140], eax",
        "mov eax, 1197",
        "mov DWORD PTR [r9+144], eax",
        "mov eax, 2304",
        "mov DWORD PTR [r9+148], eax",
        "mov eax, 2277",
        "mov DWORD PTR [r9+152], eax",
        "mov eax, 2055",
        "mov DWORD PTR [r9+156], eax",
        "mov eax, 650",
        "mov DWORD PTR [r9+160], eax",
        "mov eax, 1977",
        "mov DWORD PTR [r9+164], eax",
        "mov eax, 2513",
        "mov DWORD PTR [r9+168], eax",
        "mov eax, 632",
        "mov DWORD PTR [r9+172], eax",
        "mov eax, 2865",
        "mov DWORD PTR [r9+176], eax",
        "mov eax, 33",
        "mov DWORD PTR [r9+180], eax",
        "mov eax, 1320",
        "mov DWORD PTR [r9+184], eax",
        "mov eax, 1915",
        "mov DWORD PTR [r9+188], eax",
        "mov eax, 2319",
        "mov DWORD PTR [r9+192], eax",
        "mov eax, 1435",
        "mov DWORD PTR [r9+196], eax",
        "mov eax, 807",
        "mov DWORD PTR [r9+200], eax",
        "mov eax, 452",
        "mov DWORD PTR [r9+204], eax",
        "mov eax, 1438",
        "mov DWORD PTR [r9+208], eax",
        "mov eax, 2868",
        "mov DWORD PTR [r9+212], eax",
        "mov eax, 1534",
        "mov DWORD PTR [r9+216], eax",
        "mov eax, 2402",
        "mov DWORD PTR [r9+220], eax",
        "mov eax, 2647",
        "mov DWORD PTR [r9+224], eax",
        "mov eax, 2617",
        "mov DWORD PTR [r9+228], eax",
        "mov eax, 1481",
        "mov DWORD PTR [r9+232], eax",
        "mov eax, 648",
        "mov DWORD PTR [r9+236], eax",
        "mov eax, 2474",
        "mov DWORD PTR [r9+240], eax",
        "mov eax, 3110",
        "mov DWORD PTR [r9+244], eax",
        "mov eax, 1227",
        "mov DWORD PTR [r9+248], eax",
        "mov eax, 910",
        "mov DWORD PTR [r9+252], eax",
        "mov eax, 17",
        "mov DWORD PTR [r9+256], eax",
        "mov eax, 2761",
        "mov DWORD PTR [r9+260], eax",
        "mov eax, 583",
        "mov DWORD PTR [r9+264], eax",
        "mov eax, 2649",
        "mov DWORD PTR [r9+268], eax",
        "mov eax, 1637",
        "mov DWORD PTR [r9+272], eax",
        "mov eax, 723",
        "mov DWORD PTR [r9+276], eax",
        "mov eax, 2288",
        "mov DWORD PTR [r9+280], eax",
        "mov eax, 1100",
        "mov DWORD PTR [r9+284], eax",
        "mov eax, 1409",
        "mov DWORD PTR [r9+288], eax",
        "mov eax, 2662",
        "mov DWORD PTR [r9+292], eax",
        "mov eax, 3281",
        "mov DWORD PTR [r9+296], eax",
        "mov eax, 233",
        "mov DWORD PTR [r9+300], eax",
        "mov eax, 756",
        "mov DWORD PTR [r9+304], eax",
        "mov eax, 2156",
        "mov DWORD PTR [r9+308], eax",
        "mov eax, 3015",
        "mov DWORD PTR [r9+312], eax",
        "mov eax, 3050",
        "mov DWORD PTR [r9+316], eax",
        "mov eax, 1703",
        "mov DWORD PTR [r9+320], eax",
        "mov eax, 1651",
        "mov DWORD PTR [r9+324], eax",
        "mov eax, 2789",
        "mov DWORD PTR [r9+328], eax",
        "mov eax, 1789",
        "mov DWORD PTR [r9+332], eax",
        "mov eax, 1847",
        "mov DWORD PTR [r9+336], eax",
        "mov eax, 952",
        "mov DWORD PTR [r9+340], eax",
        "mov eax, 1461",
        "mov DWORD PTR [r9+344], eax",
        "mov eax, 2687",
        "mov DWORD PTR [r9+348], eax",
        "mov eax, 939",
        "mov DWORD PTR [r9+352], eax",
        "mov eax, 2308",
        "mov DWORD PTR [r9+356], eax",
        "mov eax, 2437",
        "mov DWORD PTR [r9+360], eax",
        "mov eax, 2388",
        "mov DWORD PTR [r9+364], eax",
        "mov eax, 733",
        "mov DWORD PTR [r9+368], eax",
        "mov eax, 2337",
        "mov DWORD PTR [r9+372], eax",
        "mov eax, 268",
        "mov DWORD PTR [r9+376], eax",
        "mov eax, 641",
        "mov DWORD PTR [r9+380], eax",
        "mov eax, 1584",
        "mov DWORD PTR [r9+384], eax",
        "mov eax, 2298",
        "mov DWORD PTR [r9+388], eax",
        "mov eax, 2037",
        "mov DWORD PTR [r9+392], eax",
        "mov eax, 3220",
        "mov DWORD PTR [r9+396], eax",
        "mov eax, 375",
        "mov DWORD PTR [r9+400], eax",
        "mov eax, 2549",
        "mov DWORD PTR [r9+404], eax",
        "mov eax, 2090",
        "mov DWORD PTR [r9+408], eax",
        "mov eax, 1645",
        "mov DWORD PTR [r9+412], eax",
        "mov eax, 1063",
        "mov DWORD PTR [r9+416], eax",
        "mov eax, 319",
        "mov DWORD PTR [r9+420], eax",
        "mov eax, 2773",
        "mov DWORD PTR [r9+424], eax",
        "mov eax, 757",
        "mov DWORD PTR [r9+428], eax",
        "mov eax, 2099",
        "mov DWORD PTR [r9+432], eax",
        "mov eax, 561",
        "mov DWORD PTR [r9+436], eax",
        "mov eax, 2466",
        "mov DWORD PTR [r9+440], eax",
        "mov eax, 2594",
        "mov DWORD PTR [r9+444], eax",
        "mov eax, 2804",
        "mov DWORD PTR [r9+448], eax",
        "mov eax, 1092",
        "mov DWORD PTR [r9+452], eax",
        "mov eax, 403",
        "mov DWORD PTR [r9+456], eax",
        "mov eax, 1026",
        "mov DWORD PTR [r9+460], eax",
        "mov eax, 1143",
        "mov DWORD PTR [r9+464], eax",
        "mov eax, 2150",
        "mov DWORD PTR [r9+468], eax",
        "mov eax, 2775",
        "mov DWORD PTR [r9+472], eax",
        "mov eax, 886",
        "mov DWORD PTR [r9+476], eax",
        "mov eax, 1722",
        "mov DWORD PTR [r9+480], eax",
        "mov eax, 1212",
        "mov DWORD PTR [r9+484], eax",
        "mov eax, 1874",
        "mov DWORD PTR [r9+488], eax",
        "mov eax, 1029",
        "mov DWORD PTR [r9+492], eax",
        "mov eax, 2110",
        "mov DWORD PTR [r9+496], eax",
        "mov eax, 2935",
        "mov DWORD PTR [r9+500], eax",
        "mov eax, 885",
        "mov DWORD PTR [r9+504], eax",
        "mov eax, 2154",
        "mov DWORD PTR [r9+508], eax",
        "mov rsi, rdi",
        "mov r8, r9",
        "add r8, 4",
        "mov edi, 1",
        "20:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, 4",
        "mov ecx, 128",
        "21:",
        "mov eax, DWORD PTR [rsi+512]",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, DWORD PTR [rsi]",
        "mov edx, eax",
        "add edx, 3329",
        "sub edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi+512], edx",
        "add eax, r10d",
        "sub eax, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add eax, r11d",
        "mov DWORD PTR [rsi], eax",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 21b",
        "add rsi, 512",
        "sub rdi, 1",
        "jne 20b",
        "sub rsi, 1024",
        "mov edi, 2",
        "22:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, 4",
        "mov ecx, 64",
        "23:",
        "mov eax, DWORD PTR [rsi+256]",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, DWORD PTR [rsi]",
        "mov edx, eax",
        "add edx, 3329",
        "sub edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi+256], edx",
        "add eax, r10d",
        "sub eax, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add eax, r11d",
        "mov DWORD PTR [rsi], eax",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 23b",
        "add rsi, 256",
        "sub rdi, 1",
        "jne 22b",
        "sub rsi, 1024",
        "mov edi, 4",
        "24:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, 4",
        "mov ecx, 32",
        "25:",
        "mov eax, DWORD PTR [rsi+128]",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, DWORD PTR [rsi]",
        "mov edx, eax",
        "add edx, 3329",
        "sub edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi+128], edx",
        "add eax, r10d",
        "sub eax, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add eax, r11d",
        "mov DWORD PTR [rsi], eax",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 25b",
        "add rsi, 128",
        "sub rdi, 1",
        "jne 24b",
        "sub rsi, 1024",
        "mov edi, 8",
        "26:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, 4",
        "mov ecx, 16",
        "27:",
        "mov eax, DWORD PTR [rsi+64]",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, DWORD PTR [rsi]",
        "mov edx, eax",
        "add edx, 3329",
        "sub edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi+64], edx",
        "add eax, r10d",
        "sub eax, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add eax, r11d",
        "mov DWORD PTR [rsi], eax",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 27b",
        "add rsi, 64",
        "sub rdi, 1",
        "jne 26b",
        "sub rsi, 1024",
        "mov edi, 16",
        "28:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, 4",
        "mov ecx, 8",
        "29:",
        "mov eax, DWORD PTR [rsi+32]",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, DWORD PTR [rsi]",
        "mov edx, eax",
        "add edx, 3329",
        "sub edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi+32], edx",
        "add eax, r10d",
        "sub eax, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add eax, r11d",
        "mov DWORD PTR [rsi], eax",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 29b",
        "add rsi, 32",
        "sub rdi, 1",
        "jne 28b",
        "sub rsi, 1024",
        "mov edi, 32",
        "210:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, 4",
        "mov ecx, 4",
        "211:",
        "mov eax, DWORD PTR [rsi+16]",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, DWORD PTR [rsi]",
        "mov edx, eax",
        "add edx, 3329",
        "sub edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi+16], edx",
        "add eax, r10d",
        "sub eax, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add eax, r11d",
        "mov DWORD PTR [rsi], eax",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 211b",
        "add rsi, 16",
        "sub rdi, 1",
        "jne 210b",
        "sub rsi, 1024",
        "mov edi, 64",
        "212:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, 4",
        "mov ecx, 2",
        "213:",
        "mov eax, DWORD PTR [rsi+8]",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, DWORD PTR [rsi]",
        "mov edx, eax",
        "add edx, 3329",
        "sub edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi+8], edx",
        "add eax, r10d",
        "sub eax, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add eax, r11d",
        "mov DWORD PTR [rsi], eax",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 213b",
        "add rsi, 8",
        "sub rdi, 1",
        "jne 212b",
        "sub rsi, 1024",
        "ret",
    )
}

/// The inverse of the ML-KEM number-theoretic transform, `NTT⁻¹` (FIPS 203 Algorithm 10), of `*f` (256 coefficients less than `q` = 3329), in place.
///
/// Contract: `VG.Spec.MlKem.nttInvContract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `f` must be valid for reads and writes of 1024 bytes, and each of its 256 `u32`s must be less than 3329.
/// * `scratch` must be valid for reads and writes of 1024 bytes. It is working space: on return it may hold intermediate values, which the caller must destroy (FIPS 203 §3.3).
/// * `f` and `scratch` must not overlap each other (distinct Rust objects never do).
/// * Neither `f` nor `scratch` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_ntt_inv(f: *mut [u32; 256], scratch: *mut [u64; 128]) {
    core::arch::naked_asm!(
        "mov r9, rsi",
        "mov eax, 1",
        "mov DWORD PTR [r9], eax",
        "mov eax, 1729",
        "mov DWORD PTR [r9+4], eax",
        "mov eax, 2580",
        "mov DWORD PTR [r9+8], eax",
        "mov eax, 3289",
        "mov DWORD PTR [r9+12], eax",
        "mov eax, 2642",
        "mov DWORD PTR [r9+16], eax",
        "mov eax, 630",
        "mov DWORD PTR [r9+20], eax",
        "mov eax, 1897",
        "mov DWORD PTR [r9+24], eax",
        "mov eax, 848",
        "mov DWORD PTR [r9+28], eax",
        "mov eax, 1062",
        "mov DWORD PTR [r9+32], eax",
        "mov eax, 1919",
        "mov DWORD PTR [r9+36], eax",
        "mov eax, 193",
        "mov DWORD PTR [r9+40], eax",
        "mov eax, 797",
        "mov DWORD PTR [r9+44], eax",
        "mov eax, 2786",
        "mov DWORD PTR [r9+48], eax",
        "mov eax, 3260",
        "mov DWORD PTR [r9+52], eax",
        "mov eax, 569",
        "mov DWORD PTR [r9+56], eax",
        "mov eax, 1746",
        "mov DWORD PTR [r9+60], eax",
        "mov eax, 296",
        "mov DWORD PTR [r9+64], eax",
        "mov eax, 2447",
        "mov DWORD PTR [r9+68], eax",
        "mov eax, 1339",
        "mov DWORD PTR [r9+72], eax",
        "mov eax, 1476",
        "mov DWORD PTR [r9+76], eax",
        "mov eax, 3046",
        "mov DWORD PTR [r9+80], eax",
        "mov eax, 56",
        "mov DWORD PTR [r9+84], eax",
        "mov eax, 2240",
        "mov DWORD PTR [r9+88], eax",
        "mov eax, 1333",
        "mov DWORD PTR [r9+92], eax",
        "mov eax, 1426",
        "mov DWORD PTR [r9+96], eax",
        "mov eax, 2094",
        "mov DWORD PTR [r9+100], eax",
        "mov eax, 535",
        "mov DWORD PTR [r9+104], eax",
        "mov eax, 2882",
        "mov DWORD PTR [r9+108], eax",
        "mov eax, 2393",
        "mov DWORD PTR [r9+112], eax",
        "mov eax, 2879",
        "mov DWORD PTR [r9+116], eax",
        "mov eax, 1974",
        "mov DWORD PTR [r9+120], eax",
        "mov eax, 821",
        "mov DWORD PTR [r9+124], eax",
        "mov eax, 289",
        "mov DWORD PTR [r9+128], eax",
        "mov eax, 331",
        "mov DWORD PTR [r9+132], eax",
        "mov eax, 3253",
        "mov DWORD PTR [r9+136], eax",
        "mov eax, 1756",
        "mov DWORD PTR [r9+140], eax",
        "mov eax, 1197",
        "mov DWORD PTR [r9+144], eax",
        "mov eax, 2304",
        "mov DWORD PTR [r9+148], eax",
        "mov eax, 2277",
        "mov DWORD PTR [r9+152], eax",
        "mov eax, 2055",
        "mov DWORD PTR [r9+156], eax",
        "mov eax, 650",
        "mov DWORD PTR [r9+160], eax",
        "mov eax, 1977",
        "mov DWORD PTR [r9+164], eax",
        "mov eax, 2513",
        "mov DWORD PTR [r9+168], eax",
        "mov eax, 632",
        "mov DWORD PTR [r9+172], eax",
        "mov eax, 2865",
        "mov DWORD PTR [r9+176], eax",
        "mov eax, 33",
        "mov DWORD PTR [r9+180], eax",
        "mov eax, 1320",
        "mov DWORD PTR [r9+184], eax",
        "mov eax, 1915",
        "mov DWORD PTR [r9+188], eax",
        "mov eax, 2319",
        "mov DWORD PTR [r9+192], eax",
        "mov eax, 1435",
        "mov DWORD PTR [r9+196], eax",
        "mov eax, 807",
        "mov DWORD PTR [r9+200], eax",
        "mov eax, 452",
        "mov DWORD PTR [r9+204], eax",
        "mov eax, 1438",
        "mov DWORD PTR [r9+208], eax",
        "mov eax, 2868",
        "mov DWORD PTR [r9+212], eax",
        "mov eax, 1534",
        "mov DWORD PTR [r9+216], eax",
        "mov eax, 2402",
        "mov DWORD PTR [r9+220], eax",
        "mov eax, 2647",
        "mov DWORD PTR [r9+224], eax",
        "mov eax, 2617",
        "mov DWORD PTR [r9+228], eax",
        "mov eax, 1481",
        "mov DWORD PTR [r9+232], eax",
        "mov eax, 648",
        "mov DWORD PTR [r9+236], eax",
        "mov eax, 2474",
        "mov DWORD PTR [r9+240], eax",
        "mov eax, 3110",
        "mov DWORD PTR [r9+244], eax",
        "mov eax, 1227",
        "mov DWORD PTR [r9+248], eax",
        "mov eax, 910",
        "mov DWORD PTR [r9+252], eax",
        "mov eax, 17",
        "mov DWORD PTR [r9+256], eax",
        "mov eax, 2761",
        "mov DWORD PTR [r9+260], eax",
        "mov eax, 583",
        "mov DWORD PTR [r9+264], eax",
        "mov eax, 2649",
        "mov DWORD PTR [r9+268], eax",
        "mov eax, 1637",
        "mov DWORD PTR [r9+272], eax",
        "mov eax, 723",
        "mov DWORD PTR [r9+276], eax",
        "mov eax, 2288",
        "mov DWORD PTR [r9+280], eax",
        "mov eax, 1100",
        "mov DWORD PTR [r9+284], eax",
        "mov eax, 1409",
        "mov DWORD PTR [r9+288], eax",
        "mov eax, 2662",
        "mov DWORD PTR [r9+292], eax",
        "mov eax, 3281",
        "mov DWORD PTR [r9+296], eax",
        "mov eax, 233",
        "mov DWORD PTR [r9+300], eax",
        "mov eax, 756",
        "mov DWORD PTR [r9+304], eax",
        "mov eax, 2156",
        "mov DWORD PTR [r9+308], eax",
        "mov eax, 3015",
        "mov DWORD PTR [r9+312], eax",
        "mov eax, 3050",
        "mov DWORD PTR [r9+316], eax",
        "mov eax, 1703",
        "mov DWORD PTR [r9+320], eax",
        "mov eax, 1651",
        "mov DWORD PTR [r9+324], eax",
        "mov eax, 2789",
        "mov DWORD PTR [r9+328], eax",
        "mov eax, 1789",
        "mov DWORD PTR [r9+332], eax",
        "mov eax, 1847",
        "mov DWORD PTR [r9+336], eax",
        "mov eax, 952",
        "mov DWORD PTR [r9+340], eax",
        "mov eax, 1461",
        "mov DWORD PTR [r9+344], eax",
        "mov eax, 2687",
        "mov DWORD PTR [r9+348], eax",
        "mov eax, 939",
        "mov DWORD PTR [r9+352], eax",
        "mov eax, 2308",
        "mov DWORD PTR [r9+356], eax",
        "mov eax, 2437",
        "mov DWORD PTR [r9+360], eax",
        "mov eax, 2388",
        "mov DWORD PTR [r9+364], eax",
        "mov eax, 733",
        "mov DWORD PTR [r9+368], eax",
        "mov eax, 2337",
        "mov DWORD PTR [r9+372], eax",
        "mov eax, 268",
        "mov DWORD PTR [r9+376], eax",
        "mov eax, 641",
        "mov DWORD PTR [r9+380], eax",
        "mov eax, 1584",
        "mov DWORD PTR [r9+384], eax",
        "mov eax, 2298",
        "mov DWORD PTR [r9+388], eax",
        "mov eax, 2037",
        "mov DWORD PTR [r9+392], eax",
        "mov eax, 3220",
        "mov DWORD PTR [r9+396], eax",
        "mov eax, 375",
        "mov DWORD PTR [r9+400], eax",
        "mov eax, 2549",
        "mov DWORD PTR [r9+404], eax",
        "mov eax, 2090",
        "mov DWORD PTR [r9+408], eax",
        "mov eax, 1645",
        "mov DWORD PTR [r9+412], eax",
        "mov eax, 1063",
        "mov DWORD PTR [r9+416], eax",
        "mov eax, 319",
        "mov DWORD PTR [r9+420], eax",
        "mov eax, 2773",
        "mov DWORD PTR [r9+424], eax",
        "mov eax, 757",
        "mov DWORD PTR [r9+428], eax",
        "mov eax, 2099",
        "mov DWORD PTR [r9+432], eax",
        "mov eax, 561",
        "mov DWORD PTR [r9+436], eax",
        "mov eax, 2466",
        "mov DWORD PTR [r9+440], eax",
        "mov eax, 2594",
        "mov DWORD PTR [r9+444], eax",
        "mov eax, 2804",
        "mov DWORD PTR [r9+448], eax",
        "mov eax, 1092",
        "mov DWORD PTR [r9+452], eax",
        "mov eax, 403",
        "mov DWORD PTR [r9+456], eax",
        "mov eax, 1026",
        "mov DWORD PTR [r9+460], eax",
        "mov eax, 1143",
        "mov DWORD PTR [r9+464], eax",
        "mov eax, 2150",
        "mov DWORD PTR [r9+468], eax",
        "mov eax, 2775",
        "mov DWORD PTR [r9+472], eax",
        "mov eax, 886",
        "mov DWORD PTR [r9+476], eax",
        "mov eax, 1722",
        "mov DWORD PTR [r9+480], eax",
        "mov eax, 1212",
        "mov DWORD PTR [r9+484], eax",
        "mov eax, 1874",
        "mov DWORD PTR [r9+488], eax",
        "mov eax, 1029",
        "mov DWORD PTR [r9+492], eax",
        "mov eax, 2110",
        "mov DWORD PTR [r9+496], eax",
        "mov eax, 2935",
        "mov DWORD PTR [r9+500], eax",
        "mov eax, 885",
        "mov DWORD PTR [r9+504], eax",
        "mov eax, 2154",
        "mov DWORD PTR [r9+508], eax",
        "mov rsi, rdi",
        "mov r8, r9",
        "add r8, 508",
        "mov edi, 64",
        "20:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, -4",
        "mov ecx, 2",
        "21:",
        "mov eax, DWORD PTR [rsi]",
        "mov r10d, DWORD PTR [rsi+8]",
        "mov edx, eax",
        "add edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi], edx",
        "add r10d, 3329",
        "sub r10d, eax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, r10d",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rsi+8], r10d",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 21b",
        "add rsi, 8",
        "sub rdi, 1",
        "jne 20b",
        "sub rsi, 1024",
        "mov edi, 32",
        "22:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, -4",
        "mov ecx, 4",
        "23:",
        "mov eax, DWORD PTR [rsi]",
        "mov r10d, DWORD PTR [rsi+16]",
        "mov edx, eax",
        "add edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi], edx",
        "add r10d, 3329",
        "sub r10d, eax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, r10d",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rsi+16], r10d",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 23b",
        "add rsi, 16",
        "sub rdi, 1",
        "jne 22b",
        "sub rsi, 1024",
        "mov edi, 16",
        "24:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, -4",
        "mov ecx, 8",
        "25:",
        "mov eax, DWORD PTR [rsi]",
        "mov r10d, DWORD PTR [rsi+32]",
        "mov edx, eax",
        "add edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi], edx",
        "add r10d, 3329",
        "sub r10d, eax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, r10d",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rsi+32], r10d",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 25b",
        "add rsi, 32",
        "sub rdi, 1",
        "jne 24b",
        "sub rsi, 1024",
        "mov edi, 8",
        "26:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, -4",
        "mov ecx, 16",
        "27:",
        "mov eax, DWORD PTR [rsi]",
        "mov r10d, DWORD PTR [rsi+64]",
        "mov edx, eax",
        "add edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi], edx",
        "add r10d, 3329",
        "sub r10d, eax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, r10d",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rsi+64], r10d",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 27b",
        "add rsi, 64",
        "sub rdi, 1",
        "jne 26b",
        "sub rsi, 1024",
        "mov edi, 4",
        "28:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, -4",
        "mov ecx, 32",
        "29:",
        "mov eax, DWORD PTR [rsi]",
        "mov r10d, DWORD PTR [rsi+128]",
        "mov edx, eax",
        "add edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi], edx",
        "add r10d, 3329",
        "sub r10d, eax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, r10d",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rsi+128], r10d",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 29b",
        "add rsi, 128",
        "sub rdi, 1",
        "jne 28b",
        "sub rsi, 1024",
        "mov edi, 2",
        "210:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, -4",
        "mov ecx, 64",
        "211:",
        "mov eax, DWORD PTR [rsi]",
        "mov r10d, DWORD PTR [rsi+256]",
        "mov edx, eax",
        "add edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi], edx",
        "add r10d, 3329",
        "sub r10d, eax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, r10d",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rsi+256], r10d",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 211b",
        "add rsi, 256",
        "sub rdi, 1",
        "jne 210b",
        "sub rsi, 1024",
        "mov edi, 1",
        "212:",
        "mov r9d, DWORD PTR [r8]",
        "add r8, -4",
        "mov ecx, 128",
        "213:",
        "mov eax, DWORD PTR [rsi]",
        "mov r10d, DWORD PTR [rsi+512]",
        "mov edx, eax",
        "add edx, r10d",
        "sub edx, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add edx, r11d",
        "mov DWORD PTR [rsi], edx",
        "add r10d, 3329",
        "sub r10d, eax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, r10d",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rsi+512], r10d",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 213b",
        "add rsi, 512",
        "sub rdi, 1",
        "jne 212b",
        "sub rsi, 1024",
        "mov r9d, 3303",
        "mov ecx, 256",
        "214:",
        "mov eax, DWORD PTR [rsi]",
        "mul r9",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rsi], r10d",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 214b",
        "ret",
    )
}

/// Adds the polynomial `*g` to `*f` modulo `q` = 3329, coefficient by coefficient (FIPS 203 (2.3)).
///
/// Contract: `VG.Spec.MlKem.addContract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `f` must be valid for reads and writes of 1024 bytes, and each of its 256 `u32`s must be less than 3329.
/// * `g` must be valid for reads of 1024 bytes, and each of its 256 `u32`s must be less than 3329.
/// * `f` must not overlap `g` (distinct Rust objects never do).
/// * Neither `f` nor `g` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_add(f: *mut [u32; 256], g: *const [u32; 256]) {
    core::arch::naked_asm!(
        "mov ecx, 256",
        "20:",
        "mov eax, DWORD PTR [rdi]",
        "add eax, DWORD PTR [rsi]",
        "sub eax, 3329",
        "sbb edx, edx",
        "and edx, 3329",
        "add eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// Subtracts the polynomial `*g` from `*f` modulo `q` = 3329, coefficient by coefficient.
///
/// Contract: `VG.Spec.MlKem.subContract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `f` must be valid for reads and writes of 1024 bytes, and each of its 256 `u32`s must be less than 3329.
/// * `g` must be valid for reads of 1024 bytes, and each of its 256 `u32`s must be less than 3329.
/// * `f` must not overlap `g` (distinct Rust objects never do).
/// * Neither `f` nor `g` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_sub(f: *mut [u32; 256], g: *const [u32; 256]) {
    core::arch::naked_asm!(
        "mov ecx, 256",
        "20:",
        "mov eax, DWORD PTR [rdi]",
        "add eax, 3329",
        "sub eax, DWORD PTR [rsi]",
        "sub eax, 3329",
        "sbb edx, edx",
        "and edx, 3329",
        "add eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// The product of two NTT representations, `MultiplyNTTs` (FIPS 203 Algorithm 11): writes the product of `*f` and `*g` to `*h`, each of 256 coefficients less than `q` = 3329.
///
/// Contract: `VG.Spec.MlKem.mulContract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `h` must be valid for writes of 1024 bytes.
/// * `f` must be valid for reads of 1024 bytes, and each of its 256 `u32`s must be less than 3329.
/// * `g` must be valid for reads of 1024 bytes, and each of its 256 `u32`s must be less than 3329.
/// * `scratch` must be valid for reads and writes of 1024 bytes. It is working space: on return it may hold intermediate values, which the caller must destroy (FIPS 203 §3.3).
/// * `h` and `scratch` must not overlap each other, `f` or `g` (distinct Rust objects never do).
/// * None of `h`, `f`, `g` and `scratch` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_multiply_ntts(h: *mut [u32; 256], f: *const [u32; 256], g: *const [u32; 256], scratch: *mut [u64; 128]) {
    core::arch::naked_asm!(
        "mov r8, rdx",
        "mov r9, rcx",
        "mov eax, 17",
        "mov DWORD PTR [r9], eax",
        "mov eax, 3312",
        "mov DWORD PTR [r9+4], eax",
        "mov eax, 2761",
        "mov DWORD PTR [r9+8], eax",
        "mov eax, 568",
        "mov DWORD PTR [r9+12], eax",
        "mov eax, 583",
        "mov DWORD PTR [r9+16], eax",
        "mov eax, 2746",
        "mov DWORD PTR [r9+20], eax",
        "mov eax, 2649",
        "mov DWORD PTR [r9+24], eax",
        "mov eax, 680",
        "mov DWORD PTR [r9+28], eax",
        "mov eax, 1637",
        "mov DWORD PTR [r9+32], eax",
        "mov eax, 1692",
        "mov DWORD PTR [r9+36], eax",
        "mov eax, 723",
        "mov DWORD PTR [r9+40], eax",
        "mov eax, 2606",
        "mov DWORD PTR [r9+44], eax",
        "mov eax, 2288",
        "mov DWORD PTR [r9+48], eax",
        "mov eax, 1041",
        "mov DWORD PTR [r9+52], eax",
        "mov eax, 1100",
        "mov DWORD PTR [r9+56], eax",
        "mov eax, 2229",
        "mov DWORD PTR [r9+60], eax",
        "mov eax, 1409",
        "mov DWORD PTR [r9+64], eax",
        "mov eax, 1920",
        "mov DWORD PTR [r9+68], eax",
        "mov eax, 2662",
        "mov DWORD PTR [r9+72], eax",
        "mov eax, 667",
        "mov DWORD PTR [r9+76], eax",
        "mov eax, 3281",
        "mov DWORD PTR [r9+80], eax",
        "mov eax, 48",
        "mov DWORD PTR [r9+84], eax",
        "mov eax, 233",
        "mov DWORD PTR [r9+88], eax",
        "mov eax, 3096",
        "mov DWORD PTR [r9+92], eax",
        "mov eax, 756",
        "mov DWORD PTR [r9+96], eax",
        "mov eax, 2573",
        "mov DWORD PTR [r9+100], eax",
        "mov eax, 2156",
        "mov DWORD PTR [r9+104], eax",
        "mov eax, 1173",
        "mov DWORD PTR [r9+108], eax",
        "mov eax, 3015",
        "mov DWORD PTR [r9+112], eax",
        "mov eax, 314",
        "mov DWORD PTR [r9+116], eax",
        "mov eax, 3050",
        "mov DWORD PTR [r9+120], eax",
        "mov eax, 279",
        "mov DWORD PTR [r9+124], eax",
        "mov eax, 1703",
        "mov DWORD PTR [r9+128], eax",
        "mov eax, 1626",
        "mov DWORD PTR [r9+132], eax",
        "mov eax, 1651",
        "mov DWORD PTR [r9+136], eax",
        "mov eax, 1678",
        "mov DWORD PTR [r9+140], eax",
        "mov eax, 2789",
        "mov DWORD PTR [r9+144], eax",
        "mov eax, 540",
        "mov DWORD PTR [r9+148], eax",
        "mov eax, 1789",
        "mov DWORD PTR [r9+152], eax",
        "mov eax, 1540",
        "mov DWORD PTR [r9+156], eax",
        "mov eax, 1847",
        "mov DWORD PTR [r9+160], eax",
        "mov eax, 1482",
        "mov DWORD PTR [r9+164], eax",
        "mov eax, 952",
        "mov DWORD PTR [r9+168], eax",
        "mov eax, 2377",
        "mov DWORD PTR [r9+172], eax",
        "mov eax, 1461",
        "mov DWORD PTR [r9+176], eax",
        "mov eax, 1868",
        "mov DWORD PTR [r9+180], eax",
        "mov eax, 2687",
        "mov DWORD PTR [r9+184], eax",
        "mov eax, 642",
        "mov DWORD PTR [r9+188], eax",
        "mov eax, 939",
        "mov DWORD PTR [r9+192], eax",
        "mov eax, 2390",
        "mov DWORD PTR [r9+196], eax",
        "mov eax, 2308",
        "mov DWORD PTR [r9+200], eax",
        "mov eax, 1021",
        "mov DWORD PTR [r9+204], eax",
        "mov eax, 2437",
        "mov DWORD PTR [r9+208], eax",
        "mov eax, 892",
        "mov DWORD PTR [r9+212], eax",
        "mov eax, 2388",
        "mov DWORD PTR [r9+216], eax",
        "mov eax, 941",
        "mov DWORD PTR [r9+220], eax",
        "mov eax, 733",
        "mov DWORD PTR [r9+224], eax",
        "mov eax, 2596",
        "mov DWORD PTR [r9+228], eax",
        "mov eax, 2337",
        "mov DWORD PTR [r9+232], eax",
        "mov eax, 992",
        "mov DWORD PTR [r9+236], eax",
        "mov eax, 268",
        "mov DWORD PTR [r9+240], eax",
        "mov eax, 3061",
        "mov DWORD PTR [r9+244], eax",
        "mov eax, 641",
        "mov DWORD PTR [r9+248], eax",
        "mov eax, 2688",
        "mov DWORD PTR [r9+252], eax",
        "mov eax, 1584",
        "mov DWORD PTR [r9+256], eax",
        "mov eax, 1745",
        "mov DWORD PTR [r9+260], eax",
        "mov eax, 2298",
        "mov DWORD PTR [r9+264], eax",
        "mov eax, 1031",
        "mov DWORD PTR [r9+268], eax",
        "mov eax, 2037",
        "mov DWORD PTR [r9+272], eax",
        "mov eax, 1292",
        "mov DWORD PTR [r9+276], eax",
        "mov eax, 3220",
        "mov DWORD PTR [r9+280], eax",
        "mov eax, 109",
        "mov DWORD PTR [r9+284], eax",
        "mov eax, 375",
        "mov DWORD PTR [r9+288], eax",
        "mov eax, 2954",
        "mov DWORD PTR [r9+292], eax",
        "mov eax, 2549",
        "mov DWORD PTR [r9+296], eax",
        "mov eax, 780",
        "mov DWORD PTR [r9+300], eax",
        "mov eax, 2090",
        "mov DWORD PTR [r9+304], eax",
        "mov eax, 1239",
        "mov DWORD PTR [r9+308], eax",
        "mov eax, 1645",
        "mov DWORD PTR [r9+312], eax",
        "mov eax, 1684",
        "mov DWORD PTR [r9+316], eax",
        "mov eax, 1063",
        "mov DWORD PTR [r9+320], eax",
        "mov eax, 2266",
        "mov DWORD PTR [r9+324], eax",
        "mov eax, 319",
        "mov DWORD PTR [r9+328], eax",
        "mov eax, 3010",
        "mov DWORD PTR [r9+332], eax",
        "mov eax, 2773",
        "mov DWORD PTR [r9+336], eax",
        "mov eax, 556",
        "mov DWORD PTR [r9+340], eax",
        "mov eax, 757",
        "mov DWORD PTR [r9+344], eax",
        "mov eax, 2572",
        "mov DWORD PTR [r9+348], eax",
        "mov eax, 2099",
        "mov DWORD PTR [r9+352], eax",
        "mov eax, 1230",
        "mov DWORD PTR [r9+356], eax",
        "mov eax, 561",
        "mov DWORD PTR [r9+360], eax",
        "mov eax, 2768",
        "mov DWORD PTR [r9+364], eax",
        "mov eax, 2466",
        "mov DWORD PTR [r9+368], eax",
        "mov eax, 863",
        "mov DWORD PTR [r9+372], eax",
        "mov eax, 2594",
        "mov DWORD PTR [r9+376], eax",
        "mov eax, 735",
        "mov DWORD PTR [r9+380], eax",
        "mov eax, 2804",
        "mov DWORD PTR [r9+384], eax",
        "mov eax, 525",
        "mov DWORD PTR [r9+388], eax",
        "mov eax, 1092",
        "mov DWORD PTR [r9+392], eax",
        "mov eax, 2237",
        "mov DWORD PTR [r9+396], eax",
        "mov eax, 403",
        "mov DWORD PTR [r9+400], eax",
        "mov eax, 2926",
        "mov DWORD PTR [r9+404], eax",
        "mov eax, 1026",
        "mov DWORD PTR [r9+408], eax",
        "mov eax, 2303",
        "mov DWORD PTR [r9+412], eax",
        "mov eax, 1143",
        "mov DWORD PTR [r9+416], eax",
        "mov eax, 2186",
        "mov DWORD PTR [r9+420], eax",
        "mov eax, 2150",
        "mov DWORD PTR [r9+424], eax",
        "mov eax, 1179",
        "mov DWORD PTR [r9+428], eax",
        "mov eax, 2775",
        "mov DWORD PTR [r9+432], eax",
        "mov eax, 554",
        "mov DWORD PTR [r9+436], eax",
        "mov eax, 886",
        "mov DWORD PTR [r9+440], eax",
        "mov eax, 2443",
        "mov DWORD PTR [r9+444], eax",
        "mov eax, 1722",
        "mov DWORD PTR [r9+448], eax",
        "mov eax, 1607",
        "mov DWORD PTR [r9+452], eax",
        "mov eax, 1212",
        "mov DWORD PTR [r9+456], eax",
        "mov eax, 2117",
        "mov DWORD PTR [r9+460], eax",
        "mov eax, 1874",
        "mov DWORD PTR [r9+464], eax",
        "mov eax, 1455",
        "mov DWORD PTR [r9+468], eax",
        "mov eax, 1029",
        "mov DWORD PTR [r9+472], eax",
        "mov eax, 2300",
        "mov DWORD PTR [r9+476], eax",
        "mov eax, 2110",
        "mov DWORD PTR [r9+480], eax",
        "mov eax, 1219",
        "mov DWORD PTR [r9+484], eax",
        "mov eax, 2935",
        "mov DWORD PTR [r9+488], eax",
        "mov eax, 394",
        "mov DWORD PTR [r9+492], eax",
        "mov eax, 885",
        "mov DWORD PTR [r9+496], eax",
        "mov eax, 2444",
        "mov DWORD PTR [r9+500], eax",
        "mov eax, 2154",
        "mov DWORD PTR [r9+504], eax",
        "mov eax, 1175",
        "mov DWORD PTR [r9+508], eax",
        "mov ecx, 128",
        "20:",
        "mov eax, DWORD PTR [rsi+4]",
        "mov edx, DWORD PTR [r8+4]",
        "mul rdx",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, DWORD PTR [r9]",
        "mul r10",
        "mov r11, rax",
        "mov eax, DWORD PTR [rsi]",
        "mov edx, DWORD PTR [r8]",
        "mul rdx",
        "add rax, r11",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rdi], r10d",
        "mov eax, DWORD PTR [rsi]",
        "mov edx, DWORD PTR [r8+4]",
        "mul rdx",
        "mov r11, rax",
        "mov eax, DWORD PTR [rsi+4]",
        "mov edx, DWORD PTR [r8]",
        "mul rdx",
        "add rax, r11",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rdi+4], r10d",
        "add rdi, 8",
        "add rsi, 8",
        "add r8, 8",
        "add r9, 4",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// `SampleNTT` (FIPS 203 Algorithm 7): writes the element of `T_q` sampled from the SHAKE128 output of the 34 bytes `*seed` to `*a` (256 coefficients less than `q` = 3329), and returns 1. Returns 0 if the loop reaches its bound, which is at least 280 iterations (FIPS 203 Appendix B; this happens with probability less than 2^-261): `*a` is then unspecified, and the caller must destroy it and treat the operation as failed.
///
/// Contract: `VG.Spec.MlKem.sampleNTTContract`. Not constant time in the seed: timing may depend on the pointer and on `*seed` (public in ML-KEM: the seed `ρ` of the matrix and two indices), but not on anything else.
///
/// # Safety
///
/// * `seed` must be valid for reads of 34 bytes.
/// * `a` must be valid for writes of 1024 bytes.
/// * `scratch` must be valid for reads and writes of 2048 bytes. It is working space: on return it may hold intermediate values, which the caller must destroy (FIPS 203 §3.3).
/// * `a` and `scratch` must not overlap each other or `seed` (distinct Rust objects never do).
/// * None of `seed`, `a` and `scratch` may overlap the return address on the stack or the 16 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_sample_ntt(seed: *const [u8; 34], a: *mut [u32; 256], scratch: *mut [u64; 256]) -> u32 {
    core::arch::naked_asm!(
        "mov QWORD PTR [rdx+1680], rbx",
        "mov QWORD PTR [rdx+1688], rbp",
        "mov rbx, rdx",
        "mov rbp, rsi",
        "mov rcx, rdi",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "mov esi, 168",
        "mov edx, 0",
        "mov r8d, 34",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "mov esi, 168",
        "mov edx, 34",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "mov esi, 168",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 840",
        "mov r8d, 840",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rsi, rbx",
        "add rsi, 840",
        "mov edi, 0",
        "mov ecx, 280",
        "20:",
        "movzx eax, BYTE PTR [rsi]",
        "movzx edx, BYTE PTR [rsi+1]",
        "movzx r8d, BYTE PTR [rsi+2]",
        "mov r9d, edx",
        "and r9d, 15",
        "ror r9d, 24",
        "add r9d, eax",
        "shr edx, 4",
        "ror r8d, 28",
        "add r8d, edx",
        "cmp rdi, 256",
        "jb 21f",
        "jmp 22f",
        "21:",
        "cmp r9d, 3329",
        "jb 23f",
        "jmp 24f",
        "23:",
        "mov DWORD PTR [rbp+rdi*4], r9d",
        "add rdi, 1",
        "24:",
        "cmp rdi, 256",
        "jb 25f",
        "jmp 26f",
        "25:",
        "cmp r8d, 3329",
        "jb 27f",
        "jmp 28f",
        "27:",
        "mov DWORD PTR [rbp+rdi*4], r8d",
        "add rdi, 1",
        "28:",
        "26:",
        "22:",
        "add rsi, 3",
        "sub rcx, 1",
        "jne 20b",
        "mov rax, rdi",
        "shr rax, 8",
        "mov rbp, QWORD PTR [rbx+1688]",
        "mov rbx, QWORD PTR [rbx+1680]",
        "ret",
        vg_keccak_absorb = sym super::sha3::vg_keccak_absorb,
        vg_keccak_pad = sym super::sha3::vg_keccak_pad,
        vg_keccak_squeeze = sym super::sha3::vg_keccak_squeeze,
    )
}

/// `ByteEncode₁₂` (FIPS 203 Algorithm 5): writes the 256 coefficients of `*f`, each less than `q` = 3329, to `*out` as 12-bit little-endian fields.
///
/// Contract: `VG.Spec.MlKem.encode12Contract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `f` must be valid for reads of 1024 bytes, and each of its 256 `u32`s must be less than 3329.
/// * `out` must be valid for writes of 384 bytes.
/// * `out` must not overlap `f` (distinct Rust objects never do).
/// * Neither `f` nor `out` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_encode12(f: *const [u32; 256], out: *mut [u8; 384]) {
    core::arch::naked_asm!(
        "mov ecx, 128",
        "20:",
        "mov eax, DWORD PTR [rdi]",
        "mov edx, DWORD PTR [rdi+4]",
        "ror edx, 20",
        "add eax, edx",
        "mov BYTE PTR [rsi], al",
        "shr eax, 8",
        "mov BYTE PTR [rsi+1], al",
        "shr eax, 8",
        "mov BYTE PTR [rsi+2], al",
        "add rdi, 8",
        "add rsi, 3",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// `ByteDecode₁₂` (FIPS 203 Algorithm 6): writes the 256 12-bit little-endian fields of `*b`, each reduced modulo `q` = 3329, to `*f`.
///
/// Contract: `VG.Spec.MlKem.decode12Contract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `b` must be valid for reads of 384 bytes.
/// * `f` must be valid for writes of 1024 bytes.
/// * `f` must not overlap `b` (distinct Rust objects never do).
/// * Neither `b` nor `f` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_decode12(b: *const [u8; 384], f: *mut [u32; 256]) {
    core::arch::naked_asm!(
        "mov ecx, 128",
        "20:",
        "movzx eax, BYTE PTR [rdi]",
        "movzx edx, BYTE PTR [rdi+1]",
        "ror edx, 24",
        "add eax, edx",
        "movzx edx, BYTE PTR [rdi+2]",
        "ror edx, 16",
        "add eax, edx",
        "mov edx, eax",
        "and eax, 4095",
        "shr edx, 12",
        "sub eax, 3329",
        "sbb r8d, r8d",
        "and r8d, 3329",
        "add eax, r8d",
        "sub edx, 3329",
        "sbb r8d, r8d",
        "and r8d, 3329",
        "add edx, r8d",
        "mov DWORD PTR [rsi], eax",
        "mov DWORD PTR [rsi+4], edx",
        "add rdi, 3",
        "add rsi, 8",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// `SamplePolyCBD₂` (FIPS 203 Algorithm 8 with `η` = 2): writes the polynomial sampled from the 128 bytes `*b` to `*f` (256 coefficients less than `q` = 3329).
///
/// Contract: `VG.Spec.MlKem.cbd2Contract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `b` must be valid for reads of 128 bytes.
/// * `f` must be valid for writes of 1024 bytes.
/// * `f` must not overlap `b` (distinct Rust objects never do).
/// * Neither `b` nor `f` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_cbd2(b: *const [u8; 128], f: *mut [u32; 256]) {
    core::arch::naked_asm!(
        "mov ecx, 128",
        "20:",
        "movzx eax, BYTE PTR [rdi]",
        "mov edx, eax",
        "shr edx, 1",
        "and eax, 85",
        "and edx, 85",
        "add eax, edx",
        "mov edx, eax",
        "and edx, 3",
        "add edx, 3329",
        "mov r8d, eax",
        "shr r8d, 2",
        "and r8d, 3",
        "sub edx, r8d",
        "sub edx, 3329",
        "sbb r9d, r9d",
        "and r9d, 3329",
        "add edx, r9d",
        "mov DWORD PTR [rsi], edx",
        "mov edx, eax",
        "shr edx, 4",
        "and edx, 3",
        "add edx, 3329",
        "shr eax, 6",
        "sub edx, eax",
        "sub edx, 3329",
        "sbb r9d, r9d",
        "and r9d, 3329",
        "add edx, r9d",
        "mov DWORD PTR [rsi+4], edx",
        "add rdi, 1",
        "add rsi, 8",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// `ByteEncode_d(Compress_d(f))` (FIPS 203 (4.7) and Algorithm 5): writes the 256 coefficients of `*f` (each less than `q` = 3329), compressed to `d` bits, to `out` as `d`-bit little-endian fields.
///
/// Contract: `VG.Spec.MlKem.compressEncodeContract`. Constant time: only the pointers, `d` and `len` may affect timing, not the data.
///
/// # Safety
///
/// * `d` must be 1, 4 or 10, and `len` must be `32 * d`.
/// * `f` must be valid for reads of 1024 bytes, and each of its 256 `u32`s must be less than 3329.
/// * `out` must be valid for writes of `len` bytes.
/// * `out` must not overlap `f` (distinct Rust objects never do).
/// * Neither `f` nor `out` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_compress_encode(f: *const [u32; 256], d: u32, out: *mut u8, len: usize) {
    core::arch::naked_asm!(
        "mov esi, esi",
        "mov r8, rdx",
        "cmp esi, 1",
        "je 20f",
        "cmp esi, 4",
        "je 22f",
        "mov r9, 161271",
        "mov ecx, 64",
        "24:",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi+12]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1023",
        "ror r10, 54",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+8]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1023",
        "ror r10, 54",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+4]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1023",
        "ror r10, 54",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1023",
        "ror r10, 54",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+1], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+2], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+3], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+4], r10b",
        "shr r10, 8",
        "add rdi, 16",
        "add r8, 5",
        "sub rcx, 1",
        "jne 24b",
        "jmp 23f",
        "22:",
        "mov r9, 2520",
        "mov ecx, 128",
        "25:",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi+4]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 15",
        "ror r10, 60",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 15",
        "ror r10, 60",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "add rdi, 8",
        "add r8, 1",
        "sub rcx, 1",
        "jne 25b",
        "23:",
        "jmp 21f",
        "20:",
        "mov r9, 315",
        "mov ecx, 32",
        "26:",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi+28]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+24]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+20]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+16]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+12]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+8]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+4]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "add rdi, 32",
        "add r8, 1",
        "sub rcx, 1",
        "jne 26b",
        "21:",
        "ret",
    )
}

/// `Decompress_d(ByteDecode_d(b))` (FIPS 203 Algorithm 6 and (4.8)): writes the 256 `d`-bit little-endian fields of the `len` bytes at `b`, decompressed, to `*f` (each less than `q` = 3329).
///
/// Contract: `VG.Spec.MlKem.decodeDecompressContract`. Constant time: only the pointers, `d` and `len` may affect timing, not the data.
///
/// # Safety
///
/// * `d` must be 1, 4 or 10, and `len` must be `32 * d`.
/// * `b` must be valid for reads of `len` bytes.
/// * `f` must be valid for writes of 1024 bytes.
/// * `f` must not overlap `b` (distinct Rust objects never do).
/// * Neither `b` nor `f` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_decode_decompress(b: *const u8, len: usize, d: u32, f: *mut [u32; 256]) {
    core::arch::naked_asm!(
        "mov edx, edx",
        "mov rsi, rcx",
        "cmp edx, 1",
        "je 20f",
        "cmp edx, 4",
        "je 22f",
        "mov r9, 3329",
        "mov ecx, 64",
        "24:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi+4]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+3]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+2]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+1]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi]",
        "ror r10, 56",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 1023",
        "mul r9",
        "add rax, 512",
        "shr rax, 10",
        "mov DWORD PTR [rsi], eax",
        "shr r10, 10",
        "mov rax, r10",
        "and eax, 1023",
        "mul r9",
        "add rax, 512",
        "shr rax, 10",
        "mov DWORD PTR [rsi+4], eax",
        "shr r10, 10",
        "mov rax, r10",
        "and eax, 1023",
        "mul r9",
        "add rax, 512",
        "shr rax, 10",
        "mov DWORD PTR [rsi+8], eax",
        "shr r10, 10",
        "mov rax, r10",
        "and eax, 1023",
        "mul r9",
        "add rax, 512",
        "shr rax, 10",
        "mov DWORD PTR [rsi+12], eax",
        "shr r10, 10",
        "add rdi, 5",
        "add rsi, 16",
        "sub rcx, 1",
        "jne 24b",
        "jmp 23f",
        "22:",
        "mov r9, 3329",
        "mov ecx, 128",
        "25:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi]",
        "ror r10, 56",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 15",
        "mul r9",
        "add rax, 8",
        "shr rax, 4",
        "mov DWORD PTR [rsi], eax",
        "shr r10, 4",
        "mov rax, r10",
        "and eax, 15",
        "mul r9",
        "add rax, 8",
        "shr rax, 4",
        "mov DWORD PTR [rsi+4], eax",
        "shr r10, 4",
        "add rdi, 1",
        "add rsi, 8",
        "sub rcx, 1",
        "jne 25b",
        "23:",
        "jmp 21f",
        "20:",
        "mov r9, 3329",
        "mov ecx, 32",
        "26:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi]",
        "ror r10, 56",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+4], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+8], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+12], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+16], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+20], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+24], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+28], eax",
        "shr r10, 1",
        "add rdi, 1",
        "add rsi, 32",
        "sub rcx, 1",
        "jne 26b",
        "21:",
        "ret",
    )
}
