// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `mlkem768` functions for `x86_64`.
#![allow(dead_code)]

/// The ML-KEM-768 encapsulation key check (FIPS 203 §7.2): returns 1 if every 12-bit integer that the first 1152 bytes of `*ek` encode is less than `q` = 3329 (the modulus check), and 0 otherwise. An encapsulation key must pass it before it is given to `vg_mlkem768_encaps`.
///
/// Contract: `VG.Spec.MlKem.checkEkContract`. Constant time: only the pointer may affect timing.
///
/// # Safety
///
/// * `ek` must be valid for reads of 1184 bytes.
/// * `ek` must not overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem768_check_ek(ek: *const [u8; 1184]) -> u32 {
    core::arch::naked_asm!(
        "mov r8d, 0",
        "mov ecx, 384",
        "20:",
        "movzx eax, BYTE PTR [rdi]",
        "movzx edx, BYTE PTR [rdi+1]",
        "ror edx, 24",
        "add eax, edx",
        "movzx edx, BYTE PTR [rdi+2]",
        "ror edx, 16",
        "add eax, edx",
        "mov edx, eax",
        "and eax, 4095",
        "shr edx, 12",
        "cmp eax, 3329",
        "adc r8, 0",
        "cmp edx, 3329",
        "adc r8, 0",
        "add rdi, 3",
        "sub rcx, 1",
        "jne 20b",
        "cmp r8, 768",
        "sbb rax, rax",
        "add rax, 1",
        "ret",
    )
}

/// ML-KEM-768 key generation from a seed, `ML-KEM.KeyGen_internal(d, z)` (FIPS 203 Algorithm 16): with `d` in bytes 0–31 of `*seed` and `z` in bytes 32–63, writes the encapsulation key to `*ek` and the decapsulation key to `*dk`. Returns 1 on success. Returns 0 if a `SampleNTT` (FIPS 203 Algorithm 7) reaches the bound on its loop's iterations, which is at least 280 (FIPS 203 Appendix B; this happens with probability less than 2^-261): the outputs are then unspecified, and the caller must destroy them and treat the operation as failed.
///
/// Contract: `VG.Spec.MlKem.keyGenContract`. Constant time but for `ρ`: timing may depend on the pointers and on `ρ` (the last 32 bytes of the encapsulation key), but not on anything else of the seed or the keys.
///
/// The function saves its caller's callee-saved registers in `scratch`; its calls use the 24 bytes of stack below its return address.
///
/// # Safety
///
/// * `seed` must be valid for reads of 64 bytes, and must be random bytes from an approved RBG (FIPS 203 §3.3), or a seed so generated before.
/// * `ek` must be valid for writes of 1184 bytes and `dk` for writes of 2400 bytes.
/// * `scratch` must be valid for reads and writes of 32768 bytes. It is working space: on return it holds intermediate values, which the caller must destroy (FIPS 203 §3.3).
/// * `ek`, `dk` and `scratch` must not overlap each other or `seed` (distinct Rust objects never do).
/// * None of `seed`, `ek`, `dk` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem768_keygen(seed: *const [u8; 64], ek: *mut [u8; 1184], dk: *mut [u8; 2400], scratch: *mut [u64; 4096]) -> u32 {
    core::arch::naked_asm!(
        "mov QWORD PTR [rcx+840], rbx",
        "mov QWORD PTR [rcx+848], rbp",
        "mov QWORD PTR [rcx+856], r12",
        "mov QWORD PTR [rcx+864], r13",
        "mov QWORD PTR [rcx+872], r14",
        "mov QWORD PTR [rcx+880], r15",
        "mov rbx, rcx",
        "mov rbp, rdi",
        "mov r12, rsi",
        "mov r13, rdx",
        "mov r15d, 1",
        "mov eax, 3",
        "mov BYTE PTR [rbx+896], al",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 72",
        "mov edx, 0",
        "mov rcx, rbp",
        "add rcx, 0",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 72",
        "mov edx, 32",
        "mov rcx, rbx",
        "add rcx, 896",
        "mov r8d, 1",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 72",
        "mov edx, 33",
        "mov ecx, 6",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 72",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1024",
        "mov r8d, 64",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rdi, rbx",
        "add rdi, 904",
        "mov rsi, rbx",
        "add rsi, 1024",
        "mov ecx, 32",
        "20:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 20b",
        "mov eax, 0",
        "mov BYTE PTR [rbx+936], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+937], al",
        "mov rdi, rbx",
        "add rdi, 904",
        "mov rsi, rbx",
        "add rsi, 10240",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mlkem_sample_ntt}",
        "and r15d, eax",
        "mov eax, 1",
        "mov BYTE PTR [rbx+936], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+937], al",
        "mov rdi, rbx",
        "add rdi, 904",
        "mov rsi, rbx",
        "add rsi, 11264",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mlkem_sample_ntt}",
        "and r15d, eax",
        "mov eax, 2",
        "mov BYTE PTR [rbx+936], al",
        "mov eax, 0",
        "mov BYTE PTR [rbx+937], al",
        "mov rdi, rbx",
        "add rdi, 904",
        "mov rsi, rbx",
        "add rsi, 12288",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mlkem_sample_ntt}",
        "and r15d, eax",
        "mov eax, 0",
        "mov BYTE PTR [rbx+936], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+937], al",
        "mov rdi, rbx",
        "add rdi, 904",
        "mov rsi, rbx",
        "add rsi, 13312",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mlkem_sample_ntt}",
        "and r15d, eax",
        "mov eax, 1",
        "mov BYTE PTR [rbx+936], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+937], al",
        "mov rdi, rbx",
        "add rdi, 904",
        "mov rsi, rbx",
        "add rsi, 14336",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mlkem_sample_ntt}",
        "and r15d, eax",
        "mov eax, 2",
        "mov BYTE PTR [rbx+936], al",
        "mov eax, 1",
        "mov BYTE PTR [rbx+937], al",
        "mov rdi, rbx",
        "add rdi, 904",
        "mov rsi, rbx",
        "add rsi, 15360",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mlkem_sample_ntt}",
        "and r15d, eax",
        "mov eax, 0",
        "mov BYTE PTR [rbx+936], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+937], al",
        "mov rdi, rbx",
        "add rdi, 904",
        "mov rsi, rbx",
        "add rsi, 16384",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mlkem_sample_ntt}",
        "and r15d, eax",
        "mov eax, 1",
        "mov BYTE PTR [rbx+936], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+937], al",
        "mov rdi, rbx",
        "add rdi, 904",
        "mov rsi, rbx",
        "add rsi, 17408",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mlkem_sample_ntt}",
        "and r15d, eax",
        "mov eax, 2",
        "mov BYTE PTR [rbx+936], al",
        "mov eax, 2",
        "mov BYTE PTR [rbx+937], al",
        "mov rdi, rbx",
        "add rdi, 904",
        "mov rsi, rbx",
        "add rsi, 18432",
        "mov rdx, rbx",
        "add rdx, 2048",
        "call {vg_mlkem_sample_ntt}",
        "and r15d, eax",
        "test r15d, r15d",
        "jne 21f",
        "jmp 22f",
        "21:",
        "mov eax, 0",
        "mov BYTE PTR [rbx+896], al",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1056",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 32",
        "mov rcx, rbx",
        "add rcx, 896",
        "mov r8d, 1",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 33",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1120",
        "mov r8d, 128",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rdi, rbx",
        "add rdi, 1120",
        "mov rsi, rbx",
        "add rsi, 4096",
        "call {vg_mlkem_cbd2}",
        "mov rdi, rbx",
        "add rdi, 4096",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mlkem_ntt}",
        "mov eax, 1",
        "mov BYTE PTR [rbx+896], al",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1056",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 32",
        "mov rcx, rbx",
        "add rcx, 896",
        "mov r8d, 1",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 33",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1120",
        "mov r8d, 128",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rdi, rbx",
        "add rdi, 1120",
        "mov rsi, rbx",
        "add rsi, 5120",
        "call {vg_mlkem_cbd2}",
        "mov rdi, rbx",
        "add rdi, 5120",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mlkem_ntt}",
        "mov eax, 2",
        "mov BYTE PTR [rbx+896], al",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1056",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 32",
        "mov rcx, rbx",
        "add rcx, 896",
        "mov r8d, 1",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 33",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1120",
        "mov r8d, 128",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rdi, rbx",
        "add rdi, 1120",
        "mov rsi, rbx",
        "add rsi, 6144",
        "call {vg_mlkem_cbd2}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mlkem_ntt}",
        "mov eax, 3",
        "mov BYTE PTR [rbx+896], al",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1056",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 32",
        "mov rcx, rbx",
        "add rcx, 896",
        "mov r8d, 1",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 33",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1120",
        "mov r8d, 128",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rdi, rbx",
        "add rdi, 1120",
        "mov rsi, rbx",
        "add rsi, 7168",
        "call {vg_mlkem_cbd2}",
        "mov rdi, rbx",
        "add rdi, 7168",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mlkem_ntt}",
        "mov eax, 4",
        "mov BYTE PTR [rbx+896], al",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1056",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 32",
        "mov rcx, rbx",
        "add rcx, 896",
        "mov r8d, 1",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 33",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1120",
        "mov r8d, 128",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rdi, rbx",
        "add rdi, 1120",
        "mov rsi, rbx",
        "add rsi, 8192",
        "call {vg_mlkem_cbd2}",
        "mov rdi, rbx",
        "add rdi, 8192",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mlkem_ntt}",
        "mov eax, 5",
        "mov BYTE PTR [rbx+896], al",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1056",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 32",
        "mov rcx, rbx",
        "add rcx, 896",
        "mov r8d, 1",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 33",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 1120",
        "mov r8d, 128",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rdi, rbx",
        "add rdi, 1120",
        "mov rsi, rbx",
        "add rsi, 9216",
        "call {vg_mlkem_cbd2}",
        "mov rdi, rbx",
        "add rdi, 9216",
        "mov rsi, rbx",
        "add rsi, 2048",
        "call {vg_mlkem_ntt}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 10240",
        "mov rdx, rbx",
        "add rdx, 4096",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mlkem_multiply_ntts}",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov rsi, rbx",
        "add rsi, 11264",
        "mov rdx, rbx",
        "add rdx, 5120",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mlkem_multiply_ntts}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 20480",
        "call {vg_mlkem_add}",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov rsi, rbx",
        "add rsi, 12288",
        "mov rdx, rbx",
        "add rdx, 6144",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mlkem_multiply_ntts}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 20480",
        "call {vg_mlkem_add}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 7168",
        "call {vg_mlkem_add}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, r12",
        "add rsi, 0",
        "call {vg_mlkem_encode12}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 13312",
        "mov rdx, rbx",
        "add rdx, 4096",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mlkem_multiply_ntts}",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov rsi, rbx",
        "add rsi, 14336",
        "mov rdx, rbx",
        "add rdx, 5120",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mlkem_multiply_ntts}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 20480",
        "call {vg_mlkem_add}",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov rsi, rbx",
        "add rsi, 15360",
        "mov rdx, rbx",
        "add rdx, 6144",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mlkem_multiply_ntts}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 20480",
        "call {vg_mlkem_add}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 8192",
        "call {vg_mlkem_add}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, r12",
        "add rsi, 384",
        "call {vg_mlkem_encode12}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 16384",
        "mov rdx, rbx",
        "add rdx, 4096",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mlkem_multiply_ntts}",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov rsi, rbx",
        "add rsi, 17408",
        "mov rdx, rbx",
        "add rdx, 5120",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mlkem_multiply_ntts}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 20480",
        "call {vg_mlkem_add}",
        "mov rdi, rbx",
        "add rdi, 20480",
        "mov rsi, rbx",
        "add rsi, 18432",
        "mov rdx, rbx",
        "add rdx, 6144",
        "mov rcx, rbx",
        "add rcx, 2048",
        "call {vg_mlkem_multiply_ntts}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 20480",
        "call {vg_mlkem_add}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, rbx",
        "add rsi, 9216",
        "call {vg_mlkem_add}",
        "mov rdi, rbx",
        "add rdi, 19456",
        "mov rsi, r12",
        "add rsi, 768",
        "call {vg_mlkem_encode12}",
        "mov rdi, rbx",
        "add rdi, 4096",
        "mov rsi, r13",
        "add rsi, 0",
        "call {vg_mlkem_encode12}",
        "mov rdi, rbx",
        "add rdi, 5120",
        "mov rsi, r13",
        "add rsi, 384",
        "call {vg_mlkem_encode12}",
        "mov rdi, rbx",
        "add rdi, 6144",
        "mov rsi, r13",
        "add rsi, 768",
        "call {vg_mlkem_encode12}",
        "mov rdi, r12",
        "add rdi, 1152",
        "mov rsi, rbx",
        "add rsi, 1024",
        "mov ecx, 32",
        "23:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 23b",
        "mov rdi, r13",
        "add rdi, 1152",
        "mov rsi, r12",
        "add rsi, 0",
        "mov ecx, 1184",
        "24:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 24b",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, r12",
        "add rcx, 0",
        "mov r8d, 1184",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 96",
        "mov ecx, 6",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "add rdi, 0",
        "mov esi, 136",
        "mov edx, 0",
        "mov rcx, r13",
        "add rcx, 2336",
        "mov r8d, 32",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rdi, r13",
        "add rdi, 2368",
        "mov rsi, rbp",
        "add rsi, 32",
        "mov ecx, 32",
        "25:",
        "movzx eax, BYTE PTR [rsi]",
        "mov BYTE PTR [rdi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 25b",
        "22:",
        "mov eax, r15d",
        "mov r15, QWORD PTR [rbx+880]",
        "mov r14, QWORD PTR [rbx+872]",
        "mov r13, QWORD PTR [rbx+864]",
        "mov r12, QWORD PTR [rbx+856]",
        "mov rbp, QWORD PTR [rbx+848]",
        "mov rbx, QWORD PTR [rbx+840]",
        "ret",
        vg_keccak_absorb = sym super::sha3::vg_keccak_absorb,
        vg_keccak_pad = sym super::sha3::vg_keccak_pad,
        vg_keccak_squeeze = sym super::sha3::vg_keccak_squeeze,
        vg_mlkem_sample_ntt = sym super::mlkem::vg_mlkem_sample_ntt,
        vg_mlkem_cbd2 = sym super::mlkem::vg_mlkem_cbd2,
        vg_mlkem_ntt = sym super::mlkem::vg_mlkem_ntt,
        vg_mlkem_multiply_ntts = sym super::mlkem::vg_mlkem_multiply_ntts,
        vg_mlkem_add = sym super::mlkem::vg_mlkem_add,
        vg_mlkem_encode12 = sym super::mlkem::vg_mlkem_encode12,
    )
}
