// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `mlkem1024` functions for `x86_64`.
#![allow(dead_code)]

/// `ByteEncode_d(Compress_d(f))` (FIPS 203 (4.7) and Algorithm 5) for the widths of ML-KEM-1024: writes the 256 coefficients of `*f` (each less than `q` = 3329), compressed to `d` bits, to `out` as `d`-bit little-endian fields.
///
/// Contract: `VG.Spec.MlKem1024.compressEncodeContract`. Constant time: only the pointers, `d` and `len` may affect timing, not the data.
///
/// # Safety
///
/// * `d` must be 5 or 11, and `len` must be `32 * d`.
/// * `f` must be valid for reads of 1024 bytes, and each of its 256 `u32`s must be less than 3329.
/// * `out` must be valid for writes of `len` bytes.
/// * `out` must not overlap `f` (distinct Rust objects never do).
/// * Neither `f` nor `out` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem1024_compress_encode(f: *const [u32; 256], d: u32, out: *mut u8, len: usize) {
    core::arch::naked_asm!(
        "mov esi, esi",
        "mov r8, rdx",
        "cmp esi, 5",
        "je 20f",
        "mov r9, 322542",
        "mov ecx, 32",
        "22:",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi+16]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 2047",
        "ror r10, 53",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+12]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 2047",
        "ror r10, 53",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+8]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 2047",
        "ror r10, 53",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+4]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 2047",
        "ror r10, 53",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 2047",
        "ror r10, 53",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+1], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+2], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+3], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+4], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+5], r10b",
        "shr r10, 8",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi+28]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 2047",
        "ror r10, 53",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+24]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 2047",
        "ror r10, 53",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+20]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 2047",
        "ror r10, 53",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+16]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 2047",
        "ror r10, 53",
        "add r10, rax",
        "shr r10, 4",
        "mov BYTE PTR [r8+6], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+7], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+8], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+9], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+10], r10b",
        "shr r10, 8",
        "add rdi, 32",
        "add r8, 11",
        "sub rcx, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "mov r9, 5040",
        "mov ecx, 32",
        "23:",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi+28]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 31",
        "ror r10, 59",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+24]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 31",
        "ror r10, 59",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+20]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 31",
        "ror r10, 59",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+16]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 31",
        "ror r10, 59",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+12]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 31",
        "ror r10, 59",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+8]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 31",
        "ror r10, 59",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+4]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 31",
        "ror r10, 59",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi]",
        "mul r9",
        "add rax, 261888",
        "shr rax, 19",
        "and eax, 31",
        "ror r10, 59",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+1], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+2], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+3], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+4], r10b",
        "shr r10, 8",
        "add rdi, 32",
        "add r8, 5",
        "sub rcx, 1",
        "jne 23b",
        "21:",
        "ret",
    )
}

/// `Decompress_d(ByteDecode_d(b))` (FIPS 203 Algorithm 6 and (4.8)) for the widths of ML-KEM-1024: writes the 256 `d`-bit little-endian fields of the `len` bytes at `b`, decompressed, to `*f` (each less than `q` = 3329).
///
/// Contract: `VG.Spec.MlKem1024.decodeDecompressContract`. Constant time: only the pointers, `d` and `len` may affect timing, not the data.
///
/// # Safety
///
/// * `d` must be 5 or 11, and `len` must be `32 * d`.
/// * `b` must be valid for reads of `len` bytes.
/// * `f` must be valid for writes of 1024 bytes.
/// * `f` must not overlap `b` (distinct Rust objects never do).
/// * Neither `b` nor `f` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem1024_decode_decompress(b: *const u8, len: usize, d: u32, f: *mut [u32; 256]) {
    core::arch::naked_asm!(
        "mov edx, edx",
        "mov rsi, rcx",
        "cmp edx, 5",
        "je 20f",
        "mov r9, 3329",
        "mov ecx, 32",
        "22:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi+5]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+4]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+3]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+2]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+1]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi]",
        "ror r10, 56",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 2047",
        "mul r9",
        "add rax, 1024",
        "shr rax, 11",
        "mov DWORD PTR [rsi], eax",
        "shr r10, 11",
        "mov rax, r10",
        "and eax, 2047",
        "mul r9",
        "add rax, 1024",
        "shr rax, 11",
        "mov DWORD PTR [rsi+4], eax",
        "shr r10, 11",
        "mov rax, r10",
        "and eax, 2047",
        "mul r9",
        "add rax, 1024",
        "shr rax, 11",
        "mov DWORD PTR [rsi+8], eax",
        "shr r10, 11",
        "mov rax, r10",
        "and eax, 2047",
        "mul r9",
        "add rax, 1024",
        "shr rax, 11",
        "mov DWORD PTR [rsi+12], eax",
        "shr r10, 11",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi+10]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+9]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+8]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+7]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+6]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+5]",
        "ror r10, 56",
        "add r10, rax",
        "shr r10, 4",
        "mov rax, r10",
        "and eax, 2047",
        "mul r9",
        "add rax, 1024",
        "shr rax, 11",
        "mov DWORD PTR [rsi+16], eax",
        "shr r10, 11",
        "mov rax, r10",
        "and eax, 2047",
        "mul r9",
        "add rax, 1024",
        "shr rax, 11",
        "mov DWORD PTR [rsi+20], eax",
        "shr r10, 11",
        "mov rax, r10",
        "and eax, 2047",
        "mul r9",
        "add rax, 1024",
        "shr rax, 11",
        "mov DWORD PTR [rsi+24], eax",
        "shr r10, 11",
        "mov rax, r10",
        "and eax, 2047",
        "mul r9",
        "add rax, 1024",
        "shr rax, 11",
        "mov DWORD PTR [rsi+28], eax",
        "shr r10, 11",
        "add rdi, 11",
        "add rsi, 32",
        "sub rcx, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "mov r9, 3329",
        "mov ecx, 32",
        "23:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi+4]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+3]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+2]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+1]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi]",
        "ror r10, 56",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 31",
        "mul r9",
        "add rax, 16",
        "shr rax, 5",
        "mov DWORD PTR [rsi], eax",
        "shr r10, 5",
        "mov rax, r10",
        "and eax, 31",
        "mul r9",
        "add rax, 16",
        "shr rax, 5",
        "mov DWORD PTR [rsi+4], eax",
        "shr r10, 5",
        "mov rax, r10",
        "and eax, 31",
        "mul r9",
        "add rax, 16",
        "shr rax, 5",
        "mov DWORD PTR [rsi+8], eax",
        "shr r10, 5",
        "mov rax, r10",
        "and eax, 31",
        "mul r9",
        "add rax, 16",
        "shr rax, 5",
        "mov DWORD PTR [rsi+12], eax",
        "shr r10, 5",
        "mov rax, r10",
        "and eax, 31",
        "mul r9",
        "add rax, 16",
        "shr rax, 5",
        "mov DWORD PTR [rsi+16], eax",
        "shr r10, 5",
        "mov rax, r10",
        "and eax, 31",
        "mul r9",
        "add rax, 16",
        "shr rax, 5",
        "mov DWORD PTR [rsi+20], eax",
        "shr r10, 5",
        "mov rax, r10",
        "and eax, 31",
        "mul r9",
        "add rax, 16",
        "shr rax, 5",
        "mov DWORD PTR [rsi+24], eax",
        "shr r10, 5",
        "mov rax, r10",
        "and eax, 31",
        "mul r9",
        "add rax, 16",
        "shr rax, 5",
        "mov DWORD PTR [rsi+28], eax",
        "shr r10, 5",
        "add rdi, 5",
        "add rsi, 32",
        "sub rcx, 1",
        "jne 23b",
        "21:",
        "ret",
    )
}

/// The ML-KEM-1024 encapsulation key check (FIPS 203 §7.2): returns 1 if every 12-bit integer that the first 1536 bytes of `*ek` encode is less than `q` = 3329 (the modulus check), and 0 otherwise. An encapsulation key must pass it before it is given to `vg_mlkem1024_encaps`.
///
/// Contract: `VG.Spec.MlKem1024.checkEkContract`. Constant time: only the pointer may affect timing.
///
/// # Safety
///
/// * `ek` must be valid for reads of 1568 bytes.
/// * `ek` must not overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem1024_check_ek(ek: *const [u8; 1568]) -> u32 {
    core::arch::naked_asm!(
        "mov r8d, 0",
        "mov ecx, 512",
        "20:",
        "movzx eax, BYTE PTR [rdi]",
        "movzx edx, BYTE PTR [rdi+1]",
        "ror edx, 24",
        "add eax, edx",
        "movzx edx, BYTE PTR [rdi+2]",
        "ror edx, 16",
        "add eax, edx",
        "mov edx, eax",
        "and eax, 4095",
        "shr edx, 12",
        "cmp eax, 3329",
        "adc r8, 0",
        "cmp edx, 3329",
        "adc r8, 0",
        "add rdi, 3",
        "sub rcx, 1",
        "jne 20b",
        "cmp r8, 1024",
        "sbb rax, rax",
        "add rax, 1",
        "ret",
    )
}
