// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `mlkem` functions for `x86_64`.
#![allow(dead_code)]

/// The ML-KEM number-theoretic transform, `NTT` (FIPS 203 Algorithm 9), of the polynomial `*f` (256 coefficients less than `q` = 3329), in place.
///
/// Contract: `VG.Spec.MlKem.nttContract`. Constant time: only the pointers may affect timing, not the data.
///
/// The function computes on eight coefficients at a time in SSE2 registers. It sets MXCSR to `0x1FBF` around its multiplications (Intel's mitigation of MXCSR-configuration-dependent timing) and loads the caller's MXCSR back before returning.
///
/// # Safety
///
/// * `f` must be valid for reads and writes of 1024 bytes.
/// * `scratch` must be valid for reads and writes of 1024 bytes.
/// * Each of the 256 `u32`s of `f` must be less than 3329.
/// * `scratch` is working space: on return it may hold intermediate values, which the caller must destroy (FIPS 203 §3.3).
/// * `f` and `scratch` must not overlap each other (distinct Rust objects never do).
/// * Neither `f` nor `scratch` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_ntt(f: *mut [u32; 256], scratch: *mut [u64; 128]) {
    core::arch::naked_asm!(
        "stmxcsr DWORD PTR [rsi+768]",
        "mov r11d, DWORD PTR [rsi+768]",
        "and r11d, 65535",
        "mov eax, 8127",
        "mov DWORD PTR [rsi+772], eax",
        "ldmxcsr DWORD PTR [rsi+772]",
        "lfence",
        "movabs r9, 510045414021073133",
        "mov QWORD PTR [rsi], r9",
        "movabs r9, 56859178044360149",
        "mov QWORD PTR [rsi+8], r9",
        "movabs r9, 51235218965531734",
        "mov QWORD PTR [rsi+16], r9",
        "movabs r9, 413213233114973122",
        "mov QWORD PTR [rsi+24], r9",
        "movabs r9, 107806050082882109",
        "mov QWORD PTR [rsi+32], r9",
        "movabs r9, 900445868001462724",
        "mov QWORD PTR [rsi+40], r9",
        "movabs r9, 171139929822792280",
        "mov QWORD PTR [rsi+48], r9",
        "movabs r9, 494846426562103035",
        "mov QWORD PTR [rsi+56], r9",
        "movabs r9, 285709028528227527",
        "mov QWORD PTR [rsi+64], r9",
        "movabs r9, 502445920291588084",
        "mov QWORD PTR [rsi+72], r9",
        "movabs r9, 749580786754716164",
        "mov QWORD PTR [rsi+80], r9",
        "movabs r9, 413487282095851183",
        "mov QWORD PTR [rsi+88], r9",
        "movabs r9, 233637364892109228",
        "mov QWORD PTR [rsi+96], r9",
        "movabs r9, 669360731832189035",
        "mov QWORD PTR [rsi+104], r9",
        "movabs r9, 732968660552977267",
        "mov QWORD PTR [rsi+112], r9",
        "movabs r9, 578152510004920768",
        "mov QWORD PTR [rsi+120], r9",
        "movabs r9, 237285789102114994",
        "mov QWORD PTR [rsi+128], r9",
        "movabs r9, 29561529811011614",
        "mov QWORD PTR [rsi+136], r9",
        "movabs r9, 870884338190451110",
        "mov QWORD PTR [rsi+144], r9",
        "movabs r9, 465284896969264094",
        "mov QWORD PTR [rsi+152], r9",
        "movabs r9, 895658353811393547",
        "mov QWORD PTR [rsi+160], r9",
        "movabs r9, 314982211412232696",
        "mov QWORD PTR [rsi+168], r9",
        "movabs r9, 98245319648872139",
        "mov QWORD PTR [rsi+176], r9",
        "movabs r9, 915933202169266594",
        "mov QWORD PTR [rsi+184], r9",
        "movabs r9, 171702325730673457",
        "mov QWORD PTR [rsi+192], r9",
        "movabs r9, 108094397009888554",
        "mov QWORD PTR [rsi+200], r9",
        "movabs r9, 561266335040473154",
        "mov QWORD PTR [rsi+208], r9",
        "movabs r9, 470072410941163927",
        "mov QWORD PTR [rsi+216], r9",
        "movabs r9, 223499940604086368",
        "mov QWORD PTR [rsi+224], r9",
        "movabs r9, 134555600354477851",
        "mov QWORD PTR [rsi+232], r9",
        "movabs r9, 278945979905674389",
        "mov QWORD PTR [rsi+240], r9",
        "movabs r9, 458247799147660222",
        "mov QWORD PTR [rsi+248], r9",
        "mov eax, 218172673",
        "movq xmm15, rax",
        "pshufd xmm15, xmm15, 0",
        "mov eax, -217976063",
        "movq xmm14, rax",
        "pshufd xmm14, xmm14, 0",
        "mov r9, rdi",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov ecx, 32",
        "20:",
        "movdqu xmm0, XMMWORD PTR [r9]",
        "movdqu xmm1, XMMWORD PTR [r9+16]",
        "packssdw xmm0, xmm1",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "add r9, 32",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 20b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 2",
        "mov eax, 1",
        "21:",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 0",
        "add r8, 2",
        "mov ecx, 16",
        "22:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+256]",
        "movdqa xmm2, xmm1",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm1, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm1, xmm2",
        "movdqa xmm2, xmm1",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm1, xmm2",
        "movdqa xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "psubw xmm3, xmm1",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+256], xmm3",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 22b",
        "add rdx, 256",
        "sub rax, 1",
        "jne 21b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 4",
        "mov eax, 2",
        "23:",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 0",
        "add r8, 2",
        "mov ecx, 8",
        "24:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+128]",
        "movdqa xmm2, xmm1",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm1, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm1, xmm2",
        "movdqa xmm2, xmm1",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm1, xmm2",
        "movdqa xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "psubw xmm3, xmm1",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+128], xmm3",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 24b",
        "add rdx, 128",
        "sub rax, 1",
        "jne 23b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 8",
        "mov eax, 4",
        "25:",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 0",
        "add r8, 2",
        "mov ecx, 4",
        "26:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+64]",
        "movdqa xmm2, xmm1",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm1, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm1, xmm2",
        "movdqa xmm2, xmm1",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm1, xmm2",
        "movdqa xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "psubw xmm3, xmm1",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+64], xmm3",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 26b",
        "add rdx, 64",
        "sub rax, 1",
        "jne 25b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 16",
        "mov eax, 8",
        "27:",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 0",
        "add r8, 2",
        "mov ecx, 2",
        "28:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+32]",
        "movdqa xmm2, xmm1",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm1, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm1, xmm2",
        "movdqa xmm2, xmm1",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm1, xmm2",
        "movdqa xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "psubw xmm3, xmm1",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+32], xmm3",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 28b",
        "add rdx, 32",
        "sub rax, 1",
        "jne 27b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 32",
        "mov eax, 16",
        "29:",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 0",
        "add r8, 2",
        "mov ecx, 1",
        "210:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+16]",
        "movdqa xmm2, xmm1",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm1, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm1, xmm2",
        "movdqa xmm2, xmm1",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm1, xmm2",
        "movdqa xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "psubw xmm3, xmm1",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+16], xmm3",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 210b",
        "add rdx, 16",
        "sub rax, 1",
        "jne 29b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 64",
        "mov ecx, 16",
        "211:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+16]",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 80",
        "add r8, 4",
        "movdqa xmm2, xmm0",
        "punpcklqdq xmm0, xmm1",
        "punpckhqdq xmm2, xmm1",
        "movdqa xmm1, xmm2",
        "movdqa xmm2, xmm1",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm1, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm1, xmm2",
        "movdqa xmm2, xmm1",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm1, xmm2",
        "movdqa xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "psubw xmm3, xmm1",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqa xmm1, xmm0",
        "punpcklqdq xmm0, xmm3",
        "punpckhqdq xmm1, xmm3",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+16], xmm1",
        "add rdx, 32",
        "sub rcx, 1",
        "jne 211b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 128",
        "mov ecx, 16",
        "212:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm2, XMMWORD PTR [rdx+16]",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 228",
        "add r8, 8",
        "pshufd xmm0, xmm0, 216",
        "pshufd xmm2, xmm2, 216",
        "movdqa xmm1, xmm0",
        "punpcklqdq xmm0, xmm2",
        "punpckhqdq xmm1, xmm2",
        "movdqa xmm2, xmm1",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm1, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm1, xmm2",
        "movdqa xmm2, xmm1",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm1, xmm2",
        "movdqa xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "psubw xmm3, xmm1",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqa xmm1, xmm0",
        "punpckldq xmm0, xmm3",
        "punpckhdq xmm1, xmm3",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+16], xmm1",
        "add rdx, 32",
        "sub rcx, 1",
        "jne 212b",
        "mov r9, rdi",
        "mov rdx, rsi",
        "add rdx, 256",
        "pxor xmm4, xmm4",
        "mov ecx, 32",
        "213:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqa xmm1, xmm0",
        "punpcklwd xmm0, xmm4",
        "punpckhwd xmm1, xmm4",
        "movdqu XMMWORD PTR [r9], xmm0",
        "movdqu XMMWORD PTR [r9+16], xmm1",
        "add r9, 32",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 213b",
        "lfence",
        "mov DWORD PTR [rsi+768], r11d",
        "ldmxcsr DWORD PTR [rsi+768]",
        "ret",
    )
}

/// The inverse of the ML-KEM number-theoretic transform, `NTT⁻¹` (FIPS 203 Algorithm 10), of `*f` (256 coefficients less than `q` = 3329), in place.
///
/// Contract: `VG.Spec.MlKem.nttInvContract`. Constant time: only the pointers may affect timing, not the data.
///
/// The function computes on eight coefficients at a time in SSE2 registers. It sets MXCSR to `0x1FBF` around its multiplications (Intel's mitigation of MXCSR-configuration-dependent timing) and loads the caller's MXCSR back before returning.
///
/// # Safety
///
/// * `f` must be valid for reads and writes of 1024 bytes.
/// * `scratch` must be valid for reads and writes of 1024 bytes.
/// * Each of the 256 `u32`s of `f` must be less than 3329.
/// * `scratch` is working space: on return it may hold intermediate values, which the caller must destroy (FIPS 203 §3.3).
/// * `f` and `scratch` must not overlap each other (distinct Rust objects never do).
/// * Neither `f` nor `scratch` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_inv_ntt(f: *mut [u32; 256], scratch: *mut [u64; 128]) {
    core::arch::naked_asm!(
        "stmxcsr DWORD PTR [rsi+768]",
        "mov r11d, DWORD PTR [rsi+768]",
        "and r11d, 65535",
        "mov eax, 8127",
        "mov DWORD PTR [rsi+772], eax",
        "ldmxcsr DWORD PTR [rsi+772]",
        "lfence",
        "movabs r9, 510045414021073133",
        "mov QWORD PTR [rsi], r9",
        "movabs r9, 56859178044360149",
        "mov QWORD PTR [rsi+8], r9",
        "movabs r9, 51235218965531734",
        "mov QWORD PTR [rsi+16], r9",
        "movabs r9, 413213233114973122",
        "mov QWORD PTR [rsi+24], r9",
        "movabs r9, 107806050082882109",
        "mov QWORD PTR [rsi+32], r9",
        "movabs r9, 900445868001462724",
        "mov QWORD PTR [rsi+40], r9",
        "movabs r9, 171139929822792280",
        "mov QWORD PTR [rsi+48], r9",
        "movabs r9, 494846426562103035",
        "mov QWORD PTR [rsi+56], r9",
        "movabs r9, 285709028528227527",
        "mov QWORD PTR [rsi+64], r9",
        "movabs r9, 502445920291588084",
        "mov QWORD PTR [rsi+72], r9",
        "movabs r9, 749580786754716164",
        "mov QWORD PTR [rsi+80], r9",
        "movabs r9, 413487282095851183",
        "mov QWORD PTR [rsi+88], r9",
        "movabs r9, 233637364892109228",
        "mov QWORD PTR [rsi+96], r9",
        "movabs r9, 669360731832189035",
        "mov QWORD PTR [rsi+104], r9",
        "movabs r9, 732968660552977267",
        "mov QWORD PTR [rsi+112], r9",
        "movabs r9, 578152510004920768",
        "mov QWORD PTR [rsi+120], r9",
        "movabs r9, 237285789102114994",
        "mov QWORD PTR [rsi+128], r9",
        "movabs r9, 29561529811011614",
        "mov QWORD PTR [rsi+136], r9",
        "movabs r9, 870884338190451110",
        "mov QWORD PTR [rsi+144], r9",
        "movabs r9, 465284896969264094",
        "mov QWORD PTR [rsi+152], r9",
        "movabs r9, 895658353811393547",
        "mov QWORD PTR [rsi+160], r9",
        "movabs r9, 314982211412232696",
        "mov QWORD PTR [rsi+168], r9",
        "movabs r9, 98245319648872139",
        "mov QWORD PTR [rsi+176], r9",
        "movabs r9, 915933202169266594",
        "mov QWORD PTR [rsi+184], r9",
        "movabs r9, 171702325730673457",
        "mov QWORD PTR [rsi+192], r9",
        "movabs r9, 108094397009888554",
        "mov QWORD PTR [rsi+200], r9",
        "movabs r9, 561266335040473154",
        "mov QWORD PTR [rsi+208], r9",
        "movabs r9, 470072410941163927",
        "mov QWORD PTR [rsi+216], r9",
        "movabs r9, 223499940604086368",
        "mov QWORD PTR [rsi+224], r9",
        "movabs r9, 134555600354477851",
        "mov QWORD PTR [rsi+232], r9",
        "movabs r9, 278945979905674389",
        "mov QWORD PTR [rsi+240], r9",
        "movabs r9, 458247799147660222",
        "mov QWORD PTR [rsi+248], r9",
        "mov eax, 218172673",
        "movq xmm15, rax",
        "pshufd xmm15, xmm15, 0",
        "mov eax, -217976063",
        "movq xmm14, rax",
        "pshufd xmm14, xmm14, 0",
        "mov r9, rdi",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov ecx, 32",
        "20:",
        "movdqu xmm0, XMMWORD PTR [r9]",
        "movdqu xmm1, XMMWORD PTR [r9+16]",
        "packssdw xmm0, xmm1",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "add r9, 32",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 20b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 248",
        "mov ecx, 16",
        "21:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm2, XMMWORD PTR [rdx+16]",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 27",
        "add r8, -8",
        "pshufd xmm0, xmm0, 216",
        "pshufd xmm2, xmm2, 216",
        "movdqa xmm1, xmm0",
        "punpcklqdq xmm0, xmm2",
        "punpckhqdq xmm1, xmm2",
        "movdqa xmm3, xmm1",
        "psubw xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "movdqa xmm2, xmm3",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm3, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm3, xmm2",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqa xmm1, xmm0",
        "punpckldq xmm0, xmm3",
        "punpckhdq xmm1, xmm3",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+16], xmm1",
        "add rdx, 32",
        "sub rcx, 1",
        "jne 21b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 124",
        "mov ecx, 16",
        "22:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+16]",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 5",
        "add r8, -4",
        "movdqa xmm2, xmm0",
        "punpcklqdq xmm0, xmm1",
        "punpckhqdq xmm2, xmm1",
        "movdqa xmm1, xmm2",
        "movdqa xmm3, xmm1",
        "psubw xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "movdqa xmm2, xmm3",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm3, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm3, xmm2",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqa xmm1, xmm0",
        "punpcklqdq xmm0, xmm3",
        "punpckhqdq xmm1, xmm3",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+16], xmm1",
        "add rdx, 32",
        "sub rcx, 1",
        "jne 22b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 62",
        "mov eax, 16",
        "23:",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 0",
        "add r8, -2",
        "mov ecx, 1",
        "24:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+16]",
        "movdqa xmm3, xmm1",
        "psubw xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "movdqa xmm2, xmm3",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm3, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm3, xmm2",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+16], xmm3",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 24b",
        "add rdx, 16",
        "sub rax, 1",
        "jne 23b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 30",
        "mov eax, 8",
        "25:",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 0",
        "add r8, -2",
        "mov ecx, 2",
        "26:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+32]",
        "movdqa xmm3, xmm1",
        "psubw xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "movdqa xmm2, xmm3",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm3, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm3, xmm2",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+32], xmm3",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 26b",
        "add rdx, 32",
        "sub rax, 1",
        "jne 25b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 14",
        "mov eax, 4",
        "27:",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 0",
        "add r8, -2",
        "mov ecx, 4",
        "28:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+64]",
        "movdqa xmm3, xmm1",
        "psubw xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "movdqa xmm2, xmm3",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm3, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm3, xmm2",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+64], xmm3",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 28b",
        "add rdx, 64",
        "sub rax, 1",
        "jne 27b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 6",
        "mov eax, 2",
        "29:",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 0",
        "add r8, -2",
        "mov ecx, 8",
        "210:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+128]",
        "movdqa xmm3, xmm1",
        "psubw xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "movdqa xmm2, xmm3",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm3, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm3, xmm2",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+128], xmm3",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 210b",
        "add rdx, 128",
        "sub rax, 1",
        "jne 29b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov r8, rsi",
        "add r8, 2",
        "mov eax, 1",
        "211:",
        "movdqu xmm13, XMMWORD PTR [r8]",
        "punpcklwd xmm13, xmm13",
        "pshufd xmm13, xmm13, 0",
        "add r8, -2",
        "mov ecx, 16",
        "212:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqu xmm1, XMMWORD PTR [rdx+256]",
        "movdqa xmm3, xmm1",
        "psubw xmm3, xmm0",
        "paddw xmm0, xmm1",
        "psubw xmm0, xmm15",
        "movdqa xmm2, xmm0",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm0, xmm2",
        "movdqa xmm2, xmm3",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm3, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm3, xmm2",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqu XMMWORD PTR [rdx], xmm0",
        "movdqu XMMWORD PTR [rdx+256], xmm3",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 212b",
        "add rdx, 256",
        "sub rax, 1",
        "jne 211b",
        "mov rdx, rsi",
        "add rdx, 256",
        "mov eax, 33554944",
        "movq xmm13, rax",
        "pshufd xmm13, xmm13, 0",
        "mov ecx, 32",
        "213:",
        "movdqu xmm3, XMMWORD PTR [rdx]",
        "movdqa xmm2, xmm3",
        "pmullw xmm2, xmm13",
        "pmullw xmm2, xmm14",
        "pmulhw xmm3, xmm13",
        "pmulhw xmm2, xmm15",
        "psubw xmm3, xmm2",
        "movdqa xmm2, xmm3",
        "psraw xmm2, 15",
        "pand xmm2, xmm15",
        "paddw xmm3, xmm2",
        "movdqu XMMWORD PTR [rdx], xmm3",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 213b",
        "mov r9, rdi",
        "mov rdx, rsi",
        "add rdx, 256",
        "pxor xmm4, xmm4",
        "mov ecx, 32",
        "214:",
        "movdqu xmm0, XMMWORD PTR [rdx]",
        "movdqa xmm1, xmm0",
        "punpcklwd xmm0, xmm4",
        "punpckhwd xmm1, xmm4",
        "movdqu XMMWORD PTR [r9], xmm0",
        "movdqu XMMWORD PTR [r9+16], xmm1",
        "add r9, 32",
        "add rdx, 16",
        "sub rcx, 1",
        "jne 214b",
        "lfence",
        "mov DWORD PTR [rsi+768], r11d",
        "ldmxcsr DWORD PTR [rsi+768]",
        "ret",
    )
}

/// Adds the polynomial `*g` to `*f` modulo `q` = 3329, coefficient by coefficient (FIPS 203 (2.3)).
///
/// Contract: `VG.Spec.MlKem.addContract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `f` must be valid for reads and writes of 1024 bytes.
/// * `g` must be valid for reads of 1024 bytes.
/// * Each of the 256 `u32`s of `f` must be less than 3329.
/// * Each of the 256 `u32`s of `g` must be less than 3329.
/// * `f` must not overlap `g` (distinct Rust objects never do).
/// * Neither `f` nor `g` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_add(f: *mut [u32; 256], g: *const [u32; 256]) {
    core::arch::naked_asm!(
        "mov ecx, 256",
        "20:",
        "mov eax, DWORD PTR [rdi]",
        "add eax, DWORD PTR [rsi]",
        "sub eax, 3329",
        "sbb edx, edx",
        "and edx, 3329",
        "add eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// Subtracts the polynomial `*g` from `*f` modulo `q` = 3329, coefficient by coefficient.
///
/// Contract: `VG.Spec.MlKem.subContract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `f` must be valid for reads and writes of 1024 bytes.
/// * `g` must be valid for reads of 1024 bytes.
/// * Each of the 256 `u32`s of `f` must be less than 3329.
/// * Each of the 256 `u32`s of `g` must be less than 3329.
/// * `f` must not overlap `g` (distinct Rust objects never do).
/// * Neither `f` nor `g` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_sub(f: *mut [u32; 256], g: *const [u32; 256]) {
    core::arch::naked_asm!(
        "mov ecx, 256",
        "20:",
        "mov eax, DWORD PTR [rdi]",
        "add eax, 3329",
        "sub eax, DWORD PTR [rsi]",
        "sub eax, 3329",
        "sbb edx, edx",
        "and edx, 3329",
        "add eax, edx",
        "mov DWORD PTR [rdi], eax",
        "add rdi, 4",
        "add rsi, 4",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// The product of two NTT representations, `MultiplyNTTs` (FIPS 203 Algorithm 11): writes the product of `*f` and `*g` to `*h`, each of 256 coefficients less than `q` = 3329.
///
/// Contract: `VG.Spec.MlKem.mulContract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `h` must be valid for reads and writes of 1024 bytes.
/// * `f` must be valid for reads of 1024 bytes.
/// * `g` must be valid for reads of 1024 bytes.
/// * `scratch` must be valid for reads and writes of 1024 bytes.
/// * Each of the 256 `u32`s of `f` must be less than 3329.
/// * Each of the 256 `u32`s of `g` must be less than 3329.
/// * `scratch` is working space: on return it may hold intermediate values, which the caller must destroy (FIPS 203 §3.3).
/// * `h` and `scratch` must not overlap each other, `f` or `g` (distinct Rust objects never do).
/// * None of `h`, `f`, `g` and `scratch` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_multiply_ntts(h: *mut [u32; 256], f: *const [u32; 256], g: *const [u32; 256], scratch: *mut [u64; 128]) {
    core::arch::naked_asm!(
        "mov r8, rdx",
        "mov r9, rcx",
        "mov eax, 17",
        "mov DWORD PTR [r9], eax",
        "mov eax, 3312",
        "mov DWORD PTR [r9+4], eax",
        "mov eax, 2761",
        "mov DWORD PTR [r9+8], eax",
        "mov eax, 568",
        "mov DWORD PTR [r9+12], eax",
        "mov eax, 583",
        "mov DWORD PTR [r9+16], eax",
        "mov eax, 2746",
        "mov DWORD PTR [r9+20], eax",
        "mov eax, 2649",
        "mov DWORD PTR [r9+24], eax",
        "mov eax, 680",
        "mov DWORD PTR [r9+28], eax",
        "mov eax, 1637",
        "mov DWORD PTR [r9+32], eax",
        "mov eax, 1692",
        "mov DWORD PTR [r9+36], eax",
        "mov eax, 723",
        "mov DWORD PTR [r9+40], eax",
        "mov eax, 2606",
        "mov DWORD PTR [r9+44], eax",
        "mov eax, 2288",
        "mov DWORD PTR [r9+48], eax",
        "mov eax, 1041",
        "mov DWORD PTR [r9+52], eax",
        "mov eax, 1100",
        "mov DWORD PTR [r9+56], eax",
        "mov eax, 2229",
        "mov DWORD PTR [r9+60], eax",
        "mov eax, 1409",
        "mov DWORD PTR [r9+64], eax",
        "mov eax, 1920",
        "mov DWORD PTR [r9+68], eax",
        "mov eax, 2662",
        "mov DWORD PTR [r9+72], eax",
        "mov eax, 667",
        "mov DWORD PTR [r9+76], eax",
        "mov eax, 3281",
        "mov DWORD PTR [r9+80], eax",
        "mov eax, 48",
        "mov DWORD PTR [r9+84], eax",
        "mov eax, 233",
        "mov DWORD PTR [r9+88], eax",
        "mov eax, 3096",
        "mov DWORD PTR [r9+92], eax",
        "mov eax, 756",
        "mov DWORD PTR [r9+96], eax",
        "mov eax, 2573",
        "mov DWORD PTR [r9+100], eax",
        "mov eax, 2156",
        "mov DWORD PTR [r9+104], eax",
        "mov eax, 1173",
        "mov DWORD PTR [r9+108], eax",
        "mov eax, 3015",
        "mov DWORD PTR [r9+112], eax",
        "mov eax, 314",
        "mov DWORD PTR [r9+116], eax",
        "mov eax, 3050",
        "mov DWORD PTR [r9+120], eax",
        "mov eax, 279",
        "mov DWORD PTR [r9+124], eax",
        "mov eax, 1703",
        "mov DWORD PTR [r9+128], eax",
        "mov eax, 1626",
        "mov DWORD PTR [r9+132], eax",
        "mov eax, 1651",
        "mov DWORD PTR [r9+136], eax",
        "mov eax, 1678",
        "mov DWORD PTR [r9+140], eax",
        "mov eax, 2789",
        "mov DWORD PTR [r9+144], eax",
        "mov eax, 540",
        "mov DWORD PTR [r9+148], eax",
        "mov eax, 1789",
        "mov DWORD PTR [r9+152], eax",
        "mov eax, 1540",
        "mov DWORD PTR [r9+156], eax",
        "mov eax, 1847",
        "mov DWORD PTR [r9+160], eax",
        "mov eax, 1482",
        "mov DWORD PTR [r9+164], eax",
        "mov eax, 952",
        "mov DWORD PTR [r9+168], eax",
        "mov eax, 2377",
        "mov DWORD PTR [r9+172], eax",
        "mov eax, 1461",
        "mov DWORD PTR [r9+176], eax",
        "mov eax, 1868",
        "mov DWORD PTR [r9+180], eax",
        "mov eax, 2687",
        "mov DWORD PTR [r9+184], eax",
        "mov eax, 642",
        "mov DWORD PTR [r9+188], eax",
        "mov eax, 939",
        "mov DWORD PTR [r9+192], eax",
        "mov eax, 2390",
        "mov DWORD PTR [r9+196], eax",
        "mov eax, 2308",
        "mov DWORD PTR [r9+200], eax",
        "mov eax, 1021",
        "mov DWORD PTR [r9+204], eax",
        "mov eax, 2437",
        "mov DWORD PTR [r9+208], eax",
        "mov eax, 892",
        "mov DWORD PTR [r9+212], eax",
        "mov eax, 2388",
        "mov DWORD PTR [r9+216], eax",
        "mov eax, 941",
        "mov DWORD PTR [r9+220], eax",
        "mov eax, 733",
        "mov DWORD PTR [r9+224], eax",
        "mov eax, 2596",
        "mov DWORD PTR [r9+228], eax",
        "mov eax, 2337",
        "mov DWORD PTR [r9+232], eax",
        "mov eax, 992",
        "mov DWORD PTR [r9+236], eax",
        "mov eax, 268",
        "mov DWORD PTR [r9+240], eax",
        "mov eax, 3061",
        "mov DWORD PTR [r9+244], eax",
        "mov eax, 641",
        "mov DWORD PTR [r9+248], eax",
        "mov eax, 2688",
        "mov DWORD PTR [r9+252], eax",
        "mov eax, 1584",
        "mov DWORD PTR [r9+256], eax",
        "mov eax, 1745",
        "mov DWORD PTR [r9+260], eax",
        "mov eax, 2298",
        "mov DWORD PTR [r9+264], eax",
        "mov eax, 1031",
        "mov DWORD PTR [r9+268], eax",
        "mov eax, 2037",
        "mov DWORD PTR [r9+272], eax",
        "mov eax, 1292",
        "mov DWORD PTR [r9+276], eax",
        "mov eax, 3220",
        "mov DWORD PTR [r9+280], eax",
        "mov eax, 109",
        "mov DWORD PTR [r9+284], eax",
        "mov eax, 375",
        "mov DWORD PTR [r9+288], eax",
        "mov eax, 2954",
        "mov DWORD PTR [r9+292], eax",
        "mov eax, 2549",
        "mov DWORD PTR [r9+296], eax",
        "mov eax, 780",
        "mov DWORD PTR [r9+300], eax",
        "mov eax, 2090",
        "mov DWORD PTR [r9+304], eax",
        "mov eax, 1239",
        "mov DWORD PTR [r9+308], eax",
        "mov eax, 1645",
        "mov DWORD PTR [r9+312], eax",
        "mov eax, 1684",
        "mov DWORD PTR [r9+316], eax",
        "mov eax, 1063",
        "mov DWORD PTR [r9+320], eax",
        "mov eax, 2266",
        "mov DWORD PTR [r9+324], eax",
        "mov eax, 319",
        "mov DWORD PTR [r9+328], eax",
        "mov eax, 3010",
        "mov DWORD PTR [r9+332], eax",
        "mov eax, 2773",
        "mov DWORD PTR [r9+336], eax",
        "mov eax, 556",
        "mov DWORD PTR [r9+340], eax",
        "mov eax, 757",
        "mov DWORD PTR [r9+344], eax",
        "mov eax, 2572",
        "mov DWORD PTR [r9+348], eax",
        "mov eax, 2099",
        "mov DWORD PTR [r9+352], eax",
        "mov eax, 1230",
        "mov DWORD PTR [r9+356], eax",
        "mov eax, 561",
        "mov DWORD PTR [r9+360], eax",
        "mov eax, 2768",
        "mov DWORD PTR [r9+364], eax",
        "mov eax, 2466",
        "mov DWORD PTR [r9+368], eax",
        "mov eax, 863",
        "mov DWORD PTR [r9+372], eax",
        "mov eax, 2594",
        "mov DWORD PTR [r9+376], eax",
        "mov eax, 735",
        "mov DWORD PTR [r9+380], eax",
        "mov eax, 2804",
        "mov DWORD PTR [r9+384], eax",
        "mov eax, 525",
        "mov DWORD PTR [r9+388], eax",
        "mov eax, 1092",
        "mov DWORD PTR [r9+392], eax",
        "mov eax, 2237",
        "mov DWORD PTR [r9+396], eax",
        "mov eax, 403",
        "mov DWORD PTR [r9+400], eax",
        "mov eax, 2926",
        "mov DWORD PTR [r9+404], eax",
        "mov eax, 1026",
        "mov DWORD PTR [r9+408], eax",
        "mov eax, 2303",
        "mov DWORD PTR [r9+412], eax",
        "mov eax, 1143",
        "mov DWORD PTR [r9+416], eax",
        "mov eax, 2186",
        "mov DWORD PTR [r9+420], eax",
        "mov eax, 2150",
        "mov DWORD PTR [r9+424], eax",
        "mov eax, 1179",
        "mov DWORD PTR [r9+428], eax",
        "mov eax, 2775",
        "mov DWORD PTR [r9+432], eax",
        "mov eax, 554",
        "mov DWORD PTR [r9+436], eax",
        "mov eax, 886",
        "mov DWORD PTR [r9+440], eax",
        "mov eax, 2443",
        "mov DWORD PTR [r9+444], eax",
        "mov eax, 1722",
        "mov DWORD PTR [r9+448], eax",
        "mov eax, 1607",
        "mov DWORD PTR [r9+452], eax",
        "mov eax, 1212",
        "mov DWORD PTR [r9+456], eax",
        "mov eax, 2117",
        "mov DWORD PTR [r9+460], eax",
        "mov eax, 1874",
        "mov DWORD PTR [r9+464], eax",
        "mov eax, 1455",
        "mov DWORD PTR [r9+468], eax",
        "mov eax, 1029",
        "mov DWORD PTR [r9+472], eax",
        "mov eax, 2300",
        "mov DWORD PTR [r9+476], eax",
        "mov eax, 2110",
        "mov DWORD PTR [r9+480], eax",
        "mov eax, 1219",
        "mov DWORD PTR [r9+484], eax",
        "mov eax, 2935",
        "mov DWORD PTR [r9+488], eax",
        "mov eax, 394",
        "mov DWORD PTR [r9+492], eax",
        "mov eax, 885",
        "mov DWORD PTR [r9+496], eax",
        "mov eax, 2444",
        "mov DWORD PTR [r9+500], eax",
        "mov eax, 2154",
        "mov DWORD PTR [r9+504], eax",
        "mov eax, 1175",
        "mov DWORD PTR [r9+508], eax",
        "mov ecx, 128",
        "20:",
        "mov eax, DWORD PTR [rsi+4]",
        "mov edx, DWORD PTR [r8+4]",
        "mul rdx",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov eax, DWORD PTR [r9]",
        "mul r10",
        "mov r11, rax",
        "mov eax, DWORD PTR [rsi]",
        "mov edx, DWORD PTR [r8]",
        "mul rdx",
        "add rax, r11",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rdi], r10d",
        "mov eax, DWORD PTR [rsi]",
        "mov edx, DWORD PTR [r8+4]",
        "mul rdx",
        "mov r11, rax",
        "mov eax, DWORD PTR [rsi+4]",
        "mov edx, DWORD PTR [r8]",
        "mul rdx",
        "add rax, r11",
        "mov r10, rax",
        "mov r11, 1290167",
        "mul r11",
        "shr rax, 32",
        "mov r11, 3329",
        "mul r11",
        "sub r10, rax",
        "sub r10d, 3329",
        "sbb r11d, r11d",
        "and r11d, 3329",
        "add r10d, r11d",
        "mov DWORD PTR [rdi+4], r10d",
        "add rdi, 8",
        "add rsi, 8",
        "add r8, 8",
        "add r9, 4",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// `SampleNTT` (FIPS 203 Algorithm 7): writes the element of `T_q` sampled from the SHAKE128 output of the 34 bytes `*seed` to `*a` (256 coefficients less than `q` = 3329), and returns 1. Returns 0 if the loop reaches its bound, which is at least 280 iterations (FIPS 203 Appendix B; this happens with probability less than 2^-261): `*a` is then unspecified, and the caller must destroy it and treat the operation as failed.
///
/// Contract: `VG.Spec.MlKem.sampleNTTContract`. Not constant time in the seed: timing may depend on the pointer and on `*seed` (public in ML-KEM: the seed `ρ` of the matrix and two indices), but not on anything else.
///
/// # Safety
///
/// * `seed` must be valid for reads of 34 bytes.
/// * `a` must be valid for reads and writes of 1024 bytes.
/// * `scratch` must be valid for reads and writes of 2048 bytes.
/// * `scratch` is working space: on return it may hold intermediate values, which the caller must destroy (FIPS 203 §3.3).
/// * `a` and `scratch` must not overlap each other or `seed` (distinct Rust objects never do).
/// * None of `seed`, `a` and `scratch` may overlap the return address on the stack or the 16 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_sample_ntt(seed: *const [u8; 34], a: *mut [u32; 256], scratch: *mut [u64; 256]) -> u32 {
    core::arch::naked_asm!(
        "mov QWORD PTR [rdx+1680], rbx",
        "mov QWORD PTR [rdx+1688], rbp",
        "mov QWORD PTR [rdx+1696], rdi",
        "mov rbx, rdx",
        "mov rbp, rsi",
        "mov rcx, rdi",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "mov esi, 168",
        "mov edx, 0",
        "mov r8d, 34",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "mov esi, 168",
        "mov edx, 34",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "mov esi, 168",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 840",
        "mov r8d, 504",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rsi, rbx",
        "add rsi, 840",
        "mov edi, 0",
        "mov ecx, 168",
        "20:",
        "movzx eax, BYTE PTR [rsi]",
        "movzx edx, BYTE PTR [rsi+1]",
        "movzx r8d, BYTE PTR [rsi+2]",
        "mov r9d, edx",
        "and r9d, 15",
        "ror r9d, 24",
        "add r9d, eax",
        "shr edx, 4",
        "ror r8d, 28",
        "add r8d, edx",
        "cmp rdi, 256",
        "jb 21f",
        "jmp 22f",
        "21:",
        "mov DWORD PTR [rbp+rdi*4], r9d",
        "cmp r9d, 3329",
        "adc rdi, 0",
        "cmp rdi, 256",
        "jb 23f",
        "jmp 24f",
        "23:",
        "mov DWORD PTR [rbp+rdi*4], r8d",
        "cmp r8d, 3329",
        "adc rdi, 0",
        "24:",
        "22:",
        "add rsi, 3",
        "sub rcx, 1",
        "jne 20b",
        "cmp rdi, 256",
        "jb 25f",
        "jmp 26f",
        "25:",
        "mov rcx, QWORD PTR [rbx+1696]",
        "mov eax, 0",
        "mov QWORD PTR [rbx], rax",
        "mov QWORD PTR [rbx+8], rax",
        "mov QWORD PTR [rbx+16], rax",
        "mov QWORD PTR [rbx+24], rax",
        "mov QWORD PTR [rbx+32], rax",
        "mov QWORD PTR [rbx+40], rax",
        "mov QWORD PTR [rbx+48], rax",
        "mov QWORD PTR [rbx+56], rax",
        "mov QWORD PTR [rbx+64], rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov QWORD PTR [rbx+80], rax",
        "mov QWORD PTR [rbx+88], rax",
        "mov QWORD PTR [rbx+96], rax",
        "mov QWORD PTR [rbx+104], rax",
        "mov QWORD PTR [rbx+112], rax",
        "mov QWORD PTR [rbx+120], rax",
        "mov QWORD PTR [rbx+128], rax",
        "mov QWORD PTR [rbx+136], rax",
        "mov QWORD PTR [rbx+144], rax",
        "mov QWORD PTR [rbx+152], rax",
        "mov QWORD PTR [rbx+160], rax",
        "mov QWORD PTR [rbx+168], rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov QWORD PTR [rbx+192], rax",
        "mov rdi, rbx",
        "mov esi, 168",
        "mov edx, 0",
        "mov r8d, 34",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_absorb}",
        "mov rdi, rbx",
        "mov esi, 168",
        "mov edx, 34",
        "mov ecx, 31",
        "mov r8, rbx",
        "add r8, 200",
        "call {vg_keccak_pad}",
        "mov rdi, rbx",
        "mov esi, 168",
        "mov edx, 0",
        "mov rcx, rbx",
        "add rcx, 840",
        "mov r8d, 840",
        "mov r9, rbx",
        "add r9, 200",
        "call {vg_keccak_squeeze}",
        "mov rsi, rbx",
        "add rsi, 840",
        "mov edi, 0",
        "mov ecx, 280",
        "27:",
        "movzx eax, BYTE PTR [rsi]",
        "movzx edx, BYTE PTR [rsi+1]",
        "movzx r8d, BYTE PTR [rsi+2]",
        "mov r9d, edx",
        "and r9d, 15",
        "ror r9d, 24",
        "add r9d, eax",
        "shr edx, 4",
        "ror r8d, 28",
        "add r8d, edx",
        "cmp rdi, 256",
        "jb 28f",
        "jmp 29f",
        "28:",
        "mov DWORD PTR [rbp+rdi*4], r9d",
        "cmp r9d, 3329",
        "adc rdi, 0",
        "cmp rdi, 256",
        "jb 210f",
        "jmp 211f",
        "210:",
        "mov DWORD PTR [rbp+rdi*4], r8d",
        "cmp r8d, 3329",
        "adc rdi, 0",
        "211:",
        "29:",
        "add rsi, 3",
        "sub rcx, 1",
        "jne 27b",
        "26:",
        "mov rax, rdi",
        "shr rax, 8",
        "mov rbp, QWORD PTR [rbx+1688]",
        "mov rbx, QWORD PTR [rbx+1680]",
        "ret",
        vg_keccak_absorb = sym super::sha3::vg_keccak_absorb,
        vg_keccak_pad = sym super::sha3::vg_keccak_pad,
        vg_keccak_squeeze = sym super::sha3::vg_keccak_squeeze,
    )
}

/// `ByteEncode₁₂` (FIPS 203 Algorithm 5): writes the 256 coefficients of `*f`, each less than `q` = 3329, to `*out` as 12-bit little-endian fields.
///
/// Contract: `VG.Spec.MlKem.encode12Contract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `f` must be valid for reads of 1024 bytes.
/// * `out` must be valid for reads and writes of 384 bytes.
/// * Each of the 256 `u32`s of `f` must be less than 3329.
/// * `out` must not overlap `f` (distinct Rust objects never do).
/// * Neither `f` nor `out` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_encode12(f: *const [u32; 256], out: *mut [u8; 384]) {
    core::arch::naked_asm!(
        "mov ecx, 128",
        "20:",
        "mov eax, DWORD PTR [rdi]",
        "mov edx, DWORD PTR [rdi+4]",
        "ror edx, 20",
        "add eax, edx",
        "mov BYTE PTR [rsi], al",
        "shr eax, 8",
        "mov BYTE PTR [rsi+1], al",
        "shr eax, 8",
        "mov BYTE PTR [rsi+2], al",
        "add rdi, 8",
        "add rsi, 3",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// `ByteDecode₁₂` (FIPS 203 Algorithm 6): writes the 256 12-bit little-endian fields of `*b`, each reduced modulo `q` = 3329, to `*f`.
///
/// Contract: `VG.Spec.MlKem.decode12Contract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `b` must be valid for reads of 384 bytes.
/// * `f` must be valid for reads and writes of 1024 bytes.
/// * `f` must not overlap `b` (distinct Rust objects never do).
/// * Neither `b` nor `f` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_decode12(b: *const [u8; 384], f: *mut [u32; 256]) {
    core::arch::naked_asm!(
        "mov ecx, 128",
        "20:",
        "movzx eax, BYTE PTR [rdi]",
        "movzx edx, BYTE PTR [rdi+1]",
        "ror edx, 24",
        "add eax, edx",
        "movzx edx, BYTE PTR [rdi+2]",
        "ror edx, 16",
        "add eax, edx",
        "mov edx, eax",
        "and eax, 4095",
        "shr edx, 12",
        "sub eax, 3329",
        "sbb r8d, r8d",
        "and r8d, 3329",
        "add eax, r8d",
        "sub edx, 3329",
        "sbb r8d, r8d",
        "and r8d, 3329",
        "add edx, r8d",
        "mov DWORD PTR [rsi], eax",
        "mov DWORD PTR [rsi+4], edx",
        "add rdi, 3",
        "add rsi, 8",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// `SamplePolyCBD₂` (FIPS 203 Algorithm 8 with `η` = 2): writes the polynomial sampled from the 128 bytes `*b` to `*f` (256 coefficients less than `q` = 3329).
///
/// Contract: `VG.Spec.MlKem.cbd2Contract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `b` must be valid for reads of 128 bytes.
/// * `f` must be valid for reads and writes of 1024 bytes.
/// * `f` must not overlap `b` (distinct Rust objects never do).
/// * Neither `b` nor `f` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_cbd2(b: *const [u8; 128], f: *mut [u32; 256]) {
    core::arch::naked_asm!(
        "mov ecx, 128",
        "20:",
        "movzx eax, BYTE PTR [rdi]",
        "mov edx, eax",
        "shr edx, 1",
        "and eax, 85",
        "and edx, 85",
        "add eax, edx",
        "mov edx, eax",
        "and edx, 3",
        "add edx, 3329",
        "mov r8d, eax",
        "shr r8d, 2",
        "and r8d, 3",
        "sub edx, r8d",
        "sub edx, 3329",
        "sbb r9d, r9d",
        "and r9d, 3329",
        "add edx, r9d",
        "mov DWORD PTR [rsi], edx",
        "mov edx, eax",
        "shr edx, 4",
        "and edx, 3",
        "add edx, 3329",
        "shr eax, 6",
        "sub edx, eax",
        "sub edx, 3329",
        "sbb r9d, r9d",
        "and r9d, 3329",
        "add edx, r9d",
        "mov DWORD PTR [rsi+4], edx",
        "add rdi, 1",
        "add rsi, 8",
        "sub rcx, 1",
        "jne 20b",
        "ret",
    )
}

/// `ByteEncode_d(Compress_d(f))` (FIPS 203 (4.7) and Algorithm 5): writes the 256 coefficients of `*f` (each less than `q` = 3329), compressed to `d` bits, to `out` as `d`-bit little-endian fields.
///
/// Contract: `VG.Spec.MlKem.compressEncodeContract`. Constant time: only the pointers, `d` and `len` may affect timing, not the data.
///
/// # Safety
///
/// * `f` must be valid for reads of 1024 bytes.
/// * `out` must be valid for reads and writes of `len` bytes.
/// * `d` must be 1, 4 or 10, and `len` must be `32 * d`.
/// * Each of the 256 `u32`s of `f` must be less than 3329.
/// * `out` must not overlap `f` (distinct Rust objects never do).
/// * Neither `f` nor `out` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_compress_encode(f: *const [u32; 256], d: u32, out: *mut u8, len: usize) {
    core::arch::naked_asm!(
        "mov esi, esi",
        "mov r8, rdx",
        "cmp esi, 1",
        "je 20f",
        "cmp esi, 4",
        "je 22f",
        "mov r9, 161271",
        "mov ecx, 64",
        "24:",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi+12]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1023",
        "ror r10, 54",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+8]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1023",
        "ror r10, 54",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+4]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1023",
        "ror r10, 54",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1023",
        "ror r10, 54",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+1], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+2], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+3], r10b",
        "shr r10, 8",
        "mov BYTE PTR [r8+4], r10b",
        "shr r10, 8",
        "add rdi, 16",
        "add r8, 5",
        "sub rcx, 1",
        "jne 24b",
        "jmp 23f",
        "22:",
        "mov r9, 2520",
        "mov ecx, 128",
        "25:",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi+4]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 15",
        "ror r10, 60",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 15",
        "ror r10, 60",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "add rdi, 8",
        "add r8, 1",
        "sub rcx, 1",
        "jne 25b",
        "23:",
        "jmp 21f",
        "20:",
        "mov r9, 315",
        "mov ecx, 32",
        "26:",
        "mov r10d, 0",
        "mov eax, DWORD PTR [rdi+28]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+24]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+20]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+16]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+12]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+8]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi+4]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov eax, DWORD PTR [rdi]",
        "mul r9",
        "add rax, 262080",
        "shr rax, 19",
        "and eax, 1",
        "ror r10, 63",
        "add r10, rax",
        "mov BYTE PTR [r8], r10b",
        "shr r10, 8",
        "add rdi, 32",
        "add r8, 1",
        "sub rcx, 1",
        "jne 26b",
        "21:",
        "ret",
    )
}

/// `Decompress_d(ByteDecode_d(b))` (FIPS 203 Algorithm 6 and (4.8)): writes the 256 `d`-bit little-endian fields of the `len` bytes at `b`, decompressed, to `*f` (each less than `q` = 3329).
///
/// Contract: `VG.Spec.MlKem.decodeDecompressContract`. Constant time: only the pointers, `d` and `len` may affect timing, not the data.
///
/// # Safety
///
/// * `b` must be valid for reads of `len` bytes.
/// * `f` must be valid for reads and writes of 1024 bytes.
/// * `d` must be 1, 4 or 10, and `len` must be `32 * d`.
/// * `f` must not overlap `b` (distinct Rust objects never do).
/// * Neither `b` nor `f` may overlap the return address on the stack, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_mlkem_decode_decompress(b: *const u8, len: usize, d: u32, f: *mut [u32; 256]) {
    core::arch::naked_asm!(
        "mov edx, edx",
        "mov rsi, rcx",
        "cmp edx, 1",
        "je 20f",
        "cmp edx, 4",
        "je 22f",
        "mov r9, 3329",
        "mov ecx, 64",
        "24:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi+4]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+3]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+2]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi+1]",
        "ror r10, 56",
        "add r10, rax",
        "movzx eax, BYTE PTR [rdi]",
        "ror r10, 56",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 1023",
        "mul r9",
        "add rax, 512",
        "shr rax, 10",
        "mov DWORD PTR [rsi], eax",
        "shr r10, 10",
        "mov rax, r10",
        "and eax, 1023",
        "mul r9",
        "add rax, 512",
        "shr rax, 10",
        "mov DWORD PTR [rsi+4], eax",
        "shr r10, 10",
        "mov rax, r10",
        "and eax, 1023",
        "mul r9",
        "add rax, 512",
        "shr rax, 10",
        "mov DWORD PTR [rsi+8], eax",
        "shr r10, 10",
        "mov rax, r10",
        "and eax, 1023",
        "mul r9",
        "add rax, 512",
        "shr rax, 10",
        "mov DWORD PTR [rsi+12], eax",
        "shr r10, 10",
        "add rdi, 5",
        "add rsi, 16",
        "sub rcx, 1",
        "jne 24b",
        "jmp 23f",
        "22:",
        "mov r9, 3329",
        "mov ecx, 128",
        "25:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi]",
        "ror r10, 56",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 15",
        "mul r9",
        "add rax, 8",
        "shr rax, 4",
        "mov DWORD PTR [rsi], eax",
        "shr r10, 4",
        "mov rax, r10",
        "and eax, 15",
        "mul r9",
        "add rax, 8",
        "shr rax, 4",
        "mov DWORD PTR [rsi+4], eax",
        "shr r10, 4",
        "add rdi, 1",
        "add rsi, 8",
        "sub rcx, 1",
        "jne 25b",
        "23:",
        "jmp 21f",
        "20:",
        "mov r9, 3329",
        "mov ecx, 32",
        "26:",
        "mov r10d, 0",
        "movzx eax, BYTE PTR [rdi]",
        "ror r10, 56",
        "add r10, rax",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+4], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+8], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+12], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+16], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+20], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+24], eax",
        "shr r10, 1",
        "mov rax, r10",
        "and eax, 1",
        "mul r9",
        "add rax, 1",
        "shr rax, 1",
        "mov DWORD PTR [rsi+28], eax",
        "shr r10, 1",
        "add rdi, 1",
        "add rsi, 32",
        "sub rcx, 1",
        "jne 26b",
        "21:",
        "ret",
    )
}
