// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `pbkdf2_md5` functions for `x86_64`.
#![allow(dead_code)]

/// Runs `n` steps of PBKDF2-HMAC-MD5's iteration: if, for a 64-byte key `K₀`, the MD5 streaming state in bytes 0 to 79 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 80 to 159 represents `K₀ ⊕ opad` (as `vg_hmac_md5_init` leaves them), repeats `U ← HMAC-MD5 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.md5I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 160 bytes.
/// * `u` must be valid for reads of 16 bytes.
/// * `t` must be valid for reads and writes of 16 bytes.
/// * `scratch` must be valid for reads and writes of 384 bytes.
/// * The contents of `scratch` on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u` (distinct Rust objects never do).
/// * None of `key`, `u`, `t` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_md5_iterate(key: *const [u8; 160], u: *const [u8; 16], n: u32, t: *mut [u8; 16], scratch: *mut [u64; 48]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+64], rbx",
        "mov QWORD PTR [r8+72], rbp",
        "mov QWORD PTR [r8+80], r12",
        "mov QWORD PTR [r8+88], r13",
        "mov QWORD PTR [r8+96], r14",
        "mov QWORD PTR [r8+104], r15",
        "mov r15, r8",
        "mov r12, rdi",
        "mov r13, rcx",
        "mov r14d, edx",
        "mov rbx, r8",
        "add rbx, 112",
        "mov rbp, r8",
        "add rbp, 128",
        "mov eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rbp], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rbp+4], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rbp+8], eax",
        "mov eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rbp+12], eax",
        "mov eax, 128",
        "mov DWORD PTR [rbp+16], eax",
        "mov eax, 0",
        "mov DWORD PTR [rbp+20], eax",
        "mov DWORD PTR [rbp+24], eax",
        "mov DWORD PTR [rbp+28], eax",
        "mov DWORD PTR [rbp+32], eax",
        "mov DWORD PTR [rbp+36], eax",
        "mov DWORD PTR [rbp+40], eax",
        "mov DWORD PTR [rbp+44], eax",
        "mov DWORD PTR [rbp+48], eax",
        "mov DWORD PTR [rbp+52], eax",
        "mov r12d, 80",
        "mov rax, r12",
        "add rax, rax",
        "add rax, rax",
        "add rax, rax",
        "mov QWORD PTR [rbx+72], rax",
        "mov r12, rdi",
        "test r14, r14",
        "je 20f",
        "22:",
        "mov eax, DWORD PTR [r12]",
        "mov DWORD PTR [rbx], eax",
        "mov eax, DWORD PTR [r12+4]",
        "mov DWORD PTR [rbx+4], eax",
        "mov eax, DWORD PTR [r12+8]",
        "mov DWORD PTR [rbx+8], eax",
        "mov eax, DWORD PTR [r12+12]",
        "mov DWORD PTR [rbx+12], eax",
        "mov rsi, rbp",
        "mov rdi, rbx",
        "mov edx, 1",
        "mov rcx, r15",
        "call {vg_md5_compress}",
        "mov rbx, rdi",
        "mov r15, rcx",
        "mov eax, DWORD PTR [rbx]",
        "mov DWORD PTR [rbp], eax",
        "mov eax, DWORD PTR [rbx+4]",
        "mov DWORD PTR [rbp+4], eax",
        "mov eax, DWORD PTR [rbx+8]",
        "mov DWORD PTR [rbp+8], eax",
        "mov eax, DWORD PTR [rbx+12]",
        "mov DWORD PTR [rbp+12], eax",
        "mov eax, DWORD PTR [r12+80]",
        "mov DWORD PTR [rbx], eax",
        "mov eax, DWORD PTR [r12+84]",
        "mov DWORD PTR [rbx+4], eax",
        "mov eax, DWORD PTR [r12+88]",
        "mov DWORD PTR [rbx+8], eax",
        "mov eax, DWORD PTR [r12+92]",
        "mov DWORD PTR [rbx+12], eax",
        "mov rsi, rbp",
        "mov rdi, rbx",
        "mov edx, 1",
        "mov rcx, r15",
        "call {vg_md5_compress}",
        "mov rbx, rdi",
        "mov r15, rcx",
        "mov eax, DWORD PTR [rbx]",
        "mov DWORD PTR [rbp], eax",
        "mov eax, DWORD PTR [rbx+4]",
        "mov DWORD PTR [rbp+4], eax",
        "mov eax, DWORD PTR [rbx+8]",
        "mov DWORD PTR [rbp+8], eax",
        "mov eax, DWORD PTR [rbx+12]",
        "mov DWORD PTR [rbp+12], eax",
        "mov eax, DWORD PTR [rbp]",
        "xor eax, DWORD PTR [r13]",
        "mov DWORD PTR [r13], eax",
        "mov eax, DWORD PTR [rbp+4]",
        "xor eax, DWORD PTR [r13+4]",
        "mov DWORD PTR [r13+4], eax",
        "mov eax, DWORD PTR [rbp+8]",
        "xor eax, DWORD PTR [r13+8]",
        "mov DWORD PTR [r13+8], eax",
        "mov eax, DWORD PTR [rbp+12]",
        "xor eax, DWORD PTR [r13+12]",
        "mov DWORD PTR [r13+12], eax",
        "sub r14, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r15+64]",
        "mov rbp, QWORD PTR [r15+72]",
        "mov r12, QWORD PTR [r15+80]",
        "mov r13, QWORD PTR [r15+88]",
        "mov r14, QWORD PTR [r15+96]",
        "mov r15, QWORD PTR [r15+104]",
        "ret",
        vg_md5_compress = sym super::md5::vg_md5_compress,
    )
}
