// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `pbkdf2` functions for `x86_64`.
#![allow(dead_code)]

/// Runs `n` steps of PBKDF2-HMAC-SHA-1's iteration: if, for a 64-byte key `K₀`, the SHA-1 streaming state in bytes 0 to 83 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 84 to 167 represents `K₀ ⊕ opad` (as `vg_hmac_sha1_init` leaves them), repeats `U ← HMAC-SHA-1 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.sha1I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 168 bytes, and `u` for reads of 20 bytes.
/// * `t` must be valid for reads and writes of 20 bytes.
/// * `scratch` must be valid for reads and writes of 448 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u`, and none of the four regions may overlap the return address on the stack or the 16 bytes of stack below it, where its calls, and theirs, store their return addresses (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha1_iterate(key: *const [u8; 168], u: *const [u8; 20], n: u32, t: *mut [u8; 20], scratch: *mut [u64; 56]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+160], rbx",
        "mov QWORD PTR [r8+168], rbp",
        "mov QWORD PTR [r8+176], r12",
        "mov QWORD PTR [r8+184], r13",
        "mov QWORD PTR [r8+192], r14",
        "mov QWORD PTR [r8+200], r15",
        "mov r13d, edx",
        "mov rbx, rdi",
        "mov r12, rcx",
        "mov r15, r8",
        "mov r14d, 0",
        "20:",
        "movzx eax, BYTE PTR [rsi+r14*1]",
        "mov BYTE PTR [r15+r14*1+312], al",
        "add r14, 1",
        "cmp r14, 20",
        "jne 20b",
        "test r13, r13",
        "je 21f",
        "23:",
        "mov r14d, 0",
        "24:",
        "movzx eax, BYTE PTR [rbx+r14*1]",
        "mov BYTE PTR [r15+r14*1+208], al",
        "add r14, 1",
        "cmp r14, 84",
        "jne 24b",
        "mov rdi, r15",
        "add rdi, 208",
        "mov esi, 64",
        "mov rdx, r15",
        "add rdx, 312",
        "mov ecx, 20",
        "mov r8, r15",
        "call {vg_sha1_update}",
        "mov rdi, r15",
        "add rdi, 208",
        "mov esi, 84",
        "mov rdx, r15",
        "add rdx, 292",
        "mov rcx, r15",
        "call {vg_sha1_finalize}",
        "mov r14d, 0",
        "25:",
        "movzx eax, BYTE PTR [rbx+r14*1+84]",
        "mov BYTE PTR [r15+r14*1+208], al",
        "add r14, 1",
        "cmp r14, 84",
        "jne 25b",
        "mov rdi, r15",
        "add rdi, 208",
        "mov esi, 64",
        "mov rdx, r15",
        "add rdx, 292",
        "mov ecx, 20",
        "mov r8, r15",
        "call {vg_sha1_update}",
        "mov rdi, r15",
        "add rdi, 208",
        "mov esi, 84",
        "mov rdx, r15",
        "add rdx, 312",
        "mov rcx, r15",
        "call {vg_sha1_finalize}",
        "mov r14d, 0",
        "26:",
        "movzx eax, BYTE PTR [r15+r14*1+312]",
        "movzx ecx, BYTE PTR [r12+r14*1]",
        "xor eax, ecx",
        "mov BYTE PTR [r12+r14*1], al",
        "add r14, 1",
        "cmp r14, 20",
        "jne 26b",
        "sub r13, 1",
        "jne 23b",
        "jmp 22f",
        "21:",
        "22:",
        "mov rbx, QWORD PTR [r15+160]",
        "mov rbp, QWORD PTR [r15+168]",
        "mov r12, QWORD PTR [r15+176]",
        "mov r13, QWORD PTR [r15+184]",
        "mov r14, QWORD PTR [r15+192]",
        "mov r15, QWORD PTR [r15+200]",
        "ret",
        vg_sha1_update = sym super::sha1::vg_sha1_update,
        vg_sha1_finalize = sym super::sha1::vg_sha1_finalize,
    )
}

/// Runs `n` steps of PBKDF2-HMAC-MD5's iteration: if, for a 64-byte key `K₀`, the MD5 streaming state in bytes 0 to 79 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 80 to 159 represents `K₀ ⊕ opad` (as `vg_hmac_md5_init` leaves them), repeats `U ← HMAC-MD5 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.md5I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 160 bytes, and `u` for reads of 16 bytes.
/// * `t` must be valid for reads and writes of 16 bytes.
/// * `scratch` must be valid for reads and writes of 384 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u`, and none of the four regions may overlap the return address on the stack or the 16 bytes of stack below it, where its calls, and theirs, store their return addresses (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_md5_iterate(key: *const [u8; 160], u: *const [u8; 16], n: u32, t: *mut [u8; 16], scratch: *mut [u64; 48]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+112], rbx",
        "mov QWORD PTR [r8+120], rbp",
        "mov QWORD PTR [r8+128], r12",
        "mov QWORD PTR [r8+136], r13",
        "mov QWORD PTR [r8+144], r14",
        "mov QWORD PTR [r8+152], r15",
        "mov r13d, edx",
        "mov rbx, rdi",
        "mov r12, rcx",
        "mov r15, r8",
        "mov r14d, 0",
        "20:",
        "movzx eax, BYTE PTR [rsi+r14*1]",
        "mov BYTE PTR [r15+r14*1+256], al",
        "add r14, 1",
        "cmp r14, 16",
        "jne 20b",
        "test r13, r13",
        "je 21f",
        "23:",
        "mov r14d, 0",
        "24:",
        "movzx eax, BYTE PTR [rbx+r14*1]",
        "mov BYTE PTR [r15+r14*1+160], al",
        "add r14, 1",
        "cmp r14, 80",
        "jne 24b",
        "mov rdi, r15",
        "add rdi, 160",
        "mov esi, 64",
        "mov rdx, r15",
        "add rdx, 256",
        "mov ecx, 16",
        "mov r8, r15",
        "call {vg_md5_update}",
        "mov rdi, r15",
        "add rdi, 160",
        "mov esi, 80",
        "mov rdx, r15",
        "add rdx, 240",
        "mov rcx, r15",
        "call {vg_md5_finalize}",
        "mov r14d, 0",
        "25:",
        "movzx eax, BYTE PTR [rbx+r14*1+80]",
        "mov BYTE PTR [r15+r14*1+160], al",
        "add r14, 1",
        "cmp r14, 80",
        "jne 25b",
        "mov rdi, r15",
        "add rdi, 160",
        "mov esi, 64",
        "mov rdx, r15",
        "add rdx, 240",
        "mov ecx, 16",
        "mov r8, r15",
        "call {vg_md5_update}",
        "mov rdi, r15",
        "add rdi, 160",
        "mov esi, 80",
        "mov rdx, r15",
        "add rdx, 256",
        "mov rcx, r15",
        "call {vg_md5_finalize}",
        "mov r14d, 0",
        "26:",
        "movzx eax, BYTE PTR [r15+r14*1+256]",
        "movzx ecx, BYTE PTR [r12+r14*1]",
        "xor eax, ecx",
        "mov BYTE PTR [r12+r14*1], al",
        "add r14, 1",
        "cmp r14, 16",
        "jne 26b",
        "sub r13, 1",
        "jne 23b",
        "jmp 22f",
        "21:",
        "22:",
        "mov rbx, QWORD PTR [r15+112]",
        "mov rbp, QWORD PTR [r15+120]",
        "mov r12, QWORD PTR [r15+128]",
        "mov r13, QWORD PTR [r15+136]",
        "mov r14, QWORD PTR [r15+144]",
        "mov r15, QWORD PTR [r15+152]",
        "ret",
        vg_md5_update = sym super::md5::vg_md5_update,
        vg_md5_finalize = sym super::md5::vg_md5_finalize,
    )
}

/// Runs `n` steps of PBKDF2-HMAC-SHA-384's iteration: if, for a 128-byte key `K₀`, the SHA-384 streaming state in bytes 0 to 191 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 192 to 383 represents `K₀ ⊕ opad` (as `vg_hmac_sha384_init` leaves them), repeats `U ← HMAC-SHA-384 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.sha384I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 384 bytes, and `u` for reads of 48 bytes.
/// * `t` must be valid for reads and writes of 48 bytes.
/// * `scratch` must be valid for reads and writes of 768 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u`, and none of the four regions may overlap the return address on the stack or the 16 bytes of stack below it, where its calls, and theirs, store their return addresses (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha384_iterate(key: *const [u8; 384], u: *const [u8; 48], n: u32, t: *mut [u8; 48], scratch: *mut [u64; 96]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+272], rbx",
        "mov QWORD PTR [r8+280], rbp",
        "mov QWORD PTR [r8+288], r12",
        "mov QWORD PTR [r8+296], r13",
        "mov QWORD PTR [r8+304], r14",
        "mov QWORD PTR [r8+312], r15",
        "mov r13d, edx",
        "mov rbx, rdi",
        "mov r12, rcx",
        "mov r15, r8",
        "mov r14d, 0",
        "20:",
        "movzx eax, BYTE PTR [rsi+r14*1]",
        "mov BYTE PTR [r15+r14*1+576], al",
        "add r14, 1",
        "cmp r14, 48",
        "jne 20b",
        "test r13, r13",
        "je 21f",
        "23:",
        "mov r14d, 0",
        "24:",
        "movzx eax, BYTE PTR [rbx+r14*1]",
        "mov BYTE PTR [r15+r14*1+320], al",
        "add r14, 1",
        "cmp r14, 192",
        "jne 24b",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 128",
        "mov rdx, r15",
        "add rdx, 576",
        "mov ecx, 48",
        "mov r8, r15",
        "call {vg_sha512_update}",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 176",
        "mov rdx, r15",
        "add rdx, 512",
        "mov rcx, r15",
        "call {vg_sha512_finalize}",
        "mov r14d, 0",
        "25:",
        "movzx eax, BYTE PTR [rbx+r14*1+192]",
        "mov BYTE PTR [r15+r14*1+320], al",
        "add r14, 1",
        "cmp r14, 192",
        "jne 25b",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 128",
        "mov rdx, r15",
        "add rdx, 512",
        "mov ecx, 48",
        "mov r8, r15",
        "call {vg_sha512_update}",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 176",
        "mov rdx, r15",
        "add rdx, 576",
        "mov rcx, r15",
        "call {vg_sha512_finalize}",
        "mov r14d, 0",
        "26:",
        "movzx eax, BYTE PTR [r15+r14*1+576]",
        "movzx ecx, BYTE PTR [r12+r14*1]",
        "xor eax, ecx",
        "mov BYTE PTR [r12+r14*1], al",
        "add r14, 1",
        "cmp r14, 48",
        "jne 26b",
        "sub r13, 1",
        "jne 23b",
        "jmp 22f",
        "21:",
        "22:",
        "mov rbx, QWORD PTR [r15+272]",
        "mov rbp, QWORD PTR [r15+280]",
        "mov r12, QWORD PTR [r15+288]",
        "mov r13, QWORD PTR [r15+296]",
        "mov r14, QWORD PTR [r15+304]",
        "mov r15, QWORD PTR [r15+312]",
        "ret",
        vg_sha512_update = sym super::sha512::vg_sha512_update,
        vg_sha512_finalize = sym super::sha512::vg_sha512_finalize,
    )
}

/// Runs `n` steps of PBKDF2-HMAC-SHA-512's iteration: if, for a 128-byte key `K₀`, the SHA-512 streaming state in bytes 0 to 191 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 192 to 383 represents `K₀ ⊕ opad` (as `vg_hmac_sha512_init` leaves them), repeats `U ← HMAC-SHA-512 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.sha512I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 384 bytes, and `u` for reads of 64 bytes.
/// * `t` must be valid for reads and writes of 64 bytes.
/// * `scratch` must be valid for reads and writes of 768 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u`, and none of the four regions may overlap the return address on the stack or the 16 bytes of stack below it, where its calls, and theirs, store their return addresses (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha512_iterate(key: *const [u8; 384], u: *const [u8; 64], n: u32, t: *mut [u8; 64], scratch: *mut [u64; 96]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+272], rbx",
        "mov QWORD PTR [r8+280], rbp",
        "mov QWORD PTR [r8+288], r12",
        "mov QWORD PTR [r8+296], r13",
        "mov QWORD PTR [r8+304], r14",
        "mov QWORD PTR [r8+312], r15",
        "mov r13d, edx",
        "mov rbx, rdi",
        "mov r12, rcx",
        "mov r15, r8",
        "mov r14d, 0",
        "20:",
        "movzx eax, BYTE PTR [rsi+r14*1]",
        "mov BYTE PTR [r15+r14*1+576], al",
        "add r14, 1",
        "cmp r14, 64",
        "jne 20b",
        "test r13, r13",
        "je 21f",
        "23:",
        "mov r14d, 0",
        "24:",
        "movzx eax, BYTE PTR [rbx+r14*1]",
        "mov BYTE PTR [r15+r14*1+320], al",
        "add r14, 1",
        "cmp r14, 192",
        "jne 24b",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 128",
        "mov rdx, r15",
        "add rdx, 576",
        "mov ecx, 64",
        "mov r8, r15",
        "call {vg_sha512_update}",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 192",
        "mov rdx, r15",
        "add rdx, 512",
        "mov rcx, r15",
        "call {vg_sha512_finalize}",
        "mov r14d, 0",
        "25:",
        "movzx eax, BYTE PTR [rbx+r14*1+192]",
        "mov BYTE PTR [r15+r14*1+320], al",
        "add r14, 1",
        "cmp r14, 192",
        "jne 25b",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 128",
        "mov rdx, r15",
        "add rdx, 512",
        "mov ecx, 64",
        "mov r8, r15",
        "call {vg_sha512_update}",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 192",
        "mov rdx, r15",
        "add rdx, 576",
        "mov rcx, r15",
        "call {vg_sha512_finalize}",
        "mov r14d, 0",
        "26:",
        "movzx eax, BYTE PTR [r15+r14*1+576]",
        "movzx ecx, BYTE PTR [r12+r14*1]",
        "xor eax, ecx",
        "mov BYTE PTR [r12+r14*1], al",
        "add r14, 1",
        "cmp r14, 64",
        "jne 26b",
        "sub r13, 1",
        "jne 23b",
        "jmp 22f",
        "21:",
        "22:",
        "mov rbx, QWORD PTR [r15+272]",
        "mov rbp, QWORD PTR [r15+280]",
        "mov r12, QWORD PTR [r15+288]",
        "mov r13, QWORD PTR [r15+296]",
        "mov r14, QWORD PTR [r15+304]",
        "mov r15, QWORD PTR [r15+312]",
        "ret",
        vg_sha512_update = sym super::sha512::vg_sha512_update,
        vg_sha512_finalize = sym super::sha512::vg_sha512_finalize,
    )
}

/// Runs `n` steps of PBKDF2-HMAC-SHA-512/224's iteration: if, for a 128-byte key `K₀`, the SHA-512/224 streaming state in bytes 0 to 191 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 192 to 383 represents `K₀ ⊕ opad` (as `vg_hmac_sha512_224_init` leaves them), repeats `U ← HMAC-SHA-512/224 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.sha512_224I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 384 bytes, and `u` for reads of 28 bytes.
/// * `t` must be valid for reads and writes of 28 bytes.
/// * `scratch` must be valid for reads and writes of 768 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u`, and none of the four regions may overlap the return address on the stack or the 16 bytes of stack below it, where its calls, and theirs, store their return addresses (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha512_224_iterate(key: *const [u8; 384], u: *const [u8; 28], n: u32, t: *mut [u8; 28], scratch: *mut [u64; 96]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+272], rbx",
        "mov QWORD PTR [r8+280], rbp",
        "mov QWORD PTR [r8+288], r12",
        "mov QWORD PTR [r8+296], r13",
        "mov QWORD PTR [r8+304], r14",
        "mov QWORD PTR [r8+312], r15",
        "mov r13d, edx",
        "mov rbx, rdi",
        "mov r12, rcx",
        "mov r15, r8",
        "mov r14d, 0",
        "20:",
        "movzx eax, BYTE PTR [rsi+r14*1]",
        "mov BYTE PTR [r15+r14*1+576], al",
        "add r14, 1",
        "cmp r14, 28",
        "jne 20b",
        "test r13, r13",
        "je 21f",
        "23:",
        "mov r14d, 0",
        "24:",
        "movzx eax, BYTE PTR [rbx+r14*1]",
        "mov BYTE PTR [r15+r14*1+320], al",
        "add r14, 1",
        "cmp r14, 192",
        "jne 24b",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 128",
        "mov rdx, r15",
        "add rdx, 576",
        "mov ecx, 28",
        "mov r8, r15",
        "call {vg_sha512_update}",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 156",
        "mov rdx, r15",
        "add rdx, 512",
        "mov rcx, r15",
        "call {vg_sha512_finalize}",
        "mov r14d, 0",
        "25:",
        "movzx eax, BYTE PTR [rbx+r14*1+192]",
        "mov BYTE PTR [r15+r14*1+320], al",
        "add r14, 1",
        "cmp r14, 192",
        "jne 25b",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 128",
        "mov rdx, r15",
        "add rdx, 512",
        "mov ecx, 28",
        "mov r8, r15",
        "call {vg_sha512_update}",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 156",
        "mov rdx, r15",
        "add rdx, 576",
        "mov rcx, r15",
        "call {vg_sha512_finalize}",
        "mov r14d, 0",
        "26:",
        "movzx eax, BYTE PTR [r15+r14*1+576]",
        "movzx ecx, BYTE PTR [r12+r14*1]",
        "xor eax, ecx",
        "mov BYTE PTR [r12+r14*1], al",
        "add r14, 1",
        "cmp r14, 28",
        "jne 26b",
        "sub r13, 1",
        "jne 23b",
        "jmp 22f",
        "21:",
        "22:",
        "mov rbx, QWORD PTR [r15+272]",
        "mov rbp, QWORD PTR [r15+280]",
        "mov r12, QWORD PTR [r15+288]",
        "mov r13, QWORD PTR [r15+296]",
        "mov r14, QWORD PTR [r15+304]",
        "mov r15, QWORD PTR [r15+312]",
        "ret",
        vg_sha512_update = sym super::sha512::vg_sha512_update,
        vg_sha512_finalize = sym super::sha512::vg_sha512_finalize,
    )
}

/// Runs `n` steps of PBKDF2-HMAC-SHA-512/256's iteration: if, for a 128-byte key `K₀`, the SHA-512/256 streaming state in bytes 0 to 191 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 192 to 383 represents `K₀ ⊕ opad` (as `vg_hmac_sha512_256_init` leaves them), repeats `U ← HMAC-SHA-512/256 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.sha512_256I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 384 bytes, and `u` for reads of 32 bytes.
/// * `t` must be valid for reads and writes of 32 bytes.
/// * `scratch` must be valid for reads and writes of 768 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u`, and none of the four regions may overlap the return address on the stack or the 16 bytes of stack below it, where its calls, and theirs, store their return addresses (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha512_256_iterate(key: *const [u8; 384], u: *const [u8; 32], n: u32, t: *mut [u8; 32], scratch: *mut [u64; 96]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+272], rbx",
        "mov QWORD PTR [r8+280], rbp",
        "mov QWORD PTR [r8+288], r12",
        "mov QWORD PTR [r8+296], r13",
        "mov QWORD PTR [r8+304], r14",
        "mov QWORD PTR [r8+312], r15",
        "mov r13d, edx",
        "mov rbx, rdi",
        "mov r12, rcx",
        "mov r15, r8",
        "mov r14d, 0",
        "20:",
        "movzx eax, BYTE PTR [rsi+r14*1]",
        "mov BYTE PTR [r15+r14*1+576], al",
        "add r14, 1",
        "cmp r14, 32",
        "jne 20b",
        "test r13, r13",
        "je 21f",
        "23:",
        "mov r14d, 0",
        "24:",
        "movzx eax, BYTE PTR [rbx+r14*1]",
        "mov BYTE PTR [r15+r14*1+320], al",
        "add r14, 1",
        "cmp r14, 192",
        "jne 24b",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 128",
        "mov rdx, r15",
        "add rdx, 576",
        "mov ecx, 32",
        "mov r8, r15",
        "call {vg_sha512_update}",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 160",
        "mov rdx, r15",
        "add rdx, 512",
        "mov rcx, r15",
        "call {vg_sha512_finalize}",
        "mov r14d, 0",
        "25:",
        "movzx eax, BYTE PTR [rbx+r14*1+192]",
        "mov BYTE PTR [r15+r14*1+320], al",
        "add r14, 1",
        "cmp r14, 192",
        "jne 25b",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 128",
        "mov rdx, r15",
        "add rdx, 512",
        "mov ecx, 32",
        "mov r8, r15",
        "call {vg_sha512_update}",
        "mov rdi, r15",
        "add rdi, 320",
        "mov esi, 160",
        "mov rdx, r15",
        "add rdx, 576",
        "mov rcx, r15",
        "call {vg_sha512_finalize}",
        "mov r14d, 0",
        "26:",
        "movzx eax, BYTE PTR [r15+r14*1+576]",
        "movzx ecx, BYTE PTR [r12+r14*1]",
        "xor eax, ecx",
        "mov BYTE PTR [r12+r14*1], al",
        "add r14, 1",
        "cmp r14, 32",
        "jne 26b",
        "sub r13, 1",
        "jne 23b",
        "jmp 22f",
        "21:",
        "22:",
        "mov rbx, QWORD PTR [r15+272]",
        "mov rbp, QWORD PTR [r15+280]",
        "mov r12, QWORD PTR [r15+288]",
        "mov r13, QWORD PTR [r15+296]",
        "mov r14, QWORD PTR [r15+304]",
        "mov r15, QWORD PTR [r15+312]",
        "ret",
        vg_sha512_update = sym super::sha512::vg_sha512_update,
        vg_sha512_finalize = sym super::sha512::vg_sha512_finalize,
    )
}

/// Runs `n` steps of PBKDF2-HMAC-SHA-256's iteration: if, for a 64-byte key `K₀`, the SHA-256 streaming state in bytes 0 to 95 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 96 to 191 represents `K₀ ⊕ opad` (as `vg_hmac_sha256_init` leaves them), repeats `U ← HMAC-SHA-256 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Pbkdf2.iterateSha256Contract`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 192 bytes, and `u` for reads of 32 bytes.
/// * `t` must be valid for reads and writes of 32 bytes.
/// * `scratch` must be valid for reads and writes of 384 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u`, and none of the four regions may overlap the return address on the stack or the 8 bytes of stack below it, where its calls of `vg_sha256_compress` store their return address (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha256_iterate(key: *const [u8; 192], u: *const [u8; 32], n: u32, t: *mut [u8; 32], scratch: *mut [u64; 48]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+208], rbx",
        "mov QWORD PTR [r8+216], rbp",
        "mov QWORD PTR [r8+224], r13",
        "mov r13d, edx",
        "mov rbx, rdi",
        "mov rbp, rcx",
        "mov rcx, r8",
        "mov rdi, r8",
        "add rdi, 112",
        "mov rax, QWORD PTR [rsi]",
        "mov QWORD PTR [rcx+144], rax",
        "mov rax, QWORD PTR [rsi+8]",
        "mov QWORD PTR [rcx+152], rax",
        "mov rax, QWORD PTR [rsi+16]",
        "mov QWORD PTR [rcx+160], rax",
        "mov rax, QWORD PTR [rsi+24]",
        "mov QWORD PTR [rcx+168], rax",
        "mov eax, 128",
        "mov QWORD PTR [rcx+176], rax",
        "mov eax, 0",
        "mov QWORD PTR [rcx+184], rax",
        "mov QWORD PTR [rcx+192], rax",
        "mov DWORD PTR [rcx+200], eax",
        "mov eax, 196608",
        "mov DWORD PTR [rcx+204], eax",
        "test r13, r13",
        "je 20f",
        "22:",
        "mov rax, QWORD PTR [rbx]",
        "mov QWORD PTR [rdi], rax",
        "mov rax, QWORD PTR [rbx+8]",
        "mov QWORD PTR [rdi+8], rax",
        "mov rax, QWORD PTR [rbx+16]",
        "mov QWORD PTR [rdi+16], rax",
        "mov rax, QWORD PTR [rbx+24]",
        "mov QWORD PTR [rdi+24], rax",
        "mov rsi, rcx",
        "add rsi, 144",
        "mov edx, 1",
        "call {vg_sha256_compress}",
        "mov eax, DWORD PTR [rdi]",
        "bswap eax",
        "mov DWORD PTR [rcx+144], eax",
        "mov eax, DWORD PTR [rdi+4]",
        "bswap eax",
        "mov DWORD PTR [rcx+148], eax",
        "mov eax, DWORD PTR [rdi+8]",
        "bswap eax",
        "mov DWORD PTR [rcx+152], eax",
        "mov eax, DWORD PTR [rdi+12]",
        "bswap eax",
        "mov DWORD PTR [rcx+156], eax",
        "mov eax, DWORD PTR [rdi+16]",
        "bswap eax",
        "mov DWORD PTR [rcx+160], eax",
        "mov eax, DWORD PTR [rdi+20]",
        "bswap eax",
        "mov DWORD PTR [rcx+164], eax",
        "mov eax, DWORD PTR [rdi+24]",
        "bswap eax",
        "mov DWORD PTR [rcx+168], eax",
        "mov eax, DWORD PTR [rdi+28]",
        "bswap eax",
        "mov DWORD PTR [rcx+172], eax",
        "mov rax, QWORD PTR [rbx+96]",
        "mov QWORD PTR [rdi], rax",
        "mov rax, QWORD PTR [rbx+104]",
        "mov QWORD PTR [rdi+8], rax",
        "mov rax, QWORD PTR [rbx+112]",
        "mov QWORD PTR [rdi+16], rax",
        "mov rax, QWORD PTR [rbx+120]",
        "mov QWORD PTR [rdi+24], rax",
        "mov rsi, rcx",
        "add rsi, 144",
        "mov edx, 1",
        "call {vg_sha256_compress}",
        "mov eax, DWORD PTR [rdi]",
        "bswap eax",
        "mov DWORD PTR [rcx+144], eax",
        "mov eax, DWORD PTR [rdi+4]",
        "bswap eax",
        "mov DWORD PTR [rcx+148], eax",
        "mov eax, DWORD PTR [rdi+8]",
        "bswap eax",
        "mov DWORD PTR [rcx+152], eax",
        "mov eax, DWORD PTR [rdi+12]",
        "bswap eax",
        "mov DWORD PTR [rcx+156], eax",
        "mov eax, DWORD PTR [rdi+16]",
        "bswap eax",
        "mov DWORD PTR [rcx+160], eax",
        "mov eax, DWORD PTR [rdi+20]",
        "bswap eax",
        "mov DWORD PTR [rcx+164], eax",
        "mov eax, DWORD PTR [rdi+24]",
        "bswap eax",
        "mov DWORD PTR [rcx+168], eax",
        "mov eax, DWORD PTR [rdi+28]",
        "bswap eax",
        "mov DWORD PTR [rcx+172], eax",
        "mov rax, QWORD PTR [rcx+144]",
        "xor rax, QWORD PTR [rbp]",
        "mov QWORD PTR [rbp], rax",
        "mov rax, QWORD PTR [rcx+152]",
        "xor rax, QWORD PTR [rbp+8]",
        "mov QWORD PTR [rbp+8], rax",
        "mov rax, QWORD PTR [rcx+160]",
        "xor rax, QWORD PTR [rbp+16]",
        "mov QWORD PTR [rbp+16], rax",
        "mov rax, QWORD PTR [rcx+168]",
        "xor rax, QWORD PTR [rbp+24]",
        "mov QWORD PTR [rbp+24], rax",
        "sub r13, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [rcx+208]",
        "mov rbp, QWORD PTR [rcx+216]",
        "mov r13, QWORD PTR [rcx+224]",
        "ret",
        vg_sha256_compress = sym super::sha256::vg_sha256_compress,
    )
}
