// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `pbkdf2_sha256` functions for `x86_64`.
#![allow(dead_code)]

/// Runs `n` steps of PBKDF2-HMAC-SHA-256's iteration: if, for a 64-byte key `K₀`, the SHA-256 streaming state in bytes 0 to 95 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 96 to 191 represents `K₀ ⊕ opad` (as `vg_hmac_sha256_init` leaves them), repeats `U ← HMAC-SHA-256 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Pbkdf2.iterateSha256Contract`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 192 bytes, and `u` for reads of 32 bytes.
/// * `t` must be valid for reads and writes of 32 bytes.
/// * `scratch` must be valid for reads and writes of 384 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u` (distinct Rust objects never do).
/// * None of `key`, `u`, `t` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha256_iterate(key: *const [u8; 192], u: *const [u8; 32], n: u32, t: *mut [u8; 32], scratch: *mut [u64; 48]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+208], rbx",
        "mov QWORD PTR [r8+216], rbp",
        "mov QWORD PTR [r8+224], r13",
        "mov r13d, edx",
        "mov rbx, rdi",
        "mov rbp, rcx",
        "mov rcx, r8",
        "mov rdi, r8",
        "add rdi, 112",
        "mov rax, QWORD PTR [rsi]",
        "mov QWORD PTR [rcx+144], rax",
        "mov rax, QWORD PTR [rsi+8]",
        "mov QWORD PTR [rcx+152], rax",
        "mov rax, QWORD PTR [rsi+16]",
        "mov QWORD PTR [rcx+160], rax",
        "mov rax, QWORD PTR [rsi+24]",
        "mov QWORD PTR [rcx+168], rax",
        "mov eax, 128",
        "mov QWORD PTR [rcx+176], rax",
        "mov eax, 0",
        "mov QWORD PTR [rcx+184], rax",
        "mov QWORD PTR [rcx+192], rax",
        "mov DWORD PTR [rcx+200], eax",
        "mov eax, 196608",
        "mov DWORD PTR [rcx+204], eax",
        "test r13, r13",
        "je 20f",
        "22:",
        "mov rax, QWORD PTR [rbx]",
        "mov QWORD PTR [rdi], rax",
        "mov rax, QWORD PTR [rbx+8]",
        "mov QWORD PTR [rdi+8], rax",
        "mov rax, QWORD PTR [rbx+16]",
        "mov QWORD PTR [rdi+16], rax",
        "mov rax, QWORD PTR [rbx+24]",
        "mov QWORD PTR [rdi+24], rax",
        "mov rsi, rcx",
        "add rsi, 144",
        "mov edx, 1",
        "call {vg_sha256_compress}",
        "mov eax, DWORD PTR [rdi]",
        "bswap eax",
        "mov DWORD PTR [rcx+144], eax",
        "mov eax, DWORD PTR [rdi+4]",
        "bswap eax",
        "mov DWORD PTR [rcx+148], eax",
        "mov eax, DWORD PTR [rdi+8]",
        "bswap eax",
        "mov DWORD PTR [rcx+152], eax",
        "mov eax, DWORD PTR [rdi+12]",
        "bswap eax",
        "mov DWORD PTR [rcx+156], eax",
        "mov eax, DWORD PTR [rdi+16]",
        "bswap eax",
        "mov DWORD PTR [rcx+160], eax",
        "mov eax, DWORD PTR [rdi+20]",
        "bswap eax",
        "mov DWORD PTR [rcx+164], eax",
        "mov eax, DWORD PTR [rdi+24]",
        "bswap eax",
        "mov DWORD PTR [rcx+168], eax",
        "mov eax, DWORD PTR [rdi+28]",
        "bswap eax",
        "mov DWORD PTR [rcx+172], eax",
        "mov rax, QWORD PTR [rbx+96]",
        "mov QWORD PTR [rdi], rax",
        "mov rax, QWORD PTR [rbx+104]",
        "mov QWORD PTR [rdi+8], rax",
        "mov rax, QWORD PTR [rbx+112]",
        "mov QWORD PTR [rdi+16], rax",
        "mov rax, QWORD PTR [rbx+120]",
        "mov QWORD PTR [rdi+24], rax",
        "mov rsi, rcx",
        "add rsi, 144",
        "mov edx, 1",
        "call {vg_sha256_compress}",
        "mov eax, DWORD PTR [rdi]",
        "bswap eax",
        "mov DWORD PTR [rcx+144], eax",
        "mov eax, DWORD PTR [rdi+4]",
        "bswap eax",
        "mov DWORD PTR [rcx+148], eax",
        "mov eax, DWORD PTR [rdi+8]",
        "bswap eax",
        "mov DWORD PTR [rcx+152], eax",
        "mov eax, DWORD PTR [rdi+12]",
        "bswap eax",
        "mov DWORD PTR [rcx+156], eax",
        "mov eax, DWORD PTR [rdi+16]",
        "bswap eax",
        "mov DWORD PTR [rcx+160], eax",
        "mov eax, DWORD PTR [rdi+20]",
        "bswap eax",
        "mov DWORD PTR [rcx+164], eax",
        "mov eax, DWORD PTR [rdi+24]",
        "bswap eax",
        "mov DWORD PTR [rcx+168], eax",
        "mov eax, DWORD PTR [rdi+28]",
        "bswap eax",
        "mov DWORD PTR [rcx+172], eax",
        "mov rax, QWORD PTR [rcx+144]",
        "xor rax, QWORD PTR [rbp]",
        "mov QWORD PTR [rbp], rax",
        "mov rax, QWORD PTR [rcx+152]",
        "xor rax, QWORD PTR [rbp+8]",
        "mov QWORD PTR [rbp+8], rax",
        "mov rax, QWORD PTR [rcx+160]",
        "xor rax, QWORD PTR [rbp+16]",
        "mov QWORD PTR [rbp+16], rax",
        "mov rax, QWORD PTR [rcx+168]",
        "xor rax, QWORD PTR [rbp+24]",
        "mov QWORD PTR [rbp+24], rax",
        "sub r13, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [rcx+208]",
        "mov rbp, QWORD PTR [rcx+216]",
        "mov r13, QWORD PTR [rcx+224]",
        "ret",
        vg_sha256_compress = sym super::sha256::vg_sha256_compress,
    )
}

/// PBKDF2-HMAC-SHA-256 (RFC 8018 §5.2, with HMAC-SHA-256 as the pseudorandom function): writes the `out_len`-byte key derived from the `password_len` bytes at `password` and the `salt_len` bytes at `salt` with `c` iterations to `out`. Calls the verified SHA-256 and HMAC-SHA-256 functions and `vg_pbkdf2_hmac_sha256_iterate`.
///
/// Contract: `VG.Spec.Pbkdf2.pbkdf2Sha256Contract`. Constant time: only the pointers, the lengths and `c` may affect timing, not the password, the salt or the key.
///
/// Each 32-byte block `T_i` starts from a copy of the key's inner HMAC state that has already absorbed the salt: `vg_sha256_update` adds `INT (i)` and `vg_hmac_sha256_finalize` gives `U₁`, then `vg_pbkdf2_hmac_sha256_iterate` the other `c - 1` steps, each called with this function's suffix. A password longer than 64 bytes is hashed first.
///
/// # Safety
///
/// * `c` must be positive, and `out_len` at most `(2^32 - 1) * 32`.
/// * `password` must be valid for reads of `password_len` bytes, and `salt` for reads of `salt_len` bytes.
/// * `out` must be valid for reads and writes of `out_len` bytes.
/// * `scratch` must be valid for reads and writes of 2048 bytes; its contents on return are unspecified.
/// * `out` and `scratch` must not overlap each other, `password` or `salt` (distinct Rust objects never do).
/// * None of `password`, `salt`, `out` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha256(password: *const u8, password_len: usize, salt: *const u8, salt_len: usize, c: u32, out: *mut u8, out_len: usize, scratch: *mut [u64; 256]) {
    core::arch::naked_asm!(
        "mov rax, QWORD PTR [rsp+16]",
        "mov QWORD PTR [rax+432], rbp",
        "mov QWORD PTR [rax+440], r12",
        "mov QWORD PTR [rax+448], r13",
        "mov QWORD PTR [rax+456], r14",
        "mov QWORD PTR [rax+464], r15",
        "mov QWORD PTR [rax+424], rbx",
        "mov rbx, rax",
        "mov r12, rdi",
        "mov r13, rsi",
        "mov r14, rdx",
        "mov r15, rcx",
        "mov rbp, r9",
        "mov DWORD PTR [rbx+472], r8d",
        "cmp r13, 65",
        "jb 20f",
        "mov rdi, rbx",
        "add rdi, 288",
        "call {vg_sha256_init}",
        "mov rdi, rbx",
        "add rdi, 288",
        "mov esi, 0",
        "mov rdx, r12",
        "mov rcx, r13",
        "mov r8, rbx",
        "add r8, 512",
        "call {vg_sha256_update}",
        "mov rdi, rbx",
        "add rdi, 288",
        "mov rsi, r13",
        "mov rdx, rbx",
        "add rdx, 480",
        "mov rcx, rbx",
        "add rcx, 512",
        "call {vg_sha256_finalize}",
        "mov r12, rbx",
        "add r12, 480",
        "mov r13d, 32",
        "jmp 21f",
        "20:",
        "21:",
        "mov rdi, rbx",
        "mov rsi, rbx",
        "add rsi, 96",
        "mov rdx, r12",
        "mov rcx, r13",
        "mov r8, rbx",
        "add r8, 512",
        "call {vg_hmac_sha256_init}",
        "mov rax, QWORD PTR [rbx]",
        "mov QWORD PTR [rbx+192], rax",
        "mov rax, QWORD PTR [rbx+8]",
        "mov QWORD PTR [rbx+200], rax",
        "mov rax, QWORD PTR [rbx+16]",
        "mov QWORD PTR [rbx+208], rax",
        "mov rax, QWORD PTR [rbx+24]",
        "mov QWORD PTR [rbx+216], rax",
        "mov rax, QWORD PTR [rbx+32]",
        "mov QWORD PTR [rbx+224], rax",
        "mov rax, QWORD PTR [rbx+40]",
        "mov QWORD PTR [rbx+232], rax",
        "mov rax, QWORD PTR [rbx+48]",
        "mov QWORD PTR [rbx+240], rax",
        "mov rax, QWORD PTR [rbx+56]",
        "mov QWORD PTR [rbx+248], rax",
        "mov rax, QWORD PTR [rbx+64]",
        "mov QWORD PTR [rbx+256], rax",
        "mov rax, QWORD PTR [rbx+72]",
        "mov QWORD PTR [rbx+264], rax",
        "mov rax, QWORD PTR [rbx+80]",
        "mov QWORD PTR [rbx+272], rax",
        "mov rax, QWORD PTR [rbx+88]",
        "mov QWORD PTR [rbx+280], rax",
        "mov rdi, rbx",
        "add rdi, 192",
        "mov esi, 64",
        "mov rdx, r14",
        "mov rcx, r15",
        "mov r8, rbx",
        "add r8, 512",
        "call {vg_sha256_update}",
        "add r15, 64",
        "mov r14d, DWORD PTR [rbx+472]",
        "sub r14, 1",
        "mov r12d, 1",
        "mov r13, QWORD PTR [rsp+8]",
        "test r13, r13",
        "je 22f",
        "24:",
        "mov rax, QWORD PTR [rbx+192]",
        "mov QWORD PTR [rbx+288], rax",
        "mov rax, QWORD PTR [rbx+200]",
        "mov QWORD PTR [rbx+296], rax",
        "mov rax, QWORD PTR [rbx+208]",
        "mov QWORD PTR [rbx+304], rax",
        "mov rax, QWORD PTR [rbx+216]",
        "mov QWORD PTR [rbx+312], rax",
        "mov rax, QWORD PTR [rbx+224]",
        "mov QWORD PTR [rbx+320], rax",
        "mov rax, QWORD PTR [rbx+232]",
        "mov QWORD PTR [rbx+328], rax",
        "mov rax, QWORD PTR [rbx+240]",
        "mov QWORD PTR [rbx+336], rax",
        "mov rax, QWORD PTR [rbx+248]",
        "mov QWORD PTR [rbx+344], rax",
        "mov rax, QWORD PTR [rbx+256]",
        "mov QWORD PTR [rbx+352], rax",
        "mov rax, QWORD PTR [rbx+264]",
        "mov QWORD PTR [rbx+360], rax",
        "mov rax, QWORD PTR [rbx+272]",
        "mov QWORD PTR [rbx+368], rax",
        "mov rax, QWORD PTR [rbx+280]",
        "mov QWORD PTR [rbx+376], rax",
        "mov eax, r12d",
        "bswap eax",
        "mov DWORD PTR [rbx+416], eax",
        "mov rdi, rbx",
        "add rdi, 288",
        "mov rsi, r15",
        "mov rdx, rbx",
        "add rdx, 416",
        "mov ecx, 4",
        "mov r8, rbx",
        "add r8, 512",
        "call {vg_sha256_update}",
        "mov rdi, rbx",
        "add rdi, 288",
        "mov rsi, rbx",
        "add rsi, 96",
        "mov rdx, r15",
        "add rdx, 4",
        "mov rcx, rbx",
        "add rcx, 896",
        "call {vg_hmac_sha256_finalize}",
        "mov rax, QWORD PTR [rbx+1072]",
        "mov QWORD PTR [rbx+384], rax",
        "mov rax, QWORD PTR [rbx+1080]",
        "mov QWORD PTR [rbx+392], rax",
        "mov rax, QWORD PTR [rbx+1088]",
        "mov QWORD PTR [rbx+400], rax",
        "mov rax, QWORD PTR [rbx+1096]",
        "mov QWORD PTR [rbx+408], rax",
        "mov rdi, rbx",
        "mov rsi, rbx",
        "add rsi, 1072",
        "mov edx, r14d",
        "mov rcx, rbx",
        "add rcx, 384",
        "mov r8, rbx",
        "add r8, 512",
        "call {vg_pbkdf2_hmac_sha256_iterate}",
        "mov ecx, 32",
        "cmp r13, 32",
        "jb 25f",
        "jmp 26f",
        "25:",
        "mov rcx, r13",
        "26:",
        "sub r13, rcx",
        "mov rdi, rbx",
        "add rdi, 384",
        "mov rsi, rbp",
        "27:",
        "movzx eax, BYTE PTR [rdi]",
        "mov BYTE PTR [rsi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 27b",
        "mov rbp, rsi",
        "add r12, 1",
        "test r13, r13",
        "jne 24b",
        "jmp 23f",
        "22:",
        "23:",
        "mov rbp, QWORD PTR [rbx+432]",
        "mov r12, QWORD PTR [rbx+440]",
        "mov r13, QWORD PTR [rbx+448]",
        "mov r14, QWORD PTR [rbx+456]",
        "mov r15, QWORD PTR [rbx+464]",
        "mov rbx, QWORD PTR [rbx+424]",
        "ret",
        vg_sha256_init = sym super::sha256::vg_sha256_init,
        vg_sha256_update = sym super::sha256::vg_sha256_update,
        vg_sha256_finalize = sym super::sha256::vg_sha256_finalize,
        vg_hmac_sha256_init = sym super::hmac_sha256::vg_hmac_sha256_init,
        vg_hmac_sha256_finalize = sym super::hmac_sha256::vg_hmac_sha256_finalize,
        vg_pbkdf2_hmac_sha256_iterate = sym super::pbkdf2_sha256::vg_pbkdf2_hmac_sha256_iterate,
    )
}

/// The CPU features `vg_pbkdf2_hmac_sha256_iterate_shani` requires (`Artifact.features`).
pub(crate) const VG_PBKDF2_HMAC_SHA256_ITERATE_SHANI_FEATURES: &[&str] = &["sha", "ssse3"];

/// Runs `n` steps of PBKDF2-HMAC-SHA-256's iteration: if, for a 64-byte key `K₀`, the SHA-256 streaming state in bytes 0 to 95 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 96 to 191 represents `K₀ ⊕ opad` (as `vg_hmac_sha256_init` leaves them), repeats `U ← HMAC-SHA-256 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Pbkdf2.iterateSha256Contract`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 192 bytes, and `u` for reads of 32 bytes.
/// * `t` must be valid for reads and writes of 32 bytes.
/// * `scratch` must be valid for reads and writes of 384 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u` (distinct Rust objects never do).
/// * None of `key`, `u`, `t` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `sha` and `ssse3` target features.
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha256_iterate_shani(key: *const [u8; 192], u: *const [u8; 32], n: u32, t: *mut [u8; 32], scratch: *mut [u64; 48]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+208], rbx",
        "mov QWORD PTR [r8+216], rbp",
        "mov QWORD PTR [r8+224], r13",
        "mov r13d, edx",
        "mov rbx, rdi",
        "mov rbp, rcx",
        "mov rcx, r8",
        "mov rdi, r8",
        "add rdi, 112",
        "mov rax, QWORD PTR [rsi]",
        "mov QWORD PTR [rcx+144], rax",
        "mov rax, QWORD PTR [rsi+8]",
        "mov QWORD PTR [rcx+152], rax",
        "mov rax, QWORD PTR [rsi+16]",
        "mov QWORD PTR [rcx+160], rax",
        "mov rax, QWORD PTR [rsi+24]",
        "mov QWORD PTR [rcx+168], rax",
        "mov eax, 128",
        "mov QWORD PTR [rcx+176], rax",
        "mov eax, 0",
        "mov QWORD PTR [rcx+184], rax",
        "mov QWORD PTR [rcx+192], rax",
        "mov DWORD PTR [rcx+200], eax",
        "mov eax, 196608",
        "mov DWORD PTR [rcx+204], eax",
        "test r13, r13",
        "je 20f",
        "22:",
        "mov rax, QWORD PTR [rbx]",
        "mov QWORD PTR [rdi], rax",
        "mov rax, QWORD PTR [rbx+8]",
        "mov QWORD PTR [rdi+8], rax",
        "mov rax, QWORD PTR [rbx+16]",
        "mov QWORD PTR [rdi+16], rax",
        "mov rax, QWORD PTR [rbx+24]",
        "mov QWORD PTR [rdi+24], rax",
        "mov rsi, rcx",
        "add rsi, 144",
        "mov edx, 1",
        "call {vg_sha256_compress_shani}",
        "mov eax, DWORD PTR [rdi]",
        "bswap eax",
        "mov DWORD PTR [rcx+144], eax",
        "mov eax, DWORD PTR [rdi+4]",
        "bswap eax",
        "mov DWORD PTR [rcx+148], eax",
        "mov eax, DWORD PTR [rdi+8]",
        "bswap eax",
        "mov DWORD PTR [rcx+152], eax",
        "mov eax, DWORD PTR [rdi+12]",
        "bswap eax",
        "mov DWORD PTR [rcx+156], eax",
        "mov eax, DWORD PTR [rdi+16]",
        "bswap eax",
        "mov DWORD PTR [rcx+160], eax",
        "mov eax, DWORD PTR [rdi+20]",
        "bswap eax",
        "mov DWORD PTR [rcx+164], eax",
        "mov eax, DWORD PTR [rdi+24]",
        "bswap eax",
        "mov DWORD PTR [rcx+168], eax",
        "mov eax, DWORD PTR [rdi+28]",
        "bswap eax",
        "mov DWORD PTR [rcx+172], eax",
        "mov rax, QWORD PTR [rbx+96]",
        "mov QWORD PTR [rdi], rax",
        "mov rax, QWORD PTR [rbx+104]",
        "mov QWORD PTR [rdi+8], rax",
        "mov rax, QWORD PTR [rbx+112]",
        "mov QWORD PTR [rdi+16], rax",
        "mov rax, QWORD PTR [rbx+120]",
        "mov QWORD PTR [rdi+24], rax",
        "mov rsi, rcx",
        "add rsi, 144",
        "mov edx, 1",
        "call {vg_sha256_compress_shani}",
        "mov eax, DWORD PTR [rdi]",
        "bswap eax",
        "mov DWORD PTR [rcx+144], eax",
        "mov eax, DWORD PTR [rdi+4]",
        "bswap eax",
        "mov DWORD PTR [rcx+148], eax",
        "mov eax, DWORD PTR [rdi+8]",
        "bswap eax",
        "mov DWORD PTR [rcx+152], eax",
        "mov eax, DWORD PTR [rdi+12]",
        "bswap eax",
        "mov DWORD PTR [rcx+156], eax",
        "mov eax, DWORD PTR [rdi+16]",
        "bswap eax",
        "mov DWORD PTR [rcx+160], eax",
        "mov eax, DWORD PTR [rdi+20]",
        "bswap eax",
        "mov DWORD PTR [rcx+164], eax",
        "mov eax, DWORD PTR [rdi+24]",
        "bswap eax",
        "mov DWORD PTR [rcx+168], eax",
        "mov eax, DWORD PTR [rdi+28]",
        "bswap eax",
        "mov DWORD PTR [rcx+172], eax",
        "mov rax, QWORD PTR [rcx+144]",
        "xor rax, QWORD PTR [rbp]",
        "mov QWORD PTR [rbp], rax",
        "mov rax, QWORD PTR [rcx+152]",
        "xor rax, QWORD PTR [rbp+8]",
        "mov QWORD PTR [rbp+8], rax",
        "mov rax, QWORD PTR [rcx+160]",
        "xor rax, QWORD PTR [rbp+16]",
        "mov QWORD PTR [rbp+16], rax",
        "mov rax, QWORD PTR [rcx+168]",
        "xor rax, QWORD PTR [rbp+24]",
        "mov QWORD PTR [rbp+24], rax",
        "sub r13, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [rcx+208]",
        "mov rbp, QWORD PTR [rcx+216]",
        "mov r13, QWORD PTR [rcx+224]",
        "ret",
        vg_sha256_compress_shani = sym super::sha256::vg_sha256_compress_shani,
    )
}

/// The CPU features `vg_pbkdf2_hmac_sha256_shani` requires (`Artifact.features`).
pub(crate) const VG_PBKDF2_HMAC_SHA256_SHANI_FEATURES: &[&str] = &["sha", "ssse3"];

/// PBKDF2-HMAC-SHA-256 (RFC 8018 §5.2, with HMAC-SHA-256 as the pseudorandom function): writes the `out_len`-byte key derived from the `password_len` bytes at `password` and the `salt_len` bytes at `salt` with `c` iterations to `out`. Calls the verified SHA-256 and HMAC-SHA-256 functions and `vg_pbkdf2_hmac_sha256_iterate`.
///
/// Contract: `VG.Spec.Pbkdf2.pbkdf2Sha256Contract`. Constant time: only the pointers, the lengths and `c` may affect timing, not the password, the salt or the key.
///
/// Each 32-byte block `T_i` starts from a copy of the key's inner HMAC state that has already absorbed the salt: `vg_sha256_update` adds `INT (i)` and `vg_hmac_sha256_finalize` gives `U₁`, then `vg_pbkdf2_hmac_sha256_iterate` the other `c - 1` steps, each called with this function's suffix. A password longer than 64 bytes is hashed first.
///
/// # Safety
///
/// * `c` must be positive, and `out_len` at most `(2^32 - 1) * 32`.
/// * `password` must be valid for reads of `password_len` bytes, and `salt` for reads of `salt_len` bytes.
/// * `out` must be valid for reads and writes of `out_len` bytes.
/// * `scratch` must be valid for reads and writes of 2048 bytes; its contents on return are unspecified.
/// * `out` and `scratch` must not overlap each other, `password` or `salt` (distinct Rust objects never do).
/// * None of `password`, `salt`, `out` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `sha` and `ssse3` target features.
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha256_shani(password: *const u8, password_len: usize, salt: *const u8, salt_len: usize, c: u32, out: *mut u8, out_len: usize, scratch: *mut [u64; 256]) {
    core::arch::naked_asm!(
        "mov rax, QWORD PTR [rsp+16]",
        "mov QWORD PTR [rax+432], rbp",
        "mov QWORD PTR [rax+440], r12",
        "mov QWORD PTR [rax+448], r13",
        "mov QWORD PTR [rax+456], r14",
        "mov QWORD PTR [rax+464], r15",
        "mov QWORD PTR [rax+424], rbx",
        "mov rbx, rax",
        "mov r12, rdi",
        "mov r13, rsi",
        "mov r14, rdx",
        "mov r15, rcx",
        "mov rbp, r9",
        "mov DWORD PTR [rbx+472], r8d",
        "cmp r13, 65",
        "jb 20f",
        "mov rdi, rbx",
        "add rdi, 288",
        "call {vg_sha256_init}",
        "mov rdi, rbx",
        "add rdi, 288",
        "mov esi, 0",
        "mov rdx, r12",
        "mov rcx, r13",
        "mov r8, rbx",
        "add r8, 512",
        "call {vg_sha256_update_shani}",
        "mov rdi, rbx",
        "add rdi, 288",
        "mov rsi, r13",
        "mov rdx, rbx",
        "add rdx, 480",
        "mov rcx, rbx",
        "add rcx, 512",
        "call {vg_sha256_finalize_shani}",
        "mov r12, rbx",
        "add r12, 480",
        "mov r13d, 32",
        "jmp 21f",
        "20:",
        "21:",
        "mov rdi, rbx",
        "mov rsi, rbx",
        "add rsi, 96",
        "mov rdx, r12",
        "mov rcx, r13",
        "mov r8, rbx",
        "add r8, 512",
        "call {vg_hmac_sha256_init_shani}",
        "mov rax, QWORD PTR [rbx]",
        "mov QWORD PTR [rbx+192], rax",
        "mov rax, QWORD PTR [rbx+8]",
        "mov QWORD PTR [rbx+200], rax",
        "mov rax, QWORD PTR [rbx+16]",
        "mov QWORD PTR [rbx+208], rax",
        "mov rax, QWORD PTR [rbx+24]",
        "mov QWORD PTR [rbx+216], rax",
        "mov rax, QWORD PTR [rbx+32]",
        "mov QWORD PTR [rbx+224], rax",
        "mov rax, QWORD PTR [rbx+40]",
        "mov QWORD PTR [rbx+232], rax",
        "mov rax, QWORD PTR [rbx+48]",
        "mov QWORD PTR [rbx+240], rax",
        "mov rax, QWORD PTR [rbx+56]",
        "mov QWORD PTR [rbx+248], rax",
        "mov rax, QWORD PTR [rbx+64]",
        "mov QWORD PTR [rbx+256], rax",
        "mov rax, QWORD PTR [rbx+72]",
        "mov QWORD PTR [rbx+264], rax",
        "mov rax, QWORD PTR [rbx+80]",
        "mov QWORD PTR [rbx+272], rax",
        "mov rax, QWORD PTR [rbx+88]",
        "mov QWORD PTR [rbx+280], rax",
        "mov rdi, rbx",
        "add rdi, 192",
        "mov esi, 64",
        "mov rdx, r14",
        "mov rcx, r15",
        "mov r8, rbx",
        "add r8, 512",
        "call {vg_sha256_update_shani}",
        "add r15, 64",
        "mov r14d, DWORD PTR [rbx+472]",
        "sub r14, 1",
        "mov r12d, 1",
        "mov r13, QWORD PTR [rsp+8]",
        "test r13, r13",
        "je 22f",
        "24:",
        "mov rax, QWORD PTR [rbx+192]",
        "mov QWORD PTR [rbx+288], rax",
        "mov rax, QWORD PTR [rbx+200]",
        "mov QWORD PTR [rbx+296], rax",
        "mov rax, QWORD PTR [rbx+208]",
        "mov QWORD PTR [rbx+304], rax",
        "mov rax, QWORD PTR [rbx+216]",
        "mov QWORD PTR [rbx+312], rax",
        "mov rax, QWORD PTR [rbx+224]",
        "mov QWORD PTR [rbx+320], rax",
        "mov rax, QWORD PTR [rbx+232]",
        "mov QWORD PTR [rbx+328], rax",
        "mov rax, QWORD PTR [rbx+240]",
        "mov QWORD PTR [rbx+336], rax",
        "mov rax, QWORD PTR [rbx+248]",
        "mov QWORD PTR [rbx+344], rax",
        "mov rax, QWORD PTR [rbx+256]",
        "mov QWORD PTR [rbx+352], rax",
        "mov rax, QWORD PTR [rbx+264]",
        "mov QWORD PTR [rbx+360], rax",
        "mov rax, QWORD PTR [rbx+272]",
        "mov QWORD PTR [rbx+368], rax",
        "mov rax, QWORD PTR [rbx+280]",
        "mov QWORD PTR [rbx+376], rax",
        "mov eax, r12d",
        "bswap eax",
        "mov DWORD PTR [rbx+416], eax",
        "mov rdi, rbx",
        "add rdi, 288",
        "mov rsi, r15",
        "mov rdx, rbx",
        "add rdx, 416",
        "mov ecx, 4",
        "mov r8, rbx",
        "add r8, 512",
        "call {vg_sha256_update_shani}",
        "mov rdi, rbx",
        "add rdi, 288",
        "mov rsi, rbx",
        "add rsi, 96",
        "mov rdx, r15",
        "add rdx, 4",
        "mov rcx, rbx",
        "add rcx, 896",
        "call {vg_hmac_sha256_finalize_shani}",
        "mov rax, QWORD PTR [rbx+1072]",
        "mov QWORD PTR [rbx+384], rax",
        "mov rax, QWORD PTR [rbx+1080]",
        "mov QWORD PTR [rbx+392], rax",
        "mov rax, QWORD PTR [rbx+1088]",
        "mov QWORD PTR [rbx+400], rax",
        "mov rax, QWORD PTR [rbx+1096]",
        "mov QWORD PTR [rbx+408], rax",
        "mov rdi, rbx",
        "mov rsi, rbx",
        "add rsi, 1072",
        "mov edx, r14d",
        "mov rcx, rbx",
        "add rcx, 384",
        "mov r8, rbx",
        "add r8, 512",
        "call {vg_pbkdf2_hmac_sha256_iterate_shani}",
        "mov ecx, 32",
        "cmp r13, 32",
        "jb 25f",
        "jmp 26f",
        "25:",
        "mov rcx, r13",
        "26:",
        "sub r13, rcx",
        "mov rdi, rbx",
        "add rdi, 384",
        "mov rsi, rbp",
        "27:",
        "movzx eax, BYTE PTR [rdi]",
        "mov BYTE PTR [rsi], al",
        "add rdi, 1",
        "add rsi, 1",
        "sub rcx, 1",
        "jne 27b",
        "mov rbp, rsi",
        "add r12, 1",
        "test r13, r13",
        "jne 24b",
        "jmp 23f",
        "22:",
        "23:",
        "mov rbp, QWORD PTR [rbx+432]",
        "mov r12, QWORD PTR [rbx+440]",
        "mov r13, QWORD PTR [rbx+448]",
        "mov r14, QWORD PTR [rbx+456]",
        "mov r15, QWORD PTR [rbx+464]",
        "mov rbx, QWORD PTR [rbx+424]",
        "ret",
        vg_sha256_init = sym super::sha256::vg_sha256_init,
        vg_sha256_update_shani = sym super::sha256::vg_sha256_update_shani,
        vg_sha256_finalize_shani = sym super::sha256::vg_sha256_finalize_shani,
        vg_hmac_sha256_init_shani = sym super::hmac_sha256::vg_hmac_sha256_init_shani,
        vg_hmac_sha256_finalize_shani = sym super::hmac_sha256::vg_hmac_sha256_finalize_shani,
        vg_pbkdf2_hmac_sha256_iterate_shani = sym super::pbkdf2_sha256::vg_pbkdf2_hmac_sha256_iterate_shani,
    )
}
