// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `pbkdf2_sha256` functions for `x86_64`.
#![allow(dead_code)]

/// Runs `n` steps of PBKDF2-HMAC-SHA-256's iteration: if, for a 64-byte key `K₀`, the SHA-256 streaming state in bytes 0 to 95 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 96 to 191 represents `K₀ ⊕ opad` (as `vg_hmac_sha256_init` leaves them), repeats `U ← HMAC-SHA-256 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Pbkdf2.iterateSha256Contract`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 192 bytes, and `u` for reads of 32 bytes.
/// * `t` must be valid for reads and writes of 32 bytes.
/// * `scratch` must be valid for reads and writes of 384 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u` (distinct Rust objects never do).
/// * None of `key`, `u`, `t` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha256_iterate(key: *const [u8; 192], u: *const [u8; 32], n: u32, t: *mut [u8; 32], scratch: *mut [u64; 48]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+208], rbx",
        "mov QWORD PTR [r8+216], rbp",
        "mov QWORD PTR [r8+224], r13",
        "mov r13d, edx",
        "mov rbx, rdi",
        "mov rbp, rcx",
        "mov rcx, r8",
        "mov rdi, r8",
        "add rdi, 112",
        "mov rax, QWORD PTR [rsi]",
        "mov QWORD PTR [rcx+144], rax",
        "mov rax, QWORD PTR [rsi+8]",
        "mov QWORD PTR [rcx+152], rax",
        "mov rax, QWORD PTR [rsi+16]",
        "mov QWORD PTR [rcx+160], rax",
        "mov rax, QWORD PTR [rsi+24]",
        "mov QWORD PTR [rcx+168], rax",
        "mov eax, 128",
        "mov QWORD PTR [rcx+176], rax",
        "mov eax, 0",
        "mov QWORD PTR [rcx+184], rax",
        "mov QWORD PTR [rcx+192], rax",
        "mov DWORD PTR [rcx+200], eax",
        "mov eax, 196608",
        "mov DWORD PTR [rcx+204], eax",
        "test r13, r13",
        "je 20f",
        "22:",
        "mov rax, QWORD PTR [rbx]",
        "mov QWORD PTR [rdi], rax",
        "mov rax, QWORD PTR [rbx+8]",
        "mov QWORD PTR [rdi+8], rax",
        "mov rax, QWORD PTR [rbx+16]",
        "mov QWORD PTR [rdi+16], rax",
        "mov rax, QWORD PTR [rbx+24]",
        "mov QWORD PTR [rdi+24], rax",
        "mov rsi, rcx",
        "add rsi, 144",
        "mov edx, 1",
        "call {vg_sha256_compress}",
        "mov eax, DWORD PTR [rdi]",
        "bswap eax",
        "mov DWORD PTR [rcx+144], eax",
        "mov eax, DWORD PTR [rdi+4]",
        "bswap eax",
        "mov DWORD PTR [rcx+148], eax",
        "mov eax, DWORD PTR [rdi+8]",
        "bswap eax",
        "mov DWORD PTR [rcx+152], eax",
        "mov eax, DWORD PTR [rdi+12]",
        "bswap eax",
        "mov DWORD PTR [rcx+156], eax",
        "mov eax, DWORD PTR [rdi+16]",
        "bswap eax",
        "mov DWORD PTR [rcx+160], eax",
        "mov eax, DWORD PTR [rdi+20]",
        "bswap eax",
        "mov DWORD PTR [rcx+164], eax",
        "mov eax, DWORD PTR [rdi+24]",
        "bswap eax",
        "mov DWORD PTR [rcx+168], eax",
        "mov eax, DWORD PTR [rdi+28]",
        "bswap eax",
        "mov DWORD PTR [rcx+172], eax",
        "mov rax, QWORD PTR [rbx+96]",
        "mov QWORD PTR [rdi], rax",
        "mov rax, QWORD PTR [rbx+104]",
        "mov QWORD PTR [rdi+8], rax",
        "mov rax, QWORD PTR [rbx+112]",
        "mov QWORD PTR [rdi+16], rax",
        "mov rax, QWORD PTR [rbx+120]",
        "mov QWORD PTR [rdi+24], rax",
        "mov rsi, rcx",
        "add rsi, 144",
        "mov edx, 1",
        "call {vg_sha256_compress}",
        "mov eax, DWORD PTR [rdi]",
        "bswap eax",
        "mov DWORD PTR [rcx+144], eax",
        "mov eax, DWORD PTR [rdi+4]",
        "bswap eax",
        "mov DWORD PTR [rcx+148], eax",
        "mov eax, DWORD PTR [rdi+8]",
        "bswap eax",
        "mov DWORD PTR [rcx+152], eax",
        "mov eax, DWORD PTR [rdi+12]",
        "bswap eax",
        "mov DWORD PTR [rcx+156], eax",
        "mov eax, DWORD PTR [rdi+16]",
        "bswap eax",
        "mov DWORD PTR [rcx+160], eax",
        "mov eax, DWORD PTR [rdi+20]",
        "bswap eax",
        "mov DWORD PTR [rcx+164], eax",
        "mov eax, DWORD PTR [rdi+24]",
        "bswap eax",
        "mov DWORD PTR [rcx+168], eax",
        "mov eax, DWORD PTR [rdi+28]",
        "bswap eax",
        "mov DWORD PTR [rcx+172], eax",
        "mov rax, QWORD PTR [rcx+144]",
        "xor rax, QWORD PTR [rbp]",
        "mov QWORD PTR [rbp], rax",
        "mov rax, QWORD PTR [rcx+152]",
        "xor rax, QWORD PTR [rbp+8]",
        "mov QWORD PTR [rbp+8], rax",
        "mov rax, QWORD PTR [rcx+160]",
        "xor rax, QWORD PTR [rbp+16]",
        "mov QWORD PTR [rbp+16], rax",
        "mov rax, QWORD PTR [rcx+168]",
        "xor rax, QWORD PTR [rbp+24]",
        "mov QWORD PTR [rbp+24], rax",
        "sub r13, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [rcx+208]",
        "mov rbp, QWORD PTR [rcx+216]",
        "mov r13, QWORD PTR [rcx+224]",
        "ret",
        vg_sha256_compress = sym super::sha256::vg_sha256_compress,
    )
}

/// The CPU features `vg_pbkdf2_hmac_sha256_iterate_shani` requires (`Artifact.features`).
pub(crate) const VG_PBKDF2_HMAC_SHA256_ITERATE_SHANI_FEATURES: &[&str] = &["sha", "ssse3"];

/// Runs `n` steps of PBKDF2-HMAC-SHA-256's iteration: if, for a 64-byte key `K₀`, the SHA-256 streaming state in bytes 0 to 95 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 96 to 191 represents `K₀ ⊕ opad` (as `vg_hmac_sha256_init` leaves them), repeats `U ← HMAC-SHA-256 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Pbkdf2.iterateSha256Contract`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 192 bytes, and `u` for reads of 32 bytes.
/// * `t` must be valid for reads and writes of 32 bytes.
/// * `scratch` must be valid for reads and writes of 384 bytes; its contents on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u` (distinct Rust objects never do).
/// * None of `key`, `u`, `t` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `sha` and `ssse3` target features.
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha256_iterate_shani(key: *const [u8; 192], u: *const [u8; 32], n: u32, t: *mut [u8; 32], scratch: *mut [u64; 48]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+208], rbx",
        "mov QWORD PTR [r8+216], rbp",
        "mov QWORD PTR [r8+224], r13",
        "mov r13d, edx",
        "mov rbx, rdi",
        "mov rbp, rcx",
        "mov rcx, r8",
        "mov rdi, r8",
        "add rdi, 112",
        "mov rax, QWORD PTR [rsi]",
        "mov QWORD PTR [rcx+144], rax",
        "mov rax, QWORD PTR [rsi+8]",
        "mov QWORD PTR [rcx+152], rax",
        "mov rax, QWORD PTR [rsi+16]",
        "mov QWORD PTR [rcx+160], rax",
        "mov rax, QWORD PTR [rsi+24]",
        "mov QWORD PTR [rcx+168], rax",
        "mov eax, 128",
        "mov QWORD PTR [rcx+176], rax",
        "mov eax, 0",
        "mov QWORD PTR [rcx+184], rax",
        "mov QWORD PTR [rcx+192], rax",
        "mov DWORD PTR [rcx+200], eax",
        "mov eax, 196608",
        "mov DWORD PTR [rcx+204], eax",
        "test r13, r13",
        "je 20f",
        "22:",
        "mov rax, QWORD PTR [rbx]",
        "mov QWORD PTR [rdi], rax",
        "mov rax, QWORD PTR [rbx+8]",
        "mov QWORD PTR [rdi+8], rax",
        "mov rax, QWORD PTR [rbx+16]",
        "mov QWORD PTR [rdi+16], rax",
        "mov rax, QWORD PTR [rbx+24]",
        "mov QWORD PTR [rdi+24], rax",
        "mov rsi, rcx",
        "add rsi, 144",
        "mov edx, 1",
        "call {vg_sha256_compress_shani}",
        "mov eax, DWORD PTR [rdi]",
        "bswap eax",
        "mov DWORD PTR [rcx+144], eax",
        "mov eax, DWORD PTR [rdi+4]",
        "bswap eax",
        "mov DWORD PTR [rcx+148], eax",
        "mov eax, DWORD PTR [rdi+8]",
        "bswap eax",
        "mov DWORD PTR [rcx+152], eax",
        "mov eax, DWORD PTR [rdi+12]",
        "bswap eax",
        "mov DWORD PTR [rcx+156], eax",
        "mov eax, DWORD PTR [rdi+16]",
        "bswap eax",
        "mov DWORD PTR [rcx+160], eax",
        "mov eax, DWORD PTR [rdi+20]",
        "bswap eax",
        "mov DWORD PTR [rcx+164], eax",
        "mov eax, DWORD PTR [rdi+24]",
        "bswap eax",
        "mov DWORD PTR [rcx+168], eax",
        "mov eax, DWORD PTR [rdi+28]",
        "bswap eax",
        "mov DWORD PTR [rcx+172], eax",
        "mov rax, QWORD PTR [rbx+96]",
        "mov QWORD PTR [rdi], rax",
        "mov rax, QWORD PTR [rbx+104]",
        "mov QWORD PTR [rdi+8], rax",
        "mov rax, QWORD PTR [rbx+112]",
        "mov QWORD PTR [rdi+16], rax",
        "mov rax, QWORD PTR [rbx+120]",
        "mov QWORD PTR [rdi+24], rax",
        "mov rsi, rcx",
        "add rsi, 144",
        "mov edx, 1",
        "call {vg_sha256_compress_shani}",
        "mov eax, DWORD PTR [rdi]",
        "bswap eax",
        "mov DWORD PTR [rcx+144], eax",
        "mov eax, DWORD PTR [rdi+4]",
        "bswap eax",
        "mov DWORD PTR [rcx+148], eax",
        "mov eax, DWORD PTR [rdi+8]",
        "bswap eax",
        "mov DWORD PTR [rcx+152], eax",
        "mov eax, DWORD PTR [rdi+12]",
        "bswap eax",
        "mov DWORD PTR [rcx+156], eax",
        "mov eax, DWORD PTR [rdi+16]",
        "bswap eax",
        "mov DWORD PTR [rcx+160], eax",
        "mov eax, DWORD PTR [rdi+20]",
        "bswap eax",
        "mov DWORD PTR [rcx+164], eax",
        "mov eax, DWORD PTR [rdi+24]",
        "bswap eax",
        "mov DWORD PTR [rcx+168], eax",
        "mov eax, DWORD PTR [rdi+28]",
        "bswap eax",
        "mov DWORD PTR [rcx+172], eax",
        "mov rax, QWORD PTR [rcx+144]",
        "xor rax, QWORD PTR [rbp]",
        "mov QWORD PTR [rbp], rax",
        "mov rax, QWORD PTR [rcx+152]",
        "xor rax, QWORD PTR [rbp+8]",
        "mov QWORD PTR [rbp+8], rax",
        "mov rax, QWORD PTR [rcx+160]",
        "xor rax, QWORD PTR [rbp+16]",
        "mov QWORD PTR [rbp+16], rax",
        "mov rax, QWORD PTR [rcx+168]",
        "xor rax, QWORD PTR [rbp+24]",
        "mov QWORD PTR [rbp+24], rax",
        "sub r13, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [rcx+208]",
        "mov rbp, QWORD PTR [rcx+216]",
        "mov r13, QWORD PTR [rcx+224]",
        "ret",
        vg_sha256_compress_shani = sym super::sha256::vg_sha256_compress_shani,
    )
}
