// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `pbkdf2_sha1` functions for `x86_64`.
#![allow(dead_code)]

/// Runs `n` steps of PBKDF2-HMAC-SHA-1's iteration: if, for a 64-byte key `K₀`, the SHA-1 streaming state in bytes 0 to 83 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 84 to 167 represents `K₀ ⊕ opad` (as `vg_hmac_sha1_init` leaves them), repeats `U ← HMAC-SHA-1 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.sha1I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 168 bytes.
/// * `u` must be valid for reads of 20 bytes.
/// * `t` must be valid for reads and writes of 20 bytes.
/// * `scratch` must be valid for reads and writes of 448 bytes.
/// * The contents of `scratch` on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u` (distinct Rust objects never do).
/// * None of `key`, `u`, `t` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha1_iterate(key: *const [u8; 168], u: *const [u8; 20], n: u32, t: *mut [u8; 20], scratch: *mut [u64; 56]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+112], rbx",
        "mov QWORD PTR [r8+120], rbp",
        "mov QWORD PTR [r8+128], r12",
        "mov QWORD PTR [r8+136], r13",
        "mov QWORD PTR [r8+144], r14",
        "mov QWORD PTR [r8+152], r15",
        "mov r15, r8",
        "mov r12, rdi",
        "mov r13, rcx",
        "mov r14d, edx",
        "mov rbx, r8",
        "add rbx, 160",
        "mov rbp, r8",
        "add rbp, 180",
        "mov eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rbp], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rbp+4], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rbp+8], eax",
        "mov eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rbp+12], eax",
        "mov eax, DWORD PTR [rsi+16]",
        "mov DWORD PTR [rbp+16], eax",
        "mov eax, 128",
        "mov DWORD PTR [rbp+20], eax",
        "mov eax, 0",
        "mov DWORD PTR [rbp+24], eax",
        "mov DWORD PTR [rbp+28], eax",
        "mov DWORD PTR [rbp+32], eax",
        "mov DWORD PTR [rbp+36], eax",
        "mov DWORD PTR [rbp+40], eax",
        "mov DWORD PTR [rbp+44], eax",
        "mov DWORD PTR [rbp+48], eax",
        "mov DWORD PTR [rbp+52], eax",
        "mov r12d, 84",
        "mov rax, r12",
        "add rax, rax",
        "add rax, rax",
        "add rax, rax",
        "bswap rax",
        "mov QWORD PTR [rbx+76], rax",
        "mov r12, rdi",
        "test r14, r14",
        "je 20f",
        "22:",
        "mov eax, DWORD PTR [r12]",
        "mov DWORD PTR [rbx], eax",
        "mov eax, DWORD PTR [r12+4]",
        "mov DWORD PTR [rbx+4], eax",
        "mov eax, DWORD PTR [r12+8]",
        "mov DWORD PTR [rbx+8], eax",
        "mov eax, DWORD PTR [r12+12]",
        "mov DWORD PTR [rbx+12], eax",
        "mov eax, DWORD PTR [r12+16]",
        "mov DWORD PTR [rbx+16], eax",
        "mov rsi, rbp",
        "mov rdi, rbx",
        "mov edx, 1",
        "mov rcx, r15",
        "call {vg_sha1_compress}",
        "mov rbx, rdi",
        "mov r15, rcx",
        "mov eax, DWORD PTR [rbx]",
        "bswap eax",
        "mov DWORD PTR [rbp], eax",
        "mov eax, DWORD PTR [rbx+4]",
        "bswap eax",
        "mov DWORD PTR [rbp+4], eax",
        "mov eax, DWORD PTR [rbx+8]",
        "bswap eax",
        "mov DWORD PTR [rbp+8], eax",
        "mov eax, DWORD PTR [rbx+12]",
        "bswap eax",
        "mov DWORD PTR [rbp+12], eax",
        "mov eax, DWORD PTR [rbx+16]",
        "bswap eax",
        "mov DWORD PTR [rbp+16], eax",
        "mov eax, DWORD PTR [r12+84]",
        "mov DWORD PTR [rbx], eax",
        "mov eax, DWORD PTR [r12+88]",
        "mov DWORD PTR [rbx+4], eax",
        "mov eax, DWORD PTR [r12+92]",
        "mov DWORD PTR [rbx+8], eax",
        "mov eax, DWORD PTR [r12+96]",
        "mov DWORD PTR [rbx+12], eax",
        "mov eax, DWORD PTR [r12+100]",
        "mov DWORD PTR [rbx+16], eax",
        "mov rsi, rbp",
        "mov rdi, rbx",
        "mov edx, 1",
        "mov rcx, r15",
        "call {vg_sha1_compress}",
        "mov rbx, rdi",
        "mov r15, rcx",
        "mov eax, DWORD PTR [rbx]",
        "bswap eax",
        "mov DWORD PTR [rbp], eax",
        "mov eax, DWORD PTR [rbx+4]",
        "bswap eax",
        "mov DWORD PTR [rbp+4], eax",
        "mov eax, DWORD PTR [rbx+8]",
        "bswap eax",
        "mov DWORD PTR [rbp+8], eax",
        "mov eax, DWORD PTR [rbx+12]",
        "bswap eax",
        "mov DWORD PTR [rbp+12], eax",
        "mov eax, DWORD PTR [rbx+16]",
        "bswap eax",
        "mov DWORD PTR [rbp+16], eax",
        "mov eax, DWORD PTR [rbp]",
        "xor eax, DWORD PTR [r13]",
        "mov DWORD PTR [r13], eax",
        "mov eax, DWORD PTR [rbp+4]",
        "xor eax, DWORD PTR [r13+4]",
        "mov DWORD PTR [r13+4], eax",
        "mov eax, DWORD PTR [rbp+8]",
        "xor eax, DWORD PTR [r13+8]",
        "mov DWORD PTR [r13+8], eax",
        "mov eax, DWORD PTR [rbp+12]",
        "xor eax, DWORD PTR [r13+12]",
        "mov DWORD PTR [r13+12], eax",
        "mov eax, DWORD PTR [rbp+16]",
        "xor eax, DWORD PTR [r13+16]",
        "mov DWORD PTR [r13+16], eax",
        "sub r14, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r15+112]",
        "mov rbp, QWORD PTR [r15+120]",
        "mov r12, QWORD PTR [r15+128]",
        "mov r13, QWORD PTR [r15+136]",
        "mov r14, QWORD PTR [r15+144]",
        "mov r15, QWORD PTR [r15+152]",
        "ret",
        vg_sha1_compress = sym super::sha1::vg_sha1_compress,
    )
}

/// The CPU features `vg_pbkdf2_hmac_sha1_iterate_shani` requires (`Artifact.features`).
pub(crate) const VG_PBKDF2_HMAC_SHA1_ITERATE_SHANI_FEATURES: &[&str] = &["sha", "ssse3"];

/// Runs `n` steps of PBKDF2-HMAC-SHA-1's iteration: if, for a 64-byte key `K₀`, the SHA-1 streaming state in bytes 0 to 83 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 84 to 167 represents `K₀ ⊕ opad` (as `vg_hmac_sha1_init` leaves them), repeats `U ← HMAC-SHA-1 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.sha1I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 168 bytes.
/// * `u` must be valid for reads of 20 bytes.
/// * `t` must be valid for reads and writes of 20 bytes.
/// * `scratch` must be valid for reads and writes of 448 bytes.
/// * The contents of `scratch` on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u` (distinct Rust objects never do).
/// * None of `key`, `u`, `t` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `sha` and `ssse3` target features.
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha1_iterate_shani(key: *const [u8; 168], u: *const [u8; 20], n: u32, t: *mut [u8; 20], scratch: *mut [u64; 56]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+112], rbx",
        "mov QWORD PTR [r8+120], rbp",
        "mov QWORD PTR [r8+128], r12",
        "mov QWORD PTR [r8+136], r13",
        "mov QWORD PTR [r8+144], r14",
        "mov QWORD PTR [r8+152], r15",
        "mov r15, r8",
        "mov r12, rdi",
        "mov r13, rcx",
        "mov r14d, edx",
        "mov rbx, r8",
        "add rbx, 160",
        "mov rbp, r8",
        "add rbp, 180",
        "mov eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rbp], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rbp+4], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rbp+8], eax",
        "mov eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rbp+12], eax",
        "mov eax, DWORD PTR [rsi+16]",
        "mov DWORD PTR [rbp+16], eax",
        "mov eax, 128",
        "mov DWORD PTR [rbp+20], eax",
        "mov eax, 0",
        "mov DWORD PTR [rbp+24], eax",
        "mov DWORD PTR [rbp+28], eax",
        "mov DWORD PTR [rbp+32], eax",
        "mov DWORD PTR [rbp+36], eax",
        "mov DWORD PTR [rbp+40], eax",
        "mov DWORD PTR [rbp+44], eax",
        "mov DWORD PTR [rbp+48], eax",
        "mov DWORD PTR [rbp+52], eax",
        "mov r12d, 84",
        "mov rax, r12",
        "add rax, rax",
        "add rax, rax",
        "add rax, rax",
        "bswap rax",
        "mov QWORD PTR [rbx+76], rax",
        "mov r12, rdi",
        "test r14, r14",
        "je 20f",
        "22:",
        "mov eax, DWORD PTR [r12]",
        "mov DWORD PTR [rbx], eax",
        "mov eax, DWORD PTR [r12+4]",
        "mov DWORD PTR [rbx+4], eax",
        "mov eax, DWORD PTR [r12+8]",
        "mov DWORD PTR [rbx+8], eax",
        "mov eax, DWORD PTR [r12+12]",
        "mov DWORD PTR [rbx+12], eax",
        "mov eax, DWORD PTR [r12+16]",
        "mov DWORD PTR [rbx+16], eax",
        "mov rsi, rbp",
        "mov rdi, rbx",
        "mov edx, 1",
        "mov rcx, r15",
        "call {vg_sha1_compress_shani}",
        "mov rbx, rdi",
        "mov r15, rcx",
        "mov eax, DWORD PTR [rbx]",
        "bswap eax",
        "mov DWORD PTR [rbp], eax",
        "mov eax, DWORD PTR [rbx+4]",
        "bswap eax",
        "mov DWORD PTR [rbp+4], eax",
        "mov eax, DWORD PTR [rbx+8]",
        "bswap eax",
        "mov DWORD PTR [rbp+8], eax",
        "mov eax, DWORD PTR [rbx+12]",
        "bswap eax",
        "mov DWORD PTR [rbp+12], eax",
        "mov eax, DWORD PTR [rbx+16]",
        "bswap eax",
        "mov DWORD PTR [rbp+16], eax",
        "mov eax, DWORD PTR [r12+84]",
        "mov DWORD PTR [rbx], eax",
        "mov eax, DWORD PTR [r12+88]",
        "mov DWORD PTR [rbx+4], eax",
        "mov eax, DWORD PTR [r12+92]",
        "mov DWORD PTR [rbx+8], eax",
        "mov eax, DWORD PTR [r12+96]",
        "mov DWORD PTR [rbx+12], eax",
        "mov eax, DWORD PTR [r12+100]",
        "mov DWORD PTR [rbx+16], eax",
        "mov rsi, rbp",
        "mov rdi, rbx",
        "mov edx, 1",
        "mov rcx, r15",
        "call {vg_sha1_compress_shani}",
        "mov rbx, rdi",
        "mov r15, rcx",
        "mov eax, DWORD PTR [rbx]",
        "bswap eax",
        "mov DWORD PTR [rbp], eax",
        "mov eax, DWORD PTR [rbx+4]",
        "bswap eax",
        "mov DWORD PTR [rbp+4], eax",
        "mov eax, DWORD PTR [rbx+8]",
        "bswap eax",
        "mov DWORD PTR [rbp+8], eax",
        "mov eax, DWORD PTR [rbx+12]",
        "bswap eax",
        "mov DWORD PTR [rbp+12], eax",
        "mov eax, DWORD PTR [rbx+16]",
        "bswap eax",
        "mov DWORD PTR [rbp+16], eax",
        "mov eax, DWORD PTR [rbp]",
        "xor eax, DWORD PTR [r13]",
        "mov DWORD PTR [r13], eax",
        "mov eax, DWORD PTR [rbp+4]",
        "xor eax, DWORD PTR [r13+4]",
        "mov DWORD PTR [r13+4], eax",
        "mov eax, DWORD PTR [rbp+8]",
        "xor eax, DWORD PTR [r13+8]",
        "mov DWORD PTR [r13+8], eax",
        "mov eax, DWORD PTR [rbp+12]",
        "xor eax, DWORD PTR [r13+12]",
        "mov DWORD PTR [r13+12], eax",
        "mov eax, DWORD PTR [rbp+16]",
        "xor eax, DWORD PTR [r13+16]",
        "mov DWORD PTR [r13+16], eax",
        "sub r14, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r15+112]",
        "mov rbp, QWORD PTR [r15+120]",
        "mov r12, QWORD PTR [r15+128]",
        "mov r13, QWORD PTR [r15+136]",
        "mov r14, QWORD PTR [r15+144]",
        "mov r15, QWORD PTR [r15+152]",
        "ret",
        vg_sha1_compress_shani = sym super::sha1::vg_sha1_compress_shani,
    )
}
