// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `pbkdf2_sha512` functions for `x86_64`.
#![allow(dead_code)]

/// Runs `n` steps of PBKDF2-HMAC-SHA-512's iteration: if, for a 128-byte key `K₀`, the SHA-512 streaming state in bytes 0 to 191 of `*key` represents `K₀ ⊕ ipad` and the one in bytes 192 to 383 represents `K₀ ⊕ opad` (as `vg_hmac_sha512_init` leaves them), repeats `U ← HMAC-SHA-512 (K₀, U)`, `T ← T ⊕ U` `n` times, from `U = *u` and `T = *t`, and leaves the final `T` in `*t` (RFC 8018, step 3 of `F`).
///
/// Contract: `VG.Spec.Hmac.Instance.iterateContract` of `VG.Spec.Hmac.sha512I`. Constant time: only the pointers and `n` may affect timing, not the key, `U` or `T`.
///
/// # Safety
///
/// * `key` must be valid for reads of 384 bytes.
/// * `u` must be valid for reads of 64 bytes.
/// * `t` must be valid for reads and writes of 64 bytes.
/// * `scratch` must be valid for reads and writes of 1872 bytes.
/// * The contents of `scratch` on return are unspecified.
/// * `t` and `scratch` must not overlap each other, `key` or `u` (distinct Rust objects never do).
/// * None of `key`, `u`, `t` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_pbkdf2_hmac_sha512_iterate(key: *const [u8; 384], u: *const [u8; 64], n: u32, t: *mut [u8; 64], scratch: *mut [u64; 234]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+176], rbx",
        "mov QWORD PTR [r8+184], rbp",
        "mov QWORD PTR [r8+192], r12",
        "mov QWORD PTR [r8+200], r13",
        "mov QWORD PTR [r8+208], r14",
        "mov QWORD PTR [r8+216], r15",
        "mov r15, r8",
        "mov r12, rdi",
        "mov r13, rcx",
        "mov r14d, edx",
        "mov rbx, r8",
        "add rbx, 224",
        "mov rbp, r8",
        "add rbp, 288",
        "mov eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rbp], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rbp+4], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rbp+8], eax",
        "mov eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rbp+12], eax",
        "mov eax, DWORD PTR [rsi+16]",
        "mov DWORD PTR [rbp+16], eax",
        "mov eax, DWORD PTR [rsi+20]",
        "mov DWORD PTR [rbp+20], eax",
        "mov eax, DWORD PTR [rsi+24]",
        "mov DWORD PTR [rbp+24], eax",
        "mov eax, DWORD PTR [rsi+28]",
        "mov DWORD PTR [rbp+28], eax",
        "mov eax, DWORD PTR [rsi+32]",
        "mov DWORD PTR [rbp+32], eax",
        "mov eax, DWORD PTR [rsi+36]",
        "mov DWORD PTR [rbp+36], eax",
        "mov eax, DWORD PTR [rsi+40]",
        "mov DWORD PTR [rbp+40], eax",
        "mov eax, DWORD PTR [rsi+44]",
        "mov DWORD PTR [rbp+44], eax",
        "mov eax, DWORD PTR [rsi+48]",
        "mov DWORD PTR [rbp+48], eax",
        "mov eax, DWORD PTR [rsi+52]",
        "mov DWORD PTR [rbp+52], eax",
        "mov eax, DWORD PTR [rsi+56]",
        "mov DWORD PTR [rbp+56], eax",
        "mov eax, DWORD PTR [rsi+60]",
        "mov DWORD PTR [rbp+60], eax",
        "mov eax, 128",
        "mov DWORD PTR [rbp+64], eax",
        "mov eax, 0",
        "mov DWORD PTR [rbp+68], eax",
        "mov DWORD PTR [rbp+72], eax",
        "mov DWORD PTR [rbp+76], eax",
        "mov DWORD PTR [rbp+80], eax",
        "mov DWORD PTR [rbp+84], eax",
        "mov DWORD PTR [rbp+88], eax",
        "mov DWORD PTR [rbp+92], eax",
        "mov DWORD PTR [rbp+96], eax",
        "mov DWORD PTR [rbp+100], eax",
        "mov DWORD PTR [rbp+104], eax",
        "mov DWORD PTR [rbp+108], eax",
        "mov r12d, 192",
        "mov rax, r12",
        "shr rax, 61",
        "bswap rax",
        "mov QWORD PTR [rbx+176], rax",
        "mov rax, r12",
        "add rax, rax",
        "add rax, rax",
        "add rax, rax",
        "bswap rax",
        "mov QWORD PTR [rbx+184], rax",
        "mov r12, rdi",
        "test r14, r14",
        "je 20f",
        "22:",
        "mov eax, DWORD PTR [r12]",
        "mov DWORD PTR [rbx], eax",
        "mov eax, DWORD PTR [r12+4]",
        "mov DWORD PTR [rbx+4], eax",
        "mov eax, DWORD PTR [r12+8]",
        "mov DWORD PTR [rbx+8], eax",
        "mov eax, DWORD PTR [r12+12]",
        "mov DWORD PTR [rbx+12], eax",
        "mov eax, DWORD PTR [r12+16]",
        "mov DWORD PTR [rbx+16], eax",
        "mov eax, DWORD PTR [r12+20]",
        "mov DWORD PTR [rbx+20], eax",
        "mov eax, DWORD PTR [r12+24]",
        "mov DWORD PTR [rbx+24], eax",
        "mov eax, DWORD PTR [r12+28]",
        "mov DWORD PTR [rbx+28], eax",
        "mov eax, DWORD PTR [r12+32]",
        "mov DWORD PTR [rbx+32], eax",
        "mov eax, DWORD PTR [r12+36]",
        "mov DWORD PTR [rbx+36], eax",
        "mov eax, DWORD PTR [r12+40]",
        "mov DWORD PTR [rbx+40], eax",
        "mov eax, DWORD PTR [r12+44]",
        "mov DWORD PTR [rbx+44], eax",
        "mov eax, DWORD PTR [r12+48]",
        "mov DWORD PTR [rbx+48], eax",
        "mov eax, DWORD PTR [r12+52]",
        "mov DWORD PTR [rbx+52], eax",
        "mov eax, DWORD PTR [r12+56]",
        "mov DWORD PTR [rbx+56], eax",
        "mov eax, DWORD PTR [r12+60]",
        "mov DWORD PTR [rbx+60], eax",
        "mov rsi, rbp",
        "mov rdi, rbx",
        "mov edx, 1",
        "mov rcx, r15",
        "call {vg_sha512_compress}",
        "mov rbx, rdi",
        "mov r15, rcx",
        "mov rax, QWORD PTR [rbx]",
        "bswap rax",
        "mov QWORD PTR [rbp], rax",
        "mov rax, QWORD PTR [rbx+8]",
        "bswap rax",
        "mov QWORD PTR [rbp+8], rax",
        "mov rax, QWORD PTR [rbx+16]",
        "bswap rax",
        "mov QWORD PTR [rbp+16], rax",
        "mov rax, QWORD PTR [rbx+24]",
        "bswap rax",
        "mov QWORD PTR [rbp+24], rax",
        "mov rax, QWORD PTR [rbx+32]",
        "bswap rax",
        "mov QWORD PTR [rbp+32], rax",
        "mov rax, QWORD PTR [rbx+40]",
        "bswap rax",
        "mov QWORD PTR [rbp+40], rax",
        "mov rax, QWORD PTR [rbx+48]",
        "bswap rax",
        "mov QWORD PTR [rbp+48], rax",
        "mov rax, QWORD PTR [rbx+56]",
        "bswap rax",
        "mov QWORD PTR [rbp+56], rax",
        "mov eax, DWORD PTR [r12+192]",
        "mov DWORD PTR [rbx], eax",
        "mov eax, DWORD PTR [r12+196]",
        "mov DWORD PTR [rbx+4], eax",
        "mov eax, DWORD PTR [r12+200]",
        "mov DWORD PTR [rbx+8], eax",
        "mov eax, DWORD PTR [r12+204]",
        "mov DWORD PTR [rbx+12], eax",
        "mov eax, DWORD PTR [r12+208]",
        "mov DWORD PTR [rbx+16], eax",
        "mov eax, DWORD PTR [r12+212]",
        "mov DWORD PTR [rbx+20], eax",
        "mov eax, DWORD PTR [r12+216]",
        "mov DWORD PTR [rbx+24], eax",
        "mov eax, DWORD PTR [r12+220]",
        "mov DWORD PTR [rbx+28], eax",
        "mov eax, DWORD PTR [r12+224]",
        "mov DWORD PTR [rbx+32], eax",
        "mov eax, DWORD PTR [r12+228]",
        "mov DWORD PTR [rbx+36], eax",
        "mov eax, DWORD PTR [r12+232]",
        "mov DWORD PTR [rbx+40], eax",
        "mov eax, DWORD PTR [r12+236]",
        "mov DWORD PTR [rbx+44], eax",
        "mov eax, DWORD PTR [r12+240]",
        "mov DWORD PTR [rbx+48], eax",
        "mov eax, DWORD PTR [r12+244]",
        "mov DWORD PTR [rbx+52], eax",
        "mov eax, DWORD PTR [r12+248]",
        "mov DWORD PTR [rbx+56], eax",
        "mov eax, DWORD PTR [r12+252]",
        "mov DWORD PTR [rbx+60], eax",
        "mov rsi, rbp",
        "mov rdi, rbx",
        "mov edx, 1",
        "mov rcx, r15",
        "call {vg_sha512_compress}",
        "mov rbx, rdi",
        "mov r15, rcx",
        "mov rax, QWORD PTR [rbx]",
        "bswap rax",
        "mov QWORD PTR [rbp], rax",
        "mov rax, QWORD PTR [rbx+8]",
        "bswap rax",
        "mov QWORD PTR [rbp+8], rax",
        "mov rax, QWORD PTR [rbx+16]",
        "bswap rax",
        "mov QWORD PTR [rbp+16], rax",
        "mov rax, QWORD PTR [rbx+24]",
        "bswap rax",
        "mov QWORD PTR [rbp+24], rax",
        "mov rax, QWORD PTR [rbx+32]",
        "bswap rax",
        "mov QWORD PTR [rbp+32], rax",
        "mov rax, QWORD PTR [rbx+40]",
        "bswap rax",
        "mov QWORD PTR [rbp+40], rax",
        "mov rax, QWORD PTR [rbx+48]",
        "bswap rax",
        "mov QWORD PTR [rbp+48], rax",
        "mov rax, QWORD PTR [rbx+56]",
        "bswap rax",
        "mov QWORD PTR [rbp+56], rax",
        "mov eax, DWORD PTR [rbp]",
        "xor eax, DWORD PTR [r13]",
        "mov DWORD PTR [r13], eax",
        "mov eax, DWORD PTR [rbp+4]",
        "xor eax, DWORD PTR [r13+4]",
        "mov DWORD PTR [r13+4], eax",
        "mov eax, DWORD PTR [rbp+8]",
        "xor eax, DWORD PTR [r13+8]",
        "mov DWORD PTR [r13+8], eax",
        "mov eax, DWORD PTR [rbp+12]",
        "xor eax, DWORD PTR [r13+12]",
        "mov DWORD PTR [r13+12], eax",
        "mov eax, DWORD PTR [rbp+16]",
        "xor eax, DWORD PTR [r13+16]",
        "mov DWORD PTR [r13+16], eax",
        "mov eax, DWORD PTR [rbp+20]",
        "xor eax, DWORD PTR [r13+20]",
        "mov DWORD PTR [r13+20], eax",
        "mov eax, DWORD PTR [rbp+24]",
        "xor eax, DWORD PTR [r13+24]",
        "mov DWORD PTR [r13+24], eax",
        "mov eax, DWORD PTR [rbp+28]",
        "xor eax, DWORD PTR [r13+28]",
        "mov DWORD PTR [r13+28], eax",
        "mov eax, DWORD PTR [rbp+32]",
        "xor eax, DWORD PTR [r13+32]",
        "mov DWORD PTR [r13+32], eax",
        "mov eax, DWORD PTR [rbp+36]",
        "xor eax, DWORD PTR [r13+36]",
        "mov DWORD PTR [r13+36], eax",
        "mov eax, DWORD PTR [rbp+40]",
        "xor eax, DWORD PTR [r13+40]",
        "mov DWORD PTR [r13+40], eax",
        "mov eax, DWORD PTR [rbp+44]",
        "xor eax, DWORD PTR [r13+44]",
        "mov DWORD PTR [r13+44], eax",
        "mov eax, DWORD PTR [rbp+48]",
        "xor eax, DWORD PTR [r13+48]",
        "mov DWORD PTR [r13+48], eax",
        "mov eax, DWORD PTR [rbp+52]",
        "xor eax, DWORD PTR [r13+52]",
        "mov DWORD PTR [r13+52], eax",
        "mov eax, DWORD PTR [rbp+56]",
        "xor eax, DWORD PTR [r13+56]",
        "mov DWORD PTR [r13+56], eax",
        "mov eax, DWORD PTR [rbp+60]",
        "xor eax, DWORD PTR [r13+60]",
        "mov DWORD PTR [r13+60], eax",
        "sub r14, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r15+176]",
        "mov rbp, QWORD PTR [r15+184]",
        "mov r12, QWORD PTR [r15+192]",
        "mov r13, QWORD PTR [r15+200]",
        "mov r14, QWORD PTR [r15+208]",
        "mov r15, QWORD PTR [r15+216]",
        "ret",
        vg_sha512_compress = sym super::sha512::vg_sha512_compress,
    )
}
