// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `scrypt` functions for `x86_64`.
#![allow(dead_code)]

/// The Salsa20/8 Core (RFC 7914 §3): replaces the 64 bytes `*b` by their Salsa20/8 Core (the 16 little-endian words, 8 rounds, then the input added word by word).
///
/// Contract: `VG.Spec.Scrypt.salsaContract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `b` must be valid for reads and writes of 64 bytes.
/// * `scratch` must be valid for reads and writes of 64 bytes. It is working space: its contents on return are unspecified.
/// * `b` and `scratch` must not overlap each other, nor the return address on the stack, and neither may wrap around the end of the address space (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_salsa20_8(b: *mut [u8; 64], scratch: *mut [u32; 16]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [rsi+16], rbx",
        "mov QWORD PTR [rsi+24], rbp",
        "mov QWORD PTR [rsi+32], r12",
        "mov QWORD PTR [rsi+40], r13",
        "mov QWORD PTR [rsi+48], r14",
        "mov QWORD PTR [rsi+56], r15",
        "mov ecx, DWORD PTR [rdi]",
        "mov edx, DWORD PTR [rdi+4]",
        "mov r8d, DWORD PTR [rdi+8]",
        "mov r9d, DWORD PTR [rdi+12]",
        "mov r10d, DWORD PTR [rdi+16]",
        "mov r11d, DWORD PTR [rdi+20]",
        "mov ebx, DWORD PTR [rdi+24]",
        "mov ebp, DWORD PTR [rdi+28]",
        "mov r12d, DWORD PTR [rdi+32]",
        "mov r13d, DWORD PTR [rdi+36]",
        "mov r14d, DWORD PTR [rdi+40]",
        "mov r15d, DWORD PTR [rdi+44]",
        "mov eax, DWORD PTR [rdi+48]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rdi+52]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rdi+56]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rdi+60]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 25",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ecx",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r10d",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, r12d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, edx",
        "ror eax, 25",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r11d",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, r13d",
        "ror eax, 19",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, ebx",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, r14d",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 19",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r8d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, r15d",
        "ror eax, 25",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, r9d",
        "ror eax, 19",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, ebp",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, r9d",
        "ror eax, 25",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, ecx",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, edx",
        "ror eax, 19",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, r8d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, r10d",
        "ror eax, 25",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r11d",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, ebx",
        "ror eax, 19",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ebp",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, r13d",
        "ror eax, 25",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, r14d",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r15d",
        "ror eax, 19",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r12d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 25",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ecx",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r10d",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, r12d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, edx",
        "ror eax, 25",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r11d",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, r13d",
        "ror eax, 19",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, ebx",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, r14d",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 19",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r8d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, r15d",
        "ror eax, 25",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, r9d",
        "ror eax, 19",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, ebp",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, r9d",
        "ror eax, 25",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, ecx",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, edx",
        "ror eax, 19",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, r8d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, r10d",
        "ror eax, 25",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r11d",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, ebx",
        "ror eax, 19",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ebp",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, r13d",
        "ror eax, 25",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, r14d",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r15d",
        "ror eax, 19",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r12d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 25",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ecx",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r10d",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, r12d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, edx",
        "ror eax, 25",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r11d",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, r13d",
        "ror eax, 19",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, ebx",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, r14d",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 19",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r8d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, r15d",
        "ror eax, 25",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, r9d",
        "ror eax, 19",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, ebp",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, r9d",
        "ror eax, 25",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, ecx",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, edx",
        "ror eax, 19",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, r8d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, r10d",
        "ror eax, 25",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r11d",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, ebx",
        "ror eax, 19",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ebp",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, r13d",
        "ror eax, 25",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, r14d",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r15d",
        "ror eax, 19",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r12d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 25",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ecx",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r10d",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, r12d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, edx",
        "ror eax, 25",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r11d",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, r13d",
        "ror eax, 19",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, ebx",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, r14d",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 19",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r8d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, r15d",
        "ror eax, 25",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, r9d",
        "ror eax, 19",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, ebp",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, r9d",
        "ror eax, 25",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, ecx",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, edx",
        "ror eax, 19",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, r8d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, r10d",
        "ror eax, 25",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r11d",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, ebx",
        "ror eax, 19",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ebp",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, r13d",
        "ror eax, 25",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, r14d",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r15d",
        "ror eax, 19",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r12d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "add ecx, DWORD PTR [rdi]",
        "mov DWORD PTR [rdi], ecx",
        "add edx, DWORD PTR [rdi+4]",
        "mov DWORD PTR [rdi+4], edx",
        "add r8d, DWORD PTR [rdi+8]",
        "mov DWORD PTR [rdi+8], r8d",
        "add r9d, DWORD PTR [rdi+12]",
        "mov DWORD PTR [rdi+12], r9d",
        "add r10d, DWORD PTR [rdi+16]",
        "mov DWORD PTR [rdi+16], r10d",
        "add r11d, DWORD PTR [rdi+20]",
        "mov DWORD PTR [rdi+20], r11d",
        "add ebx, DWORD PTR [rdi+24]",
        "mov DWORD PTR [rdi+24], ebx",
        "add ebp, DWORD PTR [rdi+28]",
        "mov DWORD PTR [rdi+28], ebp",
        "add r12d, DWORD PTR [rdi+32]",
        "mov DWORD PTR [rdi+32], r12d",
        "add r13d, DWORD PTR [rdi+36]",
        "mov DWORD PTR [rdi+36], r13d",
        "add r14d, DWORD PTR [rdi+40]",
        "mov DWORD PTR [rdi+40], r14d",
        "add r15d, DWORD PTR [rdi+44]",
        "mov DWORD PTR [rdi+44], r15d",
        "mov eax, DWORD PTR [rsi]",
        "add eax, DWORD PTR [rdi+48]",
        "mov DWORD PTR [rdi+48], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, DWORD PTR [rdi+52]",
        "mov DWORD PTR [rdi+52], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, DWORD PTR [rdi+56]",
        "mov DWORD PTR [rdi+56], eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, DWORD PTR [rdi+60]",
        "mov DWORD PTR [rdi+60], eax",
        "mov rbx, QWORD PTR [rsi+16]",
        "mov rbp, QWORD PTR [rsi+24]",
        "mov r12, QWORD PTR [rsi+32]",
        "mov r13, QWORD PTR [rsi+40]",
        "mov r14, QWORD PTR [rsi+48]",
        "mov r15, QWORD PTR [rsi+56]",
        "ret",
    )
}
