// @generated from lean/VerifiedGarbage/Artifacts.lean by lean/Emit.lean. DO NOT EDIT.
//! Verified `scrypt` functions for `x86_64`.
#![allow(dead_code)]

/// The Salsa20/8 Core (RFC 7914 §3): replaces the 64 bytes `*b` by their Salsa20/8 Core (the 16 little-endian words, 8 rounds, then the input added word by word).
///
/// Contract: `VG.Spec.Scrypt.salsaContract`. Constant time: only the pointers may affect timing, not the data.
///
/// # Safety
///
/// * `b` must be valid for reads and writes of 64 bytes.
/// * `scratch` must be valid for reads and writes of 64 bytes. It is working space: its contents on return are unspecified.
/// * `b` and `scratch` must not overlap each other, nor the return address on the stack, and neither may wrap around the end of the address space (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_salsa20_8(b: *mut [u8; 64], scratch: *mut [u32; 16]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [rsi+16], rbx",
        "mov QWORD PTR [rsi+24], rbp",
        "mov QWORD PTR [rsi+32], r12",
        "mov QWORD PTR [rsi+40], r13",
        "mov QWORD PTR [rsi+48], r14",
        "mov QWORD PTR [rsi+56], r15",
        "mov ecx, DWORD PTR [rdi]",
        "mov edx, DWORD PTR [rdi+4]",
        "mov r8d, DWORD PTR [rdi+8]",
        "mov r9d, DWORD PTR [rdi+12]",
        "mov r10d, DWORD PTR [rdi+16]",
        "mov r11d, DWORD PTR [rdi+20]",
        "mov ebx, DWORD PTR [rdi+24]",
        "mov ebp, DWORD PTR [rdi+28]",
        "mov r12d, DWORD PTR [rdi+32]",
        "mov r13d, DWORD PTR [rdi+36]",
        "mov r14d, DWORD PTR [rdi+40]",
        "mov r15d, DWORD PTR [rdi+44]",
        "mov eax, DWORD PTR [rdi+48]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rdi+52]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rdi+56]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rdi+60]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 25",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ecx",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r10d",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, r12d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, edx",
        "ror eax, 25",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r11d",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, r13d",
        "ror eax, 19",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, ebx",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, r14d",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 19",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r8d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, r15d",
        "ror eax, 25",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, r9d",
        "ror eax, 19",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, ebp",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, r9d",
        "ror eax, 25",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, ecx",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, edx",
        "ror eax, 19",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, r8d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, r10d",
        "ror eax, 25",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r11d",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, ebx",
        "ror eax, 19",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ebp",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, r13d",
        "ror eax, 25",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, r14d",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r15d",
        "ror eax, 19",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r12d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 25",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ecx",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r10d",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, r12d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, edx",
        "ror eax, 25",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r11d",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, r13d",
        "ror eax, 19",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, ebx",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, r14d",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 19",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r8d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, r15d",
        "ror eax, 25",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, r9d",
        "ror eax, 19",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, ebp",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, r9d",
        "ror eax, 25",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, ecx",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, edx",
        "ror eax, 19",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, r8d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, r10d",
        "ror eax, 25",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r11d",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, ebx",
        "ror eax, 19",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ebp",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, r13d",
        "ror eax, 25",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, r14d",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r15d",
        "ror eax, 19",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r12d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 25",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ecx",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r10d",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, r12d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, edx",
        "ror eax, 25",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r11d",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, r13d",
        "ror eax, 19",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, ebx",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, r14d",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 19",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r8d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, r15d",
        "ror eax, 25",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, r9d",
        "ror eax, 19",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, ebp",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, r9d",
        "ror eax, 25",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, ecx",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, edx",
        "ror eax, 19",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, r8d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, r10d",
        "ror eax, 25",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r11d",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, ebx",
        "ror eax, 19",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ebp",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, r13d",
        "ror eax, 25",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, r14d",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r15d",
        "ror eax, 19",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r12d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 25",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ecx",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r10d",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, r12d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, edx",
        "ror eax, 25",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r11d",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, r13d",
        "ror eax, 19",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, ebx",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, r14d",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 19",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r8d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, r15d",
        "ror eax, 25",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, r9d",
        "ror eax, 19",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, ebp",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "mov eax, ecx",
        "add eax, r9d",
        "ror eax, 25",
        "xor edx, eax",
        "mov eax, edx",
        "add eax, ecx",
        "ror eax, 23",
        "xor r8d, eax",
        "mov eax, r8d",
        "add eax, edx",
        "ror eax, 19",
        "xor r9d, eax",
        "mov eax, r9d",
        "add eax, r8d",
        "ror eax, 14",
        "xor ecx, eax",
        "mov eax, r11d",
        "add eax, r10d",
        "ror eax, 25",
        "xor ebx, eax",
        "mov eax, ebx",
        "add eax, r11d",
        "ror eax, 23",
        "xor ebp, eax",
        "mov eax, ebp",
        "add eax, ebx",
        "ror eax, 19",
        "xor r10d, eax",
        "mov eax, r10d",
        "add eax, ebp",
        "ror eax, 14",
        "xor r11d, eax",
        "mov eax, r14d",
        "add eax, r13d",
        "ror eax, 25",
        "xor r15d, eax",
        "mov eax, r15d",
        "add eax, r14d",
        "ror eax, 23",
        "xor r12d, eax",
        "mov eax, r12d",
        "add eax, r15d",
        "ror eax, 19",
        "xor r13d, eax",
        "mov eax, r13d",
        "add eax, r12d",
        "ror eax, 14",
        "xor r14d, eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, DWORD PTR [rsi+8]",
        "ror eax, 25",
        "xor eax, DWORD PTR [rsi]",
        "mov DWORD PTR [rsi], eax",
        "mov eax, DWORD PTR [rsi]",
        "add eax, DWORD PTR [rsi+12]",
        "ror eax, 23",
        "xor eax, DWORD PTR [rsi+4]",
        "mov DWORD PTR [rsi+4], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, DWORD PTR [rsi]",
        "ror eax, 19",
        "xor eax, DWORD PTR [rsi+8]",
        "mov DWORD PTR [rsi+8], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, DWORD PTR [rsi+4]",
        "ror eax, 14",
        "xor eax, DWORD PTR [rsi+12]",
        "mov DWORD PTR [rsi+12], eax",
        "add ecx, DWORD PTR [rdi]",
        "mov DWORD PTR [rdi], ecx",
        "add edx, DWORD PTR [rdi+4]",
        "mov DWORD PTR [rdi+4], edx",
        "add r8d, DWORD PTR [rdi+8]",
        "mov DWORD PTR [rdi+8], r8d",
        "add r9d, DWORD PTR [rdi+12]",
        "mov DWORD PTR [rdi+12], r9d",
        "add r10d, DWORD PTR [rdi+16]",
        "mov DWORD PTR [rdi+16], r10d",
        "add r11d, DWORD PTR [rdi+20]",
        "mov DWORD PTR [rdi+20], r11d",
        "add ebx, DWORD PTR [rdi+24]",
        "mov DWORD PTR [rdi+24], ebx",
        "add ebp, DWORD PTR [rdi+28]",
        "mov DWORD PTR [rdi+28], ebp",
        "add r12d, DWORD PTR [rdi+32]",
        "mov DWORD PTR [rdi+32], r12d",
        "add r13d, DWORD PTR [rdi+36]",
        "mov DWORD PTR [rdi+36], r13d",
        "add r14d, DWORD PTR [rdi+40]",
        "mov DWORD PTR [rdi+40], r14d",
        "add r15d, DWORD PTR [rdi+44]",
        "mov DWORD PTR [rdi+44], r15d",
        "mov eax, DWORD PTR [rsi]",
        "add eax, DWORD PTR [rdi+48]",
        "mov DWORD PTR [rdi+48], eax",
        "mov eax, DWORD PTR [rsi+4]",
        "add eax, DWORD PTR [rdi+52]",
        "mov DWORD PTR [rdi+52], eax",
        "mov eax, DWORD PTR [rsi+8]",
        "add eax, DWORD PTR [rdi+56]",
        "mov DWORD PTR [rdi+56], eax",
        "mov eax, DWORD PTR [rsi+12]",
        "add eax, DWORD PTR [rdi+60]",
        "mov DWORD PTR [rdi+60], eax",
        "mov rbx, QWORD PTR [rsi+16]",
        "mov rbp, QWORD PTR [rsi+24]",
        "mov r12, QWORD PTR [rsi+32]",
        "mov r13, QWORD PTR [rsi+40]",
        "mov r14, QWORD PTR [rsi+48]",
        "mov r15, QWORD PTR [rsi+56]",
        "ret",
    )
}

/// scryptBlockMix (RFC 7914 §4) with block size parameter `r`: writes scryptBlockMix of the `128 * r` bytes at `b` to the `128 * ry` bytes at `y`. Calls `vg_salsa20_8` for each 64-byte block.
///
/// Contract: `VG.Spec.Scrypt.blockMixContract`. Constant time: only the pointers and `r` may affect timing, not the data.
///
/// # Safety
///
/// * `ry` must equal `r`, and `r` must be positive.
/// * `b` must be valid for reads of `128 * r` bytes, and `y` for reads and writes of `128 * ry` bytes.
/// * `scratch` must be valid for reads and writes of 128 bytes. It is working space: its contents on return are unspecified.
/// * `b`, `y` and `scratch` must not overlap each other, the return address on the stack, or the 8 bytes of stack below it, where its calls of `vg_salsa20_8` store their return address, and none may wrap around the end of the address space (distinct Rust objects never do).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_scrypt_blockmix(b: *const [u8; 128], r: usize, y: *mut [u8; 128], ry: usize, scratch: *mut [u32; 32]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r8+64], rbx",
        "mov QWORD PTR [r8+72], rbp",
        "mov QWORD PTR [r8+80], r12",
        "mov QWORD PTR [r8+88], r14",
        "mov QWORD PTR [r8+96], r15",
        "mov QWORD PTR [r8+104], r13",
        "mov r14, rsi",
        "mov rbx, rdi",
        "mov rbp, rdx",
        "mov r13, r8",
        "add rsi, rsi",
        "add rsi, rsi",
        "add rsi, rsi",
        "add rsi, rsi",
        "add rsi, rsi",
        "add rsi, rsi",
        "mov r12, rdx",
        "add r12, rsi",
        "mov r15, rdi",
        "add r15, rsi",
        "add r15, rsi",
        "sub r15, 64",
        "20:",
        "mov rax, QWORD PTR [r15]",
        "xor rax, QWORD PTR [rbx]",
        "mov QWORD PTR [rbp], rax",
        "mov rax, QWORD PTR [r15+8]",
        "xor rax, QWORD PTR [rbx+8]",
        "mov QWORD PTR [rbp+8], rax",
        "mov rax, QWORD PTR [r15+16]",
        "xor rax, QWORD PTR [rbx+16]",
        "mov QWORD PTR [rbp+16], rax",
        "mov rax, QWORD PTR [r15+24]",
        "xor rax, QWORD PTR [rbx+24]",
        "mov QWORD PTR [rbp+24], rax",
        "mov rax, QWORD PTR [r15+32]",
        "xor rax, QWORD PTR [rbx+32]",
        "mov QWORD PTR [rbp+32], rax",
        "mov rax, QWORD PTR [r15+40]",
        "xor rax, QWORD PTR [rbx+40]",
        "mov QWORD PTR [rbp+40], rax",
        "mov rax, QWORD PTR [r15+48]",
        "xor rax, QWORD PTR [rbx+48]",
        "mov QWORD PTR [rbp+48], rax",
        "mov rax, QWORD PTR [r15+56]",
        "xor rax, QWORD PTR [rbx+56]",
        "mov QWORD PTR [rbp+56], rax",
        "mov rdi, rbp",
        "mov rsi, r13",
        "call {vg_salsa20_8}",
        "add rbx, 64",
        "mov rax, QWORD PTR [rbp]",
        "xor rax, QWORD PTR [rbx]",
        "mov QWORD PTR [r12], rax",
        "mov rax, QWORD PTR [rbp+8]",
        "xor rax, QWORD PTR [rbx+8]",
        "mov QWORD PTR [r12+8], rax",
        "mov rax, QWORD PTR [rbp+16]",
        "xor rax, QWORD PTR [rbx+16]",
        "mov QWORD PTR [r12+16], rax",
        "mov rax, QWORD PTR [rbp+24]",
        "xor rax, QWORD PTR [rbx+24]",
        "mov QWORD PTR [r12+24], rax",
        "mov rax, QWORD PTR [rbp+32]",
        "xor rax, QWORD PTR [rbx+32]",
        "mov QWORD PTR [r12+32], rax",
        "mov rax, QWORD PTR [rbp+40]",
        "xor rax, QWORD PTR [rbx+40]",
        "mov QWORD PTR [r12+40], rax",
        "mov rax, QWORD PTR [rbp+48]",
        "xor rax, QWORD PTR [rbx+48]",
        "mov QWORD PTR [r12+48], rax",
        "mov rax, QWORD PTR [rbp+56]",
        "xor rax, QWORD PTR [rbx+56]",
        "mov QWORD PTR [r12+56], rax",
        "mov rdi, r12",
        "mov rsi, r13",
        "call {vg_salsa20_8}",
        "mov r15, r12",
        "add rbx, 64",
        "add rbp, 64",
        "add r12, 64",
        "sub r14, 1",
        "jne 20b",
        "mov rbx, QWORD PTR [r13+64]",
        "mov rbp, QWORD PTR [r13+72]",
        "mov r12, QWORD PTR [r13+80]",
        "mov r14, QWORD PTR [r13+88]",
        "mov r15, QWORD PTR [r13+96]",
        "mov r13, QWORD PTR [r13+104]",
        "ret",
        vg_salsa20_8 = sym super::scrypt::vg_salsa20_8,
    )
}
