// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `selftest` functions for `x86_64`.
#![allow(dead_code)]

/// Pipeline self-test: returns `a.wrapping_add(b)`.
///
/// Contract: `VG.Spec.Selftest.addContract`. No safety requirements.
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_selftest_add(a: u64, b: u64) -> u64 {
    core::arch::naked_asm!(
        "mov rax, rdi",
        "add rax, rsi",
        "ret",
    )
}
